### ISSUE TITLE
Unsent messages are too easy to lose and forget about.

### ISSUE THREAD

**Issue by lampholder** [vector-im/element-web#10230]
This isn't a dup of #1351 because #1351 has a specific impl in mind; this is just an ask that unsent messages are as obvious as they need to be. #1351 is just one way of fixing that.

https://github.com/vector-im/riot-web/issues/1351
(https://github.com/vector-im/riot-web/issues/7210)

**Comment by aaronraimist** [comment]
Related: https://github.com/vector-im/riot-web/issues/11838 https://github.com/vector-im/riot-web/issues/11386 https://github.com/vector-im/riot-web/issues/1898

**Comment by aaronraimist** [comment]
(Imo I don't think it is great to track different but very closely related solutions to problems as separate issues. The issue should describe the problem and then people should add comments about different possible solutions to the problem. Otherwise all these issues (which are actually possible solutions to the same problem) just get lost in a sea of issues.)

**Comment by turt2live** [comment]
Closing this in favour of https://github.com/vector-im/element-web/issues/14181
