### ISSUE TITLE
Warn users about e2e when logging out of their last device

### ISSUE THREAD

**Issue by nadonomy** [vector-im/element-web#10242]
When users log out of all of their devices, other users don't have a list of devices to encrypt messages for. Therefore, we should warn users when they're logging out of their last device/session.

**Comment by dbkr** [comment]
Hopefully once dehydrated devices are a thing (https://github.com/matrix-org/matrix-react-sdk/pull/5239) this should be unnecessary.

**Comment by ShadowJonathan** [comment]
I just got feedback via-via through a colleague on this issue, where someone was completely turned off of matrix because they lost their encrypted history twice, i mused that this person logged out of all of their sessions, and via this, they lost their history.

IMO, element should educate users about this the *first* time they log in and set up their keys, alongside a wider "story" about how encryption works in element, and the ["hot potato"](https://idioms.thefreedictionary.com/drop+me+like+a+hot+potato) problem that exists once every session is logged out.

Furthermore, a more heavy emphasis and priority should be placed on dehydrated devices, the current state of E2EE is being held to "it kinda works", while it should be "it works, reliably, with backups and redundancies, with informed users", and with only the former you'll get a lot of users that get a wrong "incomplete" impression of element.

**Comment by ShadowJonathan** [comment]
@dbkr I dont know, the client should still verify if the dehydrated device is up and verified before it will think that its "alright" to log off.

Also, the user should be warned that the next time they log in, they need to use their password, this should maybe only happen the first time around, and the user can then "test" their knowledge by putting in the password to see if it gets the dehydrated device decrypted. Telegram has this approach for if you dont log in for a while, to test your 2FA password, and i think this should apply to logging out here, to make sure the user doesnt lose E2EE history.

**Comment by ShadowJonathan** [comment]
As of 16 dec on `develop.`, Element displays the following if the user hasn't yet enabled Key Backup;

![image](https://user-images.githubusercontent.com/22740616/146411809-81b9218b-8fc5-4540-bbd8-bc2ac13c9a3e.png)

**Comment by kittykat** [comment]
Closing as the UI has changed :+1:
