### ISSUE TITLE
Features cannot be set to default on

### ISSUE THREAD

**Issue by jryans** [vector-im/element-web#10360]
* We should document this
* Consider reverting https://github.com/matrix-org/matrix-react-sdk/commit/202f6fb94d91a42d864431176984b4e6c6294a81 as it doesn't really do what I thought (was testing with `enableLabs: true`)

**Comment by turt2live** [comment]
a bit of background (mostly for my context): we want to be able to turn on features by default, however the intended use of feature flags is that they are for unstable code. They have previously been opt-in on a per-deployment basis (which is why the PR mentioned in the OP doesn't work as intended) because we don't want to tell other deployments how to use our unstable code. 

In our current climate, we have the option of converting the feature flag to a real setting (or just removing the feature flag), which assumes that the code is stable enough to be released. This challenges the availability of supporting documentation and potentially spec which might not be ready. The coordination of spec, docs, and when to remove/replace a flag is more of a job for the product/management team though and less so the flag itself. In an ideal world: the flag would exist, even if stable, until the spec+docs are ready to go (or at least at a point where they are unlikely to change, such as being in a FCP).

Feature flags are also confusing pre-202f6fb because they have a `default` which isn't a default. Regular settings do correctly have a default, but the feature flag's default is only there to communicate type and expected behaviour. The confusing part comes when one wants to change the expected behaviour and realizes that the flag did nothing. https://github.com/matrix-org/matrix-react-sdk/commit/202f6fb94d91a42d864431176984b4e6c6294a81 changes this by making it actually do something, which helps us get closer to the goal of better enabling features by default (and I think it's for the better anyways).

**Comment by turt2live** [comment]
oh, hmm, this shouldn't have been closed.
