### ISSUE TITLE
Unexpected behaviour when creating new direct room

### ISSUE THREAD

**Issue by vnscriptkid** [vector-im/element-web#10520]
When I create a new direct room, the room first shows up in `Rooms` section, and only after a while (a couple of seconds), the room jumps into `People` magically (where it should reside in the first place). I want to ask why is this behavior and is it considered a bug, if it is, what is the reason and how I can fix it?

**Comment by turt2live** [comment]
This is due to server behaviour, particularly Synapse. It creates a boring room first which gets sent to the client, but the client doesn't know anything about it. Then the server populates more information about it and the client thus moves it around.

This is not something we can realistically fix in Element.
