### ISSUE TITLE
Standardise casing of homeserver, identity server

### ISSUE THREAD

**Issue by jryans** [vector-im/element-web#10569]
These terms should be spelled "homeserver", "identity server", and "integration manager" in all user visible text.

Other variants such as:

* Identity Server
* ID Server
* Home Server
* Integrations Manager
* Integs

should all be replaced.

(Of course, if it's the first word in a sentence, the first letter should be capitalised.)

**Comment by turt2live** [comment]
while we're here: It's Integration Manager, not Integrations Manager, Integs, etc

**Comment by jryans** [comment]
> while we're here: It's Integration Manager, not Integrations Manager, Integs, etc

And also lowercase as in "integration manager"? (For consistency with the others, I am hoping so...)

**Comment by turt2live** [comment]
yes, probably. It doesn't need to be a fancy thing

**Comment by jryans** [comment]
Edited top comment to include it.

**Comment by keremgocen** [comment]
I'm new here and looking for low hanging fruits unless anyone is on it?

**Comment by SimonBrandner** [comment]
@keremgocen, it has the _Help wanted_ label and no-one is assigned, please go ahead!

**Comment by keremgocen** [comment]
dropping this one for now, feel free to grab please

**Comment by gsouquet** [comment]
Closed by #17980

**Comment by psrpinto** [comment]
It's worth noting that, in addition to the changes in the PRs linked above, given that the _source strings_ [were modified](https://github.com/matrix-org/matrix-react-sdk/pull/6365/files#diff-20527b4ae184e85263f5a70fc00d1cb022b054ea126e404332da46983247e5bc), extra work was required to recover existing translations for those strings (otherwise those translations would be lost).

I did this by using the _Automatic suggestions_ feature of Weblate, which - for each string, in each language - suggested the previously-existing translation. Recovered translations were marked as _Needs editing_ so that they are eventually checked by a translator.

For reference, here's the list of the source strings on Weblate, along with the recovered translations (navigate to the "Other languages" tab):

- [Identity server URL must be HTTPS](https://translate.element.io/translate/element-web/matrix-react-sdk/en/?checksum=9477149ba914d600#translations)
- [Not a valid identity server (status code %(code)s)](https://translate.element.io/translate/element-web/matrix-react-sdk/en/?checksum=9b0d08eddae1f84f#translations)
- [Could not connect to identity server](https://translate.element.io/translate/element-web/matrix-react-sdk/en/?checksum=2e24122ebd7f065d#translations)
- [Identity server (%(server)s)](https://translate.element.io/translate/element-web/matrix-react-sdk/en/?checksum=b5a9db4d2404c41c#translations)
- [Identity server](https://translate.element.io/translate/element-web/matrix-react-sdk/en/?checksum=6a48c9cb01cee703#translations)
- [Use an integration manager <b>(%(serverName)s)</b> to manage bots, widgets, and sticker packs.](https://translate.element.io/translate/element-web/matrix-react-sdk/en/?checksum=e1113976c6564027#translations)
- [Use an integration manager to manage bots, widgets, and sticker packs.](https://translate.element.io/translate/element-web/matrix-react-sdk/en/?checksum=5af0d267e02f13d0#translations)
- [Integration managers receive configuration data, and can modify widgets, send room invites, and set power levels on your behalf.](https://translate.element.io/translate/element-web/matrix-react-sdk/en/?checksum=43ce76589720bff#translations)
- [Identity server is](https://translate.element.io/translate/element-web/matrix-react-sdk/en/?checksum=50a7b551f3b49c28#translations)
- [Using this widget may share data <helpIcon /> with %(widgetDomain)s & your integration manager.](https://translate.element.io/translate/element-web/matrix-react-sdk/en/?checksum=85d5797f9e9c7561#translations)
- [Your %(brand)s doesn't allow you to use an integration manager to do this. Please contact an admin.](https://translate.element.io/translate/element-web/matrix-react-sdk/en/?checksum=829fc8430fbd0716#translations)
- [Integration manager](https://translate.element.io/translate/element-web/matrix-react-sdk/en/?checksum=32259dc014b09160#translations)
