### ISSUE TITLE
Special symbols in matrix names

### ISSUE THREAD

**Issue by itay-grudev** [vector-im/element-web#10994]
### Description

When a user uses special characters in their name it breaks the citing feature. Here is an example of a user that uses two line feed characters in their name which produces the following result in the message input field:

![Screenshot from 2019-09-29 12-47-51](https://user-images.githubusercontent.com/2123767/65830462-5e920b00-e2b8-11e9-96ac-d067f45c91c5.png)

And after posting produces the following message:

![Screenshot from 2019-09-29 12-48-39](https://user-images.githubusercontent.com/2123767/65830393-b714d880-e2b7-11e9-8bd6-11d230639ee0.png)

The exact JSON with the user details is the following:

```
{ 
    "displayname": "\n\nJonas"
}
```

Interesting note: The API returns the _line feeds_ in the name, but the user claims what they originally inputted was an em-space character. So this is likely the results of an ASCII transformation of the non-ASCII characters (hence his message, intentionally included in the screenshot).

### Steps to reproduce

- Find a user with a hacked name that includes new lines
- Try and cite them
- Be miserable for a second hating Riot and Matrix while they are both really great projects.
- Post the message, then edit it and remove the new lines to produce a nice looking pill.

### Version information

riot: 1.4.0 
matrix-react-sdk version: 1.6.0
riot-web version: master
olm version: 3.1.0

**Comment by weeman1337** [comment]
Cannot reproduce any more

![image](https://user-images.githubusercontent.com/6216686/225552407-2c48ccd1-f9c7-42da-acaf-5071b4cddc8f.png)

Thank you for opening an issue. Unfortunately I wasn’t able to reproduce it. If you keep experiencing this defect, please update your description with steps/screenshots/video/more details and add a comment with @weeman1337  to let me know that it’s ready to be reopened.

**Comment by weeman1337** [comment]
Still valid

**Comment by Johennes** [comment]
Otherwise I can reproduce the issue. After changing my display name to this

<img width="652" alt="Screenshot 2023-06-28 at 20 10 24" src="https://github.com/vector-im/element-web/assets/1137962/4dac5e1a-a824-478b-a31a-bf7dbdc02af2">

others can still mention me in the composer

<img width="277" alt="Screenshot 2023-06-28 at 20 11 05" src="https://github.com/vector-im/element-web/assets/1137962/658d2a18-6352-4c15-b018-fe66f7d5b9a2">

<img width="265" alt="Screenshot 2023-06-28 at 20 11 11" src="https://github.com/vector-im/element-web/assets/1137962/ca4b68d0-3608-4399-9e14-6397eb6cf6db">

but the timeline rendering doesn't display the user pill

<img width="613" alt="Screenshot 2023-06-28 at 20 11 21" src="https://github.com/vector-im/element-web/assets/1137962/a3e7440f-2fc2-4ee0-b949-184badd9b519">

**Comment by Johennes** [comment]
I think part of the issue here is that Markdown doesn't support linebreaks in links without HTML. E.g. you can't do

```
[a
b](foo.bar)
```

but you can do

```
[a<br/>b](foo.bar)
```

I tried replacing `\n` with `<br/>` when serializing the user pill to Markdown in https://github.com/matrix-org/matrix-react-sdk/blob/develop/src/editor/serialize.ts#L51. That actually unbreaks the timeline rendering of pills but the HTML that is serialized from the Markdown+HTML ends up being half-escaped only:

```
<a href=\"https://matrix.to/#/@johannesm:element.io\">Johannes&lt;br/&gt;<br>Marbach</a>
```

**Comment by Johennes** [comment]
> [...] but the HTML that is serialized from the Markdown+HTML ends up being half-escaped only

Actually scratch that. I was missing the `g` flag on the regex replace. 🤦‍♂️

**Comment by Johennes** [comment]
I think we would actually want the `<br/>`s to be unescaped in the HTML though. For this to happen, we'd have to allow them in https://github.com/matrix-org/matrix-react-sdk/blob/develop/src/Markdown.ts#L30. It looks like that might get quite fiddly though because we probably only want to allow them in this edge case.

**Comment by Johennes** [comment]
In reconsidering, something else we could do is simply strip the newlines from both `body` and `formatted_body`. We already ignore them when rendering pills due to our use of `textContent`.

**Comment by Johennes** [comment]
> I don't think that necessarily has to be true. Technically commonmark is a superset of HTML even though we don't treat it as such. We allow certain tags like `del` `u` `sup` `sub` so adding `br` wouldn't be a big deal.

Hm, good point. It would just mean that you couldn't send a literal `"<br/>"` anymore without putting it into backticks. But that's probably not problematic.

> Stripping newlines from body would break paragraphs in plaintext messages, no?

Yes sorry, I meant stripping them only within user display name parts.

That being said, since we can easily and generally exclude `br`s from escaping in our Markdown to HTML conversion, retaining the newlines is probably the more correct fix.

**Comment by t3chguy** [comment]
> without putting it into backticks

or escape it using `\`
