### ISSUE TITLE
Consider treating an edit of deleting all text a redaction

### ISSUE THREAD

**Issue by turt2live** [vector-im/element-web#11024]
ie: send a message, edit it, select all, delete, send. Should probably be a redaction

**Comment by aaronraimist** [comment]
Related: #10738

**Comment by dbkr** [comment]
I'd prefer if we changed the presentation of a message that's been edited to be blank. A redaction is intended to be a very specific thing where the user actively needs to purge the message from as many places as possible, eg. because it leaks sensitive content or contains something illegal, although we don't really present it like this in the UI at the moment or offer an alternative. I think we should be trying to move towards redactions being a special and unusual case rather than doing redactions where the user didn't ask to.

**Comment by aaronraimist** [comment]
To me it seems like a user editing their message to blank means they didn't want to send that message and just didn't know that they were supposed to click the Remove button. It seems like the only reason a user would do that is because they intend for their message to not be seen anymore (which btw isn't what happens even with my PR due to https://github.com/vector-im/riot-web/issues/11978 still existing). Imo it is a fairly big privacy issue. Maybe there are examples of a user editing their message to blank and not intending for their message to be deleted but I can't think of any.

**Comment by dbkr** [comment]
I think the app should be as clear as possible about what operation has been performed, so the user can understand what has happened and use the app to achieve what they intend, rather than second-guessing the user's intentions. If a user does edit their message to be blank, I think it's better if they can then see that the history is still visible, so if they really want to try to remove the old message, they can then still choose to redact.

**Comment by nadonomy** [comment]
+1, basically echoed by my comment (with suggested comp) here:

https://github.com/matrix-org/matrix-react-sdk/pull/4623#issuecomment-647450384

**Comment by dkowis** [comment]
Is a "redaction" different than "Deleting a message"

In my case, I typed a message that was part of a longer message, and accidentally hit the enter key. So it's very much incomplete. I could just edit the message and have it updated, but it's still sitting there, partially completed, on everyone's screen.

I'd rather drop it, and start my message over again. I don't see the same "redacted" semantics as described by @dbkr . To me, it's just a message that I do want deleted, not for any of the mentioned reasons, but I want it gone. To me, it doesn't matter if it's "Redacted" or "Deleted" it doesn't contribute to the conversation, and is erroneous.

**Comment by t3chguy** [comment]
Redaction is the Matrix term for it, in the UI it is exposed as `Remove`

**Comment by ShadowJonathan** [comment]
For some context, Discord and Telegram have this behaviour, so some users could/would be expecting this, coming from other platforms.

**Comment by SethFalco** [comment]
Just copy/pasting an excerpt from a duplicate issue I made.

> The following applications have this behavior already:
> * Discord
> * Slack
> * Rocket.Chat
> 
> — https://github.com/vector-im/element-web/issues/18684

Editing a message with empty content will prompt for the deletion of the message as if the delete button was pushed. (Usually with an "Are you sure?" on in the of Element, probably asking for the reason.

**Comment by ShadowJonathan** [comment]
@SethFalco added that to my comment

**Comment by WRMSRwasTaken** [comment]
You can add Mattermost to this list, the prompt to delete a message is also confirm-able with the return key (same as Discord, haven't tested others).

**Comment by ShadowJonathan** [comment]
This seems to be implemented now on app.element.io, though i don't know where, or by whom :eyes:

@SimonBrandner could this be closed?
