### ISSUE TITLE
Element shows fatal misconfigured error when default homeserver can't be reached

### ISSUE THREAD

**Issue by bwindels** [vector-im/element-web#11154]
Element shows fatal misconfigured error when default homeserver can't be reached.

> Failed to start
>
> Your Element is misconfigured
>
> Invalid homeserver discovery response

![](https://user-images.githubusercontent.com/51663/133259495-297bf102-623f-4b5c-88ce-3cf561e5d305.png)

## Potential solution

See https://github.com/vector-im/element-web/issues/11655#issuecomment-646065432

**Comment by bwindels** [comment]
![invalid-wk-response-offline](https://user-images.githubusercontent.com/274386/67066612-d7bbaa00-f162-11e9-88d3-08212752ca06.png)

**Comment by turt2live** [comment]
Are you logged in?

**Comment by bwindels** [comment]
> Are you logged in?

No

**Comment by turt2live** [comment]
That's currently expected behaviour :(

**Comment by bwindels** [comment]
:(

**Comment by jryans** [comment]
@turt2live How complex would it be to change this case to be a inline warning in the auth flow instead of blocking the app like this?

Blocking the entire app for what might be temporary network failure out of the user's control seems too strong here.

**Comment by turt2live** [comment]
Not difficult but does have side effects such as us having a default server again and the config being untested.

We could also retry, or put a continue anyways button on it.

**Comment by neutralinsomniac** [comment]
I know this issue seems like a minor one since most anyone using matrix will be in an internet-connect environment, but my employer uses matrix/riot on a completely closed network, which means that this bug causes any new employees to be unable to use riot at all. Is there a workaround for this?

**Comment by t3chguy** [comment]
Change the default homeserver via config.json

**Comment by neutralinsomniac** [comment]
and rebuild a custom riot-desktop for every release that comes out?

**Comment by t3chguy** [comment]
Or ship a config.json via GPO? https://github.com/vector-im/riot-desktop#user-specified-configjson

**Comment by neutralinsomniac** [comment]
That'll work, thank you!

**Comment by tim-seoss** [comment]
Can I have confirmation that this is definitely a dupe of #15386 please?
If-so I think it is a significant UI problem, since it creates a very poor impression if it occurs on the first visit of a new user to Element / Matrix.  An extract from the quoted issue:

 
> This looks like a serious first-impressions failure unfortunately, when encouraging others to try Matrix / Element...
> What I expected to see
> 
> I think Element should try hard not to show a message which is either baffling or flaky looking to users.
> 
> Perhaps it should either retry silently, prompt the user to retry, and/or display a more human-readable message.

Thanks!

Tim.

**Comment by rc0r** [comment]
I'm seeing this error as well. Tried adding a `config.json` to `~/.config/Element` but that didn't change anything.

How am I supposed to log in when I see this error?

**Comment by t3chguy** [comment]
@rc0r what exactly did you put into that `config.json` file and what does starting the app from the command line say in your stdout?

**Comment by rc0r** [comment]
Here's my `config.json`:

```bash
$ cat ~/.config/Element/config.json
{
  "update_base_url": "https://packages.riot.im/desktop/update/",
  "default_server_name": "matrix.org",
  "brand": "Element",
  "integrations_ui_url": "https://scalar.vector.im/",
  "integrations_rest_url": "https://scalar.vector.im/api",
  "integrations_widgets_urls": [
    "https://scalar.vector.im/_matrix/integrations/v1",
    "https://scalar.vector.im/api",
    "https://scalar-staging.vector.im/_matrix/integrations/v1",
    "https://scalar-staging.vector.im/api",
    "https://scalar-staging.riot.im/scalar/api"
  ],
  "hosting_signup_link": "https://element.io/matrix-services?utm_source=element-web&utm_medium=web",
  "bug_report_endpoint_url": "https://element.io/bugreports/submit",
  "roomDirectory": {
    "servers": [
      "matrix.org"
    ]
  },
  "showLabsSettings": false,
  "piwik": {
    "url": "https://piwik.riot.im/",
    "siteId": 1,
    "policyUrl": "https://element.io/cookie-policy"
    },
  "enable_presence_by_hs_url": {
  "https://matrix.org": false,
  "https://matrix-client.matrix.org": false
  },
  "terms_and_conditions_links": [
    {
      "url": "https://element.io/privacy",
      "text": "Privacy Policy"
    },
    {
      "url": "https://element.io/cookie-policy",
      "text": "Cookie Policy"
    }
  ]
}
```

And `stdout`:

```bash
$ element-desktop
/home/rc0r/.config/Element exists: yes
/home/rc0r/.config/Riot exists: no

(electron:1779): Gtk-WARNING **: 17:03:13.351: Theme parsing error: gtk.css:2:33: Failed to import: Fehler beim Öffnen der Datei »/home/rc0r/.config/gtk-3.0/window_decorations.css«: Datei oder Verzeichnis nicht gefunden
Gtk-Message: 17:03:13.397: Failed to load module "appmenu-gtk-module"
Starting auto update with base URL: https://packages.riot.im/desktop/update/
Auto update not supported on this platform

```

**Comment by t3chguy** [comment]
`"default_server_name": "matrix.org",`

You are still trying to connect to matrix.org - so if its unavailable to then the app will refuse to start.
If you are trying to reach matrix.org then you have some network connectivity (firewall/jail/otherwise) issue.

**Comment by rc0r** [comment]
@t3chguy Thanks for your help. It was a proxy issue on my side.

**Comment by WestXu** [comment]
@t3chguy Can you provide a full config.json to those like me who simply host a server on a local network without internet connection?

Tried `{"default_server_name": "http://{some-ip}:8008"}` but it didn't work. 

I just want a nice local IM service is all.

**Comment by t3chguy** [comment]
`server_name` should be just that, a server_name - not a URL.
e.g `mozilla.org` is a server_name, their URL is `https://mozilla.modular.im` as resolved via `.well-known`

https://github.com/vector-im/element-web/blob/develop/docs/config.md

**Comment by WestXu** [comment]
What if the server is not connected to the internet either and simply doesn't have a server_name?

I used the https://hub.docker.com/r/matrixdotorg/synapse/ to deploy a most simple server with all configs (except for enable_registration: true) as default to a local server with a static IP. Can element work in such environment?

I don't quite understand the config.md you provide althoght I've read it for many times, and I just find many people encounter the same question on internet without knowing what to do to make it work. 

I tried input `http://{my-server-ip}:8008/.well-known/matrix/client` to a browser and it just returned a `.well-known not available`. And I don't know how to tell my client what my server IP is. 

The whole process is such a frustration and I completely lost my track. I deploy a rocket.chat instead. It simply works like a charm. 

BTW, don't you think the matrix.org is a single-point of failure of such a "decentralized communication service"?

**Comment by t3chguy** [comment]
@WestXu every server has a server_name but as per the Matrix spec a well-known has to be on HTTPS.
In your case just use the other config mechanism, e.g `default_hs_url` OR `default_server_config`

**Comment by WestXu** [comment]
`default_hs_url` works. Thanks. @t3chguy

**Comment by askender** [comment]
In some place,  `matrix.org` and `matrix.org` is blocked by `somebody` who control their network. 
But people have their own homeserver, and they still want to use <https://app.element.io/> as a great matrix web client.   

Hope fail to connect to `default_server_name`  doesn't affect the using of <https://app.element.io/>, so that people can choose homeserver freely, and no `single point of failure`.

**Comment by PowerOfVoid** [comment]
I get the same error message from the second screenshot ("Invalid homeserver discovery response") on Linux Mint 20.2

* My package manger lists the version as 1.9.4
* I installed the flatpak from the repositories today
* I am connected to the Internet
* I am not aware of any restrictions on outgoing connections in my Internet connection.

**Comment by Krysme** [comment]
Would you please fix this for Chinese users? The GFW blocks the official server, and it's a hassle for those everyday users to edit configs. If I am to introduce them to log in to my server, for now, it's an immense pain for them to get on board.

**Comment by Erudition** [comment]
This issue is affecting me on the desktop/electron build, with no proxy, and a homeserver that very much CAN be reached - I can browse to https://matrix.org/.well-known/matrix/client in my browser. In the developer console of electron, i'm seeing a CORS error, however. 
![image](https://user-images.githubusercontent.com/3915447/143627698-b88da1ac-e4e8-4b52-ad91-245cf90c5665.png)

**Comment by askender** [comment]
I solved this issue by deploy `element-web` as a new website:   https://chat.dweb-lab.com/  ,  and if you need a tmp solution, you can use ti too, or change the homeserver to anything you wish.
I'm considering compiling a desktop version too. 

By the way, Welcome to our matrix space too:   https://matrix.to/#/#dweb-space:matrix.dweb-lab.com

**Comment by evan0greenup** [comment]
@t3chguy 
Why not add some exception handling mechanism? For example, if some exception happens during enabling homeserver discover feature. Then simply disable it and try to load the main page again.

It doesn't affect the performance of current instance, but also make this issue resolved.

**Comment by t3chguy** [comment]
Because it was a product decision to not let the app start with a faulty config and that includes the default hs being inaccessible. This decision is still being reworked.

**Comment by evan0greenup** [comment]
@t3chguy ,

I believe this design is against the philosophy of Matrix protocol.

Because the inspiration of Matrix protocol different from other instant message app is decentralization. 

As the official reference implementation of Matrix protocol client. 

`element-web` is obviously now make the matrix service centralized.

As a libre and open source software, Element are supposed to be working unless the security problem occurs.

**Comment by t3chguy** [comment]
No, its the given instance that chooses to be configured to that specific server.
You can run your own `element-web` instance configured to any other Matrix homeserver.
It isn't an ideal scenario but it was a product decision to yield a more expected experience for new users who have no idea what homeservers and decentralisation are.

https://github.com/vector-im/element-web/issues/11655#issuecomment-646065432 has more info.

**Comment by aaronraimist** [comment]
The product decision needs to be revised though. Use uMatrix or similar to block matrix.org and then try https://github.com/vector-im/element-web/pull/19695 and app.element.io. I'm not sure anyone could actually say app.element.io provides a better experience.

**Comment by vwas2** [comment]
this also happens if app.element.io does not like zour ip

**Comment by evan0greenup** [comment]
@t3chguy I understand this decision is to protect fresh user from 3rd part untrusted homeserver. But letting user know that matrix.org is unreachable is enough, making app completely not work doesn't make any sense.

As far as I see, it would be a good idea to give the user chance to let them specify homeserver when matrix.org is unreachable.

**Comment by t3chguy** [comment]
@evan0greenup see https://github.com/vector-im/element-web/issues/11655#issuecomment-646065432 for the plan

**Comment by Subnet-Masked** [comment]
I just installed Element-Desktop, however I am n a network that blocks matrix.org - Because of this, I am getting the screen shown in the OP which is making it impossible to sign into my own homeserver which is approved on this network. This seems like a major oversight, a client application should not fail fatally if the default option is not available and should instead tell me that that server is unavailable and give me the option to input my own.

**Comment by rmalchow** [comment]
i think it would be a great improvement if, upon a failure here, the client would simply ask for a custom homeserver instead. maybe even with matrix.org prefilled.

**Comment by wioxjk** [comment]
I encounter this on fresh windows installs. Is there a workaround for this yet?

**Comment by cxzlw** [comment]
This is not an uncommon issue. In China, the GFW (Great Firewall) blocks matrix.org, while there still exists many homeservers that are easily to connect from China. However, as Element shows the misconfigured page when it is unable to connect to matrix.org, common Chinese users cannot enter the login page and switch to other available homeservers, which makes it difficult to introduce Element (and matrix) to Chinese users because they cannot use it directly.

**Comment by cxzlw** [comment]
> Because it was a product decision to not let the app start with a faulty config and that includes the default hs being inaccessible. This decision is still being reworked. 

But there are users who cannot access the matrix.org server. Also, for decentralisation reasons, Element should rely on a (specific one) server, while there are lots of server offering matrix service and should enable users to use it without matrix.org. So matrix.org won't be able to stop users from using Element.

**Comment by cxzlw** [comment]
> Because it was a product decision to not let the app start with a faulty config and that includes the default hs being inaccessible. This decision is still being reworked. 

Then add an option to easily set another homeserver, and do anything on that server instead of matrix.org. Relying on matrix.org should be erased because it (relying) is not decentralised.

**Comment by cxzlw** [comment]
Although we can bypass the verification by editting the config, or even deploy a modded Element like what @askender has done, most people dont know how or dont want to do this. 

Those common people that cannot access matrix.org easily and legally have to use a third-party modded Element application (assume they dont want to learn config editting. You know, they want to use a out-of-the-box client. ). 

But using third-party Element instance (or modded Element application) is dangerous because they (common people) cannot determine if there is any malicious code such as account recorder or chat recorder. 

It is irresponsible to force those pitful people to use Element at that risk. We should provide the method to bypass the verification in a simple, reliable and official way.

**Comment by SteveSWang47** [comment]
My friend is in China and he knows nothing about those config-editing stuff, and it's **IMPOSSIBLE** for me to explain how to do it.

This behaviour makes matrix.org **the CENTRALISED SERVER WHICH ENABLES USERS TO USE THE OTHER SERVERS**. Thus, **it is REALLY against the philosophy of Matrix protocol**.

**Comment by SteveSWang47** [comment]
In my opinion, this "decision" equals to **PURE DISCRIMINATION**.

**Comment by linuxtim** [comment]
> In my opinion, this "decision" equals to **PURE DISCRIMINATION**.

This issue is still in the "Open" state, i.e. it has not been given the status of invalid/won't-fix etc. it is merely unfinished.  There are many demands placed on the time of the Matrix developers (both those who are paid for their work, and those who are not).  Since Element is open source, you do of course have the option of contributing a fix to this issue yourself and/or sponsoring someone else to do-so.

**Comment by t3chguy** [comment]
As linked before - there is a plan - just not enough people to action it right now https://github.com/vector-im/element-web/issues/11655#issuecomment-646065432

Contributions welcome.

**Comment by t3chguy** [comment]
This is fixed by https://github.com/vector-im/element-web/pull/25682
For deployments that wish to avoid this behaviour they should use `default_server_config` (either alone or with conjunction with `default_server_name`) - the configs for the element.io deployments and Element Desktop/Nightly will be updated to do this.
