### ISSUE TITLE
we've lost the display of the emoji picker on hover over

### ISSUE THREAD

**Issue by AmandineLP** [vector-im/element-web#11176]
since the wider emoji picker landed we have to click to display it, which is a pain

**Comment by bwindels** [comment]
There was some contention while discussion this on matrix whether this is a feature or a bug.

**Comment by nadonomy** [comment]
@bwindels can you point me to that discussion? It's always been the intention to have hover interactions since the original design 5 months ago (https://zpl.io/a3e7okQ) & I've just filed #11204 to reflect that.

In either case, we already had quick reactions on hover implemented— and hastily merged in a PR removing the functionality without discussion, which doesn't feel correct to me.

**Comment by bwindels** [comment]
@nadonomy Starting at https://matrix.to/#/!RbKRuLTvHIhArQcvjr:matrix.org/$1571659079446680ENMpP:matrix.org?via=matrix.org&via=vector.modular.im&via=lant.uk

**Comment by t3chguy** [comment]
This got readded
