### ISSUE TITLE
/rainbow and stickers do not behave correctly when replying

### ISSUE THREAD

**Issue by benparsons** [vector-im/element-web#12081]
# Description

When a message is selected to reply, if the user enters `/rainbow message`, the behaviour is incorrect.

Instead of replying with rainbow text, the text is sent, but not as a reply. Also, the reply overlay does not close.

### Version information

1.5.8

**Comment by tulir** [comment]
The `/rainbow` issue is probably the same as #11170.

Sticker replies would be trivial (clients already render them and technically non-spec-compliant clients can send them), but it probably needs extensible events to be spec-compliant, because some people insisted on requiring fallbacks for everything.

**Comment by SimonBrandner** [comment]
This doesn't seem to be an issue anymore
