### ISSUE TITLE
room pills break with emojis

### ISSUE THREAD

**Issue by jomat** [vector-im/element-web#12196]
### Description

room pills don't display emojis. user pills work as expected.

### Steps to reproduce

- add an emoji to a room name
- autocomplete so the pill appears in the input field
- send the message

Instead of displaying the emoji, something that looks urlencoded is displayed.

What i write:
![image](https://user-images.githubusercontent.com/381286/73608640-6bec3880-45bd-11ea-9fed-4319a40d62a1.png)

What is displayed:
![image](https://user-images.githubusercontent.com/381286/73608649-87574380-45bd-11ea-8ab5-6f719e3d7694.png)

Logs being sent: no

### Version information

- **Platform**: web

For the web app:

- **Browser**: Tested in Chrome and Firefox
- **OS**: Linux
- **URL**: riot.im/app

**Comment by weeman1337** [comment]
The issue seems to be fixed:
![image](https://user-images.githubusercontent.com/6216686/225549873-254fb6e8-7028-4c03-b78d-d975f7d75430.png)

Thank you for opening an issue. Unfortunately I wasn’t able to reproduce it. If you keep experiencing this defect, please update your description with steps/screenshots/video/more details and add a comment with @weeman1337  to let me know that it’s ready to be reopened.
