### ISSUE TITLE
Unable to expand left sidebar on mobile

### ISSUE THREAD

**Issue by twouters** [vector-im/element-web#12203]
I've just spent half an hour trying to find a way to join a room on mobile firefox and chrome.

I've read reports that there should be some sort of mystical left sidebar with a button to join/explore rooms but I have not been able to discover the secret gesture to make it appear.

**Comment by turt2live** [comment]
We don't support mobile browsers at the moment, but if you are interested in us formally supporting this then please add a 👍 to #9814

**Comment by jryans** [comment]
I think it's helpful to keep this open to be aware of where mobile web breaks down today, but as @turt2live, we don't currently support mobile web, so we'll likely be relying heavily on interested community member to help patch issues like this.

**Comment by tawfiek** [comment]
I am interesting to work on that  can you assign it to me ?! @jryans

**Comment by SimonBrandner** [comment]
@tawfiek, I've assigned you to the issue

**Comment by tawfiek** [comment]
I added the ability to toggle the `LeftPanel`  by clicking the bottom area under the list of rooms. 
I know it's not a valid UX but I just make it  to implement the functionality first.

Now I got confused about the right UX to do that.
Since we don't support the mobile view should we just add a  burger icon to toggle the menu or go ahead and implement a swipe event on the left panel on mobile and take the chance to make the app more mobile friendly ?!
lets discuss it  : @SimonBrandner @jryans

**Comment by SimonBrandner** [comment]
Swiping isn't good UX since that is the way you go back on Android 10... I am not sure what would be the ideal solution here. This is probably something for the Design team to figure out. But they are quite busy and this isn't even officially supported so they _will_ prioritise other things... So I think you either need to figure out a UX yourself or move onto another issue. Trust me there is a lot to choose from :D People in [Element Design](https://matrix.to/#/#element-design:matrix.org?via=matrix.org&via=privacytools.io&via=kde.org) _might_ be able to help you

**Comment by ShadowJonathan** [comment]
(Have you tried [hydrogen](https://github.com/vector-im/hydrogen-web)?)

**Comment by tawfiek** [comment]
Yea in hydrogen the `LeftPanel` take full side in small screens but in the element it collapsed should I clone the same behavior from hydrogen into element. 
I don't thing it's a good idea !

**Comment by novocaine** [comment]
This is S-minor because we don't support mobile browsers and there is a simple workaround: view it as a desktop site

![desktop-site](https://user-images.githubusercontent.com/57377/130827299-7e3c2cd2-1ac9-4e4d-9c35-abb3004e0bf4.png)
