### ISSUE TITLE
Message for ACL change should be collapsable

### ISSUE THREAD

**Issue by aaronraimist** [vector-im/element-web#12474]
and probably collapsed by default

ACL changes create a lot of gunk in the timeline, especially as the list of ACLed servers grows. Also someone could easily use offensive language in the server name and it would be displayed to everyone in the room when they are banned by a server ACL.

<img width="826" src="https://user-images.githubusercontent.com/5855073/75085117-a0cc1b00-54eb-11ea-8154-d73371ffff22.png">

**Comment by ilmari** [comment]
This appears to be fixed now, e.g. in #homeowners:matrix.org I just saw the following:

![Screenshot from 2021-05-06 12-09-29](https://user-images.githubusercontent.com/72175/117289126-25425980-ae64-11eb-8471-1575cc676c27.png)

Or is that just because the ACL is too long to show?

What I would prefer is something like the message edit history, where you can click to see what was added and removed.

**Comment by turt2live** [comment]
I'm going to count this as fixed - please open a new issue if this doesn't feel fixed.
