### ISSUE TITLE
Editing messages that contain markdown quotes inserts a newline after the `>`

### ISSUE THREAD

**Issue by jeffcasavant** [vector-im/element-web#12535]
### Description

When editing a message containing a markdown quote, Riot will insert a newline that has to be manually removed to retain the quote formatting.

```
> This is my original message
```

when edited, becomes

```
>
This is my original message.
```

### Steps to reproduce

- Send a message of the format above.
- Begin to edit the message either via the pencil button or the up arrow.

Logs being sent: yes

<img width="279" alt="Screen Shot 2020-02-26 at 1 41 16 PM" src="https://user-images.githubusercontent.com/2212754/75376247-bc457600-589d-11ea-9bc9-01e0864a7077.png">

<img width="464" alt="Screen Shot 2020-02-26 at 1 41 26 PM" src="https://user-images.githubusercontent.com/2212754/75376256-bea7d000-589d-11ea-80e8-620096ec3b90.png">

### Version information

- Riot-Desktop 1.5.10
- macOS

**Comment by AgentOak** [comment]
This is super annoying because of #16069. About half of the time when I quote something I forget to do a double newline, like so

```
>quote
comment
```

Element includes both lines in the quote so I edit my message to insert the extra newline, but then Element shows the message source as this:

```
> 
quote
> comment
```

Not only has it inserted a newline like OP describes, it also inserted multiple unnecessary spaces and an additional quote character. This is quite a mess and super annoying because it requires multiple edits/jumps to undo all the changes.
(Confirm for Element 1.9.0)
