### ISSUE TITLE
The 'recently messaged N minutes ago' text on the invite dialog is sufficiently confusing that we should hide it until it's fixed

### ISSUE THREAD

**Issue by ara4n** [vector-im/element-web#12834]
I'm not sure people care about when they last DMed someone (particularly with our weird definition of DMs, and the feeling that even then the timings can be wrong).  It's very jarring if you're talking to Bob in a private room, then try to invite them to a new room, and it says '5 weeks ago', despite the fact you were just talking to him.  For now, i wonder if we should just hide it? cc @nadonomy

**Comment by nadonomy** [comment]
Without it the ordering of the list is ambiguous. I find the feature incredibly useful— rather than hiding it what about if we renamed the section from 'Recent Conversations' to 'Recently Direct Messaged'?

That way it's clearer, doubly so when entering from the Create DM journey, and it solves this issue, while not removing useful functionality or making the sort order of the list more ambiguous.

**Comment by turt2live** [comment]
I feel like this was supposed to be actioned 2 years ago, but we didn't. Closing as no longer required - if this is untrue, please open a new issue with fresh information.
