### ISSUE TITLE
Select-all when clicking on EditableText breaks linux clipboard

### ISSUE THREAD

**Issue by ara4n** [vector-im/element-web#1287]

**Comment by afranke** [comment]
Just tried with Firefox 91 on Wayland. In a room where I am an administrator, when I click in the topic textarea, there is no “select-all”. Selecting text in another window and then middle-click-pasting in this textarea works as expected. I’ll go out on a limb here and assume this behaviour has been removed in the 5 years since the last activity here, and close this issue now. Feel free to reopen if it actually still is an issue with recent versions of the software.
