### ISSUE TITLE
Input field animations have too many frames

### ISSUE THREAD

**Issue by ghost** [vector-im/element-web#12876]
### the Email/user/phone and password box in the login page animation should have fewer frames and be more fluid, or even just jump from the middle to the top instantly (1 frame)

the problem is that this look crancky and not refined to have the same title two times in the same box

### Steps to reproduce

- open login page
- click on the email and password boxes

the expected function would be 2/3 frames or even just one so that it doesnt feel laggy or unrefined.

https://cloud01.opsdata.ch/index.php/s/pL5bGxRntjGmsCB

**Comment by turt2live** [comment]
This would apply to all fields across the app

**Comment by sk-alexis** [comment]
@turt2live  I only tested on login page in the password and user/email field. For example when Phone is selected this issue disappears because of the countrie indicative box. This is more an esthetic bug than anything else so not that priority. But should be pretty easily to fix. It an-shame my codding skills are still not there, to commit a PR for it. In the video you can notice it pretty easily.

**Comment by sk-alexis** [comment]
@turt2live is not to few but to many, in the title.

**Comment by MadLittleMods** [comment]
The original video isn't available anymore. I only see some slight crunchiness on Firefox on Windows but this feels like a problem with the way Firefox does `position` animations. It looks like we could make it smooth by using `transform: translateY(-13px);` instead of `top: -13px` .

On macOS 11.1, both Chrome and Firefox feel smooth.

Windows 10, Chrome 95.0.4637.2 (feels nice and smooth)

https://user-images.githubusercontent.com/558581/132748756-b28b9535-358f-4903-b63a-7aed3dc9339e.mp4


Windows 10, Firefox 92.0 (feels a bit crunchy)

https://user-images.githubusercontent.com/558581/132748825-4828f2b1-ffb0-461e-acea-4457de746908.mp4
