### ISSUE TITLE
Trying to search in E2E encrypted rooms without Seshat should error

### ISSUE THREAD

**Issue by ara4n** [vector-im/element-web#12896]
Rather than silently failing.

Similarly FilePanel.

**Comment by t3chguy** [comment]
But what about a room that has unencrypted history?

**Comment by ara4n** [comment]
perhaps we put a warning in the search results saying that hits may be missing; go use riot/desktop if you want it to work

**Comment by t3chguy** [comment]
This was mentioned in #4982 before it got closed

**Comment by bwindels** [comment]
Probably needs some design?

**Comment by nadonomy** [comment]
Some notes from quick internal discussion on solving this:

- We think it's preferable to advertise the value adds of the desktop app (rather than e.g. not showing the panel at all)
- If we're advertising the desktop app, we should consider Element admins who don't want to drive traffic to the desktop apps (e.g. private deployments)— should we make a flag to disable this? or can we be smarter with whitelisting domains? etc

**Comment by lampholder** [comment]
We're already planning a flag for this: https://github.com/vector-im/element-web/issues/15184

**Comment by nadonomy** [comment]
Closing as this is now fixed in https://github.com/matrix-org/matrix-react-sdk/pull/5225
