### ISSUE TITLE
MessageComposer does not resize correctly when contents are modified externally.

### ISSUE THREAD

**Issue by aviraldg** [vector-im/element-web#1293]
(without keypress)

**Comment by ara4n** [comment]
especially obvious on insert-to-click

**Comment by afranke** [comment]
I just tried on Firefox 91 on Linux (Fedora 34, GNOME, Wayland), selecting multiple paragraphs of text in another window and pasting it with middle click in the composer.  It works as expected. Not surprising that an issue that is 5 years old might get fixed in the meantime. Closing, feel free to reopen if you can reproduce, and please provide explicit steps as well as details of your platforms.
