### ISSUE TITLE
Email addresses do not show up in the Settings tab

### ISSUE THREAD

**Issue by schopenhauer** [vector-im/element-web#13033]
### Description

After registering and validating a new email address in Riot-web, the new address does not show up in the Settings tab.

### Steps to reproduce

1. Add new email address
2. Validate new email address via confirmation email
3. Click on the 'Continue' button and enter password
4.- Done.

The expected result would be to see the newly added email address, but the email address does not show up in the list. In fact, the list remains empty, even if I add additional email addresses, although the system reminds me that the email address is already in use, when I retry with the same address.

### Screenshot (after adding email address)

![image](https://user-images.githubusercontent.com/2085103/78472216-67680b80-7737-11ea-85a2-c88f85dac609.png)

### Version information

- **Platform**: web (in-browser)
- **Browser**: Firefox 74.0.1
- **OS**: Manjaro Linux
- **URL**: private server running v1.5.15

**Comment by dreamerchris** [comment]
I noticed that when I click in the input box of "add email" my email shows in a few seconds

![before clicking the input box](https://user-images.githubusercontent.com/51272727/79696608-5adec980-8286-11ea-9c78-cd8b232ae815.png)
![after clicking the input box and waiting a few seconds](https://user-images.githubusercontent.com/51272727/79696609-5ca88d00-8286-11ea-9a34-468380358341.png)

**Comment by t3chguy** [comment]
This is just matrix.org being slow. On other servers it is near-instant.

**Comment by betimi91** [comment]
In our server we have same problem as @schopenhauer who opened this issue. We are using matrix in our University so user registers through RIOT client, receives confirmation email clicks it and gets confirmed. 

It authneticates it uses system without any further problem in future even receives notifications and others can invite and find him by email etc but in his settings under profile email shows empty when it tries to add it it says email address is already in use.
Users can login with email or username in future and so email is already in database PostgreSQL!
![image](https://user-images.githubusercontent.com/20134140/79696989-4ef00900-8280-11ea-8544-70a0037ed9e9.png)

So its just a view issue in RIOT which needs a fix soon.

**Comment by t3chguy** [comment]
It is *not* an issue in Riot. It comes from the 3pid API.
![image](https://user-images.githubusercontent.com/2403652/79697300-db4afd80-8279-11ea-9f50-b7d9247b7fd5.png)
![3pid](https://user-images.githubusercontent.com/2403652/79697309-df771b00-8279-11ea-9aa0-f2965ee59a34.gif)
so if this 3pid API is slow in Synapse/whatever is servicing that API then it'll take time to show up.

**Comment by schopenhauer** [comment]
Strangely enough, Riot.im 0.9.10 correctly shows the email addresses on my Android phone, but neither Riot X, nor Riot Web show any email addresses.

**Comment by aaronraimist** [comment]
@schopenhauer your server is probably out of date

**Comment by cg505** [comment]
I noticed that fetching 3PIDs will fail if whenever the IS does not sucessfully respond (except for `"M_TERMS_NOT_SIGNED"`):
https://github.com/matrix-org/matrix-react-sdk/blob/36ccb7e75270669ee7ba0bf442f84f10ff864f6f/src/boundThreepids.js#L52

This is counterintuitive behavior. Just because there is a problem with the IS does not mean that I don't have 3PIDs on my account. For instance, testing a homeserver on localhost will cause vector.im to throw 500 errors. This means that I cannot see _any_ emails that might be associated with my homeserver account (valid as they may be).

Instead it seems like we should simply return 3PIDs without bound info when the IS errors. Maybe a warning message would be in order, but the function should still work. I can submit a patch if this seems reasonable.

**Comment by schopenhauer** [comment]
> @schopenhauer your server is probably out of date

My server is running Synapse 1.12.4, but I suspect the problem could be linked to what @cg505 has described above. If the problem was on the Synapse-level, then the email address would not show up in any of the Riot clients.

**Comment by rootuser** [comment]
I am also experiencing this issue, and maybe I can contribute a few details to this discussion.

Firstly I can confirm @schopenhauer 's experience; basically emails are shown in riot.im, but not in riot-web and riotx.

Secondly I have already tried this with users registered via riot-web, via the Synapse admin API and users fetched from an LDAP database via ma1sd.

In any of the cases email adresses are only shown in riot.im on my Android phone. Even all three email addresses of one of my LDAP accounts are shown there.
In the other clients no 'tricks' are helpful; waiting some time or clicking in the email text box do not make any difference here.

Registering an email adress in riot web works, but after that it is not shown either. Trying to re-register that same address results in an error, because it is already there (but not displayed). 
So it is 'simply' a display problem it seems.

Requesting the 3PIDs via the client-server API always cleanly results in a list of all contained email addresses for the user account. In contradiction to what has been reported above, there are no delays at all.
So to my mind @t3chguy is wrong in saying that this is not a riot bug.

My synapse server is up to date; installed via the matrix-docker-ansible-deploy script.
Server version: 1.12.4, Python version: 3.7.7, riot-web version: v1.6.0, olm version: 3.1.3

Please remember that not only the email adresses are not visible. Even more important to me is the fact that discovery options for email cannot be edited either for 'non-existing' emails.

To conclude, I beg you to take this issue seriously.

Best, Tom

**Comment by t3chguy** [comment]
Try riot.im/develop - it now has a loading spinner which will show whether the app is waiting on the server to tell it what the identifiers it knows are or not: 
![image](https://user-images.githubusercontent.com/2403652/81931124-83d25000-95e1-11ea-94ce-b49c7f257ae6.png)

**Comment by rootuser** [comment]
Hi,

thanks for your reply!

In the meantime I don't think I have to try that any more, because I found something else:
(perhaps I should have done that before) I have activated developer features in my browser now, and when opening the settings dialog of the user I get the following error:

> Access to XMLHttpRequest at 'https://matrix.mydomain.de/_matrix/identity/v2/account/register' from origin 'https://riot.mydomain.de' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.

As far as I know that basically means that requesting data from domain matrix.mydomain.de by a script on domain riot.mydomain.de  is denied.

So the response of the identity server (matrix.mydomain.de) is consequently
> HTTP/1.1 405 Method Not Allowed

I suspect this is due to a configuration problem, but I have no idea how it occurs or if it is my fault.

Any hints?

Thanks!

**Comment by t3chguy** [comment]
Yup, seems like your reverse proxy isn't adding the required ACAO (`Access-Control-Allow-Origin`) header for other origins (domains) to be able to access it.

**Comment by schopenhauer** [comment]
I presume this HTTP header need to be set by Riot Web when making the request, or is this set somewhere in the reverse proxy configuration?

**Comment by t3chguy** [comment]
Riot Web is the thing making the web request. it runs entirely in your browser.

So yes, your reverse proxy should be adding this header.

**Comment by 0x46616c6b** [comment]
I stumbled upon this error message also after setting up my own Identity Server (ma1sd). I noticed that ma1sd in latest stable release (`2.3.0`) not enable the `v2` api prefixes by default. After enabling them it worked. 

Try to fix that here spantaleev/matrix-docker-ansible-deploy#511

Maybe this is also related to your problems.

**Comment by turt2live** [comment]
I am presuming this is fixed - if it's not, please visit one of the community support rooms for troubleshooting.
