### ISSUE TITLE
New invite dialog wraps text entries despite there being ~300px of whitespace on the right of the input field.

### ISSUE THREAD

**Issue by ara4n** [vector-im/element-web#13066]
![2020-04-07 21 55 32](https://user-images.githubusercontent.com/1294269/78718624-8b377700-791a-11ea-81dd-b66a16561249.gif)

**Comment by turt2live** [comment]
Presumably this is what https://github.com/vector-im/riot-web/issues/12282 was trying to say

Would be fixed as part of https://github.com/vector-im/riot-web/issues/12205 because the composer hack is actually a tiny text field in a bigger container (like the old dialog). Will keep this open to track it separately though.

**Comment by ara4n** [comment]
this is really painful - basically any medium or larger size mxid triggers the bug.
