### ISSUE TITLE
Consider unifying user colours with avatars

### ISSUE THREAD

**Issue by nadonomy** [vector-im/element-web#13490]
<img width="232" alt="Screenshot 2020-05-04 at 13 50 59" src="https://user-images.githubusercontent.com/4626865/80967454-51209e80-8e0e-11ea-9da2-42702ea4d215.png">

Presently we only use 3 colours to fill avatars, and 8 colours to decorate users. Should we fill avatars with the same colours? The palette may need tweaking.

---

 - consistent display name and avatar color

**Comment by HarHarLinks** [comment]
> of course it looks good in the timeline, but it also starts to really change the look and feel of the room list, introducing a lot more visual noise:

![image](https://user-images.githubusercontent.com/48614497/125883683-39d63a5a-edaa-452f-b21b-99528ff6d697.png)

my thoughts:
- rooms don't need to adhere to this since they're not as representative of the conversation partner (if it is only 1) as a DM
- users usually have avatars anyway?
- so do my rooms
- one could argue that it isn't noise, but recognizability by not everything sharing the same color

**Comment by robintown** [comment]
This has been done in https://github.com/matrix-org/matrix-react-sdk/pull/11470
