### ISSUE TITLE
More explicit black shield tooltip proposal

### ISSUE THREAD

**Issue by tredondo** [vector-im/element-web#13566]
I like the new black shield for unverified conversations in 1.6, because it's not as scary as the red one and the room is after all E2E. For upgrading users, this is great.

But for users new to Riot, the tooltip may offer a slight sense of false security...:

![image](https://user-images.githubusercontent.com/10043369/81233203-19029280-8fab-11ea-8ea2-8d404ceef9a0.png)

...because while the room is encryped, some participants may be unverified.

Proposed change: keep the shield black, amend its tooltip to: "This room is end-to-end encrypted, but not everyone is verified".

**Comment by Thatoo** [comment]
It is very confusing. Both on RiotX and Riot-desktop, I experiment verified cross-signed users who had verified their own devices shown with a black shield on Riot -desktop (red-shield even on RiotX) even though on Security info they have a green verified shield for all their devices and we verified each other.

**Comment by Thatoo** [comment]
![image](https://user-images.githubusercontent.com/464782/82126768-08be9480-97af-11ea-9598-d178056d413a.png)
Both devices have been verified, they are cross-signed too we verify each other and still his shield remain black. Is there something we missed?

**Comment by t3chguy** [comment]
The verify button is still there which means you didn't verify with cross signing each other.

**Comment by Thatoo** [comment]
Then this is unclear indeed because we tried at leats 3 times because of this black shield and at the end, we both get a green shield saying that it is fine but once we click on a green button "compris" which I guess in english would be "understood", nothing happened... 
I realise now that we never got the message "you have verified..." as I got for other contacts, it stays at "you have sent a request" and "... has accepted". So it seems that verification through cross-signing has been aborted each time but we didn't get noticed.
What can be the reason it got aborted? How to solve this issue?

**Comment by Thatoo** [comment]
We tried again. No success... Can it be because we use different synapse server, him using matrix.org and me a self hosted server?
All of us using our self hosted server could verify each other with cross-signing but I can't verify this particular person. We go through the emohi verification, it says it's ok in the right side bar but it doesn't display in the chat that it was ok... and verification has obviously failed.

**Comment by Thatoo** [comment]
Aha, an interesting fact tonight is that now, I appear green on his side. It seems that for him, the verification through cross-signing has finally worked. However, on my riot-desktop he still appears black and I can still launch the verification (he can't launch anymore, he doesn't have the he verify button).

**Comment by Thatoo** [comment]
I guess my issue is described in here as we both are on different servers : https://github.com/vector-im/riot-web/issues/13204

**Comment by dbkr** [comment]
It's a tough call but I think we're resolute on keeping it simpler and keeping verification out of the picture unless users want to verify, although obviously we'll continually reevaluate these decisions.

@Thatoo you're reporting an unrelated bug: please open a new one if it's still a problem.
