### ISSUE TITLE
Less verbose ACL change messages

### ISSUE THREAD

**Issue by Twi1ightSparkle** [vector-im/element-web#14216]
**Is your suggestion related to a problem? Please describe.**
When a server is banned, this message is posted to all rooms

```
Abuse Management changed the server ACLs for this room: Servers matching matrix.veryoffensivedomain.com are now banned.
```

**Describe the solution you'd like**
Hide the message or domain in some way to not post the offensive domain for everyone to see, while still somehow having the list of banned domains available to all room members

**Comment by Half-Shot** [comment]
This is difficult, because it's a state change in a room so it's quite important to make it visible. A case would be where a user complains about `@mroffensive:matrix.veryoffensivedomain.com` in a room. The moderators react by banning the server from the room, but the user would never see the ACL in the timeline and would likely be confused as to what action the moderators have taken, being unable to see the ban themselves. Hiding the event altogether would probably be as disruptive as showing it.

One option might be to hide the domain name and only show it on mouseover, to at least mask it from view during normal conversation. It still allows users to see the action taken, without having it visible on their screen all the time.

Alternatively, we could display "The ACLs for this room have been updated", and the ACLs could be visible from room settings.

**Comment by jryans** [comment]
I have added this to the product backlog as well.

**Comment by Twi1ightSparkle** [comment]
We should also consider the same for display name changes. Currently they read:
`OffensiveUsername changed their display name to PlaceholderUser`.

**Comment by Half-Shot** [comment]
So a thing I thought about that we could do to protect people is have it be a riot config,json setting, where some events are quieted. 

This doesn't help people on different clients/servers, so perhaps moderators can provide their own hint state event flags to hide events unless the user wants them visible, but I worry about the problem of admin abuse and having their actions be hidden.

**Comment by Cadair** [comment]
I can't really +1 this hard enough. I just subscribed to the matrix.org CoC banlist and got a lot of domain names show up in a lot of channels that I really would rather didn't. Hiding it behind a click would make all the difference here, so it shows "the servers allowed to participate in this room have changed, click for details" or something would be great.
