### ISSUE TITLE
The new globe icons are unrecognizable

### ISSUE THREAD

**Issue by dkasak** [vector-im/element-web#14608]
As the title says, the new globe icons are pretty much unrecognizable. None of the users (around 10 of them) who I've switched over to Matrix have been able to tell what it is meant to represent. I've also had trouble recognizing it myself, but then I remembered that there was previously confusion about locks and discussion about switching over to globes, which is the only thing that made it click.

- **OS**:  Arch Linux
- **Version**: 1.7.1

**Comment by dkasak** [comment]
I've just now seen a screenshot of Element's light theme where the problem is a bit less pronounced due to swapped colours, but still quite problematic IMO.

**Comment by t3chguy** [comment]
They do also have a tooltip
![image](https://user-images.githubusercontent.com/2403652/87850758-88b9c580-c8ea-11ea-8cc4-ce747d7decfb.png)

**Comment by odiferousmint** [comment]
Oddly enough I do not have those icons in Element (Arch Linux, element-desktop-1.7.1), but I did have them in Riot. IIRC there was an icon for the room being encrypted and having everyone verified in the room.

**Comment by odiferousmint** [comment]
I will just upload it here because of its relevancy. I think the encrypted icon should be more visible with the dark theme:
![2020-07-19-003248_389x97_scrot](https://user-images.githubusercontent.com/43568459/87863074-893c7580-c957-11ea-83d3-306cbb94f232.png)

**Comment by turt2live** [comment]
@odiferousmint that's an entirely different problem.

**Comment by odiferousmint** [comment]
> @odiferousmint that's an entirely different problem.

Well, the globe icons are indeed unrecognizable on both Element Desktop and Element Android with the dark and the black theme. It is just too dark. For the time being I am resorting to using the light theme. Do you want me to create a new issue for this with screenshots?

**Comment by t3chguy** [comment]
I spun that off to https://github.com/vector-im/riot-web/issues/14649

**Comment by niquewoodhouse** [comment]
My favourite description of the current icon is a dolphin flexing their arm 🤣   Not. the. best. icon. ever. 🤦 

Here are some rough alternatives, I would be interested to know if any of these feel more like a globe to anyone, or if any of the non-globe options feel like a more appropriate way to say "this is a public room" and why.  Please feel free to be as honest as you can - if anything feels like a dolphin its good to hear 😄 

At the moment, these icons are 8x8, here are some 8x8:

<img width="375" alt="8x8@2x" src="https://user-images.githubusercontent.com/1587166/88387477-691f1300-cdaa-11ea-8eb8-ee78424c099c.png">

We could boost to 10x10, which gives a tiny bit more space for complexity:
<img width="375" alt="10x10@2x" src="https://user-images.githubusercontent.com/1587166/88387487-6fad8a80-cdaa-11ea-83f7-1cfeef8daeb8.png">

Here are some of the most different with the same existing size (8x8) (in context and light theme). Click to see them at actual size.

**Globe 2**
<img width="1199" alt="public-room-icons4@2x" src="https://user-images.githubusercontent.com/1587166/88387683-e9457880-cdaa-11ea-8568-51f025fbe4ee.png">


**Globe 3**
<img width="1199" alt="public-room-icons3" src="https://user-images.githubusercontent.com/1587166/88277709-10337a00-ccd9-11ea-85b9-2964eed89361.png">

**Hash**
<img width="1199" alt="public-room-icons5@2x" src="https://user-images.githubusercontent.com/1587166/88387823-39243f80-cdab-11ea-91d2-b5bfd01e92fd.png">

**Comment by odiferousmint** [comment]
I personally prefer the hash ones, specifically the one in the last screenshot.

**Comment by dkasak** [comment]
I too like the hash ones provided that they are intuitive for this purpose to a representative sample of users. On a small non-representative sample of users I've shown this to, the wireframe globe with the densest lines was preferred. I tend to agree that's most recognizable as a globe as I had the same idea.

**Comment by niquewoodhouse** [comment]
Thanks for the info @dkasak @odiferousmint 👍  

I also liked hash, and in some wider testing it was the most popular,  but at the moment the hash is used to mean different things across different apps in Element.  So I think we'd have to make quite a few non-room list web amends to make this consistent.  Would really like to do that but it would delay a 'quick' fix.

In some further testing of the globes metaphor there wasn't much of a discernable difference between the wireframe and fill versions.  Because the latest icon language in Element uses fills to communicate most things, in a design review it was decided to try the fill version and see if confusion continues at the same pace.  

I can totally see the need to take a more comprehensive look at this in the future, but it should be scoped accordingly to make `public` make sense across all platforms for consistency.  

<img width="60" alt="Screenshot 2020-08-04 at 12 36 04" src="https://user-images.githubusercontent.com/1587166/89289419-203f4800-d64f-11ea-96cf-14721d50ad98.png">

<img width="65" alt="Screenshot 2020-08-04 at 12 36 08" src="https://user-images.githubusercontent.com/1587166/89289413-1d445780-d64f-11ea-832d-18ed01f6973b.png">

[Design link](https://www.figma.com/file/rHnynEgrePUtXVear8rGT0/34-Room-List?node-id=2697%3A6242).

**Comment by dkasak** [comment]
@niquewoodhouse: Sorry, I didn't quite get what was decided as the solution from your last comment. Are you saying the current icon will be kept without changes? The Figma link requires you to be logged in so it didn't help much.

**Comment by 532910** [comment]
I'd say matrix-org/matrix-react-sdk#5106 doesn't fix this.
Globe should look so: https://duckduckgo.com/?q=globe+icon&iax=images&ia=images
