### ISSUE TITLE
New Room list v2 makes it harder to find the Explore button

### ISSUE THREAD

**Issue by dannycolin** [vector-im/element-web#14617]
### Description

With the new Room list v2, the Explore button is now only an icon. This reduce its discoverability for new users because 

1. it's hard to explain to them where to go
2. the current icon is too small and we can barely see that it represents a compass

### Steps to reproduce

- Search for the Explore button in the UI

I think re-adding the text "Explore" and enlarging the icon could make it easier for new users.

Here's an example with the text re-added:
![image](https://user-images.githubusercontent.com/7339076/87856087-88212f00-c8ea-11ea-94f8-0aea163defee.png)

Logs being sent: no

### Version information

- **Platform**: Web

For the web app:

- **Browser**: Firefox Nightly
- **OS**: Fedora 32
- **URL**: Element 1.7.1

**Comment by aaronraimist** [comment]
Hopefully with them flip flopped from that screenshot so it matches the order of the old room list

**Comment by dmose** [comment]
Having the word "explore" would definitely help a bunch.  That said, I suspect that visually attaching the tiny button to the right end of the search widget would have made it more obvious to me that it was likely to help...

**Comment by niquewoodhouse** [comment]
@dannycolin thanks for raising this :) Got some follow up questions if that's ok, just to learn a bit more.  

As an experienced user, how often do you use "explore"?  What kind of things are you looking for?  How often do you use "search"?  I wonder if treating them equally makes search look less like a functional search field, so it becomes a bit harder to find in those frustrating times when you just quickly want to find someone/something.  

With @dmose's suggestion, I like that the search will still feel like the primary thing there, and this is a secondary way to find something.

One other option might be treating them slightly differently and vertically, giving more space for copy.

<img width="249" alt="Screenshot 2020-07-23 at 15 36 10" src="https://user-images.githubusercontent.com/1587166/88299433-40d7db80-ccfa-11ea-85ae-6fae2c1a518d.png">


Or it might be that it's worth spending time on introducing other ways to help new users by promoting explore in other ways.
- Encouraging them to explore with a helpful/annoying onboarding tip
<img width="477" alt="Screenshot 2020-07-23 at 16 43 27" src="https://user-images.githubusercontent.com/1587166/88307299-ad0b0d00-cd03-11ea-95c4-4bc72f27ca4c.png">


- Add something to their list of rooms if rooms number is less than 20 (for example).
<img width="247" alt="Screenshot 2020-07-23 at 16 56 20" src="https://user-images.githubusercontent.com/1587166/88308833-71714280-cd05-11ea-8606-20c8191f6ef9.png">

**Comment by dmose** [comment]
One of the things that actually surprised me was that "Search" only searched my existing rooms.  If that's a common reaction, it may be worth considering reframing somewhow...

**Comment by dmose** [comment]
I would have actually expected Search to search both my existing and other rooms, perhaps putting my rooms at the top of the list, visually distinguished from the other results in some way.

**Comment by dmose** [comment]
I didn't really want to "Explore" at all -- I had a pretty good idea of what I was looking for.

**Comment by t3chguy** [comment]
Merging search (explore) into the room list would be tricky as how would you manage what rooms/networks to search for?

![image](https://user-images.githubusercontent.com/2403652/88316950-77b8ec00-cd10-11ea-8424-8cf0db48819d.png)

**Comment by dannycolin** [comment]
> As an experienced user, how often do you use "explore"? What kind of things are you looking for? How often do you use "search"? 

I don't use it a lot now. Maybe a few times a month and it's mainly to help someone else to find the right room on mozilla.org to ask their questions. But if I use it for my own needs, it's primarily to look at other servers room directory. I also don't use the search that much because the filter doesn't reset after choosing a room. 

I really like the onboard tip and the idea of adding an "explore" thingy to the list if there's less than 20 rooms in it. I think it'll let enough time for newcomers to associate the compass icon to the explore functionality.

**Comment by niquewoodhouse** [comment]
> I don't use it a lot now. Maybe a few times a month and it's mainly to help someone else to find the right room on mozilla.org to ask their questions. But if I use it for my own needs, it's primarily to look at other servers room directory. I also don't use the search that much because the filter doesn't reset after choosing a room.

Thanks for the info @dannycolin - really helpful.  Feels like you don't use explore that much generally because it's not regularly that useful, and separately you don't use search much because search doesn't actually work in the way it should for you.  Is that a fair assessment?  If search worked in the way it should for you, could you see yourself using it more?

If so, I think this insight says to me that it's fine that search is larger than explore, for your use, but that it's usability needs to be improved to actually become worthy of being larger.  The new user case we've chatted about a bit above and maybe some of those ideas are worth looking into separately.

**Comment by niquewoodhouse** [comment]
> One of the things that actually surprised me was that "Search" only searched my existing rooms. If that's a common reaction, it may be worth considering reframing somewhow...

That's really interesting @dmose.  I could totally understand if that was a common reaction. 
Just curious, what do you think helped you expect it to be search both your rooms and all public rooms?  

For example:
-  is it because it's shown prominently in the room list (so maybe it looks more like a global search)?
- that its labeled "search" not "filter"?

Thanks

**Comment by dmose** [comment]
I would say that it's both of those things, almost exactly.

**Comment by dannycolin** [comment]
> Thanks for the info @dannycolin - really helpful. Feels like you don't use explore that much generally because it's not regularly that useful, and separately you don't use search much because search doesn't actually work in the way it should for you. Is that a fair assessment? If search worked in the way it should for you, could you see yourself using it more?

Yes. I'd probably use it most of the time since it'd be almost the same behavior as my app launcher so it's a pattern I'm used to.

> If so, I think this insight says to me that it's fine that search is larger than explore, for your use, but that it's usability needs to be improved to actually become worthy of being larger. The new user case we've chatted about a bit above and maybe some of those ideas are worth looking into separately.

Definitely. The onboarding solution + the larger search input for regular users seem to be a good solution.

**Comment by ItielMaN** [comment]
I'd consider myself an experienced user when it comes to finding my away around unfamiliar UIs, but it took me around 5 minutes to find how to join an existing room.

Possible solutions:
1. The first screenshot in [this comment](https://github.com/vector-im/riot-web/issues/14617#issuecomment-663088555)
2. The last screenshot in that comment (note that the middle screenshot wouldn't have helped me, because I'm usually annoyed by "tour" UIs and I tend to close these popups without actually reading them. I know it'd probably my fault, but I doubt I'm the only one doing that), but always display that button and not if rooms < 20 or something, because where would that button go if rooms > 20? We'll be back to square one.
3. I would have liked to find the room with the main Search option, but unsure how the resulting UI would distinguish people/rooms from my list vs. rooms to join.
4. **My preferred solution:** Because creating a room seems to be **way less** common than joining one (untested hypothesis but I think this is right), I'd suggest making the `+` icon **search for rooms**, with a `Create New Room` button in that UI. Same as what the UI in the mobile app is doing. If that's not an option, add another icon on the left side of the `+` icons. The `Explore` one or whatever.

**Comment by niquewoodhouse** [comment]
> 3. I would have liked to find the room with the main Search option, but unsure how the resulting UI would distinguish people/rooms from my list vs. rooms to join.

That's _really_ interesting - like what @dmose has mentioned above:

> I would have actually expected Search to search both my existing and other rooms, perhaps putting my rooms at the top of the list, visually distinguished from the other results in some way.

Maybe using the room section instead of a modal might give more space for results.  Splitting results into sections `rooms you're in` etc would help people not get lost in hundreds of potential results when looking for something they're quickly looking for.

<img width="1199" alt="search - 2" src="https://user-images.githubusercontent.com/1587166/89212093-cb51f200-d5ba-11ea-8c37-72a9152c76da.png">

Or trying to use the same space as the current room list.
<img width="1199" alt="search - 3" src="https://user-images.githubusercontent.com/1587166/89213878-b165de80-d5bd-11ea-8544-908996dd7dfd.png">



> 4. **My preferred solution:** Because creating a room seems to be **way less** common than joining one (untested hypothesis but I think this is right), I'd suggest making the `+` icon **search for rooms**, with a `Create New Room` button in that UI. Same as what the UI in the mobile app is doing. 

That's a really interesting solution.  The current `explore` modal on web has a `Create new room` option.  That option could be more prominent (eg below visual) but I think, because of the noise on the current explore page, it could be harder for people to start a new room without making wider changes to that modal.  You'd also have a slightly weird interaction going from a big modal (explore) to a smaller modal (new room) if you chose to start a new room which would be a bit jarring.  So, I think it's a really appealing solution but, to iterate it well, I think you'd need to take on some extra tasks and expand the scope.
 
<img width="1199" alt="explore-rooms" src="https://user-images.githubusercontent.com/1587166/89208626-9d69af00-d5b4-11ea-8fbb-dc7a87f1b4d8.png">

> If that's not an option, add another icon on the left side of the `+` icon. The `Explore` one or whatever.

That's cool but I think that could start to make the list section headers a bit more complicated, for example, when you have mentions in the list and when you hover over the list. It starts to get a bit heavy as a UI and makes it slightly harder to use the list.

<img width="260" alt="Frame 3101" src="https://user-images.githubusercontent.com/1587166/89209588-86c45780-d5b6-11ea-910f-f9a3cf056283.png">

An alternative way of doing this could be to use a similar dialog to other icons in the room list and explicitly ask users if they want to create a new room or explore public rooms.  It adds an interaction but it will let people choose their objective - and that information might be helpful on some level for testing the hypothesis that creating a new room is way less common than joining one.

<img width="1199" alt="add room dialog" src="https://user-images.githubusercontent.com/1587166/89210125-6fd23500-d5b7-11ea-94dc-219ab9791670.png">

**Comment by ItielMaN** [comment]
> An alternative way of doing this could be to use a similar dialog to other icons in the room list and explicitly ask users if they want to create a new room or explore public rooms. It adds an interaction but it will let people choose their objective - and that information might be helpful on some level for testing the hypothesis that creating a new room is way less common than joining one.
> 
> <img alt="add room dialog" width="1199" src="https://user-images.githubusercontent.com/1587166/89210125-6fd23500-d5b7-11ea-94dc-219ab9791670.png">

That's my new preferred solution, looks great.

**Comment by dannycolin** [comment]
@niquewoodhouse I really like the second screenshot where the results are shown in the room list. I also think adding a link to the Explore room in the dropdown menu when you click on the + is a good idea. If they click on the + in search of the Explore room, they'll see the compass icon and make the connection that the one on the left of the search input is the same functionality. 

Great mockup btw! It definitely helps seeing what the proposed solution could look like :)

**Comment by niquewoodhouse** [comment]
Thanks @dannycolin & @ItielMaN 😄 

I've spun off a couple of issues to look at the global search stuff @dmose & @ItielMaN reported & the early user experience @dannycolin mentioned above.  They're obviously really important but in the interest of improving the list quickly and keeping the scope small enough, let's go ahead with the "add room" dialog, as its using pre-existing components.  

Designs for the "add room" dialog are [here](https://www.figma.com/file/rHnynEgrePUtXVear8rGT0/34-Room-List?node-id=2692%3A108), for reference.
