### ISSUE TITLE
Frustrating popups when using Element on Android and in Web browser

### ISSUE THREAD

**Issue by tomdeck** [vector-im/element-web#14635]
### Description
When I log in via the Web client, the new session immediately creates a popup on the mobile client (Android) to verify the session. This requires at least 8 clicks:
Skip (web) - Skip (web) - Verify (mobile) - Verify (web) - Start (web) - They match (web) - They match (mobile) - Done (mobile) 
After which sometimes the web version hangs in the "Verify" popup.

Then I need to click "Close" for web notifications (which I don't want) and "Learn more" that element is the new riot and then "Done".

All this punishment, because I wanted to quickly type some text on my PC instead of the mobile keyboard...

Furthermore, old web sessions are retained indefinitely, although they cannot possibly be used again. This happens when you close the browser window without signig off and clicking on "I don't want my encrypted messages".

By the way, I don't have any encrypted messages. But even if I did, this tedious workflow with repeated steps is exactly what machines are for, aren't they?

Version numbers: 
Element 1.7.1 on the Web, in Firefox
Element 1.0.0 from F-Droid on Android
I'm using a private server, running Synapse 1.14.0

**Comment by jryans** [comment]
> After which sometimes the web version hangs in the "Verify" popup.

This part should now be fixed as part of https://github.com/vector-im/element-web/issues/14970.

> Furthermore, old web sessions are retained indefinitely, although they cannot possibly be used again. This happens when you close the browser window without signig off and clicking on "I don't want my encrypted messages".

You can remove old sessions in Settings -> Security -> check sessions to remove -> click Delete.

> By the way, I don't have any encrypted messages. But even if I did, this tedious workflow with repeated steps is exactly what machines are for, aren't they?

https://github.com/vector-im/element-web/issues/13895 will defer the cross-signing setup for new accounts until after you reach your first encrypted room. As for verification in general, there's no way a machine can (that I know of) correctly guarantee that a new device truly is you, so that's why each new device needs to be verified (only 1 time per device).

Since this covers many different topics, some of which are being improved or will be soon, I'll close this as I believe it will largely be addressed (or in the case of verification generally, I don't see what can be changed).
