### ISSUE TITLE
Backups are not being restored/used after verifying the new login

### ISSUE THREAD

**Issue by turt2live** [vector-im/element-web#14689]

**Comment by ara4n** [comment]
it looks like if you hit the 'restore keys' button in settings after logging in, it recovers itself (after minutes of loading keys).

**Comment by jryans** [comment]
Ah, I think I see what has happened... Currently, we only restore at login when you use your passphrase to verify the new device, and once upon a time that was the only way, but we have since changed to support verifying new devices without involving the passphrase.

I'll track this a part of the deferred cross-signing setup track.

**Comment by turt2live** [comment]
@jryans I'd still argue it keeps fire status given we've asked the entire world to log in on a new domain.

**Comment by jryans** [comment]
> we've asked the entire world to log in on a new domain.

That's true, but it's also hopefully a one-time event which is now over, and so perhaps the ship has sailed...?

If we fix this to also restore at login for non-passphrase, it would not magically help broken users, only new logins.

Perhaps separately we should explore some kind of "auto-restore if you encounter more than N undecryptable messages" or something, so there are other points in the app flow where we attempt an auto-restore?
