### ISSUE TITLE
Only create DM room when first message is sent

### ISSUE THREAD

**Issue by turt2live** [vector-im/element-web#14736]
Instead of eagerly creating a room, only create the room when a message is sent. This could also help us use the room list search as a way to start DMs if we wanted

**Comment by t3chguy** [comment]
I am certain this is a dup but cannot find it :'(

**Comment by MadLittleMods** [comment]
@t3chguy I think I found the duplicate in https://github.com/vector-im/element-web/issues/11495 but this is better to stay open as an individual issue

**Comment by jakewbate** [comment]
Since my issue was closed as a duplicate, copying the specific requirement here, and changing title to be a little more descriptive.

- As a user sending a DM to someone I do not have an active DM conversation with
- I want the room to be created only when I first send a message (text, image or voice)
- So that the recipient receives the invite only when there is a message in the room

**Comment by gaelledel** [comment]
@turt2live @t3chguy
I am updating the behaviour for Starting a DM. What changes is the mentioned above: We're only sending the invitation when user A (sender) sends a message to user B (receiver).
I would also be keen to allow message previews for user B when receiving an invitation see below.
<img width="674" alt="Screenshot 2022-01-04 at 11 16 22" src="https://user-images.githubusercontent.com/76945183/148051279-45859a4e-3059-4df8-a480-fc89d5edbb99.png">

Is this possible? For encrypted rooms, we could have the first few words with the rest encrypted.
This would help minimise spam requests and make user B more confident in starting the DM.

Thanks

**Comment by gaelledel** [comment]
See the flows here https://www.figma.com/file/OvsSONqAyabcUDYp8tnEs6/Start-a-Chat?node-id=0%3A1

**Comment by MurzNN** [comment]
@gaelledel maybe also add a "Mutual rooms with this user" button, which will show list all rooms (and spaces?) where both of users (current user and invite owner) are members? This should be very useful to understand from which source this person founds you. Because very often I receive invites from strange persons, and need to research in which rooms/spaces I see they before.

**Comment by turt2live** [comment]
The message preview is difficult, but we do have a concept of "invite reason" we could display.

I'd be worried that the first message preview isn't all that helpful (and easy to bypass for spamming), so would encourage us to look into peeking support on invited rooms instead - a much harder technical feat.

**Comment by gaelledel** [comment]
@MurzNN Yes, that's a good point thank you. Unsure if we'd be able to pull this info at the stage of the invite though. @turt2live might know actually.


Regarding:
> The message preview is difficult, but we do have a concept of "invite reason" we could display.
> 
> I'd be worried that the first message preview isn't all that helpful (and easy to bypass for spamming), so would encourage us to look into peeking support on invited rooms instead - a much harder technical feat.

Thanks for the feedback. Could you expand on the "invite reason" concept?

**Comment by t3chguy** [comment]
The mutual rooms suggestion is already WIP https://github.com/matrix-org/matrix-react-sdk/pull/4897

**Comment by gaelledel** [comment]
Good to know indeed thanks @t3chguy

**Comment by kittykat** [comment]
@gaelledel would it make sense to change the behaviour already to create room on first message while we wait for mutual rooms and figure out how to do the message preview/peeking?

**Comment by gaelledel** [comment]
Yes this is the plan. The designs have changed since to accommodate for this. We will be showing common rooms and spaces instead.

**Comment by erkinalp** [comment]
Multiple rooms with same members are possible in the protocol level, hence Element should not make this impossible.

**Comment by turt2live** [comment]
@erkinalp that's a different issue.

**Comment by ShadowJonathan** [comment]
(https://github.com/matrix-org/matrix-react-sdk/pull/8612 seems to be relevant to this effort.)

**Comment by weeman1337** [comment]
Testing plan for community testing session:

Setup: You should have at least two users available and logged in at the same time.

| Title | Description |
| --- | --- |
| Note | The following tests should target one DM partner. The expected result is that the partner got the invite, sees the message after he joined and that the room is end-to-end encrypted. |
| Start DM with text message | Start a DM by typing a simple text message |
| Start DM with one attachment | Start a DM by sending a file using the attachment button in message composer |
| Start DM with multiple attachments | Start a DM by sending multiple files using the attachment button in message composer |
| Start DM with attachment from clipboard | Start a DM by sending a file pasted from the clipboard |
| Start DM with one attachment from drag & drop | Start a DM by sending one file pasted to the room |
| Start DM with multiple attachments from drag & drop | Start a DM by sending multiple files dragged to the room |
| Start DM with poll | Start a DM by sending a poll |
| Start DM with sticker | Start a DM by sending a sticker |
| Start DM with location share | Start a DM by sharing your location |
| Start DM with live location share | Start a DM by sharing your live location |
| Start DM with voice message | Start a DM by sending a voice message |
| Note | The following tests can be done by sending text message |
| Start DM from „People +“ | Start a DM using the „+“ from the sidebar people section |
| Start DM from room member list | Start a DM using the „Message“ button in a room member list |
| Start DM from spotlight search | Start a DM by searching a user in the spotlight search (`Ctrl + K` or click into the top left search field) |
| Start DM with two MXID users | Start a DM by inviting two users having a matrix account |
| Start DM with e-mail user | Start a DM by inviting an e-mail address. After the other side joined the room should not be encrypted. |
| Start DM with one MXID user and one e-mail user | Start a DM by inviting two users: one with MXID and another by e-mail. After all have joined the room should not be encrypted. |

**Comment by Half-Shot** [comment]
There is a *slight* issue here that it's not a safe assumption to assume that just because you can start a DM with someone, it doesn't mean that the DM will be permitted by the remote side. E.g. 

- Lots of puppeted bridges will leave a DM if the Matrix user isn't connected to the bridged service (i.e. you're not logged into Slack, you cannot DM slack users)
- Some users will have their own mechanisms for automatically blocking DMs for users they do not already know.

This means that with this features, users could end up possibly typing a fairly lengthy message only to be told they cannot talk to the remote user. There is also a slightly more problematic side in that it's very likely some services will have race conditions between a invite and a message being handled concurrently (though, I am not sure how the proposed implementation works -> maybe messages are only sent upon join?)

This doesn't mean the feature isn't a good one, but it will degrade the experience for some users.

**Comment by giomfo** [comment]
@Half-Shot the potential race conditions problematic between the invite and the message has been taken into account by the implementation

About your first point, the contact picker should be improved to prevent you from selecting people you could not talk to. Can you provide some criteria/conditions to filter the contacts list?
