### ISSUE TITLE
Separate language and region

### ISSUE THREAD

**Issue by PreownedFIN** [vector-im/element-web#14861]
**Is your suggestion related to a problem? Please describe.**
I live in a non-English speaking country, but I use most of my apps/services/whatevers in English, as translations tend to be spotty at best, and plain up incorrect at worst.
I would like to set my region to my actual country, but I want to retain the English language in the UI.

**Describe the solution you'd like**
Separate settings for the region of the user, and the display language.
At best, this would be a simple - but vast - refactoring of the display/region fields.
At worst, a massive undertaking, making this pretty much unviable, but still a blunder in assumptions. (region = language)

**Additional context**
Could also be a headache for people travelling, and for some reason having to set their region to the local one. *Could.*

**Comment by t3chguy** [comment]
> I would like to set my region to my actual country

There is no concept of Region. Your Matrix account has no concept of even Language so the only configurable thing here is the UI (and spellcheck) language, what are you hoping to achieve with a "Region setting"?

**Comment by DuncanLithgow** [comment]
I think this would be a good idea. We can all choose to use all kind of technology to mask our browser and ip address. Being able to carry our language preference with us as a user would be a good idea. I've been struggling with an untranslated UI on element.io for a while now - it just occurred to me that it could be because I mask against tracking headers with privacy possum in Firefox. Once I turned that off I got back to English.

**Comment by t3chguy** [comment]
We have the language dropdown for this.
Settings > General > Language

![image](https://user-images.githubusercontent.com/2403652/96038152-a6051e00-0e5e-11eb-96c5-36ffe8703995.png)

Not sure why it says `and region` as it does not impact it whatsoever.

For other regional things like MSISDNs you specify the area code separately 
![image](https://user-images.githubusercontent.com/2403652/96038203-b7e6c100-0e5e-11eb-9ed8-b27cce58c306.png)
