### ISSUE TITLE
15 UI/UX improvements

### ISSUE THREAD

**Issue by TR-SLimey** [vector-im/element-web#14866]
I will comment each improvement separately below so they can be voted on separately. Here's an overview:

1. Decrypt/download media should be implicit
2. There should be an option to see the details of a message
3. View (Decrypted) Source should be in a sub-menu (like "Advanced")
4. Why is "share message" blue?
5. Why isn't "report content" red?
6. Menus could use some icons to separate the options
7. Reply to message covers new messages
8. Forwarding a message is **still** ugly
9. The small version of the new room list is kind of ugly
10. The integration manager is in permanent light mode
11. The share room UI looks a little out of place/ugly/unpolished
12. The read receipts should probably be at the bottom of messages
13. Some loaders, like the one shown when clicking the "Notifications" tab, are way off-center
14. The notifications tab is in the wrong place and quite ugly
15. Many tabs, windows and menus (at least in dark mode) have no borders which makes it hard to see what is part of what

(All of the above are from Element 1.7.2 on Desktop (Electron) - Ubuntu 20.04)

**Comment by t3chguy** [comment]
Meta issues like this make things really hard to track.

> Decrypt/download media should be implicit

This is not possible in certain browser configurations (undetectable) so Decrypt actually does trigger a Download for most users, but is split into those two phases for the situations where it doesn't due to stricter browsers.

> Why is "share message" blue?

Because it is a link - https://github.com/vector-im/element-web/issues/14786

> Why isn't "report content" red?


Because it isn't a link, it is a button like the rest of the context menu options

> Forwarding a message is still ugly

Yup tracked in various issues, take your pick.

> The share room UI looks a little out of place/ugly/unpolished

Has upcoming redesign planned

> The read receipts should probably be at the bottom of messages

https://github.com/vector-im/element-web/issues/4377

---

Please check for open issues to add your commentary to for the remainder and avoid meta issues which would either become unwieldy or useless.

**Comment by TR-SLimey** [comment]
@t3chguy Got it. Thanks!
