### ISSUE TITLE
"Encryption Upgrade Available" never goes away even after following instructions

### ISSUE THREAD

**Issue by ericmigi** [vector-im/element-web#14875]
### Description

"Encryption Upgrade Available" never goes away even after following instructions
### Steps to reproduce

1. Login with user account on matrix.nova.chat
2. Get pop up

![image](https://user-images.githubusercontent.com/1048265/89366929-b47bd000-d68c-11ea-951f-1931f93303e5.png)

3. enter in passphrase
4. appears to work...but then the pop up occurs again.

Describe how what happens differs from what you expected.

Logs being sent: yes/no

### Version information

- **Platform**: web (in-browser) or desktop?

For the web app:

- **Browser**: Chrome, Safari, Firefox? which version?
Firefox, 80.0b3
- **OS**: Windows, macOS, Ubuntu, Arch Linux, etc?
Mac OS 
- **URL**: riot.im/develop / riot.im/app / somewhere else? If a private server, what version of riot-web?
app.element.io

For the desktop app:

- **OS**: Windows, macOS, Ubuntu, Arch Linux, etc?
- **Version**: 1.x.y

**Comment by ericmigi** [comment]
can't submit debug logs....

![image](https://user-images.githubusercontent.com/1048265/89367075-06245a80-d68d-11ea-84ee-a103b312e841.png)

**Comment by t3chguy** [comment]
That error means your IndexedDB is broken (and thus no logs are stored anyhow)

Are you in Firefox Private or something?

**Comment by ericmigi** [comment]
yeah that was it. sent logs now

**Comment by ericmigi** [comment]
Any update from the logs that we sent in?

**Comment by t3chguy** [comment]
Your log is filled with IndexedDB failures, are you running out of storage by any chance? Something is causing your IDB to fail.

**Comment by ericmigi** [comment]
No, terabytes of storage available.

**Comment by t3chguy** [comment]
Any browser extensions which may change behaviour of persistent storage?

**Comment by ericmigi** [comment]
possibly? The issue is that this same error is occurring inside the electron app as well.

**Comment by mystiquewolf** [comment]
I'm also having this issue...

**Comment by ilmaisin** [comment]
This is very bad UX. What those "upgrades" that "encryption" supposedly needs even are?

**Comment by WalterLuigi** [comment]
Having this same issue in the Element desktop client v1.7.30 for windows.

I'm using the matrix.org homeserver.

**Comment by EmmyGraugans** [comment]
Since the last Element-Desktop Upgrade, the same occurs for me...
- element-desktop 1.7.32 on Ubuntu 20.04
- Element 1.7.32 on MacOS 11.4

Possibly related or not: the iOS App on a mobile device was not the most recent (but didn't show the message), don't know how to find out which version is installed. Within the settings was shown something like "Version 1.0.0 rebranding #20200713192130" (and it was still named "Element (Riot.im)" Will update that now (to 1.4.3) and see if that has any effect on the message shown in the desktop-client... (though there might be other devices still, especially one "purple-matrix" (in Pidgin on Linux) which never will be able to "upgrade encryption", because encryption is simply not supported by the purple-plugin for matrix...)

**Comment by dbkr** [comment]
This is a fairly old bug which I suspect was probably a different cause of the same problem, so let's close this & use https://github.com/vector-im/element-web/issues/14875 to track this problem.

**Comment by renormalist** [comment]
Aren't we literally in #14875 here? Can we please reopen?

**Comment by robintown** [comment]
Actually, I think @dbkr meant to reference https://github.com/vector-im/element-web/issues/17886, so let's take further conversation there.

**Comment by renormalist** [comment]
Ack, I came to that conclusion, too, but long after my comment. :-)
