### ISSUE TITLE
Multiple thumbs up emojis allowed by Element/Riot?

### ISSUE THREAD

**Issue by PC-Admin** [vector-im/element-web#14900]
### Description

'Thumbs up' emoji can appear twice in a Matrix conversation, we've tested this in multiple rooms and it seems to be a recurring bug.

### Steps to reproduce

- Have one person 'thumbs up' a post.
- Second person has to do it with the tap and hold menu, rather than just tapping the existing one.
- You'll now notice 2 distinct yet identical 'thumbs up' emojis on said post. :P

### Describe how what happens differs from what you expected.

Well.. you would expect multiple 'thumbs up' emojis to add onto each other, not make a new identical emoji.

![1](https://user-images.githubusercontent.com/29645145/89611276-57139900-d8af-11ea-8dfd-a00caf8696f6.png)

![2](https://user-images.githubusercontent.com/29645145/89611294-6561b500-d8af-11ea-9b2c-ceac04140789.png)

### Version information

- Ubuntu 20.04 & Debian 10, Element version: 1.7.2 (client installed locally on my machine)
- Debian 10, Element version: 1.7.2 (nugs) (in browser)
- Android 10, Element 1.0.4 (wings) (screener below)

![Screenshot_20200807-131301](https://user-images.githubusercontent.com/29645145/89611611-3992ff00-d8b0-11ea-835f-cc5df0e69a5c.png)

**Comment by auscompgeek** [comment]
Not an element-web bug: #13926

**Comment by PC-Admin** [comment]
Wings was apparently using the latest Element client for Android.

**Comment by PC-Admin** [comment]
Can re-post this in the Android repo if needed. It does involve element-web a little bit though.

**Comment by t3chguy** [comment]
It only looks the same in element-web because of the font having both the emoji and color emoji (variant-16) looking the same.
It is definitely not a bug.

Depending on font, they can be styled differently; 
![image](https://user-images.githubusercontent.com/2403652/89623834-3b979680-d88d-11ea-8497-648dff930472.png)

https://unicode.org/emoji/charts/emoji-variants.html

element-web *COULD* group them depending on your font but this would be a massively expensive canvas operation and would go against the purpose of the emoji being unicode codepoints anyhow
