### ISSUE TITLE
Notification sound played even on lockscreen (probably linked to DE?)

### ISSUE THREAD

**Issue by bagage** [vector-im/element-web#14922]
### Description

When Element is running on a user session but with screen locked, you still have the sound of new messages. It also happens if someone else is logged in and do something unrelated. Might be related to https://github.com/vector-im/element-web/issues/7758.

### Steps to reproduce

- Start Element on one user session
- Lock screen (Super+L)
- Send a message to that user from another account.

#### Actual behavior

Notification sound is played instead of being silent.

#### Expected behavior

There should be no notification sound.

Logs being sent: no

### Version information

- **Platform**: desktop
- **OS**: Debian bullseye with Gnome Shell 3.36.4
- **Version**: 1.7.3

**Comment by Half-Shot** [comment]
@bagage That's likely due to your distros sound settings. Some distros have PulseAudio setup in such a way that you cannot hear anything without being in an authenticated session, but others seem to have it setup so that the sound is still heard even if you switch to another unauthenticated TTY.

In short, this is definitely not an Element bug but something to bring up with your distro. You can probably prove this by playing something from another app and noticing that it continues to play.

**Comment by bagage** [comment]
Yes can confirm that music continues playing as well @Half-Shot, thanks for the extra info. 
If nothing can be done on Element's side, this issue can be closed :).

**Comment by Half-Shot** [comment]
Thanks for checking.
