### ISSUE TITLE
Rename container image on docker hub

### ISSUE THREAD

**Issue by jcgruenhage** [vector-im/element-web#14930]
Related to #14896, there's another element-web artifact that is still named riot-web: https://hub.docker.com/r/vectorim/riot-web

afaict that does not require any change in the repo here, just on Docker Hub.

**Comment by Weasy666** [comment]
Just as a reminder, after changing the image name on docker hub, also change the relevant line in the README.

https://github.com/vector-im/element-web/blame/develop/README.md#L132

**Comment by Half-Shot** [comment]
I'd like to draw attention to several existing images on dockerhub for element-web https://hub.docker.com/search/?q=element-web&type=image.

I've encountered some folks in the wild using these images because they've just gone for the first search result in dockerhub and found that the image didn't work for them. I'm concerned this could be used against us if a malicious or broken image were to be uploaded, so we really should have some kind of presence on dockerhub.

**Comment by jryans** [comment]
I have created a new Docker Hub repo (https://hub.docker.com/r/vectorim/element-web) and the first builds are running now. Assuming that works, I'll update documentation to point to the new location.

Docker Hub doesn't seem to mind building 2 Docker repos from the same source, so I guess I'll leave riot-web updating as well, so there's no need for a transition.
