### ISSUE TITLE
Getting notified on every reply to user with my nickname in his mxid

### ISSUE THREAD

**Issue by JuniorJPDJ** [vector-im/element-web#14943]
My domain is juniorjpdj.pl and my nickname juniorjpdj.
This makes me getting notified/tagged on EVERY reply to any user using my homeserver.
Example is when somebody reply to message by test@juniorjpdj.pl or even any bridged puppet user (horribly annoying).
My friend also have similar problem.

**Comment by wvffle** [comment]
Same goes with display names... 

My tag is `@waff:wvffle.net` though I set my display name to `wvffle` and now, everytime when someone replies to ANY account on my domain I am notified of this. This is really annoying mostly due to all of the bridges I have.

I've prepended the display name with some non letter characters as a workaround but I don't consider it a proper solution. Server host should not be considered if it comes to notifying of the appearance of the display name/username.

**Comment by t3chguy** [comment]
Notifications are resolved via Push Rules on the Server.

You are welcome to turn off the username push rule.
![image](https://user-images.githubusercontent.com/2403652/90030896-81e95d00-dcb4-11ea-995b-c09ef3a6087b.png)

If you have complaints about the push rules I suggest opening an issue here: https://github.com/matrix-org/matrix-doc
