### ISSUE TITLE
Add HS admin-configured option to require secure backup

### ISSUE THREAD

**Issue by jryans** [vector-im/element-web#14954]
Some HS admins may want to require all users to set up secure backup (message key backup) before proceeding to use the app, as a way of reducing support burdens.

To enable this, Element will check for the following in `/.well-known/matrix/client`:

```
  "io.element.e2ee": {
    "secure_backup_required": true, 
  }
```

If this is set, then:

* flows to setup secure backup at registration become mandatory and cannot be skipped
* buttons in Settings to remove backups are hidden

Additionally as part of this work, the previous similar config key `im.vector.riot.e2ee` used for disabling encryption is deprecated. Element Web will check both `io.element.e2ee` and `im.vector.riot.e2ee` blocks, preferring `io.element.e2ee` if both exist.

**Comment by notramo** [comment]
This is also useful if a HS admin wants to gain access to all messages of a user by simply brute-forcing one single key instead of many separate Megolm keys (which he has to do if the user doesn't use the secure backup).

**Comment by TR-SLimey** [comment]
@notramo Which can be practically impossible if the password used to generate the key is strong enough (say, generated by a password manager). Here's roughly how long https://howsecureismypassword.net estimates it'll take this HS owner to crack a password I just generated with Bitwarden:

![image](https://user-images.githubusercontent.com/37966924/90445830-9d070300-e0e0-11ea-8895-6e829b26514e.png)

AND, Element by default generates a "key" which is 48 characters long (a-Z) instead of suggesting you set a passphrase nowdays, so even the lazy users will be safe.

I'm not worried :P

**Comment by notramo** [comment]
> @notramo Which can be practically impossible if the password used to generate the key is strong enough (say, generated by a password manager).

@TR-SLimey (Most of users don't use Bitwarden but a password made of their birth place and year, but yes, lazy users would rather use the automatically generated 48 char password.)

Why do the Matrix devs bother with Megolm when they could use PGP?
Because Megolm
- uses different keys for every conversation (one stolen key will let you read only part of one conversation)
- is self-healing (keys are changed regularly, so if a key is cracked/stolen, it will be changed to a new key after some time)

But with Secure Backup
- using one **single key** for securing ****
- if the backup key is stolen, the HS admin can read all your messages **until you generate another** (which doesn't happen regularly)

Secure Backup doesn't bring much benefit compared to PGP.

**Comment by notramo** [comment]
> @notramo Which can be practically impossible if the password used to generate the key is strong enough (say, generated by a password manager).

@TR-SLimey (Most of users don't use Bitwarden but a password made of their birth place and year, but yes, lazy users would rather use the automatically generated 48 char password.)

Why do the Matrix devs bother with Megolm when they could use PGP?
Because Megolm
- uses different keys for every conversation (one stolen key will let you read only part of one conversation)
- is self-healing (keys are changed regularly, so if a key is cracked/stolen, it will be changed to a new key after some time)

But with Secure Backup
- using one **single key** for securing **all conversations**
- if the backup key is stolen, the HS admin can read all your messages **until you generate another** (which doesn't happen regularly)

Secure Backup doesn't bring much benefit compared to PGP.

**Comment by chagai95** [comment]
@jryans this causes the whole well known to not be parsed in iOS because it expects the `default` parameter, could you please update this for now until this issue is fixed?

```
        "io.element.e2ee": {
                "default": true,
                "secure_backup_required": true
        }
```

It should be worked on via this internal ticket, but if it does not get done you should probably open a public ticket...

https://gitlab.matrix.org/ps/aarenet/issue-tracker/-/issues/347
