### ISSUE TITLE
Smaller inline thumbnails for uploaded images

### ISSUE THREAD

**Issue by jfrederickson** [vector-im/element-web#1520]
Currently if someone posts an image, it can fill up almost the entire chat pane. Given that images can already be expanded by clicking on them (which provides a link to the full size version as well), I think the thumbnail shown inline should be significantly smaller, to avoid pushing the rest of the conversation off the top of the screen with one message.

**Comment by ara4n** [comment]
We've experimented a bunch with this over the last few months.  I agree that usabilitywise it could be reduced, but aesthetically i also kinda like them being big.  Hmmmm.  @AmandineLP wdyt?

**Comment by jfrederickson** [comment]
Yeah, aesthetically it's kinda nice, but I personally think the interruption that can cause in a conversation could get annoying very quickly. For reference, here's the way Vector and Slack currently present the same image (and note that Slack allows you to fold it out of the way as well)

<img width="1280" alt="screen shot 2016-05-24 at 10 41 33 am" src="https://cloud.githubusercontent.com/assets/1923178/15508692/71de2ed4-219e-11e6-9000-89ffdb7b634b.png">
<img width="1280" alt="screen shot 2016-05-24 at 10 41 37 am" src="https://cloud.githubusercontent.com/assets/1923178/15508691/71ddb8b4-219e-11e6-8ab5-912dab3f677e.png">

**Comment by AmandineLP** [comment]
Agreed it's sometimes hardly usable. Even on the screenshot below and especially on small screens. It's glossy when it's a nice pic, but shouldn't block usability :) 
I would still keep it bigger than Slack though. The option to unfold it is good, but I would at least make it a setting ("display small/medium/large thumbnails"), basically like windows allows you to change the way your folder content is displayed: sometimes you need huge thumbnails, others, only details. 

We could also start by decreasing the size a bit (by the same amount of free space on the right, only the bit with the grey line). The problem on small screen is that it takes the full height, but failing to think through an algorithm which would allow to take into account the height of the window as well as the width when resizing the thumbnail....

![image](https://cloud.githubusercontent.com/assets/8582858/15509157/cf1f0d6e-21d2-11e6-899a-d9ecd0ca7ba5.png)

**Comment by jfrederickson** [comment]
Oh yeah, I didn't think about making it configurable - that would be nice. (Still leaves the question of what the default should be, but it'd be an improvement IMO.)

**Comment by napostrophe** [comment]
Bumping this. looks like a bunch of other issues have been opened and then linked here but this issue looks kinda dead. For the sake of quality of life having this resolved would be really nice (and make the app feel a lot less clunky imo)

**Comment by DJCrashdummy** [comment]
given the fact that displays may be very different in size, how about an option to set it for every device differently by the user?

**Comment by lgrn** [comment]
If deciding the right size to display is hard or complex from a UI standpoint, maybe it would make sense to at least allow the user to resize the image before it's uploaded. Gmail used to do this in the past, or maybe it still does, when you pasted an image inline you could select from "Small, Medium, Large" depending on whether you wanted the pixel and byte-size to be smaller or not.

**Comment by DJCrashdummy** [comment]
@lgrn this issue is about the **thumbnail**, not the picture itself!
...if you are suggesting to make the sender to chose how big the thumbnail should be displayed, i'm strongly against it, because a reasonable display size strongly depends on every single user and his currently used device.

that would be like hardcoding a website to its mobile-view even if your visitor has a 8k-screen. - that makes no sense!

**Comment by lgrn** [comment]
I wasn't really suggesting that the thumbnail size should be user defined, rather that the user should get an optional choice to downscale the source image if they choose before it's uploaded. While I agree it's not a good solution to the issue of thumbnail size in general, my guess was just that it would perhaps be easier to implement and would give users a way to avoid pushing a huge image file in the meantime.

There are of course separate use cases regardless of thumbnail size where your source file may be unsuitably large to share in a chat, so my idea was just that it may be a nice feature that could partly alleviate this issue until a better responsive UI scaling of the thumbnail is available.

**Comment by DJCrashdummy** [comment]
> [...] the user should get an optional choice to downscale the source image if they choose before it's uploaded.

at least in riot-android exactly this feature (you'll find it in the settings) is already implemented; you can chose between *"ask"*, *"original"*, *"big"*, *"medium"* and *"small"*.

but it seems that riot-web and riotx are missing such a feature... :open_mouth: and i have no idea about riot-ios! probably there are open issus regarding this topic, but if not, the best would be to open a separate new one.

**Comment by ara4n** [comment]
I think we should make this configurable in the new Appearance tab - it's something that comes up fairly regularly, and I don't think there's much point in being super opinionated about it.

**Comment by konomikitten** [comment]
@mcnesium sorry to bother you but do you have any idea on how to add that fix to the electron desktop client?

**Comment by mcnesium** [comment]
@konomikitten as far as I know there is no such easy way to override the CSS of an electron app. See #7316 for a discussion about this

**Comment by tildica** [comment]
My friend group always complains about this on their desktop client. The problem is you can't even have 2 whole images displayed on a 1080p screen (sometimes even if the app isn't full screen) and images can end up as high as 20 lines of text which looks and feels terrible. Most people would prefer images small enough so you can fit at least 2-3 whole images and still have extra space.
I suggest making a slider under All Settings->Appearance where the user can set the maximum height of the images.

Here's my temporary solution, based on mcnesium's code (this code can be added to Stylus, for element-web users):

```
.mx_MImageBody_thumbnail {
    height: 16em !important;
    width: auto !important;
}

.mx_MImageBody_thumbnail_container {
    height: 16em !important;
}
```

This way images will be smaller, but it's dimensions will stay consistent. If you need to see the whole image you can always click on it or even download it.
Here, 16em is just my preference on a 1080p monitor. Since people use various display sizes and have different preferences, we could make the slider go from 8em to 32em in 4em increments, and allow advanced users to manually type in a value. Of course, you can use px instead of em.

**Comment by ShadowJonathan** [comment]
Any progress on this?

**Comment by SimonBrandner** [comment]
@ShadowJonathan, there are [#5666](https://github.com/matrix-org/matrix-react-sdk/pull/5666), [#5682](https://github.com/matrix-org/matrix-react-sdk/pull/5682), [#4718](https://github.com/matrix-org/matrix-react-sdk/pull/4718). They are all waiting on some sort of design decision

**Comment by ShadowJonathan** [comment]
Thanks, I'll sub to those

**Comment by Trendyne** [comment]
The fact a single image covered the entire chat made me very often just not post them because it would cover everything. It's horrible design. I get that you guys want to be bureaucratic about everything even if it's pretty obvious, so this will take forever, but for anyone else that wants to fix this in their own instance:
```css
body .mx_MImageBody_thumbnail_container{
	max-height: 300px !important;
	display: flex !important;
}
body .mx_MImageBody_thumbnail_container > :first-child{
	display: none !important;
}
body .mx_MImageBody_thumbnail_container img{
	position: relative !important;
	max-width: 100% !important;
	width: auto !important;
	max-height: 100% !important;
}
```

**Comment by trosel** [comment]
> I get that you guys want to be bureaucratic about everything even if it's pretty obvious, so this will take forever

Is there really no single product manager or designer? where is the vision coming from? who is steering the ship here?

**Comment by Trendyne** [comment]
> > I get that you guys want to be bureaucratic about everything even if it's pretty obvious, so this will take forever
> 
> Is there really no single product manager or designer? where is the vision coming from? who is steering the ship here?

No, not really. 

[The Matrix.org Foundation | Matrix.org](https://matrix.org/foundation/)
>The evolution of Matrix is managed through an open governance process, looked after by The Matrix.org Foundation - a non-profit UK Community Interest Company, incorporated to act as the neutral guardian of the standard on behalf of the whole Matrix community.
>The Foundation defines the manifesto, mission and values of the project, the open governance process that determines how the specification develops, and provides a safety-net to ensure the project stays independent and true to its goals. The constitution of the project is defined in the Foundation’s legal Articles of Association and Rules, and is enforced by the Guardians of Matrix: the directors of the Foundation appointed to provide a balance of independent experts and the founding Matrix team to ensure the project stays on track.

**Comment by t3chguy** [comment]
Right, that's for the protocol, not for Element which is owned by New Vector Ltd T/A Element. Element Web has a Design team and a Product team, they're the ones who decided the larger timeline thumbnails in the first place.

**Comment by ShadowJonathan** [comment]
Please keep in mind that - while this process seems very bureaucratic - its "slow" effects are only made apparent because the design and product teams are absolutely swamped with work, and bigger fish to fry. There are some here which do indeed work hard on the small UX stuff in their free time (:heart: @SimonBrandner) but eventually everything would have to go through the design and product teams for approval.

Imagine this, what if there *werent* teams checking on the look of the app, and everything could just make it through like this? That was Element a few years ago, and this is a move to better organisation and less chaos, shame it's overloaded at the moment, I only hope that'll get better as the load lessens and issues like these can be pulled straight, the best contributors can try to do then is to give as less work to review as possible, and get someone to put it into the review queue.

**Comment by trosel** [comment]
> for anyone else that wants to fix this in their own instance:
> 
> ```css
> body .mx_MImageBody_thumbnail_container{
> 	max-height: 300px !important;
> 	display: flex !important;
> }
> body .mx_MImageBody_thumbnail_container > :first-child{
> 	display: none !important;
> }
> body .mx_MImageBody_thumbnail_container img{
> 	position: relative !important;
> 	max-width: 100% !important;
> 	width: auto !important;
> 	max-height: 100% !important;
> }
> ```

@Trendyne Can you just submit a PR with this added?

**Comment by SimonBrandner** [comment]
@trosel, there is no point in doing that. There already are PRs to fix this, see https://github.com/vector-im/element-web/issues/1520#issuecomment-802768308
