### ISSUE TITLE
Resetting secure storage results in "Unable to set up secret storage"

### ISSUE THREAD

**Issue by Marwel** [vector-im/element-web#15230]
### Description

I'm trying to reset cross signing and secret storage and i fill out out all required fields and when i hit finish, it only shows
"Unable to set up secret storage"

### Steps to reproduce

- Reset cross signing in Settings/Security & Privacy
- fill out the new security passphrase, next, next, finish

### Version information

- **Platform**: web (in-browser) or desktop?
Tried both. Same result.

For the web app:

- **Browser**: Chrome 85.0.4183.102
- **OS**:  Fedora 32
- **URL**: private server riot version v1.7.7

For the desktop app:

- **OS**: Fedora 32
- **Version**: Element version: 1.7.7

**Comment by jryans** [comment]
Thanks for the report, I'll work on fixing this now. @Marwel, to help me confirm I understand the issue correctly, can you tell me what you see when you open browser DevTools, and go to Application tab -> IndexedDB -> matrix-js-sdk:crypto -> account, and then what values do you see in the "key" column? (Please don't post the "value" column, those are private!)

For example, do you see something like:

<img width="246" alt="image" src="https://user-images.githubusercontent.com/279572/93593619-57be4580-f9ac-11ea-917d-a17d3d79cc10.png">

...or do you have a different list?

**Comment by mk-hs** [comment]
I've got the same issue.
There's just the - key and sss_cache:m.megolm_backup.v1
in another browser there's just - and nothing else.

**Comment by Marwel** [comment]
@jryans
There is not much.
![image](https://user-images.githubusercontent.com/741387/93658683-2d1ccd00-fa3e-11ea-8fe1-4215edb276fd.png)

**Comment by jryans** [comment]
@Marwel develop.element.io now has a fix applied for this, please test there and let us know if you're able to reset.

**Comment by Marwel** [comment]
Nope, sorry to disappoint, but it still shows the same message.

**Comment by jryans** [comment]
Hmm, okay, thanks for trying. What do you have currently on develop in the advanced section of cross-signing settings? For example, I have:

<img width="334" alt="image" src="https://user-images.githubusercontent.com/279572/93791143-c4934300-fc2b-11ea-8ee5-1248482e8c11.png">

**Comment by Marwel** [comment]
![image](https://user-images.githubusercontent.com/741387/93844136-75392b00-fc9c-11ea-9e79-0503f9406a90.png)

**Comment by jryans** [comment]
@Marwel Looking at your previous debug logs from 5 days ago, it seems like you tried the following actions:

* Clicked "Set up" in the cross-signing section, but this failed when trying to access secret storage
* Clicked "Reset" in the secret storage section, but failed when trying to copy local cross-signing keys into new secret storage (because they don't exist)
  * This part is what I attempted to fix in https://github.com/matrix-org/matrix-js-sdk/pull/1472

Could you please try the following steps?

1. Go to https://develop.element.io, logging in if needed, and open Settings -> Security
2. Click "Reset" in the secret storage section first (if this still fails, it's likely a new, different issue than last time)
3. Click "Reset" in the cross-signing section to create fresh keys and store them in the new secret storage you just made
4. If there are any problems, please submit debug logs from this session on develop

Even if you end up seeing the same messages in the UI, we may learn new things from the debug logs. Thanks for your help with this!

**Comment by nbuechner** [comment]
Uploaded logs from the development version with the same "Unable to set up secret storage" error.

**Comment by Marwel** [comment]
@jryans Yeah, you're right, this happens, when i try to finish step 2.
So i skipped step 3 and uploaded the logs. It seems to me, that the reset from cross signing does both.
Thank you for your effort on this.

**Comment by jryans** [comment]
Thanks for the additional logs! I can see now there is indeed an additional issue: secret storage reset attempts to sign key backup with cross-signing keys that are not present. According to logs, @Marwel, @nbuechner, and @PeterBadzhakov all seem to be affected by the same issue, so hopefully fixing that will help everyone. 😄

**Comment by jryans** [comment]
@Marwel, @nbuechner, and @PeterBadzhakov, the latest fix is now merged to develop. If you could test https://develop.element.io once again, that would be very helpful! The steps in https://github.com/vector-im/element-web/issues/15230#issuecomment-697346986 should be a good reference.

**Comment by mk-hs** [comment]
Resetting both secure storage and cross-signing is working now on the develop client, thanks a lot!

**Comment by Marwel** [comment]
Okay, i'm late to the "it works" party, but i have to disapoint again.
I tried on develop and it still gives me the same error on resetting secure storage.
I already uploaded the logs.

**Comment by jryans** [comment]
@Marwel Sorry to hear that 😖 It's a bit puzzling, as that seems to be exactly the error I thought I had fixed in the second round. I created a [fresh issue](https://github.com/vector-im/element-web/issues/15337) to track the remaining problems since we've already shipped fixes on this one.
