### ISSUE TITLE
Cross-signing has a set-up button but also says I'm good to go

### ISSUE THREAD

**Issue by turt2live** [vector-im/element-web#15280]
![](https://i.imgur.com/hWU3Tj0.png)
I would not expect to be able to set up cross signing if it's already ready for use.

**Comment by dbkr** [comment]
Maybe also needs-design / product to check what the intention is here

**Comment by jryans** [comment]
Yes, this definitely a case of developer (me) design... Current designs in Figma are a bit too simple to cover all states.

In this case, the "Set up" button is being shown because things are only partially set up: the master key is not cached locally (this is a recent change and will be true for anyone with an existing session from before Element 1.7.6). 

At the moment, we don't have a proper UX to trigger people to unlock 4S to cache this new missing piece. We could potentially do another round of "upgrade encryption" toasts... but I think various people found those confusing / suspicious. Alternatively, we could do nothing. The main downside of not having this key cached locally is that it can't be shared with other devices when verifying them.

**Comment by kittykat** [comment]
@jryans Does this new wording resolve the issue sufficiently for it to be closed?

![Screenshot from 2021-12-01 14-58-49](https://user-images.githubusercontent.com/51663/144257930-0d84798d-a658-4e2c-8a10-f4c332b306cd.png)

**Comment by jryans** [comment]
Yes, seems like that resolves the main issue here.
