### ISSUE TITLE
Lazy Render List leaves gaps, maybe hidpi

### ISSUE THREAD

**Issue by t3chguy** [vector-im/element-web#15341]
![image](https://user-images.githubusercontent.com/2403652/94699649-74eefe80-0332-11eb-87d7-8f8a0bf79dd4.png)

**Comment by ara4n** [comment]
i assume the bug here is the big black space at the bottom of the list here?  mine looks like this, for ease of people playing spot-the-difference:

<img width="349" alt="Screenshot 2020-10-24 at 23 53 03" src="https://user-images.githubusercontent.com/1294269/97095175-1593be00-1654-11eb-971f-6f8b33b47bca.png">

**Comment by t3chguy** [comment]
Yup, scrolling up a tiny bit more would fill that gap which would feel very jumpy
