### ISSUE TITLE
AppTile errors lead to infinite loops

### ISSUE THREAD

**Issue by jryans** [vector-im/element-web#15494]
In `AppTile#_startWidget`, we'll try to start the`StopGapWidget`. If this throws an error for some reason, the `AppTile` component gets trapped in an infinite loop constantly recreating widgets.

To simulate this, do something like adding `throw new Error()` in `StopGapWidget#start`.

**Comment by turt2live** [comment]
There's very few things which should go wrong with this area, which is why it wasn't necessarily considered ftr.

**Comment by jryans** [comment]
It's possible it might be hard to trigger in practice, but I'd like to defend against if we can, to avoid paths that might trigger loops like this. Perhaps an localised error boundary around each widget would be good to have as well.

**Comment by dbkr** [comment]
Digging into this in more detail, this is because because AppTile tries to 'reset' the widget if it's ref is set to null, so if the ref callback throws, react unmounts the widget component to replace it with its error component, calls the ref callback with null, which tries to mount it again.

I'm not sure what the logic is of trying to force the iframe back into existence if it was unmounted for some reason.

**Comment by turt2live** [comment]
> I'm not sure what the logic is of trying to force the iframe back into existence if it was unmounted for some reason.

The code is trying to stop the messaging if it was started and prepare for when the iframe might be re-mounted, as would be the case for if the user revoked permissions (or the widget changed) then re-accepted without ever leaving the room. The same also applies for minimizing the widget.

**Comment by dbkr** [comment]
Ah - so the bug here is that it shouldn't be trying to re-mount the iframe at all, but that's what it's doing.
