### ISSUE TITLE
Can't add room to community

### ISSUE THREAD

**Issue by justinfagnani** [vector-im/element-web#15498]
### Description

I've created a new community and I want to add the first room to it. If I click on add rooms them type in a name, I get an error "Unknown address"

### Steps to reproduce

- Go to community settings page
- Click "Add rooms to this community"
- Type in a name for the room, like "general"
- See that the room name is replaced by a red chip that says "Unknown address"

I would expect a new room to be created for the community.

### Version information

- **Platform**: web

For the web app:

- **Browser**: Chrome
- **OS**: macOS
- **URL**: app.element.io

**Comment by turt2live** [comment]
The room is unknown then. Visit #element-web:matrix.org for support on this please.

**Comment by justinfagnani** [comment]
> The room is unknown then.

I'm not exactly sure what this means. How does one add a room to a community then?

**Comment by stevefloyd** [comment]
The fact this is not intuitive and more well document means someone needs to close that gap, because I experienced the same thing when trying to add new rooms to my community. 

At first glance, you expect similar functionality as Slack or Riot, where you name the room and just click "add". That isn't exactly the case though, these rooms need to be created first. 

To anyone confused by this, here is what you need to do to add rooms to your Community...

1. Hover over the "+" plus sign on the "rooms" tab (to the left). 
2. When you hover over it you will see "Add room" tooltip and that will let you add a new room. 
3. You can then tie each of the rooms you create to your community. 
4. You will have to create a separate room the same way for every room you want to create. 
5. Once you have created them, go back to your community, edit the description, scroll to the bottom and click on the "add rooms to this community" link. 

Hopefully that helps resolve this for anyone searching for the answer.

**Comment by SimonBrandner** [comment]
@stevefloyd, Communities will be soon replaced by Spaces. They should be much more intuitive and featureful

**Comment by stevefloyd** [comment]
Well, until that rolls out my comment should help someone searching who is confused (this thread shows up for most related searches).

**Comment by sancarn** [comment]
Just tried binding a room to a community myself. I have a community +launchmenu:matrix.org and want to bind to the room `#launchmenu:matrix.org` but it appears that whenever I paste the room ID `#launchmenu:matrix.org` into the rooms `Add rooms to this community` section, it says `Unknown Address`.

Currently I'm getting around this by using html link `<a href="link/to/room" ...` but it would be useful to get clarification on this (and an ETA for  Spaces)

**Comment by 610th** [comment]
If you type the room name, the room will probably appear in a dropdown and everything will work. However, it is not possible to just paste a room address (as the placeholder suggest) . So this is clearly a bug. But maybe a low priority bug if the communities are on their way out.
