### ISSUE TITLE
Updating your display name isn't reliable if you're in lots of rooms

### ISSUE THREAD

**Issue by lampholder** [vector-im/element-web#15578]
1. be in 700+ rooms
2. change your displayname

The request times out (and shows a CORS error)
You have a new name in some rooms and not in others.

Also your rooms being ordered by recent activity goes out the window, as rooms one by one get 'recent activity' of your changing your name.

**Comment by t3chguy** [comment]
This is just a single API hit as far as Element is concerned, its Synapse timing out.
As for the re-ordering thing; see https://github.com/vector-im/element-web/issues/110

**Comment by ShadowJonathan** [comment]
This isn't entirely limited to Synapse, as this could happen on any kind of server, maybe a "job system" (such as changing your displayname) with element polling status on the job could be implemented? (thinking a little wider than just element and synapse on these kinds of things)

Anyhow, I had this problem recently, and it took me setting my avatar twice before it propagated to *all* rooms (which i suspect is because of the first request "warming" synapse up to such an action)

**Comment by t3chguy** [comment]
> maybe a "job system" (such as changing your displayname) with element polling status on the job could be implemented? (thinking a little wider than just element and synapse on these kinds of things)

Feel free to suggest it to the Matrix spec, or complain about the Synapse bug

**Comment by t3chguy** [comment]
Closing, if you still see this bug please open an issue in https://github.com/matrix-org/synapse/
