### ISSUE TITLE
Windows client captures the media keys

### ISSUE THREAD

**Issue by thomasfrobieter** [vector-im/element-web#15704]
### Description

I'm using the Element Windows (10) Desktop App, the problem is, Element captures the media keys (play/pause, next, prev, ...) while and after a voice call / conference.

This is hell annoying, would be very nice if element doesn't recognize on media keys at all or has a setting to disable it: 

![element_win10_media_overlay](https://user-images.githubusercontent.com/4060313/98817377-4df41400-242a-11eb-81d7-e5c3f01fb8ec.png)

After Element is restarted, i am able to control for example Spotify again.

### Steps to reproduce

- Open your music app - Spotify or whatever
- Open the Element Windows App
- Call someone in Element
- End the call
- Try to control your music app with the media keys

### Version information

- **Platform**: Windows 10 App

For the desktop app:

- **OS**: Windows 10
- **Version**: 2004 (Build: 19041.572)

**Comment by tretum** [comment]
This is a critical issue for me. I have Bluetooth headphones. Whenever a sound playback that uses the hardware media keys, with the visualization that is shown in the OP, stops, my sound breaks completely. Even just getting a voice call without answering triggers this effect as soon as the ringing stops.

There is a flag in electron which sets this behavior. Here are some links on that:
https://github.com/electron/electron/issues/21731#issuecomment-589543405
https://support.discord.com/hc/en-us/community/posts/360058523532/comments/360009931232

I would really appreciate a setting for this, as otherwise Element becomes unusable for me on Windows.

**Comment by jryans** [comment]
I think we'd happily accept a PR to just disable this media key handling entirely for everyone.

**Comment by thomasfrobieter** [comment]
Thanks @tretum Shortcut flag fixed it for me.

Example: C:\Users\USERNAME\AppData\Local\element-desktop\Element.exe" -disable-features=HardwareMediaKeyHandling

Ensure to close Element also in the tray icons, before re-starting it with this shortcut.

**Comment by JPustkuchen** [comment]
Thank you all, this is really annoying ;) The flag workaround is nice, but I'd need it for autorun. So hopefully someone know how to patch it out and this will be solved soon.

**Comment by thomasfrobieter** [comment]
For autorun, press windows-key+R, enter shell:startup and copy your modified element.ink in this folder

**Comment by tretum** [comment]
In theory, it should suffice to add the following line
`app.commandLine.appendSwitch('disable-features', 'HardwareMediaKeyHandling,MediaSessionService');`
here
https://github.com/vector-im/element-desktop/blob/239bab38cabcb5589ce63751a0c1f7fcc6b09b8d/src/electron-main.js#L811

I cant get a local dev environment working though and i don't want to simply open a pull request without testing.
