### ISSUE TITLE
Cross-signing: Two devices trust each other but not themselves

### ISSUE THREAD

**Issue by jaller94** [vector-im/element-web#15765]
### Description
Alice has two clients (Element Desktop and Element iOS). She's got cross-signing enabled and key backup enabled.
A few months ago I verified her iOS session which shows up as trusted on all my devices. I assume that's correctly set up with cross-signing.

Today her two devices seem to trust each other but not themselves. On her Desktop the "Dekstop" session is untrusted and on her Mobile the "Mobile" session is untrusted.

Neither of us sees a way to manually untrust verified devices. We're now stuck with not being able to resolve the status of her Desktop device not being signed by her cross-signing key.

Her Desktop's cross-signing status says:
```
Cross-signing public keys:	in memory
Cross-signing private keys:	in secret storage
Master private key:	not found locally
Self signing private key:	cached locally
User signing private key:	not found locally
Homeserver feature support:	exists
```

Nothing happens when she clicks on "Set Up" on her Desktop session.

### Steps to reproduce
- unknown
1. An iOS device was registered.
1. A desktop client was registered and signed out.
1. Another desktop client was registered.

Logs being sent: yes/no

### Version information

- **Platform**: web (in-browser) or desktop? Desktop

For the desktop app:

- **OS**: Windows, macOS, Ubuntu, Arch Linux, etc? Windows
- **Version**: 1.x.y

**Comment by jryans** [comment]
At the moment, I don't see any obvious quick fix, unfortunately. Alice could reset her cross-signing identity, which should resolve it, but it also means they would need to re-verify with anyone they had verified previously. I also recommend downloading a manual backup of message keys in settings just in case something prevents access to key backup.

**Comment by muelli** [comment]
how would resetting the cross-signing identity work on Android? In Settings -> Security and Privacy -> Cross-Signing doesn't yield a menu or anything interactive, for that matter.

**Comment by jryans** [comment]
I am not sure precisely, as the UIs are a bit different per device, so I'd suggest asking in #element-android:matrix.org for specific steps on Android. I believe web / desktop have more options for resetting this state, so it might be easier to achieve there. Cross-signing keys are account-wide, so resetting from web should help with all devices. Since the OP here is using desktop as one of the devices, that's likely the place to try this process.

**Comment by DuncanLithgow** [comment]
I have had a similar problem with a device not trusting itself. I feel that the state of not trusting itself ought to be obvious in the UI - at least when there are encrypted sessions configured. I get all sorts of other messages about security but it never occurred to me that my Android device could not verify other session because it did not trust itself.

**Comment by ShadowJonathan** [comment]
Can't reproduce, likely an android and ios-specific issue that caused a weird state in account E2E.

**Comment by kittykat** [comment]
From Christian:
> Sure, it was Linnea who had this issue and we don't have steps to reproduce it.
