### ISSUE TITLE
Can't download the keys at the first-login

### ISSUE THREAD

**Issue by CodingAnonymous** [vector-im/element-web#15836]
### Description

With the new first-login process I can't download the keys. How can I verify my session after I logout / close the only session? I expected that I can download the keys that can verify my session when I log in again at the first login as I could a few weeks ago. But now I can't. This is the console with one 404 error:

![Bildschirmfoto 2020-11-26 um 01 13 38](https://user-images.githubusercontent.com/7794412/100349749-39e31180-2fe9-11eb-9e3e-067ea9647c81.png)

### Steps to reproduce

- Create a new account (without any session yet) and login to element-web v1.7.14

### Version information

- **Platform**: web (in-browser)

For the web app:

- **Browser**: Chrome (v86.0.4240.198) AND Firefox (v83)
- **OS**: macOS Big Sur
- **URL**: app.element.io AND private Server v1.7.14

**Comment by CodingAnonymous** [comment]
It looked like that in German:
<img width="619" alt="Bildschirmfoto 2020-11-26 um 13 55 10" src="https://user-images.githubusercontent.com/7794412/100353838-70bc2600-2fef-11eb-9e07-77f3ef8a6096.png">

**Comment by CodingAnonymous** [comment]
I got this feedback: `the notification is shown when they enter an encrypted room for the first time`

**But:** I just tested and it is not shown. I created an encrypted room and I joined an encrypted room and didn't get the notification / popup

**Comment by aaronraimist** [comment]
> I got this feedback: the notification is shown when they enter an encrypted room for the first time

Well you aren't going to see the notification if you already setup key backup which presumably you already have since you already saw the dialog to create a security key.

FYI the notification *would be* in the top left corner of the screen and look like this:
<img width="348" alt="screenshot" src="https://user-images.githubusercontent.com/5855073/100390583-8719b000-2ff6-11eb-8698-7dbb4776ecf0.png">

----------

Assuming you have already setup key backup then you should see the following screen after you logout and log back in:
<img width="619" alt="screenshot2" src="https://user-images.githubusercontent.com/5855073/100390705-f394af00-2ff6-11eb-822e-9ffe6bd0316d.png">
Then you click on Use Recovery Key (that's a bug it should say Security Key) and then you can paste in the security key you previously downloaded.

**Comment by CodingAnonymous** [comment]
Thank you for your response @aaronraimist 
I created a new account on app.element.io in a new browser and DID NOT see the notification in the top left corner. On my self hosted version it is the same when creating a new account.

**Comment by aaronraimist** [comment]
Then that would be a bug. You should see the notification when the account joins/creates an encrypted room.

You should submit logs using the in app Bug Report feature and reference this issue number.

**Comment by jryans** [comment]
We seem to be mixing at least two concepts in this issue: "can't download keys" (which maybe means setup key backup?) and the notification toast not appearing.

@CodingAnonymous, can you try to restate the problem in terms of what you are expecting and what is not happening.

The 404 you show above is normal, for example: it just means the key backup doesn't exist yet, but then it is created a few lines later.

**Comment by CodingAnonymous** [comment]
Thank you for clarification, apart from that the prompt works after starting an encrypted chat. I'm closing this issue!
