### ISSUE TITLE
Electron won't share my camera with other processes in 1:1 calls (Jitsi is fine)

### ISSUE THREAD

**Issue by lampholder** [vector-im/element-web#15837]
When I try to initiate a 1:1 (i.e. not Jitsi call) out of Electron on Windows, _when there is another process using my camera_ (such as Microsoft Teams), I get this error:

## Call Failed

Couldn't start capturing media! Is your microphone set up and does this app have permission?:
NotReadableError: Could not start video source

Jitsi, in contrast, seems happy to share my camera with other processes.

Related to https://github.com/vector-im/element-web/issues/9931

**Comment by dbkr** [comment]
Windows in general only allows webcams to be used by one app at a time (there are workarounds people have created like ManyCam). I get an error with either a 1:1 call or Jitsi conference if another app has the camera open. Bear in mind that most browsers will multiplex a webcam between multiple *tabs*, so if you had jitsi and teams open in different tabs/windows in the same browser (eg. popping out the jitsi widget rather than using it within element) , that would probably work, which could be the behaviour you're seeing with jitsi?

**Comment by lampholder** [comment]
Okay! Yes that could be what I'm seeing with jitsi.

In which case is it possible to detect the situation to provide a better error message?

**Comment by dbkr** [comment]
Yep, that we should definitely do.

**Comment by lampholder** [comment]
/me confirms that Microsoft Teams can indeed not share my video with an ongoing Jitsi call.
