### ISSUE TITLE
Emoji picker has jumpy scroll jitter (x)

### ISSUE THREAD

**Issue by MadLittleMods** [vector-im/element-web#15940]
### Description

When filtering for the `:x:` ❌ emoji and scrolling to the bottom, the picker will jitter a couple pixels up and down continuously whenever you're touching the bottom.

### Steps to reproduce

 1. Filter for `x` in the emoji picker
 1. Scroll down to the bottom
 1. Notice the jumpy scroll jitter whenever you are at the bottom

![](https://user-images.githubusercontent.com/558581/101661631-22a31b80-3a0e-11eb-8f2f-02c217e5470f.gif)

Log: not sent    

### Version information

 - Browser: Chrome 87.0.4280.88
 - OS: Windows 10
 - URL: https://app.element.io/

I can't reproduce on macOS.

**Comment by tulir** [comment]
This happened to me: I have :2nd_place_medal: in frequently used and tried to search for "2" to react with :two:. The :two: is at the bottom, but due to that scroll/lazy loading bug, I can't actually click it (it shows up in the large preview at the bottom, but isn't clickable because it disappears from the picker itself)

https://user-images.githubusercontent.com/4224639/127865942-da43c789-8d52-495d-b823-29ebfe36d334.mp4

Firefox 91.0b9 on Ubuntu 21.04

**Comment by anoadragon453** [comment]
Still occurs with Element stable 1.7.34. It prevents me from picking some emoji at the bottom, specifically the US flag when searching for "us".

**Comment by t3chguy** [comment]
Is this still reproducible on latest develop? There was a lazy render bug which may have been related but now fixed.

**Comment by tulir** [comment]
Seems to be fixed. The lazy rendering is a bit too lazy though (it hides emoji if even 1 pixel of it is out of bounds, rather than if it's entirely out of bounds)

**Comment by MadLittleMods** [comment]
I can no longer reproduce either (and I could reproduce before refreshing today).

Fix for reference: https://github.com/matrix-org/matrix-react-sdk/pull/7225

Thanks @t3chguy 🙂
