### ISSUE TITLE
Toasts after logging in to an existing account are labelled 4/5 and 5/5

### ISSUE THREAD

**Issue by ara4n** [vector-im/element-web#15959]
despite there only being two tooltips; once urging to verify sessions, the other urging to enable analytics

**Comment by t3chguy** [comment]
Toasts*?

**Comment by jryans** [comment]
Hmm, could have sworn there was an existing issue for this... The issue here is that some toasts are auto-close before the user ever sees them. The toast list currently can't distinguish the "user has seen the list" or "was auto-closed vs. user closed", so the numbering behaves as if the user closed them.

**Comment by t3chguy** [comment]
Cannot reproduce anymore
