### ISSUE TITLE
logout button in TopLeftMenu no longer prompts in any way before logging you out

### ISSUE THREAD

**Issue by ara4n** [vector-im/element-web#15966]
I'd expect to have confirmation, ability to export keys, etc. Rather than just pausing a few seconds and then catapulting you out

**Comment by jryans** [comment]
A prompt is still shown if there are keys to export. https://github.com/matrix-org/matrix-react-sdk/pull/5410 recently changed behaviour when they are **no** keys to log out immediately. Since that was driven by the Delight team, I've send this feedback to their Inbox so they can decide how to tune from here.

**Comment by t3chguy** [comment]
Closing due to no response from the former Delight team. If this is still an issue it should probably be considered by element-meta for a cross-platform consistent implementation
