### ISSUE TITLE
@stranded:matrix.org: Cannot use their Security Key, always says invalid

### ISSUE THREAD

**Issue by aaronraimist** [vector-im/element-web#16073]
Debug logs incoming

See history from https://matrix.to/#/!YTvKGNlinIzlkMTVRl:matrix.org/$Qlm9DkA0AjJkjFvexPpvKMqXgW62APSo8iw49s1QKnU?via=matrix.org&via=privacytools.io&via=mozilla.org up

**Comment by jryans** [comment]
I would recommend they try these precise steps:

0. Consider exporting room keys to a file as a backup in an existing session via top left menu -> Settings -> Security -> Export E2E room keys (but you've said you don't have encrypted rooms at the moment)
1. If you don't have an existing develop session, it should be fine to login and skip any verification prompts
2. Reset secure backup first (this should now succeed without confusingly asking for previous keys)
3. Reset cross-signing keys (this may prompt for security key / phrase, it's expecting the new one you just made in step 2)
4. On other sessions, you should be able to either verify the new session and receive new keys or go to Settings and "setup" Secure Backup (green button instead of the red "reset"), which maybe prompt for the new security key / phrase as part of downloading your keys

**Comment by jryans** [comment]
It doesn't seem the original user is interacting here, and we have https://github.com/vector-im/element-web/issues/16118 for the general problem.
