### ISSUE TITLE
Invitation doesn't work on "old" Android Google Chrome version

### ISSUE THREAD

**Issue by cfeltz34** [vector-im/element-web#16133]
### Description

Invitation doesn't work on "old" Android Google Chrome version

### Steps to reproduce
- On Android device with Google Chrome v71.0.3578.99 (Android 6.0.1, Redmi 3S Build/MMB29)
- Open a group invitation "https://matrix.to/#/!JLjeKQflTkcRkvJNUa:matrix.org?via=matrix.org"
- Chrome is open with a white page
--> I want to have an invitation page with a link to download application
 - Update Chrome version to the latest version
 - Open the invitation group link
--> invitation page is OK

Remark : same issue with a old IOS mobile (iPhone6, iOS 12.4.9, Safari)

For the web app:
- **Browser**: Google Chrome v71.0.3578.99 (Android 6.0.1, Redmi 3S Build/MMB29
- **OS**: Android 6.0.1

**Comment by aaronraimist** [comment]
If it is an issue loading https://matrix.to then please open an issue on https://github.com/matrix-org/matrix.to

If the issue is loading Element, Element only supports the last 2 major versions of Chrome, Firefox, and Safari https://github.com/vector-im/element-web#supported-environments so this is not likely to be fixed.

**Comment by cfeltz34** [comment]
Ok, the bug has been transfered to https://github.com/matrix-org/matrix.to/issues/190
