### ISSUE TITLE
Deep links don't give a mobile guide

### ISSUE THREAD

**Issue by turt2live** [vector-im/element-web#16283]
see https://github.com/matrix-org/conference-bot/issues/27

**Comment by jryans** [comment]
Hmm, I guess I am forgetting some of the history of _why_ we're skipping the mobile guide for deep links and 3PID invites, but it's clearly an intentional choice as part of https://github.com/vector-im/element-web/issues/7378.

**Comment by benparsons** [comment]
Appears that the decision in 2018 was to show a room preview when the page is loaded on mobile web. Now, the question is whether this preview can also include a mobile guide - a banner which says "if you have the element app installed click to open this room in the app".

Options:

1. as we are now, a static preview of a room
2. redirect to mobile app (what happens if the app is not installed? does the browser show an error, or silently fail, sating on the preview page?)
3. have a CTA banner which suggests those with the app installed click to open the room in the app

**Comment by nadonomy** [comment]
@benparsons @jryans I think the rationale in https://github.com/vector-im/element-web/issues/7378 to show unstyled/non-responsive rooms in the mobile browser is a little short sighted.

Some things that spring to mind for the right solution would be:

- On iOS, ensure we display a smart app banner with `app-argument` deep linking
- On Android, is there an equivalent? I found [this](https://developers.google.com/web/fundamentals/app-install-banners/native) on first look but looks to be Chrome only.
- Improving responsive styling

In an ideal world we'd have all of the above, but @benparsons I know you're looking for something in the immediate term. For your use case, I wonder if we can shortcut this by using matrix.to links instead of deep links to an element web instance? Might be easier to chat in a room so will ping you somewhere sane.

**Comment by jryans** [comment]
After chatting with @ara4n today, we're thinking for deep links to rooms generally, matrix.to links with an additional parameter that suggests a specific Element Web deployment (which would need to be added to matrix.to) would be ideal here.

There's a separate problem of 3PID invites, so I'll file an issue for that.

**Comment by jryans** [comment]
@bwindels is going to work on support to suggest specific client instances in matrix.to.

I will work on adding some kind of banner to suggest mobile once you are inside.

**Comment by jryans** [comment]
The mobile guide toast has merged to develop, and can be enabled with `mobileGuideToast: true` in `config.json`.

**Comment by jryans** [comment]
I believe the matrix.to side of this has been resolved by @bwindels, so I believe we're all done here.
