### ISSUE TITLE
Element-desktop: The authenticity of this encrypted message can't be guaranteed on this device 

### ISSUE THREAD

**Issue by electricOzone** [vector-im/element-web#16336]
### Description

When using Element-desktop, many encrypted DMs and group chats show `the authenticity of this encrypted message can't be guaranteed on this device` on my messages sent from other devices, and other user's messages.
![element_desktop_error](https://user-images.githubusercontent.com/20979879/106468197-3b0a4200-6463-11eb-997b-84849677f0fa.png)

### Steps to reproduce

- Use Element-desktop
- Messages from other devices and other user's devices appear with error

Describe how what happens differs from what you expected.
Messages from my devices and from users I've verified should show up without error.

Logs being sent: yes

### Version information

- **Platform**: desktop
- **OS**: Ubuntu
- **Version**: 1.7.18

**Comment by phildenhoff** [comment]
Appears to be a duplicate of #16318

**Comment by electricOzone** [comment]
The platform in that case is web. This is specific to desktop (I realize the desktop app is still technically electron).

Also, that issue makes no mention of the user seeing the problem on their own devices.

**Comment by jryans** [comment]
@electricOzone Did you happen to restore from backup on your desktop session? There's nothing different between web vs. desktop in this area, so it should mainly revolve around whether your desktop session has accessed the backup or not.

**Comment by electricOzone** [comment]
I verified the new sessions using my cell phone by scanning the QR code.

**Comment by electricOzone** [comment]
The security menu also shows that secure backup seems to be working just by scanning the QR code.
![1](https://user-images.githubusercontent.com/20979879/107256808-9312ec80-69ff-11eb-87c4-5f9e1900e75f.png)

**Comment by thany** [comment]
I just installed Element on Windows 10, in addition to already perfectly working Element for Android and another one on Windows 10.

The last one I've now installed is also showing this shield & message for each and every message, and the other two clients are not. I've left *every* option on whatever the default is, as this is a totally fresh virgin vanilla install. This computer has never had Element installed before in its lifetime.

Nothing in the Security & Privacy settings indicates a problem. And like I said, I left them to whatever their defaults are.

**Comment by jryans** [comment]
@thany It sounds like you are seeing the authenticity gray shield only for old messages, in which case your issue is the same as https://github.com/vector-im/element-web/issues/14323.

**Comment by jryans** [comment]
@electricOzone Are you seeing authenticity gray shields even for new messages after you added the new session, or only pre-existing messages from before the new session was added?

**Comment by electricOzone** [comment]
Hm, I'm actually no longer seeing the grey shields. Previously, I was seeing them on new messages as well, yes. However, maybe this was fixed in 1.7.20?

**Comment by jryans** [comment]
As far as I know, there haven't been any changes in this area recently. My impression at the moment is you were perhaps getting message keys either from backup or from a different session for a time even on the new device.

In general, this seems like a duplicate of either https://github.com/vector-im/element-web/issues/16318 or https://github.com/vector-im/element-web/issues/14323. Since it's fixed now, let's close this.

**Comment by thany** [comment]
@jryans  
> @thany It sounds like you are seeing the authenticity gray shield only for old messages, in which case your issue is the same as #14323.

I have no way of knowing that they are two distinctly different problems. I just don't want to see that kind of message *at all* when I have verified and chosen to trust this device in all honestly, with a pre-existing verified&trusted device.

As an experienced pc user, I can kinda sorta imagine how such a problem comes into being. But for a novice user this might be an alarming message. They might believe something is wrong with their devices security-wise and/or choose to distrust the session, the messages, or Element as an application/service.

**Comment by HacKanCuBa** [comment]
I had this issue 2 years ago, and stopped using Element desktop. I started using it today, and I'm seeing gray shield on both old and new messages. What's more, I can't decrypt old messages, so that is irrelevant I guess.

On the browser, the gray shield is not visible. On Element Android, the gray shield is not visible.

The room version is 10, not sure if that is relevant.

The user in question is of course verified, and all his and my devices are fully verified/signed/cross-signed, and we even sacrificed a goat during the cross-signing ritual, everything, just in case, you know.

So yeah, this is very much not solved 🤷 .

**Comment by HacKanCuBa** [comment]
I had this issue 2 years ago, and stopped using Element desktop. I started using it today, and I'm seeing gray shield on both old and new messages. What's more, I can't decrypt old messages, so that is irrelevant I guess.

On the browser, the gray shield is not visible. On Element Android, the gray shield is not visible.

It is a 1:1 chat, and the room version is 10, not sure if that is relevant.

The user in question is of course verified, and all his and my devices are fully verified/signed/cross-signed, and we even sacrificed a goat during the cross-signing ritual, everything, just in case, you know.

So yeah, this is very much not solved 🤷 .

It looks like https://github.com/element-hq/element-ios/issues/5766

**Comment by theUpsider** [comment]
Bump. Same issue persists.

**Comment by speedyconzales** [comment]
also experiencing this issue

**Comment by shmerl** [comment]
I'm seeing it now with Element web, it started after this big cloudflare outage when element was down.

**Comment by Avamander** [comment]
Just logged in, all the messages have this warning. Unsure why this issue was closed if this is really not solved.

**Comment by thany** [comment]
It's definitely not solved. I've seen it "randomly" over the past years as well.

And again, anyone intimately familiar with Element and Matrix might shrug it off as normal/expected behaviour. But most people are not like that - most people are likely to be novices, who are understandably concerned when seeing this message.

So if there's *not* actually a genuine problem: just don't display these grey shields. You're only making the user concerned for no reason.
If there *is* a genuine problem: well, solve it then please 🙏🏻 Or at the utmost minimum, update the message to be more indicative of what the actual problem is and how to solve it.

⚠ This issue needs reopening, because neither has been done, and people are still experiencing the issue.

**Comment by Klumni932** [comment]
Same Problem.

In this case, the recipient uses Linux wrapper. The sender uses Windows Desktop.

Messages from the sender are marked with the symbol in the Linux client, everything looks normal in the Win client.

Everything looks normal in the Android client.

**Comment by thany** [comment]
I see that the grey shield has now turned into an `(i)` icon.

Guys, this is not the solution 😒
You're just making the same exact message look friendlier or something by hiding it behind an icon that looks less intimidating. But the actual problem is still there!

Please reopen this issue and get the problem *actually* fixed.

**Comment by mysteriousbenefactor** [comment]
I'm using element desktop on linux, after verifying my account with my key all past messages have this notice attached to it, unclear what it means when our accounts are verified

**Comment by Tachytaenius** [comment]
Just got bitten by this too. I'm not really... sure what's going on? I'm new to Matrix.
Was using web app, installed desktop, couldn't get it to detect keyring stuff (I'm using Linux with i3) despite a lot of trying so I said "use no encryption" hoping I could fix it later. After verifying, I see this stuff on the messages I sent while on the web app. Is saying "use no encryption" to the desktop app that what the problem is? Or is that just for local storage stuff??

**Comment by tjnangosha** [comment]
I am currently having this issue as well. I can see the messages but the images cannot load. Mobile is working fine.

OS : Ubuntu 24.04 LTS
Client : web(chrome)
Element version: 1.12.13
Crypto version: Rust SDK 0.16.0 (1ac734e), Vodozemac 0.9.0

<img width="391" height="84" alt="Image" src="https://github.com/user-attachments/assets/481a534f-1544-472b-9d21-b285e228a91e" />
