### ISSUE TITLE
"Wrong Security Key" despite setting in the correct key

### ISSUE THREAD

**Issue by PeakPuzzle** [vector-im/element-web#16455]
### Description

"Worng Security Key" Disprite setting in the correct Security key.

### Steps to reproduce

- For bugs, list the steps
- that reproduce the bug
- using hyphens as bullet points

Describe how what happens differs from what you expected.

Whenever I want to verify my devices, I cannot use my Security Key since i apparently entered the "Wrong" Security Key, Despite having the Correct one.

I've tried to use the Encryption Secure Backup to generate different Secure Keys as well, but I'm still denied access to verification
![Screenshot_38](https://user-images.githubusercontent.com/79091373/107966163-c0d1d580-6fab-11eb-8ec2-fbb05a01c5ac.png)
.

### Version information

- **Platform**: web (in-browser) or desktop?

For the web app: Firefox, Windows, app.element.io, riot.im

- **Browser**: Chrome, Safari, Firefox? which version?
- **OS**: Windows, macOS, Ubuntu, Arch Linux, etc?
- **URL**: develop.element.io / app.element.io / somewhere else? If a private server, what version of Element Web?

For the desktop app: Windows, 1.7.20

- **OS**: Windows, macOS, Ubuntu, Arch Linux, etc?
- **Version**: 1.x.y

**Comment by jryans** [comment]
I recommend trying to reset cross signing and secret storage:

0. Consider exporting room keys to a file as a backup in an existing session via top left menu -> Settings -> Security -> Export E2E room keys (but you've said you don't have encrypted rooms at the moment)
1. If you don't have an existing develop session, it should be fine to login and skip any verification prompts
2. Reset secure backup first (this should now succeed without confusingly asking for previous keys)
3. Reset cross-signing keys (this may prompt for security key / phrase, it's expecting the new one you just made in step 2)
4. On other sessions, you should be able to either verify the new session and receive new keys or go to Settings and "setup" Secure Backup (green button instead of the red "reset"), which maybe prompt for the new security key / phrase as part of downloading your keys

**Comment by jryans** [comment]
It doesn't seem like the reporter is following this issue, and we have https://github.com/vector-im/element-web/issues/16118 for the general problem.
