### ISSUE TITLE
Read receipt markers go off screen

### ISSUE THREAD

**Issue by HarHarLinks** [vector-im/element-web#16563]
### Description

I have noticed in recent nightlies (not sure when exactly, but a week at most) that the message read receipts (room members mini avatars on the right) sometimes move "too far down" and get hidden.
Hovering my mouse over them highlights one message farther up, so if the last message is marked read, it moves out of the displayed area.

### Steps to reproduce

Probably just happens, but for reference I'm using the "more compact 'Modern' layout", dark theme, read receipts enabled.

Logs being sent: no

### Version information

- **Platform**: desktop

For the desktop app:

- **OS**: Arch
- **Version**: aur/element-desktop-nightly-bin 2021022601-1 (from the .deb nightly)

**Comment by t3chguy** [comment]
Looks like a re-regression caused by https://github.com/matrix-org/matrix-react-sdk/pull/5567 earlier caused by https://github.com/matrix-org/matrix-react-sdk/pull/3892 which was reverted in https://github.com/matrix-org/matrix-react-sdk/commit/f33c930c418475fbe8f02c0fbc73a86f7100e3b2

This sounds like https://github.com/vector-im/element-web/issues/12675 though?

**Comment by SimonBrandner** [comment]
@t3chguy, yeah that didn't work out... @turt2live has something he needs this for... The IRC layout is fine, so I guess a Modern layout override should work
