### ISSUE TITLE
Element Desktop should prompt before quit (like Chrome does)

### ISSUE THREAD

**Issue by ara4n** [vector-im/element-web#16620]
Particularly if you're using an embedded jitsi, it's muscle-memory to shut the conference by hitting ctrl-Q/cmd-Q.  This then destroys your whole Element and takes ages to recover; instead we should prompt whether the ctrl-Q/cmd-Q is really needed, just as Chrome does.

**Comment by gsouquet** [comment]
There are two main ways to address this issue

- A native dialog with two Yes/No call to action
![Screen Shot 2021-03-23 at 08 09 44](https://user-images.githubusercontent.com/769871/112283375-fc814e80-8c7f-11eb-8fdd-1d24a6f245be.png)

- A Matrix UI that would ressemble what Google Chrome does
![Screen Shot 2021-03-24 at 09 05 25](https://user-images.githubusercontent.com/769871/112283633-423e1700-8c80-11eb-803e-b90bdbf38312.png)

The former brings two advantages in my opinion, it has a native look and feel, and will match the user's OS by default. And it comes accessibility features out of the box
The latter is a bit more slick, and completely customisable

As an extra, we could with both solutions let the user opt-out from that "warn before exit" feature. Since this would exist only as part of Element Desktop, @jryans suggested to use the contextual menu a la Chrome

![Screen Shot 2021-03-24 at 09 10 20](https://user-images.githubusercontent.com/769871/112284184-dc05c400-8c80-11eb-9304-d9ee31edb753.png)

We will discuss this with the Product team (@nadonomy ) on Thursday morning to decide how to move this forward

**Comment by t3chguy** [comment]
Keep in mind that on Windows the context menu is not visible by default. Same on a lot of Linux DEs. I also don't think chrome on Windows does warn

**Comment by gsouquet** [comment]
After discussing with the Product team, a UI a la Chrome is the preferred way forward. The acccessibility concern can be alleviated using the relevant ARIA attributes

However JavaScript decided to throw a spanner in the works and the way that `keyup` works would prevent us from implementing the desired experience.

As soon as the `command` key is down no other `keyup` event will be triggered until the `command` key is released. Meaning that we would have no way of cancelling the exit request if a user only release the "Q" key and keeps the `command` key down

**Comment by jplatte** [comment]
Just upgraded element-desktop from 1.7.24 to 1.7.28 and noticed this when hitting Ctrl+Q (on a Linux system).

I don't like this change at all and haven't seen the same behavior in any other app. Chrom[e/ium], which is referenced in the issue description, doesn't listen to Ctrl+Q at all on my system, but also doesn't prompt when closing the window and critically, doesn't run in the background after the window is closed.

**Comment by gsouquet** [comment]
@jplatte you can disable this behaviour in your user preference if this does not suit your workflow.
If you feel like this does not solve your problem I would invite you to open an issue so that this can be properly tracked and discussed
