### ISSUE TITLE
Room list minimum width is bigger on 1.7.23

### ISSUE THREAD

**Issue by tjaderxyz** [vector-im/element-web#16687]
### Description

The smallest size I can have the room list before it collapses into only icons is about one third of my usual window size. Before 1.7.23 I could have it smaller than now, but I would like it to be even smaller than that. As long as I can see a couple letters of the room's name it's enough to disambiguate.

### Steps to reproduce

- open element
- try to make the room list small
- it collapses into icons as soon as it's smaller than about 300 px

Describe how what happens differs from what you expected.

I would like to be able to have the room list be as small as ~100 px without it collapsing.

This is as small as I can get it:
![image](https://user-images.githubusercontent.com/81907/111199700-b7825b80-859f-11eb-86bb-5a204197b1f8.png)

### Version information

- **Platform**: web

- **Browser**: Firefox 86.0.1
- **OS**: Windows
- **URL**: app.element.io

**Comment by WillPittenger** [comment]
I'd suggest a minimum width of only a few pixels wider than needed for icons only.  40px at most.  And yes, pixels (or points) rather than a percentage of the window width.  I'd also suggest a button to collapse/expand it.

**Comment by MacLemon** [comment]
Also affects Element/Electron 1.7.23.

Snapping behaviour is also quite position intolerant now.
Before it would snap collapse when one dragged significantly smaller than the minimum-width. That way one could comfortablby drag until the sidebar would not get any narrower and release the drag to have the sidebar use that minimum-width.

Since 1.7.23 it immediately collapses when you drag beyond the new minimum-width and the sidebar immediately collapses. This results in the requirement for a pixel-perfect drag of the user to result in a minimum-width sidebar. This is very hard to achieve for most users since many trackpads/trackpoints/mouses/tablets are barely able of pixel-perfect positioning, let alone dragging.


As an uninteded side-effect, Element/Electron now remembers the *un*collapsed state of the sidebar across application launches. Before 1.7.23 it would always launch collapsed and had to be uncollapsed upon each and every application launch. I guess this is because the new minimum-width is wider than the width that was used to determine the collapse-state upon state restoration. Please pay attention not to re-break the now correct state-restoration when fixing the minimum-width bug. :-) Thanks!

**Comment by mutualaidwork** [comment]
Behavior that I initially thought was a bug because it's suddenly so unintuitive.

After updating, I thought that my channel list was stuck with only icons, because the application launched with only channel icons visible, and moving the width adjustment bar didn't visibly do anything. Submitted a bug report then realized that the bug I was experiencing was the same as this issue, and closed my bug issue.
