### ISSUE TITLE
we shouldn't let you place or answer voip calls if you haven't accepted mic permissions

### ISSUE THREAD

**Issue by ara4n** [vector-im/element-web#16733]
we should wait until permissions are granted before actioning a place or pickup, otherwise the other person finds themselves on an empty call and assumes it's all broken

**Comment by SimonBrandner** [comment]
This already happens for outgoing calls but for some reason `m.call.hangup` isn't sent when getting `userMedia` fails while trying to answer an incoming call.

**Comment by SimonBrandner** [comment]
This should already happen...

**Comment by DantrazTrev** [comment]
The time when someone places a call if the permissions aren't then the call isn't placed with an error( which isn't much descriptive)
![image](https://user-images.githubusercontent.com/43457420/112097132-7c96ae00-8bc5-11eb-8f24-417d1ba4edcf.png)

But while answering calls if the permissions aren't given there is an error on the answering side but the call just continues on the caller's side 

 Maybe at this time we could use send hangup with a different error or just plain reject?

**Comment by SimonBrandner** [comment]
The fact that the first error is non-descriptive is weird - I'll look into it. 

I am not sure what exactly should be the behaviour here. Should the call be _rejected_ on all devices if callee can't answer on one device of the devices?

Anyway, it is not exactly clear to me what @ara4n is experiencing. Does the call keep ringing on the caller's side or does the ringing stop? If it is the former, it is the current expected behaviour (as far as I know). If it is the latter, it is a bug. From the words _empty call_ it sounds to me like the latter.

**Comment by DantrazTrev** [comment]
The call keeps ringing on the caller side if the receiver accepts the call and it fails (due to permission errors) , I could see it being useful in the case of multiple devices . But I tested it for a single device and the caller is still stuck on an empty call with no one to receive  as the only device has hungup with an error

I think @ara4n is talking about if a user receives a call they shouldn't be allowed act(more specifically answer) on it until permissions are given as this will result to an empty call with no device as a receiver (As mentioned above)

**Comment by SimonBrandner** [comment]
> But I tested it for a single device and the caller is still stuck on an empty call with no one to receive as the only device has hungup with an error

I am not sure I understand. I don't think there is a way to handle things differently based on the number of devices.

> if a user receives a call they shouldn't be allowed act(more specifically answer) on it until permissions are given as this will result to an empty call with no device as a receiver (As mentioned above)

_As far as I know_, the user isn't allowed to act on it until the permissions are given - `m.call.answer` is not sent if the permissions are not given. But maybe you mean the UI here? Do you mean that the `CallView` should not appear before permission are given?

**Comment by DantrazTrev** [comment]
> > But I tested it for a single device and the caller is still stuck on an empty call with no one to receive as the only device has hungup with an error
> 
> I am not sure I understand. I don't think there is a way to handle things differently based on the number of devices.

I was trying to justify a use case for the hangup after an error approach .


> > if a user receives a call they shouldn't be allowed act(more specifically answer) on it until permissions are given as this will result to an empty call with no device as a receiver (As mentioned above)
> 
> _As far as I know_, the user isn't allowed to act on it until the permissions are given - `m.call.answer` is not sent if the permissions are not given. But maybe you mean the UI here? Do you mean that the `CallView` should not appear before permission are given?

Yes I meant about the UI , but now I think specifying the error more clearly would help for now ; cause the above case would need a lot design and decisions

**Comment by SimonBrandner** [comment]
> but now I think specifying the error more clearly would help for now ; cause the above case would need a lot design and decisions 

Yeah, we should fix the error first. Thanks for the clarification :+1:

**Comment by ara4n** [comment]
The error I saw here was that I placed a voip call.  The signalling went out, but I hadn't given media permissions yet.  The other person answered it, and had no media.  By the time i woke up and granted permissions to the app, they'd hung up.

**Comment by SimonBrandner** [comment]
I don't think I can repro, could you share info about what browser were you using etc.

**Comment by SimonBrandner** [comment]
Thank you for opening an issue. Unfortunately, I wasn’t able to reproduce it. If you keep experiencing this defect, please update your description with steps/screenshots/video/more details and add a comment with `@SimonBrandner` to let me know that it’s ready to be reopened.
