### ISSUE TITLE
new confirm to quit not working on sway

### ISSUE THREAD

**Issue by HarHarLinks** [vector-im/element-web#16848]
### Description

A confirmation dialogue for quitting element desktop was recently added (nightly). On sway, `Ctrl+Q` makes the dialogue appear, however neither confirming nor denying does quit element. `Ctrl+Shift+Q` minimizes Element to tray, makes the dialogue appear somewhere behind something.

This applies not only when Element is in focus, but it actually steals focus for the key combo even from other applications, e.g. my browser. Apparently also `F4` is captured the same way from htop within uxrvt (`Alt+F4` being the relevant key combo on windows). Noticably both of these are not native wayland apps but run through xwayland.

### Steps to reproduce

- as above
- hit me with techincal questions about details that may be missing

Logs being sent: yes

### Version information

- **Platform**: desktop

For the desktop app:

- **OS**: Arch Linux
- **Version**: aur/element-desktop-nightly-bin 2021033001

**Comment by SimonBrandner** [comment]
The dialog doesn't work for me either - it doesn't allow me to quit.

+ KDE+i3wm
+ Debian Bullseye 
+ Element Nightly version: 2021040101

**Comment by SimonBrandner** [comment]
> This applies not only when Element is in focus

This should be solved in a later build

**Comment by SimonBrandner** [comment]
Also, if you try to debug this make sure you have only one instance of Element running otherwise _weird things happen_

**Comment by SimonBrandner** [comment]
It looks as if simply setting an event listener prevents the default handling of the event (at least on Linux). 

We could simply do this, but there might be a better solution

```js
if (shouldCancelCloseRequest) {
    event.preventDefault();
} else {
    app.quit();
}
```

**Comment by HarHarLinks** [comment]
Disabling the dialogue in the settings does not improve the situation, only the dialogue isn't shown at all.

**Comment by HarHarLinks** [comment]
I'm now on Element Nightly version 2021040201 and it appears resolved if you can confirm, @SimonBrandner?

**Comment by SimonBrandner** [comment]
Weird, I thought I could have reproduced this on develop branch, works on `2021040201` :man_shrugging:

**Comment by DaAngus** [comment]
I have the same setup and everything is updated.
I found out about this dialogue trough this thread, have never seen it.
What I experience is the same problem as described in the opening issue.

During this now fixed issue #20926 I had to restart frequently.
The lingering electron processes prevented me (and most likely others there) to restart element because it never exited properly.

I have watched my processes and can confirm that only `Ctrl+Q` closes element.
On Gnome it is the same I was told.

**Comment by SimonBrandner** [comment]
@DaAngus, could you please confirm your issue is a duplicate of https://github.com/vector-im/element-web/issues/18734 or https://github.com/vector-im/element-web/issues/17344?

**Comment by DaAngus** [comment]
They are related, but in #17344 the posts from 2021 are not relevant because it does indeed close with `ctrl+Q`
Just tested 5 times with and without the dialog active and it worked,

In #18734 it is similar, the issues from 2021 do not apply and I can not confirm the latest report that `Ctrl+Q`is not working.
There are both, reports that `Alt+F4` does and does not work. For me it does not work.

I guess operating systems or desktops try to catch different key combinations which are not passed trough to the application?

Most likely the same source of the error just different effects on different Setups.
