### ISSUE TITLE
The encrypted message search area does not differentiate between desktop and web

### ISSUE THREAD

**Issue by Zachinquarantine** [vector-im/element-web#16864]
### Description

Describe here the problem that you are experiencing, or the feature you are requesting.
When going to Settings > Security and Privacy on Element Desktop, and scrolling down to "message search", the following appears:
Element can't securely cache encrypted messages locally while running in a web browser. Use Element Desktop for encrypted messages to appear in search results.

The thing is, I'm using element desktop, but it's not detecting it...

### Steps to reproduce

- Go to Settings > Security and Privacy on element desktop
- Scroll down to message search
- You should see a message like the one above

Describe how what happens differs from what you expected.
I expected to be able to search encrypted messages.

Logs being sent: yes

![slika](https://user-images.githubusercontent.com/69423184/113611422-7cae9900-961c-11eb-88b3-c49862c62a8b.png)

### Version information

- **Platform**: desktop

For the web app:

For the desktop app:

- **OS**: Windows
- **Version**: 1.7.2.4

**Comment by Zachinquarantine** [comment]
logs sent

**Comment by Zachinquarantine** [comment]
Should I reopen this on vector-im/element-desktop?

**Comment by jryans** [comment]
This is the same issue as https://github.com/vector-im/element-web/issues/15168, which so far is only fixed in the nightly build. It will part of the release version next Monday.

(This will only fix the message... It's showing the wrong message because there's some kind of indexing error. Nightly also contains further work to offer a button to try resetting the index to correct the problem.)
