### ISSUE TITLE
LGBT Flag Emojis do not display on Linux.

### ISSUE THREAD

**Issue by AverytheFurry** [vector-im/element-web#16884]
![2021-04-07_12-57](https://user-images.githubusercontent.com/47131867/113926298-84686c00-97db-11eb-9325-af988818dfc4.png)

### Description

LGBT Flag Emojis do not display correctly on the linux client. I have heard other users tell me they have the same issue

### Steps to reproduce

- Paste the transgender flag emoji `🏳️‍⚧️`
- See it not display correctly (on linux), displays fine on windows and the f-droid build.

Describe how what happens differs from what you expected.

I would expect the emoji to be displayed correctly, as it is on element on windows and f-droid, but it does not.

Logs being sent: no, not relevant

### Version information

- **Platform**: web (in-browser) or desktop?

For the desktop app:

- **OS**: Arch Linux
- **Version**: 1.7.24-1

**Comment by jryans** [comment]
This was added in Unicode 13.0. We likely need to do one or more updating `emojibase` (https://github.com/vector-im/element-web/issues/15982) and updating our emoji font to include this.

**Comment by ShadowJonathan** [comment]
Im using Element Desktop on linux, on flatpak, and transgender emojis display nicely for me.

**Comment by AverytheFurry** [comment]
> Im using Element Desktop on linux, on flatpak, and transgender emojis display nicely for me.

Distro?

**Comment by ShadowJonathan** [comment]
PopOS 20.10, not sure if I have more font thingies installed to the side.

**Comment by AverytheFurry** [comment]
This is the package I'm using
https://archlinux.org/packages/community/x86_64/element-desktop/

**Comment by ShadowJonathan** [comment]
I'm using https://flathub.org/apps/details/im.riot.Riot

**Comment by samhh** [comment]
I'm seeing the same on Arch. Did you get a chance to try the linked flatpak @AverytheFurry?

**Comment by AverytheFurry** [comment]
> I'm seeing the same on Arch. Did you get a chance to try the linked flatpak @AverytheFurry?

I dont usually like installing "easy" package managers, but i can try it when I get home.

**Comment by AverytheFurry** [comment]
> I'm seeing the same on Arch. Did you get a chance to try the linked flatpak @AverytheFurry?

I have finally done it and yes it worked lol

**Comment by samhh** [comment]
Hmm, that would suggest it's an issue with the Arch package, perhaps a missing optional dependency or something.

**Comment by daenney** [comment]
I'm having the same issue on Element Desktop on Arch Linux and for the life of me I can't figure it out. It seems specific to Element Desktop, in that it works fine for other Electron apps in my case (for example VS Code or Jitsi).

**Comment by duxovni** [comment]
As a new data point: This is still present in Arch Linux's build of Element Desktop 1.10.12. It seems to be a problem with Arch's Electron more broadly, though:

### My setup
**In a fresh Arch Linux, install**
- Element Desktop (Electron 17)
- Code (Arch's build of VS Code) (Electron 17)
- Obsidian (Electron 17)
- Bitwarden (Electron 16)
- Emacs (non-Electron)

**Paste a trans flag emoji into all of these:** Element Desktop displays the broken-up white flag and trans symbol; all the others display missing-character placeholders, presumably because they aren't packaged with any emoji fonts and I haven't installed any.

**Add the `TwemojiMozilla-colr.59b896a.woff2` file from Element Desktop to `~/.fonts` and update the fontconfig cache, then reopen all the apps and repeat:** All of the Electron apps display the broken-up white flag and trans symbol, Emacs displays the trans flag emoji properly.

I'm not sure why my findings don't match @daenney's; were your VS Code and Jitsi built off of Arch's official Electron packages, or were they custom AUR versions?

In any case, this looks increasingly like not an Element bug, especially since we aren't involved in maintaining the Arch Linux package as far as I know; it'd still be nice to get fixed but I'm not sure there's much to be done on our end.

**Comment by duxovni** [comment]
Closing in favor of https://bugs.archlinux.org/task/74736
