### ISSUE TITLE
[design] Alter the `(@user:server.net)` suffix on duplicated displaynames to be "out of band" of the displayname itself

### ISSUE THREAD

**Issue by ShadowJonathan** [vector-im/element-web#16897]
I feel like i can best describe this with the comparison between two images:

![image](https://user-images.githubusercontent.com/22740616/114188061-02965100-9949-11eb-8950-0dd70e3f6446.png)
And;
![image](https://user-images.githubusercontent.com/22740616/114188075-088c3200-9949-11eb-8224-8aa8894b4c36.png)

The first image describes the current behaviour, the second one the behaviour I want; I'd want for the `(@user:server.net)` suffix of displaynames to be reworked so this displays as a "tag" instead (such as discord's "BOT" labels:
![image](https://user-images.githubusercontent.com/22740616/114188284-4721ec80-9949-11eb-808a-bea96ddbebe2.png)
But meant to be less "visible"

That mockup was generated with:
```css
color: grey;
font-size: 80%;
font-family: monospace;
margin-left: 1px;
```

Plus placing the `(@user:server.net)` manually in `<span>` tags, and then applying above CSS to the specific span.

(A bug variant of this request is #16896, which describes specific behaviour when a user detail sidebar is opened on the right)

**Comment by ShadowJonathan** [comment]
Alternate configuration where the username is "under" the displayname, like so:
![image](https://user-images.githubusercontent.com/22740616/114189625-b0562f80-994a-11eb-868f-fef8858c661c.png)

**Comment by niquewoodhouse** [comment]
I personally really like this idea because it seems small to do _and_ is hopefully high reach (hopefully most users view a populated timeline) _and_ makes it easier to read every timeline, which is pretty important.

Somethings I don't quite understand:

- Are the brackets necessary for some reason around the `(@user:server.net)`?  If so, what are they doing?
- Sometimes in my timeline I see people who don't have their `(@user:server.net)`bit, and just a name

![image](https://user-images.githubusercontent.com/1587166/115008078-9c5a8280-9ea2-11eb-9956-d80a2723dac7.png)

vs 

![image](https://user-images.githubusercontent.com/1587166/115008141-ae3c2580-9ea2-11eb-8851-84292d86c693.png)


Do we know the reasons as to why that might happen, I'm totally guessing it's something configured on the homeserver, or by a user in their settings? 

I was seperately wondering if, longer-term, forcing the `(@user:server.net)` to be visible on tapping/hovering on the user in a small pop up was as useful/might be the right place for it where you can take more actions (eg message/ignore etc)

Discord example
![image](https://user-images.githubusercontent.com/1587166/115011540-a5e5e980-9ea6-11eb-8da8-741e2f70b660.png)

Slack example
![image](https://user-images.githubusercontent.com/1587166/115011564-b0a07e80-9ea6-11eb-9dc6-bd2c6f57ed46.png)

**Comment by t3chguy** [comment]
The appended bit in brackets is a disambiguation, it only shows up for users whose display name in that room is not unique

Its to help prevent malicious acts which try and confuse you into believing a person is someone different by them setting their name+avatar to match someone you trust

**Comment by SimonBrandner** [comment]
> Are the brackets necessary for some reason around the (@user:server.net)? If so, what are they doing?

I don't think they are if a different enough styling would be used. But if we decided to have them I'd like to use the suggested square brackets (`Šimon Brandner [@simon.brandner:envs.net]`) because it nicely matches the Matrix logo (`[matrix]`)

**Comment by ShadowJonathan** [comment]
@niquewoodhouse I should note that the disambiguation side of things is noted [in the spec](https://spec.matrix.org/unstable/client-server-api/#calculating-the-display-name-for-a-user), while i feel that in this case it's more of an implementation detail (hiding as a recommendation), this could be open for design and discussion.

> But if we decided to have them I'd like to use the suggested square brackets (`Šimon Brandner [@simon.brandner:envs.net]`) because it nicely matches the Matrix logo (`[matrix]`)

Agreed, I think bracket disambiguation looks nice when styling :eyes: 

FTR, discord somewhat goes around the "malicious users" thing by implementing a bunch of other implicit trust-relationship methods, such as the Friend system, having users set special colors for admin roles (that stand out against the white), and using `#` disambiguation with usernames. All-in-all it creates tools to verify someone with, even if it's needing to be explicit.
