### ISSUE TITLE
Very confusing video conferencing

### ISSUE THREAD

**Issue by JosefWN** [vector-im/element-web#16953]
I just spun up Dendrite and tried the latest Element client (`1.7.25`) for the first time. Some of the issues might be related to setup or Dendrite, but:

1. Attempting to start a video call in a DM from the desktop client fails with a 502 against piwik and a 404 against: `_matrix/client/r0/thirdparty/user/im.vector.protocol.sip_virtual?native_mxid=...`
2. Attempting to start a video call in the very same DM from the iOS client works (using Matrix WebRTC?)
3. Attempting to start a video call in a room with only one additional participant in the desktop client works (using Matrix WebRTC?)
4. Attempting to start a video call in a room with more than two participants in total in the desktop client seems to launch Jitsi. Works but it's a bit choppy.

So four different flows for starting a meeting? I'm very confused... Why do the same function in different apps behave differently (iOS vs desktop), and why the added complexity/confusion of running multiple WebRTC solutions (seemingly custom WebRTC and Jitsi depending on the situation). Is the long-term plan to phase out Jitsi in favor of a more integrated WebRTC implementation?

**Comment by robintown** [comment]
For the record the reason that there are different solutions for 1-to-1 calls and 3+ person conference calls is that normally it is best for privacy purposes to establish a direct connection between each of the participants in the call. For a 2 person call this is what is done, but in the case of 3+ people, it is more efficient and reliable for each participant to send their video stream to a central location (a Jitsi Videobridge) in order to save bandwidth. The standard Jitsi web interface is used in this case since it works well enough, though in theory a custom UI could be developed that hides that Jitsi is being used behind the scenes (as was the case when FreeSwitch was used).

**Comment by SimonBrandner** [comment]
Also, there are _hopes_ to eventually replace Jitsi with a Matrix-based conferencing, but that is still _quite far away_

**Comment by ElementalFire53** [comment]
@JosefWN Did you ever find a solution to starting a video call in a DM from the desktop client? I just installed Dendrite and I am running into the exact same issue. 1-1 calls on iOS and Jitsi calls on desktop work, but 1-1 calls on desktop fail with the exact 404 that you stated. I haven't seen any other reports of this issue, but what you reported matches what I am experiencing exactly. Thank you for any help.

**Comment by robintown** [comment]
@ElementalFire53 The 404 sounds like it's proooobably a dendrite issue (or it might be that Element is trying something experimental that's only in synapse at the moment, not sure)

**Comment by jryans** [comment]
Thanks for the feedback on this. We're aware the different styles of conferencing can be confusing.

Since this is more of a meta-problem across both Matrix the protocol and multiple clients, I think a roadmap is a better place to track improving this, so I will close this issue. In any case, thanks for reporting this feedback! 😄
