### ISSUE TITLE
switching space resets the search filter

### ISSUE THREAD

**Issue by ara4n** [vector-im/element-web#16974]
which is super annoying if you filter your current space to find a room, discover it's not in that space, switch space, and then have to type the search term again

**Comment by t3chguy** [comment]
Mentioned here https://github.com/vector-im/element-web/issues/16847#issuecomment-818275888

@nadonomy you suggested this, should we hold off on more feedback or revert this?

**Comment by nadonomy** [comment]
There's definitely 2 opposing goals here; the other being that if I'm filtering for a room and then switch space to switch context my new space is broken while it's filtering for rooms which don't exist, and creating friction to then clear.

I think best to gather more feedback and we figure out the right trade offs to make holistically. As we get more feedback it might make sense to combine issues like this with others on filtering and switching spaces.

**Comment by ara4n** [comment]
i think there's a quick compromise solution to be had here:
 * If you've just been typing in the filter box, and then switch space *without clicking on a room tile*, then keep the edit in place.
 * However, if you select a room after having in the filter box, then when you next switch space, reset the filter.

**Comment by nadonomy** [comment]
> * If you've just been typing in the filter box, and then switch space _without first clicking on a room tile_, then keep the filter in place.

The simple common goal for all users is to switch between different spaces for different contexts with a simple click; matching affordance from Slack/Discord and to an extent browser tabs.

If we make it so users need to click twice to switch context, it makes the interaction tiresome and increases cognitive load (click -> scan & parse -> click) rather than simply click, and the last known state being presented.

I would heavily advocate against overcomplicating this simple interaction for everyone, to benefit some users who may want to persist active room filters sometime.

We could consider settings for this further down the line if we see an increased need for this? Or we could explore other interactions— for example, we could consider the primary goal to simply switch spaces with a click, and instead add a filter history for the users who do want to re-apply a previous filter.

**Comment by turt2live** [comment]
I tend to find myself clearing the filter manually once I've found the room I'm looking for anyways, or making a realization that things are filtered when I don't get the results I expect. This might be in part due to me filtering pretty harshly (typing "web" to ensure I get about 5 results, instead of "element" to get ~10), so the filter is more obvious.

At the moment this is high up there on my frustrations list, if it helps with the feedback portion.

**Comment by ara4n** [comment]
> If we make it so users need to click twice to switch context, it makes the interaction tiresome and increases cognitive load (click -> scan & parse -> click) rather than simply click, and the last known state being presented.

That's not what i'm saying.

I'm saying that if you search for a room, and it doesn't show up in your current space, then if you change space, the filter should still apply.

However, if you search for a room, and it does show up in your current space (and you show you found it by clicking on it to view the room)... and then you change space, the filter should be reset.

Is this a quick pragmatic fix, rather than making this a "let's think about it later"?

**Comment by nadonomy** [comment]
> That's not what i'm saying.

Ah gotcha. Thx for clarifying further. So with what you're describing I'd have some concerns around:

1.  Major concern around filtering currently being the wrong place in the hierarchy. Today it's presented as a child of a space rather than global, which forces an obtuse mental model for users, exacerbated by the kind of mechanics we're describing.
2. Minor-ish concerns around the filter/clear mechanics feeling unpredictable or unexpected.

Will discuss in more detail with @niquewoodhouse & @t3chguy more. In an ideal world if it's quick to experiment we could just do some hallway or beta testing on what you're describing (ironing out any thinkos).

**Comment by niquewoodhouse** [comment]
Just reading the last two comments makes me think this might work as a temporary beta fix:

![image](https://user-images.githubusercontent.com/1587166/115717434-1478ea80-a372-11eb-978c-5c05c89197fa.png)

- It avoids the filter/clear mechanics feeling unpredictable/unexpected
- Saves users from having to play the guessing game of which other space is `room name` in, so no need to scan & parse > click etc)

I'd still have the concern around the filtering being in the wrong place, but I think thats ok for the beta/we can't really change that without more substantial testing/research, and this is an issue a few people have highlighted as being super frustrating and making them think of leaving the beta, so feels like something we should fix if at all possible.

**Comment by t3chguy** [comment]
That would be *very* difficult to achieve with the way the Room List works though, definitely not doable in this sprint

**Comment by niquewoodhouse** [comment]
@t3chguy does it become much simpler if we put the results at the end of the room list, or somewhere outside of the room list?  Just curious

**Comment by t3chguy** [comment]
Not really

**Comment by t3chguy** [comment]
Given that the search is now an All rooms search I don't think this is an issue anymore. Shout if you disagree.
