### ISSUE TITLE
Can zoom in with "cmd -", but can not zoom back out

### ISSUE THREAD

**Issue by Jakob-Unfried** [vector-im/element-web#17104]
### Description

Hitting "cmd -" (to be explicit: the command key and the minus key at the same time)
zooms out on the interface.
After doing this, I can not find a way to zoom back in and everything is now too small to read.

### Steps to reproduce

- Open Element Desktop App on Mac OS
- Hit "cmd -" (multiple times)
- The view zooms out, everything (text, icons) becomes smaller
- "cmd +" does not revert this, nor does anything else i come up with, short of reinstalling the app

Logs being sent: yes (I hope I did it right, the small interface makes this somewhat hard)

### Version information

- **Platform**: desktop
- **OS**: macOS Catalina 10.15.7
- **Version**: 1.7.26

**Comment by t3chguy** [comment]
`Cmd -` and `Cmd =` (+ key next to - but without shift) works fine here
also `Cmd 0` for resetting zoom

**Comment by Jakob-Unfried** [comment]
@t3chguy 
`Cmd =` works - thanks.
However i would not have figured this out - i am using a german keyboard and `=` has nothing to do with `+` on it.

**Comment by t3chguy** [comment]
Related https://github.com/vector-im/element-web/issues/16964 https://github.com/vector-im/element-web/issues/9533

Not sure why we specify the accelerator instead of relying on the default https://github.com/vector-im/element-desktop/blob/466a871094fdc59f133b73f4e25cd685ab3745e8/src/vectormenu.js#L40

**Comment by Jakob-Unfried** [comment]
@t3chguy ping - i updated the comment above

**Comment by t3chguy** [comment]
The shortcuts are listed in the Window menu:

![image](https://user-images.githubusercontent.com/2403652/116526538-9bc5e100-a8d1-11eb-99a7-57cad7ddef77.png)

**Comment by Jakob-Unfried** [comment]
confirmed - my bad

**Comment by Jakob-Unfried** [comment]
I noticed that after all of this zooming in and back out, the letters in the read-icons on the very right side are now off-center.

![Bildschirmfoto 2021-04-29 um 11 10 57](https://user-images.githubusercontent.com/27769316/116528059-a6857380-a8db-11eb-92ff-baa68388e6db.png)


This really doesnt bother me much but I thought you might want to know.

**Comment by ewen-goisot** [comment]
"Ctrl =" does not work for me.
I use a non-standard keyboard layout named ETUSINA that you can find here :
https://configure.zsa.io/ergodox-ez/layouts/MaDpX/latest/2
and the behavior of shortcuts is quite strange : 
- "Ctrl -" works with the '-' of my own layout (bottom left, the place for 'w' in AZERTY or 'z' in QWERTY)
- "Ctrl =" does nothing (is it because I access '=' with AltGr ?)
- Same for "Ctrl 0" (it could be for the same reason, but again, I'm not sure).

After several tries, I found that "Ctrl #" can reset the zoom (because '#' on my keyboard where '=' is on QWERTY).
For example, in my current layout, the key with '=' on QWERTY has 'z' on ETUSINA, so the "zoom +" function is currently impossible to do for me (I can only do "zoom reset" to the default value).

Of course, my keyboard layout is unusual (but necessary for me),
but most other softwares allow me to zoom/unzoom with Ctrl+ and Ctrl-.
(I don't have to use the Shift key to do the '+')

I mean shortcuts have a quite unpredictable behavior on non-standard keyboard layout,
sometimes it takes the QWERTY key, and sometimes it takes the key for the other (ETUSINA) layout.

Is there a way to configure the keyboard shortcuts (currently or planned for later) ?

- Platform : desktop
- OS : Ubuntu 20.04LTS
- window manager : i3wm (it uses xorg)
- Element version : 1.9.9 (downloaded recently, with apt-get)

**Comment by sam0x17** [comment]
I am unable to zoom back in after zooming out, Ubuntu Budgie 22.04

**Comment by sam0x17** [comment]
omg I figured it out. Zoom out is just `CTRL+-` but for zoom in it's `SHIFT+CTRL+=`

**Comment by dsheeler** [comment]
@sam0x17 I swear I tried that and it didn't work until you suggested it. THANK YOU
