### ISSUE TITLE
Sign out button not working on app.element.io

### ISSUE THREAD

**Issue by ara4n** [vector-im/element-web#17217]

**Comment by ara4n** [comment]
https://user-images.githubusercontent.com/1294269/117580877-ed504600-b0f1-11eb-875b-96816c172109.mov

**Comment by ara4n** [comment]
(nothing in the console)

**Comment by jryans** [comment]
Hmm, working fine here... 😕

**Comment by HarHarLinks** [comment]
I just had a similar experience on develop.element.io:
- signed in fresh to check out some develop features
- takes a few minutes for element to sync my session
- xsign
- fiddle around for a couple minutes
- sign out
- nothing
- after a minute the sign out confirmation dialogue finally appeared and let me sign out
- since i had mashed the sign out button a dozen more times, also more of the dialogues

**Comment by t3chguy** [comment]
Duplicate of https://github.com/vector-im/element-web/issues/9319
