### ISSUE TITLE
EDUs with room id field cause notifications

### ISSUE THREAD

**Issue by timokoesters** [vector-im/element-web#17263]
### Description

Incoming EDUs over /sync can produce notifications if they contain the room_id field

Conduit:
```
{
	"ephemeral": {
		"events": [
			{
				"type": "m.receipt",
				"content": {
					"$zLsGHlRy8UIQnfoBCqagxOVz79DDb2y56XketZhxdw8": {
						"m.read": {
							"@tulir:maunium.net": {
								"ts": 1620812476643
							}
						}
					}
				},
				"room_id": "!EgoVrPyOnPSVXERlxj:gruenhage.xyz"
			}
		]
	}
}
```

Synapse:
```
{
	"ephemeral": {
		"events": [
			{
				"type": "m.receipt",
				"content": {
					"$inJlQ2wHie4DHUbNCbFRVCxInkCe5GFTqFbPwAEAbx8": {
						"m.read": {
							"@ace:kittenface.studio": {
								"ts": 1620812386378
							}
						}
					}
				}
			}
		]
	}
}
```

I assume the presence of the room_id key triggers Element to apply a push rule to the event.

You can see here in the spec that receipt events should contain a room id: https://matrix.org/docs/spec/client_server/r0.6.1#m-receipt

You can also see it in the example response to /sync: https://matrix.org/docs/spec/client_server/r0.6.1#get-matrix-client-r0-sync (but the /sync definition for `Event` doesn't list the room_id field, so maybe it's a gray zone).

I think Element should not play notifications sounds for EDUs in any case

Version: Element Web staging

**Comment by timokoesters** [comment]
I removed that field now in Conduit and it isn't a problem anymore, but this behavior still feels like some sort of bug in Element to me

**Comment by kegsay** [comment]
On further investigation, it looks like Element Web was applying push rules to events which were not live timeline events (account data, EDUs, state events, etc), due to it listening for `ClientEvent.Event`. This was changed in https://github.com/matrix-org/matrix-react-sdk/commit/d63a0d30c8de47ca1acc3886b7f6aab13976ff2c where the correct fix is just to listen for the old `Room.timeline` and check if `data.liveEvent` is true.
