### ISSUE TITLE
Customizing issues 

### ISSUE THREAD

**Issue by chagai95** [vector-im/element-web#17271]
### Description

I'd like to change the font to Helvetica and I tried a few things, but it seems to not work, probably a stupid mistake on my end...

This is what I tried...
```
"fonts": {
                        "faces": [
                            {
                                "font-family": "Inter",
                                "src": [{"url": "/fonts/Inter.ttf", "format": "ttf"}]
                            }
                        ],
                        "general": "Helvetica, sans",
                        "monospace": "'Courier New'"
                    }
```

Second issue is the buttons, found this in the code:

```
/* XXX: Our button style are a mess: buttons that happen to appear in dialogs get special styles applied
 * to them that no button anywhere else in the app gets by default. In practice, buttons in other places
 * in the app look the same by being AccessibleButtons, or possibly by having explict button classes.
 * We should go through and have one consistent set of styles for buttons throughout the app.
 * For now, I am duplicating the selectors here for mx_Dialog and mx_DialogButtons.
 */
```

I would like the default theme to have an `accent-color` of blue, but it seems to stay green for specific buttons - the join conference button for Jitsi for example (was easy to find) but more importantly the whole login flow which stays the same -  I think the red(warning-color) also stays the same but haven't checked that

**Comment by andybalaam** [comment]
For theming, please refer to https://github.com/vector-im/element-web/blob/develop/docs/config.md for information on how to do it. I don't see how the snippet you pasted above relates to that - could you link to the instructions you were following if I missed it?

The changes that are happening at the moment around [Compound](https://compound.element.io/?path=/docs/overview--docs) will hopefully make things more consistent in this area.

If you have a specific situation where you are trying some config and it's not working, please log a new issue with exactly what you did, what you expected to happen and what happened. Thanks!

I'm going to close this because I suspect you gave up ages ago. If you find specific bugs we'd welcome you creating issues, and if you have questions I'd recommend the #element-dev:matrix.org room.
