### ISSUE TITLE
UX Events in Roomlist often doesn't refresh (Context menu, Invites)

### ISSUE THREAD

**Issue by DoM1niC** [vector-im/element-web#17328]
UX Refreshing often not works here, Favourite mark don't update refresh / btn state & Roomlist.
Workaround: refreshing or clicking into the Roomlist again apply the changes as a small...

My Element is behind a NGINX via proxy_pass...

Element Web: develop
Synapse: develop

**Comment by SimonBrandner** [comment]
This feels like a regression to me. Is it?

**Comment by robintown** [comment]
Pretty sure it is, it also affects low priority

**Comment by SimonBrandner** [comment]
I've also heard reports of leaving rooms not updating the room-list... This probably caused by one of the attempts to speed up the room-list

**Comment by jryans** [comment]
Hmm, so far I can't seem to reproduce with e.g. favourites... This feature has always been very server sensitive, because it currently does not local echo the change, so it won't move until the server sends the change back across via sync.

Whenever the server has any performance issues, we often notice this feature "seemingly" not working.

Is that what's actually happening again here, or is there really something broken on the client?

**Comment by jryans** [comment]
https://github.com/vector-im/element-web/issues/14302 seems like the right issue to follow as far as adding some local echo for this.

**Comment by SimonBrandner** [comment]
Ok, after doing more tests this is just the fact that there is no local echo. @DoM1niC and @robintown, could you please confirm this?

**Comment by DoM1niC** [comment]
indeed this local echo make sense for me... the UX sometimes response in context but often not .... but this problem still already exist since I use Element/Riot, but currently the fav mark is heavy broken as before....

**Comment by robintown** [comment]
Let's continue to track this at https://github.com/vector-im/element-web/issues/14302
