### ISSUE TITLE
Remove the Element logo spinner

### ISSUE THREAD

**Issue by SimonBrandner** [vector-im/element-web#17419]
It seems that design is not interested in it...

**Comment by turt2live** [comment]
for clarity: this is a labs feature, but design has mentioned multiple times about how they don't want to use brand-based spinners due to it potentially giving a bad image to the brand (if people only see the Element logo while things are slow, people feel that Element sucks when that's not normally the reason for the slowness)

**Comment by robintown** [comment]
I'll do this :)

**Comment by t3chguy** [comment]
So travis what you are saying if I read between the lines is that we should have a Discord or Slack or MSTeams inspired spinner?

**Comment by turt2live** [comment]
![giphy (1)](https://user-images.githubusercontent.com/1190097/119048338-564e7e00-b97c-11eb-8e57-917a7868c1a8.gif)

**Comment by DantrazTrev** [comment]
Extending from this
The element logo could be used as a spinner while the web app loads so it is different from the other loading spinners? 

During this

![Screenshot from 2021-05-21 02-35-32](https://user-images.githubusercontent.com/43457420/119048979-998d0900-b9dd-11eb-9e5e-3b748ea3148b.png)

A bit like how Element Mobile does it?
