### ISSUE TITLE
Online Presence

### ISSUE THREAD

**Issue by bbacle** [vector-im/element-web#17487]
It would be great if you could make it where we can see if someone is online or not.

**Comment by aaronraimist** [comment]
That feature exists. The server you are on probably has it disabled which is why you can't see it.

**Comment by bbacle** [comment]
Can you tell me where it is so I can see if I can turn it on?

**Comment by aaronraimist** [comment]
If you are using Synapse: https://github.com/matrix-org/synapse/blob/develop/docs/sample_config.yaml#L85-L106. Otherwise you need to ask the developer of the homeserver you are using.

Element also has a config option to hide presence info so if you have that set to include your homeserver then you won't see presence. See `enable_presence_by_hs_url` in https://github.com/vector-im/element-web/blob/develop/docs/config.md
