### ISSUE TITLE
Can't scroll up in the right message panel

### ISSUE THREAD

**Issue by SimonBrandner** [vector-im/element-web#17567]
![Peek 2021-06-05 07-47](https://user-images.githubusercontent.com/25768714/120881562-49639880-c5d2-11eb-9d21-45115d3b445b.gif)

**Comment by DantrazTrev** [comment]
Seems like the bug occurs when the timeline is backpaginating. 
Probably has something to do with not passing the added `onUserScroll` props for the `FilePanel` which was not there in there earlier and is used in `ScrollPanel.js` for the wheel scroll?

If anyone else is not working I would like to take this up

**Comment by SimonBrandner** [comment]
> If anyone else is not working I would like to take this up

Sure, go ahead!

**Comment by DantrazTrev** [comment]
_Update_:
 Things probably regressed here matrix-org/matrix-react-sdk/pull/6079 . Specifically due to the relocating of `shouldComponentUpdate` from `TimelinePanel` to `RoomView` which causes the scroll component to be rerendered at every state update hence when the `onCheckupPrefill` is called when we scroll close to the top and `backpaginating` is set to true the `ScrollPanel` resets, also if you change any parent state similar change is observed 

Also when there is a new message in the timeline it resets , which is weird and unrelated.
