### ISSUE TITLE
quick theme toggle not working

### ISSUE THREAD

**Issue by HarHarLinks** [vector-im/element-web#17590]
### Description

This thing
![image](https://user-images.githubusercontent.com/2803622/121069252-8e9fea00-c7cd-11eb-8976-a5b1f14bf220.png)
isn't working for me at all.

The light theme will become selected in the menu like this
![image](https://user-images.githubusercontent.com/2803622/121069162-76c86600-c7cd-11eb-9d26-63af780eb676.png)
but theme is only applied when switching via this menu.

#17581 could be related.

### Steps to reproduce

- click light/dark theme quick toggle in the top left user menu thing
- potentially use these labs settings, especially custom themes
- no idea since when this is, i don't normally use this feature

![image](https://user-images.githubusercontent.com/2803622/121069203-83e55500-c7cd-11eb-857c-261ca77cb8e2.png)

Logs being sent: yes

### Version information

- **Platform**: desktop

For the desktop app:

- **OS**: Arch
- **Version**: aur/element-desktop-nightly-bin 2021060702-1

**Comment by Zachinquarantine** [comment]
It seems, for me on Windows running element build 1.7.30, that it will only work once you close off the app completely and reopen it.

**Comment by robintown** [comment]
This is because of setting watchers being broken, which is fixed in matrix-org/matrix-react-sdk#6143. However as the scope of that PR has grown, I think it might make more sense to just cherry-pick commit [40d2f8228f4d2a3f7f386d320c42ae1970932ee4](https://github.com/matrix-org/matrix-react-sdk/pull/6143/commits/40d2f8228f4d2a3f7f386d320c42ae1970932ee4) from it.
