### ISSUE TITLE
Upgrade electron to v13

### ISSUE THREAD

**Issue by gsouquet** [vector-im/element-web#17833]
https://www.electronjs.org/docs/breaking-changes#planned-breaking-api-changes-130

**Comment by bradtgmurray** [comment]
Looked a bit into this tonight and this is what I found:

Electron 13 also recommends an update to node version 14.17 (https://www.electronjs.org/releases/stable?version=13&page=2#13.0.0) which also means a bump in NODE_MODULE_VERSION (87 -> 89, https://github.com/nodejs/node/blob/master/doc/abi_version_registry.json#L8).

However, rebuilding seshat with this new version fails because the `neon` rust dependency is too old, and we get a few compile errors. Trying to bump just neon alone in https://github.com/matrix-org/seshat/blob/master/seshat-node/native/Cargo.toml#L21 doesn't work as `neon-serde` hasn't been updated to work with newer versions of `neon` (https://github.com/GabrielCastro/neon-serde/issues/64). It looks like there's some momentum around replacing `neon-serde` with native support within `neon` (https://github.com/neon-bindings/neon/pull/701) but it doesn't seem to be too close.

I'm guessing what needs to be done is to refactor `seshat` to no longer depend on this orphaned dependency, so we can then use a newer version of `neon`, which would allow `seshat` to be compiled with the new node verison, which then would allow us to upgrade electron.

**Comment by bradtgmurray** [comment]
Oh hey, seshat is already on it: https://github.com/matrix-org/seshat/issues/94

**Comment by julianfairfax** [comment]
> Oh hey, seshat is already on it: [matrix-org/seshat#94](https://github.com/matrix-org/seshat/issues/94)

Looks like that issue was solved

**Comment by gsouquet** [comment]
It's not been solved in https://github.com/vector-im/element-desktop yet

**Comment by PF4Public** [comment]
Running element-desktop-1.7.34 with electron 13. Works fine:
![image](https://user-images.githubusercontent.com/10319700/127874875-b7f8eff1-4ad3-40d4-9c9d-989024d2e370.png)

**Comment by gsouquet** [comment]
> Running element-desktop-1.7.34 with electron 13. Works fine:

That sounds pretty promising! Thank you for working on that
We would definitely welcome a pull request for this dependency upgrade. Feel free to open it in your own time and I will request a review from the team

**Comment by PF4Public** [comment]
But I didn't do anything special! It is already there: https://github.com/vector-im/element-desktop/commit/3fb802e563c7ecd26c25a8663a5d30c51508d837
