### ISSUE TITLE
element is not working with Tor socks proxy using cloudflare

### ISSUE THREAD

**Issue by githuberyt** [vector-im/element-web#17928]
Hey is there's a fix for this issue element is not working on Tor socks proxy and i use cloudflare on my private server i noticed matrix.org is using cloudflare as well and tor socks proxy work very well on matrix.org so maybe there's a config missing in cloudflare to activate

**Comment by gsouquet** [comment]
It appears that you have a configuration issue for your installation
You will have more luck asking for help in #element-web:matrix.org rather than filing an issue here where improvements and bugs are tracked

Will close this issue, but feel free to raise your question in the Matrix room where folks will be able to help you
