### ISSUE TITLE
Community invitation - notification

### ISSUE THREAD

**Issue by terasyntax** [vector-im/element-web#17949]
#### Description

Invite notification only appears after page reload

#### Steps to reproduce

1. User # 1 submits a community and invites user # 2 to it
2. User # 2 does not receive any invitation notifications

Has been reproduced at https://element.io/ in Chrome 91.0.4472.124

Is it a bug or a feature?

**Comment by SimonBrandner** [comment]
Element Web doesn't have push notifications if that's what you mean. The page has to be loaded for you to get notifications.

Also, communities will be replaced by spaces that are currently in beta

**Comment by terasyntax** [comment]
Thanks for the quick reply

I meant this notify 
![image](https://user-images.githubusercontent.com/5083772/125242662-33ef3600-e317-11eb-9a88-f677313bb8f8.png)

Okay, we'll try to use the spaces

**Comment by SimonBrandner** [comment]
Sorry, I am a little blind and misread your issue :sweat_smile: But yeah spaces should work better in this sense.  Feel free to read the [FAQ](https://gist.github.com/t3chguy/fdf541446d992d1fc96b8089b342fe7b) and visit the [The Spaces feedback "space" room](https://matrix.to/#/#spaces:riot.ovh) if you have any questions

Also, since this is a communities issue and they are getting replaced I am going to close this.
