### ISSUE TITLE
New replies show links in the message being replied to as clickable but they're not

### ISSUE THREAD

**Issue by babolivier** [vector-im/element-web#18017]
In that the entire message being replied to, including the link bit, is actually a link to that message in the room's timeline.

![Peek 2021-07-16 11-37](https://user-images.githubusercontent.com/5547783/125935461-e702f56b-75a1-457d-ae53-1e5deb970ba1.gif)

**Comment by t3chguy** [comment]
It is intentional, I think the missing bit is some transition to make the event you're going to more obvious than just the slight shading. This is how other platforms like Discord do it too.

![image](https://user-images.githubusercontent.com/2403652/125936221-49b0fcd3-b717-41bd-9991-5195d0494253.png)

**Comment by babolivier** [comment]
Oh, that's a pain if I have to jump to a completely different view in the timeline just to click a link, and then try to find my way back to where I was :/

**Comment by HarHarLinks** [comment]
I agree with babolivier, it is not intuitive to me. I would like to be able to click links and open pictures right where they are shown, i.e. from the "quoted" reply.

Further links (in and outside replies) should probably have a hover effect to indicate what the on click action is.

See also #18027

**Comment by SimonBrandner** [comment]
@niquewoodhouse, do you have any thoughts on this?

**Comment by HarHarLinks** [comment]
I realized why I expected replied-to images to be click-to-open-viewer in the reply: URL previews already do that.

These should absolutely follow the same/similar UX for looks and interaction
![image](https://user-images.githubusercontent.com/2803622/126680491-f2ca5c5c-a218-4511-83bb-1ae5cd3b0a5b.png)

**Comment by janogarcia** [comment]
If it looks like a link, then the user will expect it to work as such. Breaking from that default behavior is really unexpected and confusing.

We either style it as a plain-text if non-clickable or keep it as a real link. Given the current styling for quoted messages, which follows the same visual treatment as regular messages, it would be best to keep them as real links.

From a usability standpoint, I agree with @babolivier remark that it's really inconvenient to have to jump to that reply just to be able to click the link, to then jump back to the latest message.

**Comment by t3chguy** [comment]
> If it looks like a link, then the user will expect it to work as such. Breaking from that default behavior is really unexpected and confusing.

Discord does this
![image](https://user-images.githubusercontent.com/2403652/127001694-e299d120-331a-409b-b595-a1a58b244dc6.png)

hartk here is a link to a user but clicking anywhere including on hartk takes you back to the message and not that user.

**Comment by janogarcia** [comment]
It's an interesting example. Thanks, @t3chguy. But even if it's a popular and successful pattern on a specific platform, that doesn't necessarily mean that it's going to be equally successful for the masses and every possible context. 

We'd be introducing a breaking change for one of the most natural interactions on web. Following a link. Giving priority instead to a secondary action instead. Going back to a quoted message. I mean, if someone is **specifically hovering the link text/URL** and clicks on it, what is her intent?, what would be the expected behavior?, what's the most relevant thing that should happen according to the user's intent?

**Comment by babolivier** [comment]
fwiw I think the reason it might work on discord (even if I also find it meh over there personally) is because Discord makes it look much more like a preview of the message being replied to (preview appears in a small font, above the user's name/avatar, truncated quite shortly, less style on links etc (iirc), etc.) whereas Element's replies look much more like quoting the message before the reply, which I think is why people are confused about why they can't select the text, click links, etc.

**Comment by SimonBrandner** [comment]
https://github.com/matrix-org/matrix-react-sdk/pull/6396 changes that a bit though it's still not completely like Discord

**Comment by janogarcia** [comment]
Agree, @babolivier. That's actually what I meant by _"Given the current styling for quoted messages, which follows the same visual treatment as regular messages, it would be best to keep them as real links."_.

**Comment by babolivier** [comment]
Gah, I guess I skimmed too quickly over your message @janogarcia, my bad!

**Comment by janogarcia** [comment]
No worries, @babolivier! 😄
