### ISSUE TITLE
M9.1 Improved leave experience for spaces

### ISSUE THREAD

**Issue by t3chguy** [vector-im/element-web#18071]
![image](https://user-images.githubusercontent.com/2403652/126308267-e25fb3d0-0d35-4cab-ad2e-30501c7fe6cc.png)

**Comment by ShadowJonathan** [comment]
Would this recursively apply to all subspaces too?

**Comment by t3chguy** [comment]
Best effort at this time given that subspaces are as marked "Experimental"

**Comment by niquewoodhouse** [comment]
@nadonomy sharing this as I think it would benefit from your input -  we were using a previous design that gave users options to:

1. leave rooms/subpsaces
2. transfer their role to someone else

<img width="600" src="https://user-images.githubusercontent.com/1587166/127330217-160ca345-32bf-4561-a601-3411e3b4d51f.png">

But we didn't make this as above because option 2 because, unfortunately, wouldn't have worked at all with the current scope of remaining milestones.

With the one option remaining, presented as a dropdown, it can be easy to miss [1].

![image](https://user-images.githubusercontent.com/1587166/127330678-e945ac98-0bb8-46f7-b2c8-ffa2788e6ed7.png)


So better design would be to expose the options as radio buttons.  

<img src="https://user-images.githubusercontent.com/1587166/127324320-82c7a672-0cae-42a4-8696-ba104f2095ae.gif" width="600">

[1] As we don't know what kind of space you want to leave, the option to leave all rooms might be a bit too destructive for personal spaces so missing it is pretty bad.

**Comment by t3chguy** [comment]
(the animations wouldn't really be feasible without investing a decent chunk of time ftr)

**Comment by niquewoodhouse** [comment]
We're now going ahead with the radio buttons on Android, so feels even more appropriate here.
