### ISSUE TITLE
Message padding missing for room creation events

### ISSUE THREAD

**Issue by jryans** [vector-im/element-web#18137]
https://github.com/matrix-org/matrix-react-sdk/pull/6420 fixed many cases of grouped events missing padding, but it seems there's still at least one more with room creation events:

<img width="566" alt="image" src="https://user-images.githubusercontent.com/279572/126458682-9ff5f11c-ef44-44e2-b093-3eb3088ef7f7.png">

The "created and configured" line should have left padding, just like message events.

**Comment by gsouquet** [comment]
Are you still experiencing this issue?
I can't seem to have the same behaviour as you despite trying Modern, Modern (compact) and IRC layout. 

Tested on both Chromium browsers and Firefox

**Comment by nadonomy** [comment]
@gsouquet I get this issue frequently:

<img width="222" alt="Screenshot 2021-07-22 at 12 08 19" src="https://user-images.githubusercontent.com/4626865/126630107-7717dc4f-b99c-487b-9420-d7a30b6beab8.png">

Happy to jump on a quick call to help debug as I assume that'd be more useful than rageshakes.

**Comment by jryans** [comment]
> Are you still experiencing this issue?

At the moment on develop, the creation specific case appears to be fixed for me.

**Comment by robintown** [comment]
I've figured out how to reproduce this - you need to have an EventListSummary that has no event tiles before it in the timeline (happens either because of room history visibility, or undecryptable messages being hidden, or when the timeline is back-paginating). I assume this is because of a sibling selector `~` being used
