### ISSUE TITLE
Images can overflow message bubbles

### ISSUE THREAD

**Issue by robintown** [vector-im/element-web#18162]
![Screenshot 2021-07-21 at 18-19-54 Element toaq-only](https://user-images.githubusercontent.com/48614497/126567488-f694aa70-348a-43c1-8086-2057acbf05c9.png)

If you look close enough, you'll notice that the bubble ends 2/3 of the way across the screen, but the image keeps going.

**Comment by BurnyBoi** [comment]
Can confirm this is happening to me since upgrading to Element Web 1.7.33. Images in the timeline are being cut off on the right now instead of shrinking them to fit. See this comic is cut off on the right:

![image](https://user-images.githubusercontent.com/41203525/126569088-218216b3-a715-45d9-8934-9758062d2065.png)
