### ISSUE TITLE
Replies look broken on the bubble layout

### ISSUE THREAD

**Issue by SimonBrandner** [vector-im/element-web#18184]
![Screenshot_20210722_165121](https://user-images.githubusercontent.com/25768714/126659898-248e7191-103f-4fea-aa5d-bd08b97ebb19.png)

The `In reply to` is too close to the previous reply and there is no padding from the left like the URL preview has

**Comment by robintown** [comment]
I think it may have been intentional design that there's no left padding

**Comment by SimonBrandner** [comment]
While that is probably true, it looks weird nonetheless. That's why I would re-add the padding for the sake of consistency and we can iterate from there onward. 

Also, if there shouldn't be any padding, there shouldn't be any padding for URL previews

**Comment by amshakal** [comment]
While it was intentional, I don't it's working out as well. Based on the new reply design on web, I updated the design for replies for message bubbles as well. I think adding the avatar inside the bubble was turning out to be 'a bit too much'. 

Here is the simplified design for replies.
<img width="680" alt="Screenshot 2021-08-03 at 14 17 52" src="https://user-images.githubusercontent.com/85162587/128022401-fe5bf136-0ab5-4f35-b001-96b58e7ee54a.png">

**Comment by SimonBrandner** [comment]
This seems to match what I did in https://github.com/matrix-org/matrix-react-sdk/pull/6451

**Comment by amshakal** [comment]
Yeah exactly :)
