### ISSUE TITLE
Text in code blocks hardly visible in custom dark themes

### ISSUE THREAD

**Issue by PeterCxy** [vector-im/element-web#18317]
#### Description

Text in code blocks while using custom dark themes is hardly visible. It seems that the highlight.js theme is applied incorrectly (in the default dark theme, `atom-one-dark` is used for highlight.js, but it seems that it is not applied while using custom themes).

#### Steps to reproduce

- Apply a custom dark theme
- Notice that text in all code blocks look weird

#### Version information

- **Platform**: browser

For the web app:

- **Browser**: Firefox 90
- **OS**: Arch Linux
- **Element Version**: v1.7.33

#### Notes

Comparison between official dark theme and custom ones:

![2021-08-01_10-12_1](https://user-images.githubusercontent.com/4532423/127756937-fca428ac-84be-442f-bb91-fdd36c7f42cb.png)
![2021-08-01_10-12_2](https://user-images.githubusercontent.com/4532423/127756938-6afbc02e-5f61-4afd-969f-ebc29a32b9df.png)
![2021-08-01_10-12](https://user-images.githubusercontent.com/4532423/127756939-1003c30e-ceda-4fe9-894b-87524ddbc526.png)

From top to bottom: default dark theme, [Discord Dark Theme](https://github.com/aaronraimist/element-themes/blob/master/Discord/Discord-Dark/Discord-Dark-Theme.json), [Nord Dark](https://github.com/aaronraimist/element-themes/blob/master/Nord/Nord%20Dark/Nord%20Dark.json).

After checking the generated `theme-dark-custom.css` (`bundles/1bb29ac412a6c33a90c2/theme-dark-custom.css` in my case), it seems that the `hljs` styles are simply not present there, but in `theme-dark.css` they are. Manually enabling `theme-dark.css` (by removing the `disabled` flag for the `<link>` element) while a custom theme is used seems to fix the code blocks, but this is probably the wrong way to do it.

**Comment by Oha-you** [comment]
I think the initial issue (as shown on the screenshots) has been fixed in v1.9.4 by matrix-org/matrix-react-sdk/pull/6384
However, another bug stays: `hljs` styles do not persist in code blocks when custom themes are used.

My observations:
- When you send a code block when using a custom theme (like Discord Dark), `hljs` styles are applied normally
- When you restart Element Desktop and you have a custom theme enabled by default (using `"default_theme": "custom-Discord Dark"` in config.json), code is not highlighted:
![2021-12-02_183635](https://user-images.githubusercontent.com/82098328/144453618-b27e3538-7e8a-4247-9ee3-0fd960967aee.png)
- If you switch to the default Dark theme and then back **once**, the code becomes highlighted:
![2021-12-02_183743](https://user-images.githubusercontent.com/82098328/144453859-a774d2e9-c1e3-4e69-9d8f-69a2c08aad86.png)
- But if you repeat this step one more time, the text is grey again (no styles are applied, on restart too)

It looks like a `hljs` refresh event is not firing correctly for custom themes.

**Comment by SimonBrandner** [comment]
@Oha-you, could you please file a separate issue for this?

I am going to close this issue as it seems to be fixed!
