### ISSUE TITLE
Update Toast changed colour on dark theme

### ISSUE THREAD

**Issue by turt2live** [vector-im/element-web#18396]
![](https://i.imgur.com/8dBYIPn.png)

**Comment by SimonBrandner** [comment]
This was an intentional decision by @gaelledel and me in https://github.com/matrix-org/matrix-react-sdk/pull/6470. This matches the current design https://www.figma.com/file/X4XTH9iS2KGJ2wFKDqkyed/Compound?node-id=2241%3A50. 

@turt2live, is this issue just checking if this is intentional or would you like it to be reverted?

**Comment by novocaine** [comment]
Fixed by https://github.com/matrix-org/matrix-react-sdk/pull/6606

**Comment by SimonBrandner** [comment]
> Fixed by [matrix-org/matrix-react-sdk#6606](https://github.com/matrix-org/matrix-react-sdk/pull/6606)

Ah, thanks, totally forgot to do that :D
