### ISSUE TITLE
we've lost the ability to know who placed a call, and who hung it up.

### ISSUE THREAD

**Issue by ara4n** [vector-im/element-web#18405]
and <del>how long it was</del> (fixed by matrix-org/matrix-react-sdk#6570)

**Comment by ara4n** [comment]
We've still not got the ability to know who called who (did I call them, or did they call me? - pretty important) and who hung up (less important, but still useful to know if the call suddenly stops and you don't understand whether they accidentally/deliberately hung up on you, or if you somehow fatfingered and hung up on them).

**Comment by gaelledel** [comment]
@ara4n We are showing the user who calls who. This is shown on all call tiles with the name of the caller as well as their avatar. 
<img width="766" alt="Screenshot 2021-08-13 at 10 32 16" src="https://user-images.githubusercontent.com/76945183/129336952-fd5be2d1-585f-4911-9e5e-f49e833fbbc5.png">
(here if I see this tile in our DM then I know it is you who is placing the call)

For the who ended the call issue, the scenario you're describing is very specific and I'm not sure this can be taken into account especially because we have to be strict with the word count for internationalization. This will be even more the case on mobile where space is scarce. I would suggest trying to keep it short, simple and straight to the point everywhere.

**Comment by ara4n** [comment]
@gaelledel we don't show who's called who in the history once the call is over, unless i am missing it?  It's genuinely useful to know whether the calls shown in your scrollback were outbound or inbound (e.g. "when I last spoke to Foo, did they call me, or did I call them?"). 

I agree it's less useful to know who hung up the call, which is why I suggested putting it in a tooltip rather than cluttering the tile.

To show whether a call was inbound or outbound all you need is an arrow or something next to the name: "Matthew →" would be outbound and "Matthew ←" is inbound (or similar).

**Comment by SimonBrandner** [comment]
> @gaelledel we don't show who's called who in the history once the call is over, unless i am missing it? It's genuinely useful to know whether the calls shown in your scrollback were outbound or inbound (e.g. "when I last spoke to Foo, did they call me, or did I call them?").

The avatar and the name are of the person who started the call:

![Screenshot_20210813_161516](https://user-images.githubusercontent.com/25768714/129370693-3cc41c57-2ccc-47f9-886c-689febb15a03.png)

**Comment by SimonBrandner** [comment]
Thank you for opening an issue. Unfortunately, I wasn’t able to reproduce it. If you keep experiencing this defect, please update your description with steps/screenshots/video/more details and add a comment with `@SimonBrandner` to let me know that it’s ready to be reopened.
