### ISSUE TITLE
Image preview not working with SVG

### ISSUE THREAD

**Issue by gsouquet** [vector-im/element-web#18526]
### Steps to reproduce

1. Go to a room
2. Upload an SVG
3. Click on that SVG

### What happened?

The lightbox opens up but the image is not shown anywhere	

### What did you expect?

For the image to be displayed, centered in the lightbox

### Operating system

macOs

### Browser information

Chrome / Firefox

### URL for webapp

develop.element.io

**Comment by HarHarLinks** [comment]
For me the preview (thumbnails) are working, but not the lightbox (full resolution).
An explanation is offered in https://github.com/vector-im/element-web/issues/15094#issuecomment-687007095.
This is contrary to #10833 (might be outdated).

**Comment by alexanderstephan** [comment]
Hey everyone, I would like to work on this issue (in the context of a lab course at my university) sometime in the near future in order to improve the whole situation regarding svgs.

I just wanted to give a quick summary of what problems I could find as of today:

1. From what I can tell the preview thumbnail for svgs does not work at the moment and is unrelated to encryption. I tested stable and development in Firefox and Chromium each.
2. I also noticed that sometimes the thumbnail is empty (`mx_no-image-placeholder`) and other times instead a download badge for the file is displayed. Right now, I am not sure when each of these is triggered. I also used the same files.
![image](https://user-images.githubusercontent.com/30267166/137586198-17dcaa77-05da-4777-8a18-c72a61f318e7.png)

3. The lightbox viewer for svgs still works for unencrypted rooms, but not for encrypted. Sometimes it has a strange scaling behavior where the svg gets cut off like this 
![image](https://user-images.githubusercontent.com/30267166/137586147-e2857c6c-9bd1-40f2-af04-d38ab0e2cd8f.png)



If some of these just mentioned points don't match your current experience, please let me know.

**Comment by alexanderstephan** [comment]
@G2G2G2G Interesting, I asked a lot of people to try it as well, but it did work for none of them yet. But that fits in with my believe that behavior is not consistent right now.

I am also wondering why the Lightbox worked for unencrypted Rooms when the vulnerability should be identical. Converting to png would a possible solution, but it might not be ideal, especially for larger images combined with larger screens.

Also, thumbnails should not oppose a thread as far I can tell, since the svg is contained within an `img` tag. So no sanitizations should be needed in this case. 

However, we could just use something like [DOMPurify](https://github.com/cure53/DOMPurify) to solve the problem in general. I think this was mentioned in a similiar issue before.

**Comment by alexanderstephan** [comment]
@G2G2G2G Nice idea with scour! But I agree, I think we should not alter the data and also DOMPurify is a project purely dedicated to enhance security. From what I've seen scour is rather for optimizing performance. So I would prefer DOMPurify for those reasons.

I finally had some time again to do some more testing. I actually could reproduce the behavior regarding forwarding. However, I think it should not cause issues.
This [comment](https://github.com/matrix-org/matrix-react-sdk/blob/bc32f05fcbfb2f6c2219d3ad840ef20ca1749177/src/components/views/messages/MFileBody.tsx#L47 ) kinda explains the situation. The problem only occurs when the Blob URLs are generated in e2e encrypted rooms. And when sending the SVG to a not e2e encrypted room, the SVG is forwarded as is, so still not encrypted, hence no Blob URL is generated. So we should be good here imo.

I just wondered at first whether files would be encrypted in general after being forwarded to e2e rooms, but that does not seem to be the case. It makes sense to me since security is compromised when sending the data for the first time without encryption. I am preparing a PR that proposes a fix for the lightbox issue, it should be ready soon! :)

**Comment by HarHarLinks** [comment]
I have just tried this again, and it now displays both thumbnail and full resolution (presumably the actual svg) in the lightbox for me.

An issue seems to be that in contrast to pixel based images, element/electron/chromium doesn't seem to have a proper sense of scale for vector images: the image is displayed bigger than my viewport is, and can't be zoomed.

**Comment by alexanderstephan** [comment]
Very interesting, but also works for me now (non e2e of course).

If you look at the source code of the svg, does at have a specified height and width? If not, what happens if you add it? From my experience this happens when the size can't be inferred from the file. In this case the svg could be limited to a percentage of the windows width e.g., I think.

**Comment by G2G2G2G** [comment]
svgs aren't like regular images (unfortunately) in browsers, their scale can be all out of whack depending on viewbox and their internal sizes.. 
setting a static height: and width: would fix it, using javascript to get the screen size or whatever
this is why all the icon bloat packages like font awesome embed them into fonts instead of using layered single svg files with the `<g>` tag (like `<g id="item1">imgdata</g>` & `<img src="coolfile.svg#item1`) which is superior in every way except sizing/positioning/working with them.

**Comment by HarHarLinks** [comment]
> If you look at the source code of the svg, does at have a specified height and width?

The `<svg>` tag has `x="0px" y="0px" viewBox="0 0 550 400"` and a lot of the sub-elements have width and height. I added `width="550px" height="400px"`, now the thumbnail is bigger and the lightbox uses the added dimensions. @G2G2G2G seems to be correct.

**Comment by G2G2G2G** [comment]
Here's a good explanation https://www.geeksforgeeks.org/svg-viewbox-attribute/ the sizes inside of the svg are only relevant to the svg itself.. (but with nothing set the svg sometimes takes the entire space available because some viewboxes are massive) 

```
<svg viewBox="0 0 100 100" xmlns="http://www.w3.org/2000/svg">
  <!--
  with relative unit such as percentage, the visual size
  of the square looks unchanged regardless of the viewBox
  -->
  <rect x="0" y="0" width="100%" height="100%" fill="blue"/>

  <!--
  with a large viewBox the circle looks small
  as it is using user units for the r attribute:
  4 resolved against 100 as set in the viewBox
  -->
  <circle cx="50%" cy="50%" r="4" fill="white"/>
</svg>
```
(a simple svg from mozilla's site, added fill="blue" so it's easier to see on darkmode... save as whatever.svg)


The HTML inside of element currently looks like this:
```
<div class="mx_ImageView_image_wrapper">
<img src="url" alt="test.svg" class="mx_ImageView_image mx_ImageView_image_animating" draggable="true" style="cursor: default; transform: translateX(0px) translateY(0px) scale(1) rotate(0deg);">
</div>
```
```
<div class="mx_ImageView_image_wrapper">
<img src="url" alt="test.svg" class="mx_ImageView_image mx_ImageView_image_animating" draggable="true" style="cursor: default; transform: translateX(0px) translateY(0px) scale(1) rotate(0deg);" height="400px"> 
</div>
```
This will fix it, simply adding the height.. or the width.. or both, adding only 1 of them keeps the aspect ratio correct, I'd say height is probably the best, but if it's super wide then it might go off screen, say if it was 100px height and 100000px width lol

I guess getting the dimensions of the svg with javascript and then your element screen size with javascript and calculating a good view size would be the best thing so you don't mess up the aspect ratio etc
https://stackoverflow.com/questions/18147915/get-width-height-of-svg-element

**Comment by HarHarLinks** [comment]
I just came across an event like this in a public room
```json
"content": {
    "body": "unifiedpush_broad_overview.svg",
    "info": {
      "h": 1587,
      "mimetype": "image/svg+xml",
      "size": 28044,
      "w": 1123,
      "xyz.amorgan.blurhash": "TKI5MT%}56-RtRSh00ng-o?]--xV"
    },
    "msgtype": "m.image",
    "url": "mxc://librepush.net/QagMrijoMYyceCArSDpyUPfo"
  }
```
that is: svg, no thumb, yes blurhash. it displays in the timeline just the blurhash. svg works in the lightbox. timeline either fails to render the svg, or does not even try, but it really should.

---

at the same time this image uses black text on a transparent background. this is really illegible, especially with dark mode element. there should be a toggle to add (custom?) background color behind svgs at least in the lightbox.

**Comment by alexanderstephan** [comment]
Using @G2G2G2G s approach to specify the height works just fine, but the real problem is calculating the blur hash for the preview. I can't seem to get a proper blur hash as calculated in `./workers/blurhash.worker.ts`. I even set the `imageData` width and height manually or the image property itself does not work. In the end there is a hash, but it's just black e.g. something like `U009jvfQfQfQfQfQfQfQfQfQfQfQfQfQfQfQ`. You can see the blur hash value when viewing the message source. https://blurha.sh/ can preview it for example.

To solve this, my idea was to manually set the `width` and `height` attribute just for thumbnail svgs, so the blur hash gets calculated properly (note that the hash is calculated in the thumbnail method). Afterwards, the thumbnail info can get deleted again, as we already got the proper blur hash and can then we use the original SVG again for the preview (before checking that the size is let's say < 2MB). This is quite ugly, but the best I can come up with. What do you think of this solution?

Alternatively, one could probably modify the blur hash algorithm itself, but I would like to avoid it. Another alternative would be to not display this kind of SVG again like it was before, just sending it as a file that can be downloaded.

**Comment by G2G2G2G** [comment]
such a headache, I get some of it when working with svgs on web stuff... I see why so many places embed into font glyphs instead of the svg groups/layers for web images/icons 
yea I think your solution is good, even if you just defaulted to it being a file download link I wouldn't blame you lmao

That blurhash doesn't care about aspect ratio at least on their site, it smashes it to a static size and hashes it.. imo good enough for the outcome cuz it looks bad regardless, so idk if it's even worth bothering calculating the thumbnail sizes instead of just 1 static size or whatever.

**Comment by t3chguy** [comment]
Another thing to consider is that blurhash doesn't support transparency which a lot of SVGs rely on - https://github.com/vector-im/element-web/issues/18054

**Comment by turt2live** [comment]
Closing in favour of https://github.com/vector-im/element-web/issues/15094 which has security background to it.
