### ISSUE TITLE
Fix room upgrade UX before suggesting room upgrades in Spaces

### ISSUE THREAD

**Issue by turt2live** [vector-im/element-web#18676]
The UX is terrible and users are completely unaware of the consequences of upgrading, such as bridges and bots not working, settings not being transferred over, and membership being finicky. A single button press should not upgrade the room without context to the user.

**Comment by ramsey** [comment]
I was perusing the options in the latest version of Element and thought this "Upgrade Required" was a link to more information about upgrading. When I clicked it, nothing happened. So, I thought I failed to click it properly, so I clicked it again a couple of times. After returning to my room, I was presented with the standard "This room has been upgraded. The conversation continues here." link, which takes me to my new v8 room. Oops!

<img width="574" alt="Screen Shot 2021-08-20 at 12 11 24" src="https://user-images.githubusercontent.com/42941/130270282-a8d90598-b05b-4d40-81e1-2bb7f863c5d4.png">

**Comment by novocaine** [comment]
👋 it would have been easier to triage this if it had been filed using the bug template as that would have included a breakdown of actions taken and expected behaviour.

The current behaviour.. when you click on the Space members radio button, this warning appears

<img width="703" alt="Screenshot 2021-08-20 at 13 54 54" src="https://user-images.githubusercontent.com/57377/130274154-427ec28c-e81d-4d22-adad-4315e5f47cdf.png">

We can alter this copy to reflect better the ramifications of upgrading the room version (bridges, bots).

I'm wondering from the original description if this didn't show up somehow, as it hasn't been mentioned, and it mentions "A single button press should not upgrade the room without context to the user."

**Comment by novocaine** [comment]
> I was perusing the options in the latest version of Element and thought this "Upgrade Required" was a link to more information about upgrading. When I clicked it, nothing happened. So, I thought I failed to click it properly, so I clicked it again a couple of times. After returning to my room, I was presented with the standard "This room has been upgraded. The conversation continues here." link, which takes me to my new v8 room. Oops!
> 
> <img alt="Screen Shot 2021-08-20 at 12 11 24" width="574" src="https://user-images.githubusercontent.com/42941/130270282-a8d90598-b05b-4d40-81e1-2bb7f863c5d4.png">

@ramsey I can't reproduce this on https://app.element.io - when I click on either the radio itself or the Upgrade Required label, it shows the above dialog. And it definitely shouldn't upgrade without you clicking upgrade. Did you see this dialog? Are you on stable or develop?

**Comment by novocaine** [comment]
Possibly related to weirdness noted in https://github.com/vector-im/element-web/issues/18677

**Comment by turt2live** [comment]
> We can alter this copy to reflect better the ramifications of upgrading the room version (bridges, bots).

ftr, the suggestion of this issue is to literally not have the upgrade button at all. It's not really stable behaviour.

We've since committed to having it though so there's not really a point in trying to die on this hill, spec-wise. 

@ramsey I think your issue is entirely unrelated and may be deserving of a dedicated issue, if you're still seeing it.
