### ISSUE TITLE
Order of space creation steps inconsistent

### ISSUE THREAD

**Issue by nadonomy** [vector-im/element-web#18768]
### Your use case

When creating a public space, we ask users to set up their first rooms, and then share.

When creating a private space, we ask users to share/invite, and then set up their first rooms.

We should have clarity on why. 

Did we want to front-load sharing? Should we invert for consistency? Is it advantageous in cognitive load to set up rooms first so you know what you're inviting someone to/we can use richer metadata on invite?

**Comment by niquewoodhouse** [comment]
@daniellekirkwood Id suggest updating the copy on the create rooms step to be:

`What projects are your team working on?` instead of `What projects are you working on?` it refers to the team but doesn't require a lot of additional copy.  I do personally think the original copy is ok though (if we can't easily alter the copy if the user selected teams on the previous step).

**Original**
![image](https://user-images.githubusercontent.com/1587166/137124601-e6ff3db0-1ae3-4993-bcf0-52f7711ef57b.png)

**Altered**
![image](https://user-images.githubusercontent.com/1587166/137125920-09410691-e6c6-4d57-bacf-d2d163c8c6db.png)

**Comment by t3chguy** [comment]
> Can we have the copy in the headline different dependant on the previous click (without too much impact/time to build?) If so, let's go ahead and implement this approach! Thanks

Yes, but `Just me` and `Me and my teammates` don't share any later steps in the Wizard

Just me -> Add existing rooms -> done
Me and my teammates -> Create new rooms -> Invite teammates -> done

so not following where the variety is
