### ISSUE TITLE
We should consider converting emoticons to emoji when sending rather than when typing

### ISSUE THREAD

**Issue by SimonBrandner** [vector-im/element-web#18833]
If you type an emoticon at the end of a message like `Hey! :D` and press enter the emoticon doesn't get converted to emoji. To make it converted you have to type `Hey! :D `. We could always convert the last emoticon to emoji when sending a message (like Slack) but I don't like that very much because it feels inconsistent (you sometimes see the emoticons get converted and sometimes it may come as a surprise). That is why I would suggest converting emoticons to emoji when sending the message (like Discord, Viber and others probably) as that feels more consistent

**Comment by jackmawer** [comment]
As a side-effect to this issue, although perhaps better suited to an issue of its own right, is that typing a single character after a colon causes the client to freeze briefly, as it loads every emoji that starts with that specific character, even if the user just wanted to type e.g. `:P`.

A partial solution to this, and one that would pair well with this issue, would be to only start looking for matching emoji strings after two letters have been typed, since it’s then far more likely that the user intended to type a full emoji name.

For another example, `:S` is a valid emoticon in text form, but `:slight_smile:` is still easy to have autofilled after the second character.

**Comment by rda0** [comment]
#18879 felt like a bug to me, because typing `:D` + TAB shows user suggestions.

I vote for not converting emoji when sending, to avoid accidentally sending emoticons when it was not intended. I could write something in brackets with a colon at the end `(like this :)`, where I would not want it to convert to emoji.
