### ISSUE TITLE
Session loss on removing any other site data on Firefox

### ISSUE THREAD

**Issue by xvitaly** [vector-im/element-web#18862]
### Steps to reproduce

1. Login to Element Web on Firefox 91.x (confirmed on 91.0.2) and close this tab.
2. Open another tab and visit any other site that uses local storage (for example Twitch or Gmail).
3. Click the lock icon next to the address bar and press **Clear cookies and site data** (for Twitch/Gmail).
4. Confirm deletion.
5. Open Element Web tab. It will lost session including E2EE keys and ask you to login again.

### What happened?

Session loss on removing any other site data on Firefox 91+.

### What did you expect?

Sessions shouldn't be lost.

### Operating system

Fedora Linux

### Browser information

Mozilla Firefox 91.0.2

### URL for webapp

app.element.io

### Homeserver

matrix.org

### Have you submitted a rageshake?

No

**Comment by gsouquet** [comment]
For what I can read from your bug report this sounds more like an issue to do with Firefox rather than Element itself
Nonetheless that sounds pretty concerning. Would you be able to share a rageshake, that might uncover that extra information to understand what happened

**Comment by xvitaly** [comment]
> Would you be able to share a rageshake, that might uncover that extra information to understand what happened

After clearing cookies, Element Web shows login screen. I can't open Settings and export log.

**Comment by xvitaly** [comment]
Tested also self-hosted Element Web instance - the problem exists.

**Comment by gsouquet** [comment]
I'm not trying to say that the problem does not exist
But the clear site & cookie functionality is not linked in any way to Element and is a Firefox feature, we do not have any control over that.

I went ahead and tested whether the issue could have been with social login (using Google SSO feature) but even login in Element using my Google account, clearing the gmail site data, upon a refresh my session was still intact

With no further information it is going to be fairly difficult to figure out what this issue is. At this stage, I could only recommend opening an issue on Firefox's bug tracker, https://bugzilla.mozilla.org

**Comment by xvitaly** [comment]
> With no further information it is going to be fairly difficult to figure out what this issue is. At this stage, I could only recommend opening an issue on Firefox's bug tracker, https://bugzilla.mozilla.org

Done: https://bugzilla.mozilla.org/show_bug.cgi?id=1728619

**Comment by novocaine** [comment]
Thanks for warning us about this issue - it may help other Firefox users understand what's happening.

That said, I'm closing the issue here as it's hard to see what actions we can take.
