### ISSUE TITLE
Implement Token Authenticated Registration flow (m.login.registration_token) in Element

### ISSUE THREAD

**Issue by anoadragon453** [vector-im/element-web#18931]
## Description

This issue requests the implementation of [Token Authenticated Registration](https://spec.matrix.org/v1.4/client-server-api/#token-authenticated-registration) (TAR) in Element Web, such that a token can be provided to the homeserver as part of the sign up flow.

### What is Token Authenticated Registration?

As detailed in [MSC3231](https://github.com/matrix-org/matrix-doc/pull/3231), TAR allows homeserver admins to generate "registration tokens" to distribute to trusted friends and family in order to allow them to register an account.

A new [User-Interactive Authentication](https://spec.matrix.org/v1.4/client-server-api/#token-authenticated-registration) stage, `m.login.registration_token`, allows clients to present a token to the homeserver in order to successfully complete registration.

An existing implementation of this feature exists in the [nheko Matrix client](https://github.com/Nheko-Reborn/nheko): [mtxclient library PR](https://github.com/Nheko-Reborn/mtxclient/pull/60), [nheko UI PR](https://github.com/Nheko-Reborn/nheko/pull/680).

Equivalent PRs for Element Web would need to be made in [matrix-js-sdk](https://github.com/matrix-org/matrix-js-sdk/) at the base layer, whereas the UI bits would live in the [matrix-react-sdk](https://github.com/matrix-org/matrix-react-sdk/) and possibly [element-web](https://github.com/vector-im/element-web) codebases.

Note that with all feature changes, you should expect to converse and receive sign-off from Element Web's UI/UX designers on this task for the user-interface portion of the feature.

**Comment by anoadragon453** [comment]
Note that this feature can be particularly useful for homeservers that want to enable semi-public registration, without having to be given a temporary password, or requiring the homeserver operator to set up potentially complex Single Sign-On infrastructure.

**Comment by bowlbear** [comment]
this would be very useful to have included, and speed up registrations in situations like anoa describes! i hope the triage changes.

**Comment by ShadowJonathan** [comment]
I concur, @anoadragon453 this is likely to change to maybe O-Intermediate once conduit and synapse both implement this, conduit is already widely used for single or small-scope servers, so there'd definitely be demand from there.

Synapse 1.42.0 is the first synapse to include this, and [conduit also wants to implement this](https://gitlab.com/famedly/conduit/-/issues/72) (though that issue was made before the MSC was there)

**Comment by turt2live** [comment]
The triage is just for scoping, not for importance of an issue.

**Comment by GregSutcliffe** [comment]
For what it's worth, the Ansible community would find this very helpful as part of our Matrix rollout, and would be happy to take part in any appropriate discussions or trials.

**Comment by MexHigh** [comment]
Maybe a relevant update: As MSC3231 made it into to v1.2 matrix spec, synapse released a release candidate that already uses the stable endpoints (https://github.com/matrix-org/synapse/releases/tag/v1.53.0rc1).

**Comment by govynnus** [comment]
Yep, I'm in the process of updating https://github.com/matrix-org/matrix-react-sdk/pull/7275

**Comment by Half-Shot** [comment]
This is now in the spec, so we can probably drop the MSC name from the issue.

**Comment by andybalaam** [comment]
I added X-Needs-Product because this might conflict with our future direction of using OIDC.

**Comment by ShadowJonathan** [comment]
@andybalaam OIDC is a ways off, this is already in the spec, and the only reason why it's not as widely used is because element has not yet implemented it. I don't think adding any more delays is going to help bring it closer to the element client, like this.

I concur with @govynnus [here](https://github.com/matrix-org/matrix-react-sdk/pull/7275#issuecomment-1397506108), in that this suddenly "coming into question" after it might appear that OIDC would interfere with this, while this has been out for over a year, and OIDC is still heavily in the works, feels like a massive frustration to those who have been waiting for this.

**Comment by andybalaam** [comment]
Yep, it was a misunderstanding on my part, not realising that this is in the spec. I have spoken to someone from the product team just now and I hope we can make progress. I anticipate a need for the design team too, but let's take it one step at a time!

**Comment by andybalaam** [comment]
And it's worth saying again how grateful we are to @govynnus and everyone else who has worked on this feature. The delays are all down to a lack of capacity, and we're sorry.

**Comment by ShadowJonathan** [comment]
No worries, apologies for my strong words as well.
