### ISSUE TITLE
Switch from sending membership event for kick to using the /kick API

### ISSUE THREAD

**Issue by aaronraimist** [vector-im/element-web#19018]
I created a PR to to Synapse to align Synapse's implementation of membership events with the way that the spec says they should work https://github.com/matrix-org/synapse/pull/10807. The problem with that is it will reintroduce https://github.com/vector-im/element-web/issues/1961 because right now when you click the kick button in MemberInfo or use the /kick slash command Element sends a membership event for that user rather than using the dedicated API https://spec.matrix.org/unstable/client-server-api/#post_matrixclientr0roomsroomidkick

So Element needs to switch over to using the /kick API so that behavior does not come back once the Synapse PR is merged.

- [x] Change slash command to use dedicated /kick API
- [x] Change MemberInfo to use dedicated /kick API
- [x] Investigate if there are any other areas where kicking or banning happen via membership events. The ban and unban buttons in MemberInfo, /ban and /unban slash commands, and the unban button in the room settings seem to all use the proper APIs.

**Comment by t3chguy** [comment]
I think this issue belongs on https://github.com/matrix-org/matrix-js-sdk but can't transfer cross-org

**Comment by novocaine** [comment]
So I think the steps to test this from an Element Web perspective are

* Check /kick still works
* Check kick from memberinfo still works
* Check the above at different power-levels for the kicker and the kickee matches expected behaviour

We have reason to be cautious here because breaking kick would be Bad and we don't use this API elsewhere
