### ISSUE TITLE
Change Home / Show All Rooms into separate buttons

### ISSUE THREAD

**Issue by novocaine** [vector-im/element-web#19028]
The home button is currently bi-functional according to a context menu:

<img width="237" alt="Screenshot 2021-09-14 at 11 33 24" src="https://user-images.githubusercontent.com/57377/133242465-36d551d7-5c73-41b9-8aba-a71de7e756e1.png">

This functionality is useful but its quite hidden, and it doesn't feel like "Home" accurately describes the functionality.

What we want to change:

1. Change the Home button to be labelled "All" with a corresponding new icon. Change the behaviour to be what Home is currently with "Show all Rooms" enabled.

2. Add an "Other" button, putting it at the bottom of the space list. This button shows rooms according to the current Home with "Show All Rooms" disabled.

3. Remove the Home button.

If the user has no Spaces, they will see All & Other in Spaces list.

Needed: icons for both (a globe and a "..." perhaps?)

**Comment by novocaine** [comment]
Sketch from @ara4n 

![home-other](https://user-images.githubusercontent.com/57377/133243486-9c9fb4f4-928a-4309-9afe-1743b72d362f.png)

**Comment by t3chguy** [comment]
> Add an "Other" button, putting it at the bottom of the space list. This button shows rooms according to the current Home with "Show All Rooms" disabled.

This feels a bit weird given Invites, Favourites, DMs & orphans would be shown here

so Other feels like a very poor label for it
a lot of those would also be shown in some of the spaces, and certainly in the new All rooms button, so Other feels very misplaced

**Comment by niquewoodhouse** [comment]
I don't think we should do this as proposed in the issue.  

> Needed: icons for both (a globe and a "..." perhaps?)

I don't think a globe makes sense.  There are globes in Element today.  They mean a public room or public space.  Adding the same icon, or an icon that basically looks the same, to something that might contain private things feels at best confusing, at worst concerning.  

A `...` makes some sense for other, maybe, but I don't think Other is helpful for users if it includes favourites, DMs and orhpans and invites.    This issue proposes to remove one possibly confusing thing (Home having an option to view all rooms, defaulting to off) with a maybe more confusing thing (there's an Other that has basically the same things as Home/All in it, so it's not just Other, and invites will appear here too so you'll get notifications on two spaces when invited to rooms).  

Like this:

https://user-images.githubusercontent.com/1587166/133427406-1d487159-646e-488e-8d1d-ecd4c8822374.mp4

For new users who might have a handful of rooms (at most) this is especially confusing.

_________

> This functionality is useful but its quite hidden, and it doesn't feel like "Home" accurately describes the functionality.

**Based on that, I'm not sure I understand why we should remove Home if its going to just be everything.** 

It might not match the functionality well but I don't think that means changing it is better.  Maybe I'm not understanding the problem but I think it's fairly safe to assume `home` is a well known concept on the internet as a whole as a place to find an overview of everything new or latest for you.  Having almost anything else is likely to be more abstract and so, more unpredictable for many users.   If Home becomes 'show all' then it does show everything you follow/are a part of, so it feels like an ok/safe starting point to me.

Products that have a home tab/icon/link.
- Facebook (feed of latest in groups/friends/likes etc)
- Twitter (feed of content from people you follow)
- Slack workspaces have homes (list of all channels/conversations you're in)
- Youtube, Pinterest, Instagram (feed of content you're believed to be currently interested in)

Products that have a globe or something other icon that indicates the most prominent place to land/start from...
- Mail has an inbox
- Productivity apps tend to have a dashboard....
- Teams and Quill have an Activity icon 

Some other proposals for what I think this issue is looking for (more clarity in what each Spaces means) could be:

- Rooms space has rooms in it in divided into sections 

https://user-images.githubusercontent.com/1587166/133456317-0fc6d682-00d9-444b-94b8-6ef16ca24418.mp4 

(Above: when a user has a Space; below when user has no Spaces)

https://user-images.githubusercontent.com/1587166/133459526-5bfb632f-9c84-4b41-9573-ae26deb114ed.mp4

- Change the Home to have a show option on the room section

![image](https://user-images.githubusercontent.com/1587166/133611142-2061ef13-f3ec-41c8-ae86-428ae6c69a79.png)

- Change Home to have a clearer filter/tab systen at the top of the room list

<img src="https://user-images.githubusercontent.com/1587166/133614874-72833dfd-40be-44fe-97ca-45ed39c93fc5.png" width="300">

<img src="https://user-images.githubusercontent.com/1587166/133614931-4b2e30a0-c6bf-44a9-961b-6488118327b2.png" width="300">

**Comment by niquewoodhouse** [comment]
I'm going to remove needs design label as I've added my input, and tried to explain why I don't believe this is the right thing to do, and provide some alternatives.  There's a needs product label on it so product should obviously feel free to re-label/redefine as they see fit.

**Comment by novocaine** [comment]
Closing this as we intend to do fresh discovery on this area.
