### ISSUE TITLE
something went wrong

### ISSUE THREAD

**Issue by richvdh** [vector-im/element-web#19101]
### Steps to reproduce

* Receive invite to a private room
* Open room from room list
* Click "Accept" (?)

### What did you expect?

Successful join

### What happened?

"Something went wrong" screen. After a few seconds the room opened anyway.

### Application version

Element Nightly version: 2021092001

### Have you submitted a rageshake?

No

**Comment by kittykat** [comment]
@richvdh can we please have some more detail in your issue description? (Please edit your issue rather than posting a followup.)
- What sort of an invite was it? (e.g. to a private space, a public space, a private room, a public room, by email, by username, by some other method)
-  How did you accept the invite? (e.g. through a notification, went to the invite in the UI)

**Comment by robintown** [comment]
Probably fixed by https://github.com/matrix-org/matrix-react-sdk/pull/6830

**Comment by richvdh** [comment]
seems like I can't. Thanks!
