### ISSUE TITLE
Remember local per-room state chat right panel

### ISSUE THREAD

**Issue by jryans** [vector-im/element-web#19634]
In https://github.com/vector-im/element-web/issues/19633, we're adding a main timeline in right panel when a widget is maximised.

If a user closes the chat right panel, that only affects their view, and is remembered for that room. If you switch away from the room and come back to it later, the chat right panel open / close state should be restored as it last was for that room.

**Comment by toger5** [comment]
Also relates to: https://github.com/vector-im/element-web/issues/19660

**Comment by toger5** [comment]
To what extend should the right panel be saved per room? Only the open close state of the right panel? Or should we additionally store the phase? So if it was open in the Chat panel phase how should the following behave: changing room -> in the new room opening the RoomSummaryPhase -> going back to the initial room 
 - should the chat phase be opened again (the phase would than need to be stored per room as well)
 - should it be open like it was before but now also showing the RoomSummaryPhase  (This is the current standart behaviour)
 
I think storing to phase would be best, since we need to make sure that the timeline is not shown in the right panel of a room without a maximised widget (having two timelines makes almost no sense)

**Comment by jryans** [comment]
Those are all good questions, and I am not quite sure yet myself. Let's chat with the Threads team later today on this, and then sync with @gaelledel to check their thoughts on how it should work for maximised widgets.

**Comment by waclaw66** [comment]
This behaviour is annoying. How to make right pannel always visible?

**Comment by toger5** [comment]
Thanks for mentioning this. There are bunch of discussions about this topic currently and ideas are collected on how the situation could be improved. Going forward the right panel becomes more room specific (especially with threads, which are very specific to the content of a room and the right panel chat) that is why the move to a per room right panel was made.

Currently the only solution is to open the info panel in all rooms (this is probably not a satisfying answer but the situation is planned to be improved). Then this state will be saved and revisiting rooms will always prompt you with the open room info right panel.
