### ISSUE TITLE
Videos from Riot-bot not loading 

### ISSUE THREAD

**Issue by nicolae-stroncea** [vector-im/element-web#19650]
### Steps to reproduce

1. Where are you starting? What can you see?
Starting in the desktop app on Ubuntu.
2. What do you click?
I type the restart command and Riot Bot starts showing me videos , but none of them are loading.
Tangential: I have previously added Giphy into the room, unsure if that is related.

#### What did you expect?

Expected Videos to load. Instead they seem to just be looping.
![image](https://user-images.githubusercontent.com/39338488/140611448-2dd6ec3d-9a4d-4e36-9aeb-7926b94455b7.png)

### Operating system

Ubuntu 20.04, flatpak app.

### Browser information

Element Desktop App

### Application version

1.9.3.

### Homeserver

matrix.og

### Will you send logs?

Yes

**Comment by aaronraimist** [comment]
Looks like the media no longer exists on matrix.org https://matrix.org/_matrix/media/r0/download/matrix.org/rqAHkSLPWucDxWtQcSUXgPbG but is still cached on some other servers https://mozilla.modular.im/_matrix/media/r0/download/matrix.org/rqAHkSLPWucDxWtQcSUXgPbG

It is possible someone started the process of turning off RIot Bot but didn't actually turn it off? https://github.com/vector-im/element-web/issues/15383

Otherwise the media just got lost at some point. It looks like it is using the same mxc URIs from at least as far back as 2017.

**Comment by dbkr** [comment]
I'm quite surprised this is still running, so I'm not terribly surprised its videos have gone missing. If it's any consolation, the videos are all based on the Element UI from ages ago (when it was called Riot, in fact). The bot doesn't appear to have become self-aware yet, so that's a plus.

(By the way, what's the 'restart command'?)

**Comment by t3chguy** [comment]
Riot-bot is long gone
