### ISSUE TITLE
Forwarding a message which was a reply to another room has poor UX

### ISSUE THREAD

**Issue by DMRobertson** [vector-im/element-web#19769]
### Your use case

In room A, someone posts a message. I write a reply to it.
We both realise that this should conversation should have taken place in room B.
I forward my reply to room B and delete my reply from room A.

What I see in room B:
![Screenshot from 2021-11-16 14-41-36](https://user-images.githubusercontent.com/8614563/142006135-9794914a-6ff7-46ce-b919-2dfd8a4fb914.png)

The text of reply was reproduced correctly. The fact that it was a reply was also copied over. But we can't see what I replied to.

The error message
> Unable to load event that was replied to, it either does not exist or you do not have permission to view it.

Is slightly misleading. The event in question exists, just not in this room.

Thoughts:
- It would be great if the client could detect that this event was in another room and load it for me.
- But then again, some users in room B might not be in room A, so maybe it's better to show "not everyone can see this".
- Perhaps the client could warn that users won't be able to see what I was replying to when forwarding a reply?

**Comment by HarHarLinks** [comment]
more ideas and options:
- add a checkbox to forward UI to switch between forward only the reply or forward the original message + reply
- include the original msg as a quote instead of linked reply: doesn't leak others metadata, like forwarding someone else's msg currently works.
  - maybe not possible with current spec, but show the rich reply to users who can access the original but regular quote otherwise. downside: people see different things.

**Comment by t3chguy** [comment]
> It would be great if the client could detect that this event was in another room and load it for me.

The spec doesn't allow for this, only the event_id is included, no room_id
