### ISSUE TITLE
Deleting Root Messages shows Expand/Collapse in Thread List view

### ISSUE THREAD

**Issue by daniellekirkwood** [vector-im/element-web#19765]
### Your use case

When a Root message is deleted, the delete event shows in the Thread List view where instead the Thread should show and in place of the Root message it should read "Message deleted"

@janogarcia  I'm sure you have a design Figma for this, could you link it please?

---
![Screenshot 2021-11-15 at 14 51 41](https://user-images.githubusercontent.com/89144281/141968903-e1f55317-c1c7-4afd-847c-0e2606c1eae6.png)

---
![Screenshot 2021-11-15 at 14 52 26](https://user-images.githubusercontent.com/89144281/141968915-36255d85-0f4d-4a12-89fc-8bb0060bcb36.png)

---
Screenshot 2021-11-15 at 14.48.55

**Comment by janogarcia** [comment]
@daniellekirkwood Sure, I'm adding a link to Figma for reference. The actual issue here is that, when there's multiple contiguous deleted root messages in the Thread List, those are being automatically collapsed as in the room timeline, which shouldn't happen in the context of the Thread List.

↗ [Flow — Deleting the root message](https://www.figma.com/file/T309ztx0sNyOOK6NKVLHsK/Threads?node-id=1150%3A202558)
