### ISSUE TITLE
Servers should be able to serve web pages - not just previews.

### ISSUE THREAD

**Issue by Biep** [vector-im/element-web#19918]
Matrix should upon request provide the full page from the server (if both server and client have that option on).  Then Element Web/Desktop, being a web browser, could show it safely, also in countries where the page or site is blocked.  It would provide a way to read what your government doesn't want you to see.
It would give Matrix a sudden popularity in such countries too..  And given the federation, and the ease to start under-the-radar servers, it would be hard to fight by the government.

Given that the preview feature already exists, this ought not to be extremely hard to implement.

**Comment by Ersonusaini** [comment]
How to change footer powered by matrix remove from element desktop app

**Comment by ShadowJonathan** [comment]
Use a proper VPN or proxy tool if you want to bypass country blocks for certain webpages, I pretty much immediately recommend [warp](https://1.1.1.1/) if you'd like that.

Also, please tell me how exactly fetching full pages would help hiding undercover matrix servers? How would an undercover matrix server actually look like? If anything, it fetching URL previews *at all* could be a way to alert authorities that a particular IP address is accessing a blocked website, if the server is in a country that blocks these.

Furthermore, matrix is designed around open federation (at the moment), meaning a government could simply request a suspected website with a matrix query, and then figure out it is a matrix server.

I don't see how this proposal could meet any of your requirements, nor do i think it bears the cost of implementing, when reasonable alternatives exist. The URL Preview feature is for convenience, certainly not for privacy.

**Comment by Biep** [comment]
My main contacts who would use this are in China and Iran.  Especially in the former, "simply" doing something on the Internet is not trivial if it should be unknown by the government.

> Also, please tell me how exactly fetching full pages would help hiding undercover matrix servers?

It wouldn't.  Why would you think it would?

> If anything, it fetching URL previews at all could be a way to alert authorities that a particular IP address is accessing a blocked website, if the server is in a country that blocks these.

Of course - one should use a server that is outside of the country in question.  China has blocked matrix.org - but it cannot block all small servers.  They stay under the radar.

**Comment by Biep** [comment]
Maybe a bot running in a free country could do this?  Not sure whether a bot would be able to open a separate tab in the browser.  If not, then an API extension to allow that might be sufficient.

**Comment by ShadowJonathan** [comment]
A bot dumping a complete copy of a room to link to the message linking the URL would be a preferable alternative, imo.

> It wouldn't. Why would you think it would?

You were implying that, and basing this entire issue off of that. Again, i don't see how it would help.

> China has blocked matrix.org - but it cannot block all small servers.

In the current federation, china would only have to block matrix.org to cripple small servers working in those countries, because of the way matrix federation works. Additionally, matrix expects a full mesh, i.e., all servers being accessible by every other one, so this will make the servers misbehave or not properly receive or send messages. This is a known wider problem that's being fixed at the moment, but if you'd like for some more focus to be put on that, show more attention to those efforts, as that would signal to the matrix foundation that this is important.

**Comment by Biep** [comment]
> You were implying that, and basing this entire issue off of that.

Not at all - and I have reread my OP several times now, but I really cannot see how you would get that out of it.

**Comment by t3chguy** [comment]
Given this is a request for servers ability to do something it is certainly on the wrong issue tracker, I suggest the matrix-doc repo

**Comment by BEEDELLROKEJULIANLOCKHART** [comment]
This comment is response to "http://github.com/vector-im/element-web/issues/19918#issuecomment-981470440".

Transference to "http://github.com/matrix-org/matrix-doc" is superior to closure of "http://github.com/vector-im/element-web/issues/19918" for "http://github.com/vector-im/element-web/issues/19918" because transference shall retain discussion and demonstration of opinion.

**Comment by t3chguy** [comment]
It isn't possible to transfer between vector-im and matrix-org github orgs.
