### ISSUE TITLE
Replace the spinner with the Element logo in the loading screen

### ISSUE THREAD

**Issue by Linerly** [vector-im/element-web#19915]
#### What would you like to do?
Have something else in the loading screen — like an animated Element logo for the loading screen — instead of the spinner

#### Why would you like to do it?
Have a look at other chat apps:
![WhatsApp](https://user-images.githubusercontent.com/47475676/143664627-7c2fded6-fc61-4887-adba-7e0c923140a4.png)
![Discord](https://user-images.githubusercontent.com/47475676/143665051-fcf09d35-0a62-4668-b989-2c422c8eca91.png)

#### How would you like to achieve it?
Either use an SVG animation or a Lottie for the Element logo animation

**Comment by SimonBrandner** [comment]
We used to have this as a labs option though it got removed due to concerns about it associating the Element logo with loading and therefore with slowness. Doing this would have required quite a bit of research into the area. There weren't enough resources for that at that time, so it was decided to instead use a regular spinner. 

@niquewoodhouse, do you ever see us actually doing this or is it more of a `wont-fix`?

**Comment by ShadowJonathan** [comment]
I think the suggestion of an animated spinner is going a bit further than the concern, which I believe is that; "when element is loading, I don't see an icon, which is a bit weird"

Is this correct, @Linerly?

**Comment by t3chguy** [comment]
Yeah design pretty much noped this due to prior research showing that your brand being used for a loading spinner causes you to associate the brand with slowness.
