### ISSUE TITLE
"Copy link to thread" should be available in the message context menu. 

### ISSUE THREAD

**Issue by toger5** [vector-im/element-web#19936]
Currently the "Copy Link To Thread" button is only available in the threadView (not the thread list) header
<img width="300px" src="https://user-images.githubusercontent.com/16718859/143892030-6ad4275b-7b19-42ff-ae76-bf617689f200.png">
And the thread list context menu.
<img width="300px" src="https://user-images.githubusercontent.com/16718859/143892136-70599cd3-867c-4400-8102-32039cc7006b.png">
Is is not available in the timeline
<img width="300px" src="https://user-images.githubusercontent.com/16718859/143892222-fc6d8df5-118b-44b1-8974-164649403a7e.png">
event though this is a place where it might be interesting to get access to the link as well.

**Comment by janogarcia** [comment]
@toger5 The messages in the room timeline would actually benefit from having a contextual "Copy link to message" action (surfacing it as a top level action, instead of requiring the users to first reveal the "Share" dialog), but that link should point to that message in the room timeline.

Introducing an additional "Copy link to thread" action would make that menu even more complex, and we should avoid that when possible. We can rely on the contextual, less cluttered menus in the Threads panel for now. /cc @daniellekirkwood

**Comment by daniellekirkwood** [comment]
Thanks for the issue @toger5 !

Just as @janogarcia mentioned, we don't want to add too much clutter to the Timeline menus right now. Also, if you share a link to a threads root message, you will be able to see the thread summary and all the messages following that root message in the thread panel...

We need to spend some time @ Element thinking about "Copy link" and "Share" and making sure our use of them is consistent and expected everywhere. 

For now I will close this issue as its not something we're looking to solve - thanks so much for your input though :D
