### ISSUE TITLE
[Design] Change sidepanel navigation from phone-frame based to stack-based

### ISSUE THREAD

**Issue by ShadowJonathan** [vector-im/element-web#20181]
### Your use case

This has been bothering me for a while, but i couldn't ever put my finger on it;

The "press top left button to go back" button might be intuitive on phones and frames which fill the entire screen, but it is not very intuitive on a fixed right-sided panel in a larger frame.

Instead, I'm proposing to go from something like this;

![image](https://user-images.githubusercontent.com/22740616/145996588-a0836e1f-4b48-4c1b-97dc-da7b676b4c2b.png)

To something like this;

![image](https://user-images.githubusercontent.com/22740616/145996866-696006d6-388b-40e0-be69-39bf714b1b4c.png)

A stack-based approach, for which the context of the sidebar is always visible (the top layer is "Room A", then the next layer is "Members"), this could even address https://github.com/vector-im/element-web/issues/17376 by layering members this way:

![image](https://user-images.githubusercontent.com/22740616/145998602-ed74434d-9a74-460a-9133-69d6b8c091a4.png)

Changing the context "where" this sidepanel then is is as simple as changing the top-level name:

![image](https://user-images.githubusercontent.com/22740616/145998645-9f22df7b-8705-44ff-b352-74ca8c562c9c.png)

Then the user can dismiss this panel at any "level" by clicking the corresponding X on that level, clicking it on the "members" level would show the full room/space options panel again.

### Additional context

For context, Telegram has a panel like this as well, but this fills or overlays the entire screen, and converges that focus to this middle strip: 

![image](https://user-images.githubusercontent.com/22740616/145996000-b03abb27-ce1a-4b2d-942e-9a78cb0d1727.png)

![image](https://user-images.githubusercontent.com/22740616/145996053-2b350ff6-338c-414a-93e6-f74ee4d524d2.png)

The difference of this with Element, in my opinion, is that this is a *mandatory* navigation panel that now overlays the entire app, and so background navigation is blocked until this is completed. This borrows a lot of the "phone frame" semantics as well, by making the menu floating and in the centre of the screen.

**Comment by ShadowJonathan** [comment]
Note that also potentially with the stack design, one could "drill" into rooms from a space, or into subspaces, and they'd all get added to the stack.

**Comment by SimonBrandner** [comment]
@janogarcia, I think this might be interesting to you since afaik you're working on threads and the related right-panel changes

**Comment by ShadowJonathan** [comment]
Something like that could maybe drive from room -> threads -> thread X, in terms of stacking, though I’m not sure.

**Comment by janogarcia** [comment]
@ShadowJonathan Thanks for sharing your thoughts on this, but I'm afraid the navigation model you're proposing would have its flaws as well.

It's kind of a mix of stacked bottom sheets (as typically seen on mobile, or even on desktop as in the Telegram screenshot you shared) but without blocking the navigation layers beneath (which introduces all sort of issues like what happens if you close or select the "Members" layer when a Member profile is being shown), and sort of navigation breadcrumbs.

As I detailed in a [separate issue](https://github.com/vector-im/element-web/issues/19660#issuecomment-1000722635), a proper way to handle both hierarchical navigation (`Room → Members → Member`) and history navigation (back button) is by having dedicated UI elements for handling those separately:

- **Hierarchical**: Any sort of breadcrumb/navigation trail that allows the user to move up through the hierarchy.
- **History**: Back button that tracks user's navigation history.

You can find a similar pattern for example in most, if not all, file explorers:

**Hierarchical: File path**
![path](https://user-images.githubusercontent.com/60790/151617064-c6f4082c-b8b6-4dcc-bdf2-08f5774d477f.png)

**History: Back button**
![back](https://user-images.githubusercontent.com/60790/151617105-ec65cf45-3cd0-42f5-b2ec-facd01fa06a6.png)
