### ISSUE TITLE
Left panel menu options with same name link to different views

### ISSUE THREAD

**Issue by kittykat** [vector-im/element-web#20245]
### Steps to reproduce

1. Left panel
2. Drop down next to Space name -> Explore rooms
3. + next to Space name -> Explore rooms

#### What did you expect?
Menu items being consistent

#### What happened instead?
The two menu items go to different views, which was a bit confusing

![Screenshot from 2021-12-17 13-55-51](https://user-images.githubusercontent.com/51663/146555304-8a411ab5-ff00-46e6-9422-28480e517b94.png)

Potential solution could be to use different strings for them?

### Operating system

Arch Linux

### Browser information

Firefox 95.0

### URL for webapp

develop.element.io

### Application version

Element version: 9e1f39322479-react-670d7824ec43-js-36906e2ddb6d Olm version: 3.2.8

### Will you send logs?

No

**Comment by UwUnyaa** [comment]
I don't think this issue is relevant anymore, as the UI has been changed to have the same icons, but different labels:
![image](https://user-images.githubusercontent.com/16294095/150868899-f64d87c5-9534-4616-bb13-12879cd6ea87.png)
![image](https://user-images.githubusercontent.com/16294095/150869052-ed563f72-cb9d-4623-8abc-664fd0c3cc59.png)

**Comment by t3chguy** [comment]
Both do the same thing now

![image](https://user-images.githubusercontent.com/2403652/150880824-c37aedac-68d9-4b0c-941c-927e783bd964.png)
![image](https://user-images.githubusercontent.com/2403652/150880848-7dfa4f31-8ebb-48fb-b01c-0c07516b60f3.png)
