### ISSUE TITLE
Allow volume levels of individual VC members be configured.

### ISSUE THREAD

**Issue by ara4n** [vector-im/element-web#2027]
Allow volume levels of individual voice/video conference (VC) members be configured.

**Comment by ara4n** [comment]
FS supports this.  Need to define events to go through the bridge.

**Comment by TheLastProject** [comment]
This is especially important for macOS, which doesn't allow you to change volume per-application.

**Comment by MrMcShroom** [comment]
For someone like me voice volume is essential to me for a decent user experience. Please add this!

**Comment by SimonBrandner** [comment]
Jitsi has this isn't really required in 1:1 calls

**Comment by hiddeninthesand** [comment]
Sorry to necrobump, but can you clarify how Jitsi having this alleviates the issue of Element not having per-user volume sliders in a voice call?

**Comment by t3chguy** [comment]
Element uses jitsi for all calls with >2 participants. In a two participant call you don't need individual volume controls.

**Comment by hiddeninthesand** [comment]
I'd like to slightly disagree with that notion, as many people in calls do require more than 100% volume to be properly audible, and even if that wasn't necessary, having to readjust the volume of the entire program depending on if you're in a call with 1 other person or 2 seems like a bad user experience. I originally necro'd the thread specifically because of how important this feature was (to me, at least) in 1:1 calls, since it made calls with people that I had on 150%-200% volume on Discord nearly non-audible over element. Would it be possible to reopen the issue over that? This single deficiency in UX is possibly the biggest factor stopping my friend group from being able to switch over to Element for VC.

**Comment by hiddeninthesand** [comment]
Will do, thanks for the advice.
