### ISSUE TITLE
MsgBubbles: Call Layout

### ISSUE THREAD

**Issue by daniellekirkwood** [vector-im/element-web#20324]
### Your use case

Today the call notification does not appear in a bubble. 
- [x] Amsha to confirm that is the desired behaviour

All call notifications appear on the left. Which is especially weird in a DM when I placed the call... 
- [x] consider moving calls to the centre
- [x] consider moving calls to the side that corresponds with the sender?

**Comment by amshakal** [comment]
I suggest:

1. Moving calls to the center since it's an event that needs attention. 
2. If the sender have started a call, it should be green, else grey.
3. Change the grey colour to match the grey colour of bubbles.
4. We could keep the rest of the behavior the same as it is for modern layout since it's already inside a 'bubble'.
