### ISSUE TITLE
Handle room aliases better in "Explore rooms" UI

### ISSUE THREAD

**Issue by tgr** [vector-im/element-web#20350]
### Steps to reproduce issue
Open the "Explore rooms" dialog and enter a full room name with a server that's different from the one selected in the server dropdown. (E.g. select `Matrix rooms (matrix.org)` in the dropdown, then enter `#gnome-women:gnome.org` in the search bar.) You will get no results and a button for creating the room. There's a "Join" button in the search bar but it's hard to notice and it's an uncommon workflow so I expect many people will miss it as I did.

#### What would you like to do?
Ideally, the room alias should just be looked up using the server that's indicated in it, ignoring the server select dropdown, and the room details and join button should be presented in the normal search result format. If that can't be done (e.g. the room listing is not public on the given server), a "fake" search result with some explanation and a join button would still be preferable, I think.

Alternatively, the join button inside the search bar could be made more prominent.

#### Why would you like to do it?
In my experience, most users don't really have a clear understanding of Matrix's federation model. I do, but even so I found the current behavior confusing at first. Good UIs should DWIM. (The join button inside the search bar does that, but it's hard to notice, and also less informative than normal search results which contain the room description etc.)

**Comment by aaronraimist** [comment]
Yeah I can see how the UI saying "No results for #gnome-women:gnome.org" is confusing. It's a bit of a complicated UI because that screen is acting both as a way to search a specific server's room directory as well as a way to join arbitrary rooms via an alias.

> Also, adding and then removing a server just to be able to join a room is tedious. I suppose I could just visit it via the URL but the room explorer handling it would be nicer.

Just so you know there is no need to do this. When you enter a room alias into the search box, a join button appears on the right side of the search box. You can either press enter or click on the join button to join the room. You do not need to add that server to the dropdown to be able to join the room. The UI just needs some design help to make this clearer.

<img width="746" src="https://user-images.githubusercontent.com/5855073/147387747-02cabdc8-457a-436e-9a43-4a938091cf5f.png">

**Comment by aaronraimist** [comment]
You may want to rename this issue to something like "Handle room aliases better in "Explore rooms" UI".

In Matrix the server name is the domain the server is at (gnome.org, kde.org, matrix.org, etc) so that is something a bit different.

**Comment by tgr** [comment]
> Just so you know there is no need to do this. When you enter a room alias into the search box, a join button appears on the right side of the search box. You can either press enter or click on the join button to join the room.

Ah, thanks. That makes sense in hindsight. It's hard to notice though, and it's not a UI convention used elsewhere, I think. Something that's formatted as a search result would feel more intuitive to me.

**Comment by tgr** [comment]
(Updated the description to account for the Join button in the search bar.)

A related issue is entering a space name/alias in the search field, which could also use more intuitive behavior. (#18851 is related.)

**Comment by t3chguy** [comment]
Related https://github.com/vector-im/element-web/issues/15723

**Comment by t3chguy** [comment]
This got fixed

<img width="677" alt="image" src="https://user-images.githubusercontent.com/2403652/234318046-93bc7468-4135-48f1-bd50-85064035c1e7.png">
