### ISSUE TITLE
History Is Not Visible To New Members Despite Setting

### ISSUE THREAD

**Issue by apbendi** [vector-im/element-web#20393]
### Steps to reproduce

1. Create a new room that anyone in the space can join
2. Go to room settings->Security & Privacy and select "Members only (since the point in time of selecting this option)"
3. Send a new message in the chat
4. Have member from the space join the room

#### What did you expect?

The new members would be able to see the message sent in step 3

#### What happened instead?

New members could not see any history

### Operating system

macOS 12.0.1

### Application version

Element Version 1.9.8

### Will you send logs?

Yes

**Comment by robintown** [comment]
Is the room encrypted?

**Comment by ErikPrantare** [comment]
I have this same issue, the rooms are encrypted

**Comment by robintown** [comment]
Then this is happening because currently, the only situation in which new members can view history in encrypted rooms is if you share decryption keys with them by explicitly sending an invite. Requesting access to encrypted history in all other cases is tracked here: https://github.com/vector-im/element-web/issues/2286. I'm going to close this so we can focus on that issue.
