### ISSUE TITLE
Message sent status icons don't appear for polls

### ISSUE THREAD

**Issue by turt2live** [vector-im/element-web#20566]
these little guys: 
![image](https://user-images.githubusercontent.com/1190097/149588952-a1ddf107-f24c-4b22-af55-b7bec1852d39.png)

They should appear on all reasonably message-like events to indicate that they're pending (circle) or sent (checkmark). Will also need to make sure the failed status works too.

**Comment by kerryarchibald** [comment]
<img width="680" alt="Screenshot 2023-02-21 at 14 16 27" src="https://user-images.githubusercontent.com/3055605/220223534-4339b0bf-bcd3-42bd-9103-ae8fa1cc5603.png">

Polls display sent markers
Because the poll editor modal does not close until the modal is successfully created, a pending or failure marker is never shown.
