### ISSUE TITLE
Thread panel doesn't handle window resizing

### ISSUE THREAD

**Issue by turt2live** [vector-im/element-web#20594]
If the viewport changes, the right panel doesn't adjust. It seems to adjust fine when the right panel itself is resized, but not the viewport

**Comment by gsouquet** [comment]
@turt2live reading through your issue above I'm not sure to understand the expected behaviour
Would you be able to give me a bit more info please?

**Comment by turt2live** [comment]
Playing with the bottom right corner of the application window can cause this:
![image](https://user-images.githubusercontent.com/1190097/149994634-04b3f670-a00a-43d3-ac00-5ecca9a1c72c.png)

It seems to fix itself if the panel gets an update of some kind, but moving the animation itself is *very* jittery.

**Comment by novocaine** [comment]
I can still repro this

<img width="514" alt="Screenshot 2022-03-09 at 13 35 42" src="https://user-images.githubusercontent.com/57377/157452306-8692c3b4-975a-45ec-b0b0-f5e54e0330c2.png">

*drags bottom border up*

![Uploading Screenshot 2022-03-09 at 13.35.55.png…]()

**Comment by t3chguy** [comment]
This issue is surprisingly intertwined with https://github.com/vector-im/element-web/issues/20896 - the bug is caused by a (broken) workaround of https://github.com/vector-im/element-web/issues/20896 to hide the scrollbar if the events height is smaller then the container height, except the container can be in a scrolled state.
