### ISSUE TITLE
Identity Server not allowing past identity already set

### ISSUE THREAD

**Issue by feliciakelley** [vector-im/element-web#20680]

**Comment by aaronraimist** [comment]
Can you explain some more?

**Comment by feliciakelley** [comment]
> Can you explain some more?

yes that my data had been used by another person, since it explains ( same origin )

**Comment by wangxin870601** [comment]
Hi! Maybe this issue can be described as this:
1. I have binded an email on my account and the 3pid is this
![image](https://user-images.githubusercontent.com/23348963/151173825-2da87e96-f1bf-4c46-89ab-e908cce8ce66.png)
2. But I can't see the email address on general setting panel for the lookup to identity server get the errcode: "M_MISSING_PARAMS"
![image](https://user-images.githubusercontent.com/23348963/151175093-211f6527-b812-4d8c-a427-1e298aa4b96a.png)
![image](https://user-images.githubusercontent.com/23348963/151175160-5ff24f40-f40b-48f7-b98a-841279a969d1.png)
![image](https://user-images.githubusercontent.com/23348963/151175203-63d2ecdb-8346-479f-8b5c-c35bdcbf6008.png)
3. This problem is not exist in element-web v1.9.8(matrix-js-sdk v15.3.0)
4. It looks like caused by the commit feb83ba161c32c0519613b88027f573e22efa3aa of matrix-js-sdk. The http-api.ts line 506 caused the request post body error.
