### ISSUE TITLE
Emojis on the bubble layout don't fit the line and are cut-off at the top

### ISSUE THREAD

**Issue by SimonBrandner** [vector-im/element-web#20744]
![2022-01-25_18-05](https://user-images.githubusercontent.com/25768714/151024326-97dba4b7-5b51-475d-a3f9-a3023ff56d14.png)

Font size seems to affect this

**Comment by t3chguy** [comment]
Can repro in Chrome but not FF

**Comment by t3chguy** [comment]
Same thing happens in IRC mode

![image](https://user-images.githubusercontent.com/2403652/151148564-23036f58-0842-4c95-b398-eb938a4c38c9.png)

**Comment by t3chguy** [comment]
Bubble layout & irc layout are set to line-height 1.8rem, modern layout is at 2.2rem leaving enough space

For bubble layout this seems to have been done intentionally since the emoji enlargening by @robintown https://github.com/matrix-org/matrix-react-sdk/commit/6806c2cdca98fd3867b29d7bffc8d687db0a6f05#diff-11808ff6468e6efa5982f414119fcc8a3a3eea4090b1a4ebda8ed6eae732418aR91-R92

**Comment by t3chguy** [comment]
The emojis seem to be taller than the font-size we request for them to be at, an 18px font-size smiley emoji is rendered at 21px tall, and thus gets cut off by the anti-zalgo overflow hidden
