### ISSUE TITLE
Backup device suddenly requires verification

### ISSUE THREAD

**Issue by jamescl** [vector-im/element-web#20904]
### Steps to reproduce

In element web 1.10.1 (and I *think* from v1.9.7) users are suddenly prompted to verify their Backup device. This seems to occur whether or not  "feature_dehydration" is set to true or false.

This places the user in a confusing catch-22 - You are constantly asked to verify this device, but since it's sitting on your homeserver, nobody will reply to an incoming verification request and the only solution is to delete the backup device - presumably to be prompted next time you log when a new backup device is created.

Screenshots:

Prompt on reloading page:
![image](https://user-images.githubusercontent.com/2550644/152481334-e8129381-fa1c-4c28-8221-96ec0111f5cd.png)

Security and privacy page:
![image](https://user-images.githubusercontent.com/2550644/152480784-8981e315-3343-4d0f-99a7-3c297ee752fa.png)

After clicking verify:
![image](https://user-images.githubusercontent.com/2550644/152480794-86e2fc44-f0a4-4d68-b789-0bbe64bdfe32.png)
 

#### What did you expect?
No prompt to verify a backup device as per previous behavior

#### What happened instead?
Element asked me to do something that is not possible

### Application version

Element 1.10.1

### Homeserver

Synapse 1.51.0

### Will you send logs?

No

**Comment by uhoreg** [comment]
When it creates a dehydrated device, it's supposed to sign the device key with the cross-signing key (if it's available), so it shouldn't be asking for verification.  If it's asking for verification, it's most likely because either it didn't have access to the cross-signing key when it was created (which is probably a bug), or the cross-signing key got changed after the dehydrated device was created.

Removing the "Backup Device" device should be sufficient, though of course you will lose the benefit of the dehydrated device feature until a new one gets created.  But the next time a new dehydrated device is created, it *should* get cross-signed by the device that creates it.

**Comment by jamescl** [comment]
So logging out of all sessions and logging back in created a new backup device which seems to have been signed properly. I can't seem to re-create this scenario, so suspect there was a very narrow set of parameters that caused this when I updated my version of element web after logging in to a single session - will close for now since I can't re-create.
