### ISSUE TITLE
show ALL hidden events in the Main Room, when activated

### ISSUE THREAD

**Issue by JokerGermany** [vector-im/element-web#21119]
#### What would you like to do?
I want to see even the Events of a thread in the Main Room, when activated.

#### Why would you like to do it?
To have more information whats going on.

**Comment by HarHarLinks** [comment]
To put this another way: Threaded messages are *actually* just timeline messages that include a relation field. It is to my knowledge currently impossible to view the actual room TL since threads get "hidden" into the threads panel. The same way reactions are just TL messages with relations that get rendered at the message they relate to, yet they are shown in place with hidden events enabled.

**Comment by t3chguy** [comment]
> yet they are shown in place with hidden events enabled.

The js-sdk splits threads into separate event timeline sets so they can be consumed by a TimelinePanel downstream, hence them not even showing up in the main timeline set with hidden events shown, reactions unlike threads are part of the same event timeline set. Including thread's events in the "main" event timeline set will affect performance fairly significantly.

**Comment by gsouquet** [comment]
My understanding of hidden events, is that they are events that can not be rendered with an `EventTile` (a redaction, a reaction, ...). As others pointed out, thread replies do not really fit that category.

I'm not sure having a setting to display all threads messages in the room timeline and be able to see them in the thread sidebar is desirable. At this stage if you can achieve that behaviour by disabling threads in labs. We're also exploring the ability to block threads per room https://github.com/vector-im/element-web/issues/20428.

Looping product in, as they will have the most insights on the direction we're taking with this feature

**Comment by gsouquet** [comment]
I'm not quite sure this is a desirable behaviour in the long term. Allowing this will mean that different users will indefinitely have a disjointed experiences. And issues where a message is not in a thread because someone did not hit "reply" will never get fixed.

As the feature matures, more and more client will adopt it. And I can totally hear the argument that people do not like threads, in that case disable it on a per-room basis and everyone gets the same experience

**Comment by novocaine** [comment]
We don't intend to support this feature in Element Web for the reasons outlined above.
