### ISSUE TITLE
Cannot persistently clear unread messages in rooms containing threads

### ISSUE THREAD

**Issue by novocaine** [vector-im/element-web#21114]
### Steps to reproduce

Load my account in our test server. See this

<img width="380" alt="Screenshot 2022-02-17 at 13 19 10" src="https://user-images.githubusercontent.com/57377/154489855-a049b003-3811-4e57-bb71-fda2ac9a5243.png">

Click on all of the rooms in the room list to clear unread

<img width="315" alt="Screenshot 2022-02-17 at 13 19 29" src="https://user-images.githubusercontent.com/57377/154489945-31b206f1-fa46-47a4-b090-bb1537e803e9.png">

Reload the page and the unreads are back

<img width="310" alt="Screenshot 2022-02-17 at 13 20 02" src="https://user-images.githubusercontent.com/57377/154489982-d7163242-f5b4-46d0-95fd-567fcea98ab5.png">

#### What did you expect?

For the unread markers and badges to not return after they were cleared

#### What happened instead?

They came back

### Operating system

OS X

### Browser information

Chrome

### URL for webapp

develop.element.io

### Application version

Element version: ba55473a0e4e-react-c19aa957b655-js-74d24f38f742 Olm version: 3.2.8

### Homeserver

threads-dev.lab.element.dev

### Will you send logs?

No

**Comment by gsouquet** [comment]
I'm not sure whether this is related to threads or not. 
This is happening in a DM where 0 threads have been created.

Have not figured out the root of the issue yet

**Comment by novocaine** [comment]
This is no longer happening in group rooms on the test server, but it is still happening with the DM

**Comment by kittykat** [comment]
I semi-regularly have red and grey notifications appearing in Delight with no obvious messages/reactions/threads/etc to account for them

**Comment by novocaine** [comment]
I can't repro this any longer

**Comment by novocaine** [comment]
Seeing this again in "Threads Internal". It's marked permanently in bold and nothing I can do clears it

<img width="313" alt="Screenshot 2022-03-16 at 12 31 10" src="https://user-images.githubusercontent.com/57377/158590472-3d33d944-41d7-4181-8f0a-598cb4a7ce63.png">

**Comment by novocaine** [comment]
I managed to clear this by adding a reaction 

<img width="591" alt="Screenshot 2022-03-16 at 12 34 07" src="https://user-images.githubusercontent.com/57377/158590951-e0b8fa3c-d314-487c-b061-5665a0218899.png">

**Comment by novocaine** [comment]
I can't clear the unread marker in Threads P0 Delivery today at all.

**Comment by t3chguy** [comment]
Blocking on threads notifications msc work

**Comment by davepacheco** [comment]
I'm seeing a very similar behavior:

1. Every time I load Element, many rooms show unread messages.
2. I navigate to every room with unread messages and they're marked read.
3. I refresh Element -- now they all show "unread" again.

I'm using Element version: 1.11.8 (Olm version: 3.2.12) in Firefox 105.0.1 on Mac OS 11.6.8.  This has been going on with my Element session for about a week, since we recently updated our Matrix server for the recent security update.

I just checked to see what happens in my mobile (iPhone) client.  I noticed that some rooms show unread messages that should not have (I had seen all the notifications).  I went through and read them.  Now those rooms don't show as unread in _either_ the browser _or_ the mobile client.  But there remain other rooms (I think they're all currently DMs) that show unread messages in Element in the browser, but not on my mobile client.  That remains true even if I refresh the browser and restart the mobile client.  And it remains true even if I navigate to them on the mobile client.

Maybe relevant: I saw similar behavior with the Element MacOS app several weeks ago.  I gave up using the app (without debugging it further) because this problem was such a pain.  At that time, this was _not_ affecting Element in the browser.  But now it is.

Is there any other data I can provide to help resolve this?

**Comment by gsouquet** [comment]
This issue will be resolved when clients all implements https://github.com/matrix-org/matrix-spec-proposals/pull/3773

Element Web is tentatively close, and both Android and iOS will fast follow, https://github.com/matrix-org/matrix-js-sdk/pull/2726

The problem is "resolved" and pending implementations

**Comment by thiemol** [comment]
> I managed to clear this by adding a reaction _not in a thread_
> 
> <img alt="Screenshot 2022-03-16 at 12 34 07" width="591" src="https://user-images.githubusercontent.com/57377/158590951-e0b8fa3c-d314-487c-b061-5665a0218899.png">

Sorry for open this again, but we are on Version Element: 1.11.31 and Version Olm: 3.2.14 and we still have this behavior. Only add reaction to a non thread fixes it till another room shows the same behavior.

**Comment by t3chguy** [comment]
@thiemol 1.11.31 is 50 days old and 3 versions of fixes have happened since then. Please consider our time when reporting issues with old versions where active fixes have been made since.

**Comment by wielinde** [comment]
Hi, we use Element in our relatively big team on many operating systems (Linux, MacOS, Android, iPhone,...). Thank you all for that great application!

Our clients are as up-to-date as you can get it in a diverse team (the majority is on the latest Element version, however, possibly some e.g. on mobile phones could be outdated).

We encounter the problem of having wrong "unreads" all over the place (different users, OS, versions,...). Also the inability to successfully mark a room as "read", even when restarting client and/or deleting the cache multiple times.

Unfortunately the pain is so big in the team that people started openly express their anger during meetings. The main pain points are:
- Not being able to mark some rooms as read, again and again
- Thus, not trusting the "unread" badges anymore and consequently missing out important messages

If we miss anything crucial information/tip on how to resolve the mentioned issues please point us to a solution. We were not able to figure it out from the messages above.

Also, if we are the only team having that issue, I'd also appreciate the feedback as we then probably need to shift our debugging focus on our Matrix server. However, it does not look like that. Other Matrix clients do not seem to have the same problems.

We are team of software developers and could provide you with deeper and more detailed information if you need it. I am personally available for a debugging session.

Thank you!

**Comment by ayushin** [comment]
why is this issue closed, the problem is clearly there

**Comment by Tropaion** [comment]
Also having this issue, very very annoying.

**Comment by Disconn** [comment]
Hi, i also have this issue. I can not see any unread conversation but there is still the App-Indicator on home-screen telling me there is one unread message. 

Problem occures with "Element X" and "Element" on iOS. 

Is there a workaround? Am i able to reset the Counter or delete the notofication?

**Comment by t3chguy** [comment]
@Disconn Element X and Element on iOS do not use the `element-web` codebase. You would need to report your issue to the relevant project.
