### ISSUE TITLE
pictures in .heic are not shown in desktop app

### ISSUE THREAD

**Issue by Tupsi** [vector-im/element-web#21159]
### Steps to reproduce

1. make a photo with a modern android smartphone which saves pictures in .heic instead of jpg. (I used a Samsung S20)
2. share the taken picture in a matrix room with the android app.
3. The picture is shown fine in the android app.
4. the desktop app just shows a loading animation.
<img width="83" alt="image" src="https://user-images.githubusercontent.com/3730499/155143210-3e00e9ff-960c-4a79-811b-7ddb28413fff.png">
5. downloading the picture and later open it in any viewer works fine and shows the taken photo (I used IrfanView)

#### What did you expect?
shared picture shown in the room like any other image shared
#### What happened instead?
never ending loading animation

### Operating system

Windows

### Application version

Element version 1.10.4, Olm version 3.2.8

### How did you install the app?

can't remember, it is been a while

### Homeserver

Synapse 1.52.0

### Will you send logs?

No

**Comment by t3chguy** [comment]
No browsers support HEIC/HEIF at this time, Element Desktop is an Electron app which uses Chromium
https://caniuse.com/heif

**Comment by t3chguy** [comment]
Two prior issues on this topic have been closed

https://github.com/vector-im/element-web/issues/19531#issuecomment-953432008
https://github.com/vector-im/element-web/issues/9143#issuecomment-574872335

Closing alike

**Comment by justin13888** [comment]
I've been having this issue for years and always ended up inconveniently going to my phone to view it. I've seen quite a few people post an issue about it and I do think it's worth finding a solution to this. Instead of relying the chromium engine to support heic/heif (which may take many more years), what if we just allow element desktop applications to convert the heic/heif file into a commonly supported format and cache it to be viewed?

I understand if there are many other more critical issues to solve, but I'd be willing to implement a PR to test that out. Reason I'm also writing this here is because I'd like to welcome input from anybody on this, especially on the technical implementation.

**Comment by ajkessel** [comment]
I agree with @justin13888 . This is basic functionality that normal users expect to work -- if a Mac user pastes an image into a chat on the desktop app, they expect other room members to be able to view it. There are off-the-shelf free libraries that convert HEIC to JPEG, so it shouldn't be that heavy a lift to integrate into Element. Would love to see this get fixed.

**Comment by ajkessel** [comment]
A short-term workaround: [maubot-hateheif](https://github.com/ser/maubot-hateheif/)
