### ISSUE TITLE
still showing a "syncing" spinner, 2 hours after `/sync` completed

### ISSUE THREAD

**Issue by richvdh** [vector-im/element-web#21203]
### Steps to reproduce

1. log in

### Outcome

![image](https://user-images.githubusercontent.com/1389908/155570300-e295d818-3b89-4994-a3f8-135b0f1813e3.png)

According to my HS, the initial `/sync` completed at 16:42:45. It's now 16:54:40, and I'm still waiting.

### Operating system

ubuntu 20.04

### Application version

1.10.4

### How did you install the app?

debian package

### Homeserver

synapse 1.50.1

### Will you send logs?

Yes

**Comment by richvdh** [comment]
(and of course I can't stop the desktop notifications because... no UI)

**Comment by reivilibre** [comment]
I also see this issue with app.element.io on my homeserver; at least 15 minutes after the initial sync completes I'm still waiting for a usable client.
My account is not that big and this seems very unusual for it.
I left it running and had a meeting for an hour and came back to a visible client, so it seems to *eventually* figure itself out.

I exported a 'HAR' thing from Firefox's network requests developer tools — contact me OOB if that would be useful, since I guess it contains sensitive information.

**Comment by richvdh** [comment]
it seems to be spamming hundreds of room_key_requests.

**Comment by richvdh** [comment]
> it seems to be spamming hundreds of room_key_requests.

10000 of them so far.

**Comment by richvdh** [comment]
my other accounts want me to verify the new login. That doesn't seem like it's going to work, so I have declined for now.

**Comment by richvdh** [comment]
restarting the app seems to have woken it up

**Comment by richvdh** [comment]
related: #19488

**Comment by richvdh** [comment]
well, this didn't get much love :(
