### ISSUE TITLE
Update design for the new search experience to include public rooms and people in results

### ISSUE THREAD

**Issue by kittykat** [vector-im/element-web#21352]
To provide a seamless experience,  "Explore Rooms"/"Public Rooms" and "Direct Messages"/"People" dialogs should be part of the new search experience using filtering.

## Tasks

- [x] Design the interaction and UI
- [x] Update the [development task](https://github.com/vector-im/element-web/issues/21354) with the designs

**Comment by niquewoodhouse** [comment]
Flow examples for discussion:

https://user-images.githubusercontent.com/1587166/158361578-3496ce8a-a16c-4fca-87f1-61cf54c7b4c9.mov

I think this could lead to some UX complications for users who don't understand the history of public room directory and spaces.  So eventually, there might be a need to include a broader filter that lets people select spaces to search, but I obviously don't understand complexities in this area and I'm assuming a bit myself.


<img width="1440" alt="Search_amends1 2@2x" src="https://user-images.githubusercontent.com/1587166/158362690-55c49732-ca19-4e9f-9c35-553699520db4.png">

**Comment by niquewoodhouse** [comment]
@kittykat @t3chguy Hi, would you mind feeding back on this design proposal please.  I've tried to make them reflect the existing public rooms and people UX as much as possible, rather than rethink anything.

- [People flow](https://www.figma.com/file/X7PvFE7f73mI7pJ9WLM61l/%5BWeb%5D-%5BSearch%5D?node-id=184%3A17726)
- [Public room flow](https://www.figma.com/file/X7PvFE7f73mI7pJ9WLM61l/%5BWeb%5D-%5BSearch%5D?node-id=184%3A17900)
- [Optional keyboard support idea](https://www.figma.com/file/X7PvFE7f73mI7pJ9WLM61l/%5BWeb%5D-%5BSearch%5D?node-id=226%3A18466)

I think longer term making the public rooms server picker act more like a [bigger filter](https://www.figma.com/file/X7PvFE7f73mI7pJ9WLM61l/%5BWeb%5D-%5BSearch%5D?node-id=236%3A19715) might help users find the right rooms, but I think that's likely out of scope for now and needs more insights.

**Comment by t3chguy** [comment]
Hey @niquewoodhouse - thanks for taking time to do such a detailed design.

> Search for section added to top of pre-input

Not sure how I feel about this, given that once you start filtering and you don't find what you're looking for you are met with similar buttons, and by selecting them your query is maintained. Happy to keep it but it means swapping to the last room you were in is no longer `Cmd + K` `Enter`

---

> If you can't see who you're looking for, send them your invite link.

I think this should be a tile so that its do-able with the keyboard, not requiring mouse, right now it looks like a block of text with a link around a small part of it.

> People flow

Right now it only seems to have the `Suggestions` category but our current implementation also shows you `Recent conversations`, is this intentionally removed?

Rest of it looks *GREAT*

---

> Some results may be hidden for privacy

This isn't quite true, its more that some rooms just choose not to be published

> If you can't find the room you're looking for, ask for an invite or create a new room.

I think this should be a tile so that its do-able with the keyboard, not requiring mouse, right now it looks like a block of text with a link around a small part of it. (same as People flow above)

> Public room flow

Looks good, kinda worried about the dropdown but its certainly no worse than today!

---

> Down arrow highlights option similarly to other things in search
If user Esc, hint disappears

I don't think we can express this is in a way which won't confuse screen reader users
I think relying on `Search for section added to top of pre-input` might be most sane, we could special-case that the `Search for` stays at the top if your input looks like `People` or `Public rooms`

**Comment by niquewoodhouse** [comment]
Thanks @t3chguy for the thorough look through.  Based on your input I've made a new version [here](https://www.figma.com/file/X7PvFE7f73mI7pJ9WLM61l/?node-id=248%3A20656) 

- amends the pre-input to not show buttons
- changes actions in people and room lists (create new room + copy link) to be tiles
- removes privacy reference from end of room list results
- remove ideas around using input to show a dropdown 
- adds in the recent conversations section for people (but hides it if there's no match in the section)

**Comment by t3chguy** [comment]
This is great, one other thing, these don't look like tiles

![image](https://user-images.githubusercontent.com/2403652/159969662-9ebe1120-ecc2-4d96-8934-f40afa33e32c.png)

Presumably arrow keys will still move between them, could we get a hover/active state design just to see what one of these huge "tiles" looks like
