### ISSUE TITLE
Polls should not be interactive in message pinning sidebar

### ISSUE THREAD

**Issue by gsouquet** [vector-im/element-web#21409]
#### What would you like to do?

Polls should not be interactive in message pining sidebar

#### Why would you like to do it?

It's odd to vote from the message pinning sidebar as you're potentially missing on the context of when this poll was asked

#### How would you like to achieve it?

Make the poll tile clickable and make it so that you jump to that point in the conversation

**Comment by ara4n** [comment]
The main reason to pin a poll is to let people find it, in order to vote about it.  The poll should have all the context needed within it its description to allow people to vote - so i strongly feel that it's a feature, not a bug, that polls are interactive in the message pinning sidebar.

/me closes with his prod hat on
