### ISSUE TITLE
Reactions from others not being rendered in threads 

### ISSUE THREAD

**Issue by janogarcia** [vector-im/element-web#21627]
### Steps to reproduce

Check out a message in a thread that has reactions from others, but not from yourself. I spotted it when viewing the same thread on the Android client.

#### What did you expect?

The reactions to be displayed.

#### What happened instead?

No reactions being displayed at all.

### Operating system

macOS

### Browser information

Chrome 99.0.4844.74

### URL for webapp

develop.element.io

### Application version

Element version: 5077157282d1-react-f4c25e06cdbc-js-d6f1c6cfdc5a Olm version: 3.2.8

### Homeserver

matrix.org

### Will you send logs?

No

**Comment by t3chguy** [comment]
I think I figured out what is happening and it applies to edits too

When evaluating indirect threaded events (relations, redactions, edits, etc) we may not have the parent event (in the thread) accessible via findEventById due to the async operation of spinning up the thread (by means of a /relations call)

Creating a thread needs to happen eagerly and then async for filling data

**Comment by janogarcia** [comment]
(thanks for figuring out the challenging stuff)

**Comment by t3chguy** [comment]
So in part it is what I theorised, but the other part is bigger, it is the lack of bundled aggregations support for relations & edits.

The /relations call doesn't include the m.reaction event, only an aggregate count of events, so will require some rework to be able to make use of.

Related https://github.com/vector-im/element-web/issues/9743

**Comment by t3chguy** [comment]
Fixed by https://github.com/matrix-org/matrix-react-sdk/pull/8448 (except the #9743 case)
