### ISSUE TITLE
Show read recipients despite events are grouped

### ISSUE THREAD

**Issue by JokerGermany** [vector-im/element-web#21717]
### Your use case

When events are grouped you can't see on a first glance the read recipients
![grafik](https://user-images.githubusercontent.com/30293477/162401718-cdefd99b-2fbb-4ca1-a8c0-89095e97e277.png)
You need to extend it.
![grafik](https://user-images.githubusercontent.com/30293477/162402135-78c71c49-6673-4ba2-aba0-6e98ced46d31.png)

It would be nice if the read recipients would be shown grouped, too.

In this case something like this
![read recipients](https://user-images.githubusercontent.com/30293477/162403205-9dfee0b9-165a-4c25-8d26-126ba471067b.png)

**Comment by AceTheCreator** [comment]
@dbkr Is this issue been assigned to anyone yet?

**Comment by robintown** [comment]
@AceTheCreator Thank you for your interest in this issue. We will normally not assign the issue to an external contributor until they have provided at least a draft PR which is taking the right direction. For further details, see our [guidance on assigning issues](https://github.com/vector-im/element-meta/wiki/Guidance-on-assigning-issues).

This issue is likely to be a bit difficult, but if you have any technical questions, you can ask for help in [#element-dev:matrix.org](https://matrix.to/#/#element-dev:matrix.org)

**Comment by t3chguy** [comment]
I think with the new RR design this becomes easier too, as read receipts now take up much less space, so can probably just inset the `expand` button to the left of the RRs

**Comment by justjanne** [comment]
It was decided not to support this functionality for the time being. Read receipts for collapsed event summaries will remain the way they currently are.

See https://github.com/matrix-org/matrix-react-sdk/pull/8446#pullrequestreview-967589502 for clarification.
