### ISSUE TITLE
Right panel chat has lost its right margins

### ISSUE THREAD

**Issue by robintown** [vector-im/element-web#21745]
### Steps to reproduce

1. Maximize a widget
2. Open the chat panel

#### What did you expect?

The timeline and composer should be distanced from the right side of the panel.

#### What happened instead?

![Screenshot 2022-04-11 at 15-08-58 Element testing](https://user-images.githubusercontent.com/48614497/162812151-c6b78f8e-19b3-4299-91ab-e4b5ddf46563.png)

### Operating system

NixOS unstable

### Browser information

Firefox 98.0.2

### URL for webapp

develop.element.io

### Application version

Element version: cec31d0e714e-react-9ba55d1d1410-js-3b33237e51ae Olm version: 3.2.8

### Homeserver

Synapse 1.56.0

### Will you send logs?

No

**Comment by robintown** [comment]
@EECvision You're welcome to submit a fix for this issue, though since it is a regression that we likely want to make sure is fixed by the time of the next release, I'm going to leave it unassigned.

**Comment by luixxiul** [comment]
I don't think this is a regression due to recent changes as there has not been right margin since 1.10.4 at least.

![1-10-4](https://user-images.githubusercontent.com/3362943/162947070-eadc44e2-be0d-4d7e-a44f-11daeeae4419.png)

**Comment by robintown** [comment]
@luixxiul I'm not referring to a right margin within the timeline, but rather the gray border between the timeline+composer and the edge of the card

**Comment by EECvision** [comment]
> @EECvision You're welcome to submit a fix for this issue, though since it is a regression that we likely want to make sure is fixed by the time of the next release, I'm going to leave it unassigned.

Alright.

**Comment by luixxiul** [comment]
It is fairly easy to fix the margin issue if it would be possible to add another `:not()`, which I hesitate to do so as it makes the style inheritance even more complex, but there is another regression which should be addressed that the border-radius settings on top and bottom right are also gone, and it looks not so easy to fix the root cause without introducing other regressions.

(Background color of the panel was temporarily changed for clarification)
![before](https://user-images.githubusercontent.com/3362943/163021386-c2565a52-c649-42f5-816b-a73acde3cd97.png)

If it is preferred to fix the margin issue asap, I could create a PR based on that inferior solution soon, adding a `todo` flag to the line for later work to address the border-radius stuff. Which is preferred, considering the schedule of the release?
