### ISSUE TITLE
Reinstate "View Source" for events without being in developer mode

### ISSUE THREAD

**Issue by novocaine** [vector-im/element-web#21771]
#### What would you like to do?

See "developer mode" in the context menu for events, without enabling developer mode.

#### Why would you like to do it?

Element should be open. This is a tricky balance to strike, and we hide other developer options in "developer mode", but for this one, we think it having prominence for all users is important.

### Have you considered any alternatives?

We could keep view source hidden unless developer mode is enabled, consistent with other under-the-hood features.

### Additional context

explicit request from @ara4n

**Comment by Xiretza** [comment]
For anyone else that just wants "View source" back right now: developer mode can be activated by sending `/devtools` to any room, then checking "Developer mode" in the window that appears ([source](https://github.com/vector-im/element-web/issues/20683#issuecomment-1092786889)). This has all become quite obscure - that menu used to be accessible via right click on a room -> Room Settings -> Advanced -> Developer Tools (or somesuch), but this option has now disappeared completely (even with developer mode active).

**Comment by t3chguy** [comment]
>  (even with developer mode active).

Yup, because room settings isn't always available for spaces, so now it lives in more accessible places like the room menu
<img width="355" alt="image" src="https://user-images.githubusercontent.com/2403652/163180587-f3437887-8af5-4a8b-97b0-f50ce1d92467.png">
And quick settings
<img width="256" alt="image" src="https://user-images.githubusercontent.com/2403652/163180620-59ec8216-f202-45ab-acef-ff60d98d92fb.png">

**Comment by Xiretza** [comment]
> Yup, because room settings isn't always available for spaces, so now it lives in more accessible places like the room menu 

Huh, I never really realized that menu existed, and it seems to have quite a few more options than the *other* room menu (clicking the three dots or right clicking on a room in the room list).

> And quick settings

I didn't even think to look there because in my mind that menu has only ever existed as an additional hurdle to get to the actual application settings.

Anyway, neither of those options exist without developer mode active, so it looks to me like the only way to enable developer mode right now is via the borderline undiscoverable `/devtools` command.

**Comment by t3chguy** [comment]
Somewhat discoverable, it is listed in `/help`

**Comment by Xiretza** [comment]
That's a useful command - but I'm not sure how many people would think of entering it into a very graphical chat client such as Element. I've certainly never come across it in my >1.5 years of using it.

**Comment by BillCarsonFr** [comment]
Can it be there when using develop.element.io by default and not when using app.element.io.
I find it hard to see why it would be of any interest for a regular user.

**Comment by t3chguy** [comment]
Just noticed, Element Android hides View Source until you enable Developer Mode in settings

**Comment by t3chguy** [comment]
> What is the harm in leaving the "View Source" button enabled?

The context menu in which it is located can have up to 13 options rendered, removing the one which 95% of users don't need is sane

**Comment by G2G2G2G** [comment]
>-1, I've used this many times as a "regular" user to see how other people formatted their messages. You can do some interesting things with HTML/Markdown formatting, and being able to view the source is useful.

lmao sounds like a developer to me

@t3chguy 
It is in a weird place though. I understand the ROOM developer tools being where it is. I needed view source and saw it was gone and figured it was behind a "developer mode"
I looked all over the main settings, ever page.. before coming to github. Never checked the room specific settings.
For example on android it's under main settings -> help & about which makes sense. I find it in similar location on other programs too.
I'd also put it there (in help & about) also maybe on element-web/desktop or under the main dropdown of the main settings like pic related
![1](https://user-images.githubusercontent.com/50514477/164139763-229b3ceb-38c7-4367-b416-4ec765838ca4.jpg)

Thanks
