### ISSUE TITLE
Cannot invite users to my space (and rooms)

### ISSUE THREAD

**Issue by Currrupted** [vector-im/element-web#21835]
### Steps to reproduce

1. Start the Element app for Linux
2. Enable the (experimental?) "Spaces" feature
3. Go to a space you already created
4. On the space home screen, select "Invite"
5. enter the ID of a user
6. click on "Invite"

#### What did you expect?

Being the admin, when selecting "Invite users to this room" I should be able to just invite users to my space.

#### What happened instead?

When I go to "Invite users to this room" and enter the name/address of the user I want to add/invite, I get the error that I do not have sufficient permissions. 

![image](https://user-images.githubusercontent.com/13292623/163735367-3f37366e-a6a6-4953-8169-11716581e3aa.png)
![image](https://user-images.githubusercontent.com/13292623/163735465-21bd8951-b6b2-40b4-ad8d-53ec0fa10724.png)

### Operating system

Kubuntu 21.10

### Application version

Element 1.10.10

### How did you install the app?

https://element.io/get-started#linux-details

### Homeserver

nolog.chat

### Will you send logs?

No

**Comment by dbkr** [comment]
This might be some other error happening and being incorrectly interpreted as permissions. Would you be able to send debug logs?

**Comment by Currrupted** [comment]
> This might be some other error happening and being incorrectly interpreted as permissions. Would you be able to send debug logs?

Thanks for the support! If it helps, I will of course provide the logs! However, I would like to avoid sharing the information on my username there and the names of the space. Would that be possible?

**Comment by Currrupted** [comment]
I tried submitting the debug logs, but when I click on "Download logs", I get the message that there is some kind of internal server error.
![image](https://user-images.githubusercontent.com/13292623/164021020-5af555bd-7099-412e-8d76-668e926eb0e2.png)

**Comment by dbkr** [comment]
I've filed https://github.com/vector-im/element-web/issues/21926 for the issue of not being able to get the logs

**Comment by kittykat** [comment]
@Currrupted I'm going to close this issue for now because we won't be able to investigate it without logs. We can't help with getting logs from our side because nolog.chat isn't managed by us.

You have a few options that you could try:
* Ask the server admins to look into why you can't send logs
* Try sending the logs via the dialog directly (we will see your username and anyone looking into the logs will also be able to see room/space IDs)

If you can get access to the logs, please re-open the issue or reply with @kittykat and I can reopen it for you.
