### ISSUE TITLE
Error when downloading logs

### ISSUE THREAD

**Issue by dbkr** [vector-im/element-web#21926]
### Steps to reproduce

In https://github.com/vector-im/element-web/issues/21835#issuecomment-1102691033 the user is unable to download logs: it apparently fails with, "Internal server error" which is strange since no server is involved in downloading local debug logs.

Unfortunately we can't get more details, because we can't get the logs...

### Homeserver
nolog.chat

### Will you send logs?

No

**Comment by turt2live** [comment]
Unfortunately there's not enough information here or on the associated issue to really debug or investigate this. Probable causes are an extension blocking the download, an unsupported browser, or impatience while it builds the massive zip file.

I believe the referenced error message, "internal server error", is actually from a previous attempt to submit the logs rather than from the download button. This further indicates a potential size issue, or a variant of https://github.com/vector-im/element-web/issues/13290 causing invalid logs to be submitted.

If it happens again, please open a new issue with as much information as possible. Ideally even pop into a support room of some kind so we can live debug it.
