### ISSUE TITLE
Profile picture option on home screen

### ISSUE THREAD

**Issue by daniellekirkwood** [vector-im/element-web#21946]
### Your use case

As per @niquewoodhouse 's designs, add the ability for users to personalise their profile from the welcome screen. 

- [x] Add analytics to this option to match the other buttons here https://github.com/vector-im/element-web/issues/21705

<img width="245" alt="Screenshot 2022-04-26 at 09 13 32" src="https://user-images.githubusercontent.com/89144281/165442695-68574ca2-8b92-45e7-9d9c-b75978fcdeda.png">

**Comment by justjanne** [comment]
This is the current state, as it’s implemented in the app (the explanatory text is a tooltip):

![Current state of welcome screen](https://user-images.githubusercontent.com/3933349/166234331-109c30c9-8550-4d23-8319-2cbb43aa31e6.png)

It’s got two bugs (it can’t be triggered and the avatar can’t be set), but otherwise it’s been implemented like this since at least january from what git blame shows me.

**Comment by daniellekirkwood** [comment]
Thanks @justjanne. What version is that? I don't experience that. 

I'm using: Element version: 1.10.11, Olm version: 3.2.8 and this is the screen I see...

<img width="1440" alt="Screenshot 2022-05-02 at 11 29 31" src="https://user-images.githubusercontent.com/89144281/166304429-eff53715-1f16-4122-ba96-1e8873690ffb.png">

**Also, are there analytics on that click?**

**Comment by justjanne** [comment]
> Thanks @justjanne. What version is that? I don't experience that.
> 
> I'm using: Element version: 1.10.11, Olm version: 3.2.8 and this is the screen I see...
> 
> <img alt="Screenshot 2022-05-02 at 11 29 31" width="1440" src="https://user-images.githubusercontent.com/89144281/166304429-eff53715-1f16-4122-ba96-1e8873690ffb.png">
> 
> **Also, are there analytics on that click?**

It’s the version currently deployed on develop.element.io, but the trigger that’d cause that screen to show has some bugs so it never actually triggers that screen.

The way it works right now is that it only shows if you complete the registration in the same browser tab in which you started registration and never reload/refresh. On matrix.org, due to e-mail verification, this means that this welcome screen can never be triggered. (As far as I can tell).

What’s the proposed trigger for the new welcome experience? Should it show if a user has registered in the past 24h? Until a user has joined a room? Forever?

**Comment by justjanne** [comment]
Also: from what I can tell, no analytics exist on that click yet.

**Comment by daniellekirkwood** [comment]
Thanks! 

Sounds like regular users won't see this until our next deployment of develop to stable-production environment? We'll need to fix it beforehand...

**What are the current triggers?** 
Suggestion: As a temporary fix, all users would see this experience unless they have already set their profile picture. If users choose not to set the image then it might be annoying but they also won't encounter this screen often and it's not a blocking tooltip/task. @niquewoodhouse do you agree that we could add this for all users if they don't have a profile image set?

> Also, the avatar upload button is bugged and can’t be used. From what I can tell, there aren’t any analytics yet either.
What do you mean by "bugged"? 
Part of the acceptance criteria for this issue would be adding the analytics to this click, similar to the others on this screen. Would we be able to do that?

**Comment by justjanne** [comment]
> Thanks! 
> 
> Sounds like regular users won't see this until our next deployment of develop to stable-production environment? We'll need to fix it beforehand...
> 
> **What are the current triggers?** 
> Suggestion: As a temporary fix, all users would see this experience unless they have already set their profile picture. If users choose not to set the image then it might be annoying but they also won't encounter this screen often and it's not a blocking tooltip/task. @niquewoodhouse do you agree that we could add this for all users if they don't have a profile image set?
> 
> > Also, the avatar upload button is bugged and can’t be used. From what I can tell, there aren’t any analytics yet either.
> 
> What do you mean by "bugged"? 
> Part of the acceptance criteria for this issue would be adding the analytics to this click, similar to the others on this screen. Would we be able to do that?

Yes, it's definitely possible. With "bugged" I just meant that currently, even if this screen is shown, the user couldn't actually set their avatar. I've already got a fix for that ready in my local dev environment, though.

It should be relatively easy to add analytics :)

**Comment by daniellekirkwood** [comment]
Wonderful! So let's go ahead and apply the fix and add the analytics. 

Thank you, @justjanne !
