### ISSUE TITLE
Detect and delete unused code using static analysis

### ISSUE THREAD

**Issue by novocaine** [vector-im/element-web#21969]
### Your use case

For example - https://camchenry.com/blog/deleting-dead-code-in-typescript

We should consider running this in CI

**Comment by SimonBrandner** [comment]
Doing this for our project is rather tricky as `ts-prune` doesn't see into the upper layers to check whether or not an export is actually being used. It does check dependencies though, so if we run it in `element-web`, it will check all the underlying repos. That means that if we want to setup a GHA for this, we will have to clone `element-web` and all the layers below. This isn't a problem for `element-web` (surprisingly) and `matrix-react-sdk` (since we already do this there) though we don't do this in the `matrix-js-sdk`.

It will probably be necessary to do this in the `matrix-js-sdk` as not doing it there could result in the CI failing for the other repos but not for `matrix-js-sdk` itself

**Comment by SimonBrandner** [comment]
This is blocked on https://github.com/matrix-org/matrix-react-sdk/pull/8612

There are two PRs (https://github.com/matrix-org/matrix-react-sdk/pull/9052 and https://github.com/vector-im/element-web/pull/22830) which add GHAs for this but are blocked atm. This is because right now we have unused code which will be used by https://github.com/matrix-org/matrix-react-sdk/pull/8612 once merged

**Comment by SimonBrandner** [comment]
This is now done :tada:
