### ISSUE TITLE
Delight: Update image and spacing on email verification screen

### ISSUE THREAD

**Issue by daniellekirkwood** [vector-im/element-web#21984]
### Issue Ready
See the design [here](https://www.figma.com/file/ZDVvKC8odsa5Jeml9gCuLd/Web%3A-New-User's-Journey?node-id=188%3A2720)

### Your use case

The spacing and image on the verification screen needs updating.

<img width="426" alt="Screenshot 2022-04-28 at 12 39 29" src="https://user-images.githubusercontent.com/89144281/165832484-71becbd6-6263-4c67-a335-c975a2c43709.png">

This is how it looks in the new mobile flow:
<img width="595" alt="Screenshot 2022-04-28 at 12 40 11" src="https://user-images.githubusercontent.com/89144281/165832631-18f28495-5db8-4359-b38e-c4bafd2f55f8.png">

**Comment by niquewoodhouse** [comment]
I think the biggest issue is the page content.  

The Android version has:
- Image
- Title about email
- Explanation copy
- Secondary action to resend email

All of this content is to do with the email step, while the web one just has image and explanation copy to do with email step. The title still says 'create account', with stuff about hosting account before the email info.

Couple of quick suggestions:

1) Use same content as mobile

<img width="1440" alt="_option1 a@2x" src="https://user-images.githubusercontent.com/1587166/166500715-b9af5340-97f8-4a8c-bcfd-ecba375b6703.png">


I'm not sure the copy is right because 

- there's no button to tap in the email, it's just plain text I think?
- this isn't to verify your email, it's to actually create your account?  If you don't click on the link you can't actually sign in/use product, which feels (to me) something a level above verifying my email.

2) Slightly amended content

<img width="1440" alt="_option1 c@2x" src="https://user-images.githubusercontent.com/1587166/166501476-74775877-af0a-400c-86a7-a5ba193200e4.png">

- says its about account creation
- animate the email gif
- we might be able to do things like, if the email included gmail as domain, show open gmail button

**Comment by daniellekirkwood** [comment]
Great! I like the second option - we can see how it performs and then move any learnings between platforms when we have the feedback. 

As for the Gmail button... I'm unsure. Is it easy to do? What buttons should we have? Maybe we leave it off temporarily and deliver this design in 2 parts...

**Comment by niquewoodhouse** [comment]
> As for the Gmail button... I'm unsure. Is it easy to do? What buttons should we have? Maybe we leave it off temporarily and deliver this design in 2 parts...

I don't know to be honest if easy or not, or what impact it might have.  I think we'd only need to show a button if the email domain was relevant, so if ended in `@googlemail` or `@gmail` show user Open Gmail button.  If ended up `@hotmail` show Open Hotmail button.

Leaving off sounds good to me.  [Figma link](https://www.figma.com/file/ZDVvKC8odsa5Jeml9gCuLd/Web%3A-New-User's-Journey?node-id=188%3A2720)
