### ISSUE TITLE
Lots of "Mismatched room_id for inbound group session" UTDs in threads

### ISSUE THREAD

**Issue by robintown** [vector-im/element-web#22094]
### Steps to reproduce

Be in encrypted rooms where others are using threads heavily

#### What did you expect?

No UTDs

#### What happened instead?

Threaded messages occasionally show up as "\*\* Unable to decrypt: Error: Mismatched room_id for inbound group session (expected !ELvLSzljqBuAwjdBWx:t2l.io, was undefined) \*\*"

### Operating system

NixOS unstable

### Browser information

Firefox 99.0.1

### URL for webapp

develop.element.io

### Application version

Element version: 9cb0185ec2d0-react-e97536ef964b-js-6b5f4aa0a9c1 Olm version: 3.2.8

### Homeserver

Synapse 1.58.0

### Will you send logs?

Yes

**Comment by markiceman** [comment]
I have similar problem.

Element 1.10.12

Operating system: Windows

Browser: Firefox for Web version, Element desktop - both have the same problem

Homeserver: Synpase 1.58.1

Last message in thread in encrypted room is unreadable:

![obrazek](https://user-images.githubusercontent.com/54726936/167802048-b7bd58ce-e1f8-465c-b173-44352f19f562.png)

This is OK with Element 1.10.11 or Mobile App. It is problem with Element 1.10.12 only.

If I disable threads, message is readable.

Another screenshot with example:

![obrazek](https://user-images.githubusercontent.com/54726936/167800540-80a4bdc1-44f2-4de7-a7f2-c8b6e609d898.png)

**Comment by uhoreg** [comment]
It looks like Element is losing the `room_id` on some messages in threads, for some reason.  If I "view source" on these undecryptable messages, then it shows me a blank Room ID

![image](https://user-images.githubusercontent.com/1012976/169532037-3d5d7283-7345-4782-a855-b3b62606ef8a.png)

and expanding the "Original event source" shows no `room_id` field.  But it obviously has a room ID, or at least had a room ID, somewhere along the line, since it got put in a room.

Is it possible that the event object gets passed to a function that removes the `room_id` field somehow?

**Comment by t3chguy** [comment]
This sounds very similar to the other threads issue which has `thread.room` is undefined/null

**Comment by flyingcakes85** [comment]
In case it matters, it just see this issue after I logged out and logged in.

**Comment by uhoreg** [comment]
It seems to happen mainly on the last message in a thread.  Maybe there's a difference in backfilled messages vs messages from sync?  Or something related to getting the megolm session before or after we get the message?

**Comment by Wendell250** [comment]
Happened to me today as well.

I wrote a message to a thread (on encrypted channel) and switched to another channel.
But when I came back the last message in the thread was replaced with this error.

Clearing cache and restarting Element didn't fix it.

Element desktop: 1.10.13

**Comment by duxovni** [comment]
This isn't a real solution for the underlying issue, but as an interim fix while it's being investigated: the codepath throwing that error gets skipped if the provided room ID is `null`: https://github.com/matrix-org/matrix-js-sdk/blob/develop/src/crypto/OlmDevice.ts#L1066-L1073 Would it be reasonable to also skip it if the room ID is `undefined`?

**Comment by duxovni** [comment]
A tentative theory about what's actually going wrong:
- [Synapse strips out the `room_id` field when serializing individual events in sync responses, because the events are already listed under their room ID in the sync response](https://github.com/matrix-org/synapse/blob/develop/synapse/rest/client/sync.py#L223)
- [This serialization config is also applied to the latest thread reply event under `m.relations`](https://github.com/matrix-org/synapse/blob/develop/synapse/events/utils.py#L529-L534)
- [Element Web re-inserts room IDs while processing the top-level events returned by a sync](https://github.com/matrix-org/matrix-js-sdk/blob/develop/src/sync.ts#L1601-L1603)
- However, I don't see any sign of it re-inserting room IDs into events under `m.relations`. So that's a context where Element Web might ingest the `latest_event` of a thread with its room ID missing.
