### ISSUE TITLE
1px gap in edit UI

### ISSUE THREAD

**Issue by HarHarLinks** [vector-im/element-web#22108]
### Steps to reproduce

https://user-images.githubusercontent.com/2803622/167252531-c47936e9-47e9-4155-95f6-27513cd4467d.mp4

Note the background extending 1px too far down when selecting the lower message, and then the gap when selecting the upper message. Also the gap disappears when hovering.

#18269

### Outcome

see above

### Operating system

arch

### Application version

Element Nightly version: 2022050701 Olm version: 3.2.8

### How did you install the app?

aur

### Homeserver

1.57.1

### Will you send logs?

No

**Comment by luixxiul** [comment]
Unless you would provide with fresh information, this issue obviously will be closed again like #18269.

Since this is a rare case, I think you are expected to provide information such as:
- What browser do you use to open Element?
- Which desktop environment do you use?
- Is the issue reproduced on other browsers as well?
- Is the issue reproduced on other desktop environments as well?
- Is the issue reproduced on Arch linux only?

**Comment by HarHarLinks** [comment]
luixxiul: thank you for trying to help clarify the issue.

> * Which browser do you use to open Element?

none, this is nightly, as stated in OP

> * Which desktop environment do you use?

none, I use sway wm

> * Which version of `arch` do you use?

I think "up to date" is implicit in a RR unless stated otherwise

> * Is the issue reproduced on other browsers as well?

n/a

> * Is the issue reproduced on other desktop environments as well?

yes, e.g. w10

> * Is the issue reproduced on `arch` only?

no, e.g. w10

---

Anyway, thank you Simon for fixing. (Why X-Cannot-Reproduce though?)
