### ISSUE TITLE
"Face With Open Eyes And Hand Over Mouth" overflows the emoji picker

### ISSUE THREAD

**Issue by robintown** [vector-im/element-web#22126]
### Steps to reproduce

1. Open the emoji picker
2. Hover over "Face With Open Eyes And Hand Over Mouth"

#### What did you expect?

The text should be ellipsized, or something

#### What happened instead?

![overflow](https://user-images.githubusercontent.com/48614497/167548384-032f54ef-d011-478c-abd0-0f2731d87d22.png)

### Operating system

NixOS unstable

### Browser information

Firefox 99.0.1

### URL for webapp

develop.element.io

### Application version

Element version: cdf95ab8b71a-react-c1579f765a8a-js-62d77231afd4 Olm version: 3.2.8

### Homeserver

Synapse 1.58.0

### Will you send logs?

No

**Comment by yaya-usman** [comment]
@robintown how about this state? but i had to decrease the font-size a bit.

![Capture1](https://user-images.githubusercontent.com/38439166/167959943-142d6d2a-c5d3-4521-b74e-a6440195e37a.PNG)

**Comment by robintown** [comment]
Rather than decreasing the font size (which would require design review), we should probably just remove the possibility of the text overflowing the container by giving it an appropriate `overflow` property. We may also want to limit the description to 1 line in CSS.

**Comment by yaya-usman** [comment]
I decreased the fontsize a bit because no overflow property can fit the text well except the scroll property which is not ideal in my opinion. Also concerning the description text, it's too large or long to fit into one line, it's probably gonna break into two line. But if you want it to ellipsized, i can do that but the user will not be a able to read the full text as shown in the image below

![Capture1](https://user-images.githubusercontent.com/38439166/168069844-e93d4a2f-0faa-4d2b-8714-bc2e2138d334.PNG)

**Comment by SAGARGAUD01** [comment]
The issue is solved or not ?
assign me if issue is not solved yet.

**Comment by VaibhavAPatil** [comment]
I am **interested** in **this Issue**. Can I do **Pull Request** or you can **assign** this **issue to Me**.

**Comment by robintown** [comment]
Thank you for your interest, but this issue is already resolved.
