### ISSUE TITLE
Allow us to CHANGE proprietary closed-source scalar.vector.im INTEGRATIONS manager server to our own server

### ISSUE THREAD

**Issue by jittygitty** [vector-im/element-web#22209]
#### What would you like to do?
I would like to be able to go to Settings->General and under "MANAGE INTEGRATIONS" to be allowed to change from the proprietary closed-source https://scalar.vector.im  to be allowed to change that to our own server, perhaps even one by @turt2live https://github.com/turt2live/matrix-dimension 

#### Why would you like to do it?
I don't like connecting my devices to 3rd party proprietary "closed-source" servers that can track/log and who knows else, so I siply want to be able to click and CHANGE scalar.vector.im to my own server address. If there's some not so obvious way to do it that I missed, please let me know, because I found NO WAY to change it. Thanks!

#### How would you like to achieve it?
The project maintainers should be able to fix this very easily actually, its not some difficult feature request.

### Have you considered any alternatives?

Yea I ALSO tried the ANDROID app, and I could NOT change the https://scalar.vector.im INTEGRATIONS manager server in android app either. 

### Additional context

I posted already asking this simple question on how to change scalar.vector.im to a different address since I found this was asked for a few YEARS ago even. But when I asked how to do this at:
https://github.com/vector-im/element-meta/issues/260

That thread was closed and I was told to go read the documentation. Where? What documentation shows how to change that???

I already went to settings on BOTH ANDROID and DESKTOP app, and NEITHER of them ALLOW changing scalar.vector.im

So please someone show me that documentation, or add the feature thanks!

**Comment by jittygitty** [comment]
Well, apologies, I had meant to post this in Desktop, not WEB matrix client. So sorry about that. But can someone point me to documentation on how to change scalar.vector.im in the matrix WEB client's "User Interface" (ie not in source code)? thanks!

**Comment by turt2live** [comment]
Per https://github.com/vector-im/element-web/issues/17405 you are able to change the configuration. The configuration is also documented at https://github.com/vector-im/element-web/blob/develop/docs/config.md

In order to switch fully away from 3rd party services, you will need to host your own stack. This includes hosting your own Element Web with your configured integration manager of choice.

Please use [#element-web:matrix.org](https://matrix.to/#/#element-web:matrix.org) for support questions.

I'm closing this as changing integrations managers in-app is not something we can effectively support without proper consideration from the spec, particularly around how to handle Widgets, Bridges, and Stickers. These areas do not lend themselves nicely to multiple/varied integration manager support.
