### ISSUE TITLE
Broken state when editing

### ISSUE THREAD

**Issue by HarHarLinks** [vector-im/element-web#22207]
### Steps to reproduce

please see the key presses on video:

https://user-images.githubusercontent.com/2803622/168446464-ff69a0e4-8343-421d-b167-0602cacdf607.mp4

the edit composer can't tell the difference between unedited and edited-but-reverted. you get stuck in edit mode even though you reverted.

#### What did you expect?
don't get stuck: the edit composer should handle undone edits the same way as no edit at all 

#### What happened instead?
stuck

### Operating system

arch

### Application version

Element Nightly version: 2022051401 Olm version: 3.2.8

### How did you install the app?

aur

### Homeserver

1.58.1

### Will you send logs?

No

**Comment by andybalaam** [comment]
My summary of the bug - please correct me if I'm wrong.

* When I start editing a message, the Save button becomes enabled.
* If my edits result in an unchanged message (e.g. if I Undo my edits in the composer) the save button remains enabled (and when I click Save, underneath, nothing happens, but I don't know that.).
* I (HarHarLinks) think the button should become disabled again if I undo my edits.

I (AndyB) think the current behaviour is good: I don't want to have to the mental burden of remembering the initial state of the message, so that I can understand why the Save button suddenly becomes disabled. The current behaviour does no harm, and is unsurprising to the user.

I also think this is quite a minor issue, so I don't think we want to take valuable design time on it, so I'm going to close it.

If I misunderstood, please let me know. Thank you for taking the time to log this issue.

**Comment by HarHarLinks** [comment]
I can't agree with your reasoning, I do however agree this is a very minor issue you may ignore if you decide so.
I don't have a reference for how other messengers handle this.

With the current behaviour, I have the mental burden of remembering what the message was before I edited and then undid my edits. If I forget the initial contents, but am happy with the "edited" text, the UI does not show me that info. I can still send and there will not be an edit as Element will recognize that there is no change. This is not made obvious to the user.

With my suggestion, the user would get this feedback. In my eyes, it is obvious that not changing anything would disable the send button and would not increase a mental load.
The user's only option being "Cancel" is consistent with their actual action. Further, the send button's disabled status is more consistent with itself.

**Comment by HarHarLinks** [comment]
Aha, I now remember my actual UX issue! The keyboard navigation uses the same logic as the "Save" button to decide if you may continue keyboard navigation. So if I started editing and decided to stop editing one message and want to move to another message (by keyboard), then I cannot. Instead I have to completely cancel and then navigate to the message I want to edit again from the start.

**Comment by andybalaam** [comment]
Thanks for taking the time to reply. I definitely see the argument you are making, but I find the current behaviour more intuitive. I guess it's just personal taste. Glad to hear you agree it's very minor so hopefully won't be a big problem for anyone if I made the wrong call here.
