### ISSUE TITLE
Can't see everyone in the video room

### ISSUE THREAD

**Issue by kittykat** [vector-im/element-web#22285]
### Steps to reproduce

1. User1 is in a video call
2. User2 joins call
3. User1 still thinks they're on their own
4. User2 can hear user1

#### What did you expect?
Can always see everyone in the call

#### What happened instead?
Can't see anoa

### Browser information

Chromium 101.0.4951.64 (Official Build) Arch Linux (64-bit)

### URL for webapp

develop.element.io

### Application version

Element version: b2d057b7c34c-react-efc36acf9334-js-81d884f899eb Olm version: 3.2.8

### Homeserver

matrix.org

### Will you send logs?

Yes

**Comment by robintown** [comment]
The rageshake doesn't show Element doing anything obviously wrong, so this sounds like exclusively an issue on Jitsi's end, unfortunately.

The two things we *could* do to make this experience more reliable are:
- Update the meet.element.io Jitsi Meet deployment, in case the Jitsi team has since fixed this bug (→ https://github.com/matrix-org/matrix-ansible-private/issues/4811)
- Stop using Jitsi, and start using Element Call (we're working on it)

Closing this so we can focus on those more actionable points

**Comment by robintown** [comment]
Having investigated further, there's actually a way we can work around this
