### ISSUE TITLE
It is too easy to ignore a user by mistake (and too hard to discover what has happened when you ignore a user by mistake)

### ISSUE THREAD

**Issue by lampholder** [vector-im/element-web#22403]
### Your use case

A customer reported comedy/chaos on their installation resulting from some folks having ignored some other users by mistake.

- the _ignore_ feature is not easy to discover - the folks who had ignored people by mistake didn't even realise it was a product feature
- the member list includes users you have ignored, but it _doesn't_ highlight that you have ignored them - the folks who had ignored people by mistake checked the member list, but it didn't help them find the source of their problem
- there's no confirmation on the _ignore_ action
- replies to ignored users look strange without calling attention to the choice you have made that is causing the weirdness
- I'd argue that there's no real need for the _ignore_ feature on a corporate install - if you need to ignore somebody in a business situation it should probably be addressed via another route (though I could be wrong here - I'd be interested to hear other perspectives)

**Comment by BurnyBoi** [comment]
Agree that the ignore button is too easy to hit by accident (I've misclicked it instead of Invite at least once). Replies to an ignored user should just say the exact reason why the message isn't being shown. That being said. I want to say both corporate-focused messaging apps I've used for work (Skype for Business and Teams) have ignore features and it was never a problem for all the years it was a thing (never heard of anyone using it though)
