### ISSUE TITLE
Timestamps on bubble tiles in right panel chat on modern layout are in the wrong place

### ISSUE THREAD

**Issue by robintown** [vector-im/element-web#22425]
### Steps to reproduce

1. Create a video room
2. Open the chat
3. Expand the room creation event summary

#### What did you expect?

Timestamps on bubble tiles should be within the bounds of those tiles.

#### What happened instead?

They're positioned up and to the right of the tile:

![Screenshot 2022-06-02 at 11-13-39 Element Robin's video room 1](https://user-images.githubusercontent.com/48614497/171662327-a0905a96-bbc3-4068-a047-97fbee3088fc.png)

### Operating system

NixOS unstable

### Browser information

Firefox 100.0.2

### URL for webapp

develop.element.io

### Application version

Element version: 76c95352559d-react-a74b9a70836b-js-b64dbdce74b0 Olm version: 3.2.8

### Homeserver

Synapse 1.60.0

### Will you send logs?

No

**Comment by luixxiul** [comment]
It requires to style timestamp with declarations around [here](https://github.com/matrix-org/matrix-react-sdk/blob/d7642e52e90529e514422cafdeaa2d8b7ae9dc91/res/css/views/right_panel/_TimelineCard.scss#L88), which had not been worked quite well until recently before [this issue](https://github.com/vector-im/element-web/issues/21774) and therefore lacks sufficient declarations for the tiles on the *modern layout* yet (which is why I am not quite sure if it would be a regression due to recent activities on TimelineCard).

The style for the tiles should be able to be fairly easily implemented if it is fine to follow the style of tiles on the bubble layout. If not, design input would be required IMO.

**Comment by luixxiul** [comment]
On modern layout `mx_MessageTimestamp` is not included in `mx_EventTileBubble`, which I think is why the timestamp is not displayed in the same way as that of bubble layout.

**Comment by luixxiul** [comment]
If the style of the tile, `mx_EventTileBubble`, should follow the bubble message layout, the rules should be imported from `mx_EventBubbleTile`.

Despite being similar name, `mx_EventTileBubble` and `mx_EventBubbleTile` are totally different things.
