### ISSUE TITLE
Missing parts in the timeline

### ISSUE THREAD

**Issue by HarHarLinks** [vector-im/element-web#22603]
### Steps to reproduce

Not entirely clear how this happens yet, but I think this is a pretty severe issue.

1. Use Element Desktop for a day
2. Next day, use Element again, possibly from a different session like phone or another computer

#### What did you expect?
Timeline is complete

#### What happened instead?
Some messages are missing from the timeline, including some I sent myself from the same session.
Can be worked around be restarting Element.

### Operating system

arch, win 10

### Application version

Element Nightly version: 2022061501 Olm version: 3.2.8 (arch), stable 1.10.15 (win 10)

### How did you install the app?

aur, element.io

### Homeserver

synapse 1.60.0

### Will you send logs?

Yes

**Comment by HarHarLinks** [comment]
same with synapse 1.61.0

**Comment by lub** [comment]
I see the same with Synapse 1.59.1

It seems it also breaks the encryption, because after restarting Element I see the previously missing events in the timeline but only with "** Unable to decrypt: The sender's device has not sent us the keys for this message. **"

Messages sent while the timeline was incomplete also seem to be just lost after refreshing the website/restarting Element.

**Comment by HarHarLinks** [comment]
All but one room where I noticed that were encrypted and not federated, but I did not have any "Unable to decrypt" type of problem.

**Comment by HarHarLinks** [comment]
I haven't seen this in a while, maybe due to using only a single E desktop instance during this time. However I have been using E android (particularly the schildi fork), and my own messages tend to have gray shields despite being xsigned.
