### ISSUE TITLE
self-verification impossible with linux desktop, or android-app as well? simple user, longtime user on matrix.org

### ISSUE THREAD

**Issue by subscribernamegoeshere** [vector-im/element-web#22601]
### Steps to reproduce

1. Where are you starting? What can you see?
long time simple user on matrix.org server with riot chat (back then started there) now with element at present onl only two devices a linux desktop and android element from google playstore. My matrix.org account works fine (only username and credentials, no other stuff added) and I just recently added the linux desktop machine. all fine. I see my only other chatpartner on the network I can see our chat room, our previous messages, our inserted files, all good, no specialties or advanced stuff with encrypted chat or endtoend or all that just yet.  Back in riot-chat times I only had a machine at disposal where only the webform of riot-chat (on the riot.im domain) was available in a webbrowser, i was never able to use a desktop application for riot chat back then. But a stable webbrowser profile. Eventually support for the webbrowser/OS went away and gotton abandoned (i still have the webbrowser and its profile though, firefox) and I eventually switched over to android and riot (first I think) and after a while the upgrade to element via the google play store. So far so good. I think back in the old days there was not much of such concepts as verifications of sessions/machines and so on or I never took that path. now with the stable desktop machine I wanted to finish these steps. I also have only a chat/room with/to myself and a chat to another matrix participant. Thats all. Nothing fancy here. 

2. What do you click?
trying to verify my own two devices/sessions (odd naming difference in desktop and playstore app). On the desktop linux machine (running 1.10.15, x64) I see myself and the android device. The android device can only be renamed (no other buttons), my own desktop machine can be logged out, verified and renamed. Verify button clicked on this linux desktop machine, only brings up a smaller popup in element chat, telling me "verify this session", but complains that I dont have another device I can verify against or dont have security key. In order to do verification I would need to reset ( proceed reset: button) my verification keys. On the android google playstore element device (running 1.4.20) I see my own android session with red shield symbol and I can tap verify there, the short ID is the same as displayed on the linux device, and proceeding with verify on android only brings up a two symbol screen that I need to use latest element on desktop web ios or android, and only skip is available.  On the android device I see my other linux desktop session with a black shield symbol and I can sign it out or rename. Nothing else. Then I see several other very dated and ancient web sessions riot.im/app/...../.....  entries (also on linux). What is wrong here now and how can I settle this? Known bug?
3. More steps…
maybe related bug #21021  or something? https://github.com/vector-im/element-web/issues/21021 

I would also be glad to talk to some kind of customer support if this is too complicated or send over some funds or something? thanks for pointers.

### Operating system

android and linux x64

### Application version

element-app 1.4.20 and element-desktop 1.10.15

### How did you install the app?

google playstore and linux vendor build system

### Homeserver

matrix.org

### Will you send logs?

No

**Comment by duxovni** [comment]
If I understand correctly: you've set up these two new devices, on an old account, without verifying either of them; now neither of them are verified, and you don't have any other devices. I can't speak to the Android side of things, but the Web side is functioning as expected: if you don't have any verified devices or any key backups, then you need to reset your cross-signing keys as prompted by the verification dialog. Your Web client will then be verified under the new keys, and should be able to verify the Android client.

**Comment by subscribernamegoeshere** [comment]
thanks for answering, yes probably. only these "new" devices are alread kind of aged ;) the android element client was the only one I was using recently until i added the linux desktop one. before those I was only having the browser version still at the riot.im domain. So I only wanted to make sure that I dont lose any access to any of my chats, although as I said I had no explicit encryption enabled. So cross signing key means only like the own personality to begin with at a certain device from scratch and then add the second device of my own devices and then I am all fine? If I was able to recover one of my old web browser profiles and bounce that upgrade the browser to a supported one (newer os/newer browser version) and then I could start from there? would that be the better or cleaner way to do things? Or does it not matter at all? Thanks for helping I really appreciate it.

**Comment by duxovni** [comment]
Cross-signing keys belong to your account as a whole, not to any particular device; they're used to attest that a particular device really does belong to you, and to attest that you've verified other users' identities. When you create a brand new Matrix account, your first device generates cross-signing keys and signs itself with them, so your first device is always verified. That device can then verify other devices by signing them and giving them access to the private keys, allowing those devices to verify other devices as well.

If all of your verified devices have been logged out or lost, and you don't have key backups enabled, then your account's current cross-signing keys are effectively useless, because none of your devices are signed with them and nothing new can be signed with them. So resetting the cross-signing keys - generating new cross-signing keys for your account, and using those to sign the device that performed the reset - is really your only option. This won't cause any problems, you won't lose access to anything, and it's fine to just go ahead with it.

If the UI is directly telling you that your only option is to reset, then that means *none* of your devices are verified, even your old devices if you recovered those, so digging through old web browser sessions won't be any use. The key reset is harmless in this case and will make life easier in the future.

**Comment by duxovni** [comment]
(Closing this issue since there isn't an Element Web bug involved, but I can still answer questions here if this hasn't cleared things up.)
