### ISSUE TITLE
resize remote video whilst on a 1:1 video call

### ISSUE THREAD

**Issue by ara4n** [vector-im/element-web#2268]
or possibly even pop it out into its own popup.  this is entangled with coming up with a tiling UI for vector

**Comment by grinapo** [comment]
What is a **VC** in this context?

Anyway, allof these one-sentence 2016 dated tickets are unsearchable, so here's my duplicate description beefed with keywords.

Is there any process which actually keep these 4 years old open tickets in the top of the development decisions? Or are they buried forever in the grave of time, collecting duplicates?

## Problem
When doing one-to-one video calls the video area (which contains both my and the other party's image) is forced full width within the middle pane. Since its aspect ratio is fixed on a wide display it basically overlaps all the chat, making it impossible to see chat, especially if it contains image attachments.

## Advice
It would be extremely useful to be able to resize the video area independently of the pane geometry.

**Comment by t3chguy** [comment]
Video conference

**Comment by turt2live** [comment]
We'll call this the 1:1 one.

**Comment by SimonBrandner** [comment]
We seem to have this now
