### ISSUE TITLE
Double-click to edit a message

### ISSUE THREAD

**Issue by Merulox** [vector-im/element-web#22705]
#### What would you like to do?
Double click to edit a message.

#### Why would you like to do it?
Ease of use and workflow. It was the only reason I used a modified discord client back when I used discord.

#### How would you like to achieve it?
 By double-clicking anywhere on a message.

### Have you considered any alternatives?

A keyboard shortcut you can hit while hovering a message to edit it.

**Comment by Hugueprime** [comment]
The expected behavior of double clicking on a message is to select one word of this message (if hover it) or the whole message.

I don't really see the point of adding a shortcut to edit a message while hovering it as you would have your hand on the mouse (or touchpad) to hover the message and you will actually lose time (in my opinion) to go to your keyboard and use this shortcut.

Moreover (in my use case) I rarely edit an very old message and to edit a quite new message you could use the top arrow to edit the next message message you wrote.
