### ISSUE TITLE
in-app permalinks to non-pill rooms now take you to matrix.to rather than staying in-app

### ISSUE THREAD

**Issue by ara4n** [vector-im/element-web#22874]
in element-web on desktop, type a room alias like #twim:matrix.org without tab completing it into a pill. click on the link, and it takes you to matrix.to rather than taking you within the app straight to the room

**Comment by turt2live** [comment]
confirmed regression on staging, due to the work in https://github.com/matrix-org/matrix-react-sdk/pull/8394

Likely a similar fix to https://github.com/matrix-org/matrix-react-sdk/pull/8917, though this particular case seems non-trivial.

**Comment by Johennes** [comment]
Sorry for breaking this. I think / hope https://github.com/matrix-org/matrix-react-sdk/pull/9087 should fix it. It had nothing to do with the span actually.

Also, since this was labeled a release blocker and I was assigned, please note that the regressing change was a _spare time_ contribution so I'm handling this with my limited private life SLA.
