### ISSUE TITLE
Functional members (`io.element.functional_members`) is not considered when creating calls or (re)creating DMs.

### ISSUE THREAD

**Issue by Half-Shot** [vector-im/element-web#22894]
### Steps to reproduce

1. Start a call in a DM with more than two users, where a `io.element.functional_members` state event excludes all but 2 users in the room.
2. Notice that the call is a group call (Jitsi).

OR

1. Click "message" on a user where you already share a DM with that user, where the DM contains a `io.element.functional_members` state event excludes all but 2 users.
2. Notice that a new DM is created.

#### What did you expect?

In both cases, the DM behaviour to be observed rather than the group behaviour

#### What happened instead?

The group behaviour

### Operating system

Arch Linux / Wayland w/ Sway

### Browser information

Firefox 102

### URL for webapp

develop.element.io

### Application version

Element version: 1519d5672e4c-react-0053f21286e8-js-32bb4b1fc464 Olm version: 3.2.8

### Homeserver

Synapse 1.63.0

### Will you send logs?

No

**Comment by MadLittleMods** [comment]
@Half-Shot Is this a regression? Do you know if this worked as expected previously?

**Comment by karlabbott** [comment]
So I don't believe that this is a regression due to the fact that we haven't really had the adminbot and auditbot functionality in large use yet. By adding the 3rd member to the room (even though it's a bot and not a person), the room counts the membership as 3 instead of 2. This changes the behavior of the element app and we should seek to ignore bots in the counting of the room membership. I also disagree with the "uncommon" label and the "tolerable" label as just this morning, I was informed that for a particular on-premise customer, they do not have Jitsi configured and need to use the 1:1 functionality of Element and want to use the bots. Obviously, with this bug in place, they're environment will be unusable (hence why I disagree with Tolerable). Further, we simply haven't started to explore how much of an impact this will have on our potential customer base and hence why I disagree with Uncommon. It may be uncommon, but at this juncture, I'm running into this more and more each week.

I would consider this issue a high priority to address as this is impacting our ability to sell the auditbot and adminbot to on-premise customers.

**Comment by turt2live** [comment]
I've reprioritized this to match our triaging requirements. It's not to say the issue is less important, just to accurately weigh it against the other issues in the backlog.
