### ISSUE TITLE
A room with only private read receipt keeps being marked as unread.

### ISSUE THREAD

**Issue by ara4n** [vector-im/element-web#23027]
### Steps to reproduce

1. Turn on private RRs
2. Get DMed by a user
3. Answer the DM
4. Send some messages in the DM
5. Observe that the DM subsequently gets incorrectly flagged as unread (presumably because there is no RM or RR in the room at all, only a private RR?)

(appaprently the room where this was happening (!iKaweBjcahmPGZlkqW:thirdroom.dev) had a prefixed private RR in it: $OyTvOe_8mTpK_f_Lf9cLR63ZdyOvIGvCCQrGqBokXxg )

#### What did you expect?

Random DMs shouldn't keep appearing as unread.

### Application version

nightly

### How did you install the app?

nightly

### Homeserver

matrix.org

### Will you send logs?

No

**Comment by SimonBrandner** [comment]
It turns out this is an RR issue after all: I've just reproduced it by accident in my DM with Dave. The `Room::getEventReadUpTo()` method fails under certain conditions: if we don't have RRs of _all_ types, we fallback to using timestamps for the comparison, the problem then is that the ts comparison algorithm doesn't take into account the stable private read receipt not being defined, so it fails and we fallback again to picking by hand, this means the unstable private RR is chosen because it tends to have precednce even if there actually is a new RR of `m.read` type. 

This can now be considered a release blocker though a fairly simple one to fix and test
