### ISSUE TITLE
Clicking link in reply quote does nothing

### ISSUE THREAD

**Issue by HarHarLinks** [vector-im/element-web#23077]
### Steps to reproduce

1. bot sends message with a formatted link e.g. `"formatted_body": "<strong>Half-Shot</strong> opened a new PR <a href=\"https://github.com/matrix-org/matrix-hookshot/pull/443\">matrix-org/matrix-hookshot#443</a>: &quot;Fix markdown paragraphs not rendering properly&quot;",`
2. reply to it
3. try clicking the link in the reply quote

#### What did you expect?
opens in browser
#### What happened instead?
~nothing~
jumps to original event

### Operating system

arch

### Application version

Element Nightly version: 2022081501 Olm version: 3.2.12

### How did you install the app?

aur

### Will you send logs?

Yes

**Comment by t3chguy** [comment]
I can reproduce this on Desktop on macOS, just jumps to the replied to event
I cannot reproduce this on Web, opens in a new tab just fine

**Comment by Johennes** [comment]
That's possibly the issue. If the reply is right under the original message, then clicking the link inside the quote does nothing because the original message is already in view. I think we should make links in quotes clickable because otherwise, there's not much value in having them highlighted like normal links. We already do it like that for links in the room topic. Clicking the link in the topic opens it. Clicking any other non-linked text in the topic opens the topic dialog.

**Comment by Johennes** [comment]
Sorry in re-reading I'm realizing that I misunderstood you. I tested on `develop` and can reproduce this in neither Element Web nor Element Desktop. Assuming this is fixed.
