### ISSUE TITLE
Can't view my msgs, Element keeps asking for verfication

### ISSUE THREAD

**Issue by Jakolineuser** [vector-im/element-web#23099]
### Steps to reproduce

1- Open element web
2- login
3- Gets asked for verification via other sessions \(even if there is no other sessions\)
4- Can't see any of my msgs because: Unable to decrypt: The sender's device has not sent us the keys for this message
5- Open another session using another browser so you can verify
6- Still can't see any of my msgs because of the same reason

Why am I asked to verify via other sessions every time I login into the damn thing? VERIFY WHAT?

I DON'T HAVE OTHER SESSIONS

Why can't I view my older msgs? Are they lost?

### Outcome

Expected outcome: See my damn msgs without getting an error unable to decrypt

### Operating system

Debian

### Browser information

Firefox 91.10.0esr

### URL for webapp

app.element.io

### Application version

Element version: 1.11.3 Olm version: 3.2.12

### Homeserver

https://matrix-client.matrix.org

### Will you send logs?

No

**Comment by Jakolineuser** [comment]
Even after verifying, the pop-up is still there, that thing is stupidly designed and poor, why in the world is it asking for verification everytime?  Why do I have to create another session specifically to verify that damn thing?

And why can't I view my fu*king msgs?

**Comment by uhoreg** [comment]
The pop-up is a bit misleading, and there is planned work to improve it, but the issue here is that since messages are encrypted, Element needs to obtain a key to decrypt them.  The decryption keys are normally sent to each recipient by the message sender when the messages are sent, but if you log in, you won't have the keys for previously-sent messages.

The popup says to verify another session because if you have a previously-logged-in session (that has the decryption keys), then your new session can get the decryption keys from that other session, after you have verified it.  Obviously, that won't work if you log in another new session and verify against that, since that new session won't have the decryption keys either.

You could also get the decryption keys from the key backup, which is unlocked by the recovery passphrase that it should have prompted you for, or the recovery key that it should have created for you at some point.  Though this will only help with messages that were received when you were logged in to a session that was already connected to the key backup.  If you don't have the recovery passphrase or key, you can reset the key backup to create a new passphrase/key, but you will not be able to access any of the keys that were previously stored.

**Comment by Jakolineuser** [comment]
So you're basically saying that Element is useless. There should be a warning like:

"Please don't massage anyone because once you close the tab all msgs will be lost"

**Comment by Jakolineuser** [comment]
To Anyone reading this: Element can be ONLY USED to view channels, do not use it to communicate or message other users.

YOU WILL LOSE YOUR MESSAGES

**Comment by uhoreg** [comment]
Unless you are using a private browser window, or have an extension that removes stored data, you should not lose your messages simply by closing your tab, as you should remain logged in.  And unfortunately there is no way for Element to detect whether it is being run in a private browser window, otherwise we would display a warning about losing messages to users in that situation.

However, we are planning some improvements for people who use private browser windows.

**Comment by Jakolineuser** [comment]
And what happens when a user reinstall his system?

**Comment by uhoreg** [comment]
If you only have one session and you lose access to it, but it was connected to the key backup, then you should be able to use key backup to retrieve the decryption key for messages sent before that session was last active.  You will currently be unable to decrypt messages sent after that session was last active, but we are currently working on fixing that too (basically, the same fix for private browser windows also fixes this).

I've never used Signal, but my understanding was that if you reinstall, you lose any messages that were previously decrypted.  I think that you might be able to get messages that were sent but not yet received, but that relies on the original sender re-sending the message.  We are also investigating doing something similar.  But of course that depends on the original sender coming online at some point to re-send the message.

**Comment by Jakolineuser** [comment]
I don't use any browser add-ons that removes stored data. On Firefox I only use basic privacy add-ons such as "DuckDuckGo Privacy Essentials" and any ad-blocker

On Chrome (my other session) there are zero add-ons installed, none.

Everytime I visit (https://app.element.io/#/login) it prompts me to login instead of taking me directly to my active session, this behavior is wrong.

My Chrome session is old, yet I can't use it to view my recent msgs, if I click: 
"Re-request encreption keys from your other sessions", nothing happens

**Comment by t3chguy** [comment]
> Everytime I visit (https://app.element.io/#/login) it prompts me to login instead of taking me directly to my active session, this behavior is wrong.

Do you have your browser configured to delete or not store cookies? Quite often browsers & extensions will bundle other data storages in with "cookies". Might you be low on disk space where your browser is evicting stored data to fulfil quotas?

**Comment by G2G2G2G** [comment]
> To Anyone reading this: Element can be ONLY USED to view channels and rooms, do not use it to communicate or message with other users directly.
> 
> YOU WILL LOSE YOUR MESSAGES

@Jakolineuser this isn't true, only if you're deleting your browser session, don't have other devices, and are using E2EE.

You can avoid this by acting like a normal user and not do 1 of the 3 things above. I assume the easiest for your scenario would be not using E2EE since you're unwilling to fix your browser. There are no chats where you can recover messages while using E2EE if you logout and delete keys and sessions.. unless they aren't actually safe.

**Comment by richvdh** [comment]
Closing this as it seems to be due to the user's choice to drop all session data. That's kinda the point of end-to-end encryption.
