### ISSUE TITLE
Black unread dot is shown when global notifications are set to "None"

### ISSUE THREAD

**Issue by uranuspucksaxophone** [vector-im/element-web#23163]
### Steps to reproduce

1. Set global notifications to "Off/None" for group chats.
2. Go to a group chat and set notification type to "Global".
3. Take note that the unread dot is shown.

#### What did you expect?
No unread dot is displayed
#### What happened instead?
The unread dot is displayed

### Application version

Latest 1.11.2

### Homeserver

matrix.org

### Will you send logs?

Yes

**Comment by robintown** [comment]
This is expected behavior: in Matrix, notifications are an extra layer of functionality on top of the concept of unread messages. So, even if you are not receiving push notifications for a given room, Element will still inform you when it's unread. To fully hide the unread dot, you may mute individual rooms by setting their individual notification level to 'None'.
