### ISSUE TITLE
Device selection in EC video rooms doesn't always work

### ISSUE THREAD

**Issue by robintown** [vector-im/element-web#23331]

**Comment by turt2live** [comment]
Please define "doesn't work"

**Comment by dbkr** [comment]
The problem here is indeed that the browser is giving different device IDs for the same device between the different origins. Our best bet is probably to pass the device list over the postmessage API from EC -> EW so EW can present them to the user, although we'll need to prompt for user media permission before we can get the names of the devices - maybe we can show a "please accept permissions" screen in the preview like we do in element call. Previewing the input in EW is going to be an issue though: we'll have to match up the device names, which means we'll *also* need to prompt for user media permission on the element web origin if we don't already have it...

**Comment by dbkr** [comment]
As @robintown points out, if we're doing device name matching in EW to get the right preview, we may as well just pass the chosen devices over by device name rather than ID in the first place.
