### ISSUE TITLE
Wrong composer focused when hitting "escape"

### ISSUE THREAD

**Issue by gsouquet** [vector-im/element-web#23397]
### Steps to reproduce

1. Open an existing thread and click "reply" on one of the thread message
2. Hit the "escape" key to remove the reply preview

#### What did you expect?

I expect the reply to be dismissed and the focus to be on the threaded composer

#### What happened instead?

The reply is dismissed but the focus is moved to the room main composer

### Will you send logs?

No

**Comment by SoldierCorp** [comment]
Hi @gsouquet !

This is what I am currently seeing. After I pressed `Esc` the focus went into the main box message, but I am not following the expected behaviour. Could you please describe a little bit more the expected functionality?

I would like to work on this but I want to have a clear idea first. Thanks!

https://user-images.githubusercontent.com/1775881/193951977-013b969b-0861-4e5e-bb82-c00351fb3257.mov

**Comment by aaronraimist** [comment]
@SoldierCorp Instead of clicking on the "Reply" button there, click on the "Reply in thread" button to open the separate thread composer on the right side of the screen. Then click the "Reply" button on a message inside that thread view and you will be able to reproduce the issue.

**Comment by SoldierCorp** [comment]
> @SoldierCorp Instead of clicking on the "Reply" button there, click on the "Reply in thread" button to open the separate thread composer on the right side of the screen. Then click the "Reply" button on a message inside that thread view and you will be able to reproduce the issue.

Thanks!

This is what I am seeing. After I pressed `Esc`, the Thread section is not being dismissed but only the focus from the thread to the main box. From macOS.

https://user-images.githubusercontent.com/1775881/193954043-a698aba9-3c3a-4bad-8b19-0966d17a845c.mov
