### ISSUE TITLE
Matrix.to links in topic don't open in app, but redirect to website

### ISSUE THREAD

**Issue by kittykat** [vector-im/element-web#23395]
### Steps to reproduce

1. Add a matrix.to link (to a message in the same room) to a room topic (using markdown)
2. Click on the link

#### What did you expect?
Jump to message in the timeline

#### What happened instead?
The matrix.to page asking me to continue

### Browser information

Chromium 106.0.5249.61 (Official Build) Arch Linux (64-bit)

### URL for webapp

develop.element.io

### Application version

Element version: d8124d37e401-react-ff59f68a9fa0-js-4b283015bade Olm version: 3.2.12

### Will you send logs?

No

**Comment by bkil** [comment]
Same here. Also, if you mention rooms (spaces, users, etc.) textually within the room subject (i.e., `#room:hs.example`) , it similarly tries to take you to matrix.to instead of jumping to the mentioned entity. This is a regression - having worked correctly in the past.

The difference between linkified links in the topic and ones in the message body seems to be that the latter ones possess an `onclick` event handler pointing to https://github.com/matrix-org/matrix-react-sdk/blob/5398db21ad0a378fdf71b92b4aad05f01a8e39b8/src/linkify-matrix.ts#L182 while the former ones do not.

**Comment by jedahan** [comment]
#24994 not sure if this is a duplicate

**Comment by bkil** [comment]
Related: https://github.com/matrix-org/matrix-public-archive/issues/236 https://github.com/vector-im/hydrogen-web/issues/1104 https://github.com/matrix-org/matrix-static/issues/114
