### ISSUE TITLE
Profile picture overlaps with hover highlight

### ISSUE THREAD

**Issue by Nova-Aurora** [vector-im/element-web#23449]
### Steps to reproduce

1. Where are you starting? What can you see?
Go into any chatroom, hover over any message (my appearance settings are dark, modern UI, font size 15), and look at the UI elements.

#### What did you expect?
That the elements would not cross the highlighted background, due it being somewhat ugly.
#### What happened instead?
The Profile picture crosses the highlight, resulting in an ugly overlap, in addition, the actions menu overlaps for a few pixels, but it is less noticeable.
![image](https://user-images.githubusercontent.com/62871042/194736285-7f05c0c4-4915-4538-ad16-7b52ce1021a6.png)
![image](https://user-images.githubusercontent.com/62871042/194736314-e855a19c-c223-43a7-86f6-af34597eb5ac.png)
![image](https://user-images.githubusercontent.com/62871042/194736347-173af520-fb9c-4f6c-bdb3-1d0a84249f38.png)

Feel free to close this if this is intended behavior.

### Operating system

Linux

### Browser information

Firefox version 105.0.1

### URL for webapp

app.element.io

### Application version

Element version: 1.11.8 Olm version: 3.2.12

### Homeserver

matrix.org

### Will you send logs?

No

**Comment by MadLittleMods** [comment]
I assume you're talking about this little bit of overlap under the avatar with the background color of the highlight:

![](https://user-images.githubusercontent.com/558581/195445961-7c46aa65-2cd0-4a92-bda9-019fc11a817f.png)

To make it more obvious here it is with a purple background:

![](https://user-images.githubusercontent.com/558581/195446084-1dc58911-0c0e-4b0c-b4f2-f41a5032adab.png)




This doesn't seem like a problem though so I am going to close.




The real problem is when the timestamp is covered up, https://github.com/vector-im/element-web/issues/2284. A solution there would probably influence this.

A more exacerbated version of this is a `/me` message:

![](https://user-images.githubusercontent.com/558581/195446833-71d5f261-2de9-4a8d-ba90-d9776b9bd9a0.png)
