### ISSUE TITLE
Element error after long idle - `TypeError: can't access dead object`

### ISSUE THREAD

**Issue by haxwithaxe** [vector-im/element-web#23822]
### Steps to reproduce

This has happened before but I don't remember details so this describes this most recent occurrence only.

1. Where are you starting? What can you see?
I left Element alone in a background tab for at least 10 hours.

2. What do you click?
I only went back to the tab. I didn't click anything.

3. More steps…
N/A

#### What did you expect?
I expected to see the chat I had open before I left the tab.

#### What happened instead?

I got an Element error message `Something went wrong!` that occupied the entire page asking me to file a bug report. The "submit debug logs" button did nothing.

I checked the Firefox dev console and found the following errors:
* `Failed to set presence: TypeError: can't access dead object       rageshake.ts` - many many times
* `MatrixClient sync state => ERROR       rageshake.ts` - a few times

Let me know if there is anything I can do to provide debug log equivalent next time.

### Operating system

Debian Bullseye

### Browser information

102.5.0esr

### URL for webapp

element.mend.is

### Application version

Element version: 1.11.14 Olm version: 3.2.12

### Homeserver

Synapse v1.71.0

### Will you send logs?

Yes

**Comment by uhoreg** [comment]
> Let me know if there is anything I can do to provide debug log equivalent next time.

Next time, you can right-click on a message in the Firefox dev console, and select "Save all Messages to File", and then share the file somewhere.

**Comment by haxwithaxe** [comment]
It happened again. Here is the console output. Clicking the "Submit debug logs" button appears to do nothing still.
[console-export-2022-12-8_10-58-22.txt](https://github.com/vector-im/element-web/files/10187195/console-export-2022-12-8_10-58-22.txt)

**Comment by MadLittleMods** [comment]
@haxwithaxe I am guessing the following error is the culprit since it's the only React related thing that probably got caught in the [`Something went wrong!` error boundary](https://github.com/matrix-org/matrix-react-sdk/blob/2344eaab1c53b82b31721e5c8e36c723506734c4/src/components/views/elements/ErrorBoundary.tsx#L135). I can't de-obfuscate or find that exact `bundles/f504ecfab127c70b616f/` directory in our releases to suss it out.

```
AsyncWrapper promise failed TypeError: can't access dead object
    Dr https://element.mend.is/bundles/f504ecfab127c70b616f/vendors~init.js:2
    Br https://element.mend.is/bundles/f504ecfab127c70b616f/vendors~init.js:2
    ns https://element.mend.is/bundles/f504ecfab127c70b616f/vendors~init.js:2
    vA https://element.mend.is/bundles/f504ecfab127c70b616f/vendors~init.js:2
    IA https://element.mend.is/bundles/f504ecfab127c70b616f/vendors~init.js:2
    bA https://element.mend.is/bundles/f504ecfab127c70b616f/vendors~init.js:2
    _A https://element.mend.is/bundles/f504ecfab127c70b616f/vendors~init.js:2
    dA https://element.mend.is/bundles/f504ecfab127c70b616f/vendors~init.js:2
    Hi https://element.mend.is/bundles/f504ecfab127c70b616f/vendors~init.js:2
    unstable_runWithPriority https://element.mend.is/bundles/f504ecfab127c70b616f/vendors~init.js:2
    Pi https://element.mend.is/bundles/f504ecfab127c70b616f/vendors~init.js:2
    Hi https://element.mend.is/bundles/f504ecfab127c70b616f/vendors~init.js:2
    Yi https://element.mend.is/bundles/f504ecfab127c70b616f/vendors~init.js:2
    sA https://element.mend.is/bundles/f504ecfab127c70b616f/vendors~init.js:2
    enqueueSetState https://element.mend.is/bundles/f504ecfab127c70b616f/vendors~init.js:2
    setState https://element.mend.is/bundles/f504ecfab127c70b616f/vendors~init.js:2
    componentDidMount https://element.mend.is/bundles/f504ecfab127c70b616f/vendors~init.js:2
```

Not sure of the root cause though. The `TypeError: can't access dead object` error seems to be a Firefox thing when you hold onto something and try to use something that was already garbage collected. This persons quote summarizes my thoughts too:

> My understanding of the error is that some code is referencing a dead DOM object, and I can only read about that happening in the context of an extension. The stack trace does not mention any extension though, so if it is because of one, I'm unable to tell which.
>
> *-- https://github.com/mastodon/mastodon/issues/24052#issuecomment-1468127096*

You can find other applications running into the same problem searching for this problem on GitHub:

 - https://github.com/KaotoIO/kaoto-ui/issues/1439
 - https://github.com/fingerprintjs/fingerprintjs/issues/743#issuecomment-1042742978
 - [Other search results](https://github.com/search?q=can%27t+access+dead+object&type=issues)

This doesn't really feel like something we could fix. It's probably a Firefox problem. We've had one other person report this error to Element specifically, https://github.com/vector-im/element-web/issues/17901

---

These two similar errors I see in your logs wouldn't cause a total page crash with `Something went wrong!` as far as I can tell. Tested throwing a fake error in these areas.

Relevant code: [`src/http-api/utils.ts#L51`](https://github.com/matrix-org/matrix-js-sdk/blob/7f2a4c256852d285d2639472b49c3c65fa48e7f8/src/http-api/utils.ts#L51)
```
Failed to get TURN URIs TypeError: can't access dead object
    A utils.ts:51
    requestOtherUrl fetch.ts:256
    request fetch.ts:168
    authedRequest fetch.ts:148
    turnServer client.ts:6508
    checkTurnServers client.ts:6546
    checkTurnServersIntervalID client.ts:1184
```

```
Failed to set presence: TypeError: can't access dead object
    A utils.ts:51
    requestOtherUrl fetch.ts:256
    request fetch.ts:168
    authedRequest fetch.ts:148
    setPresence client.ts:5045
    setState Presence.ts:103
    a Presence.ts:80
    _invokeCallback Dispatcher.js:171
    dispatch Dispatcher.js:154
```

This one is a bit different but still doesn't crash the entire app with `Something went wrong!` if an error occurs there.

Relevant code: [`focus-visible` -> `focus-visible.js#L200`](https://github.com/WICG/focus-visible/blob/6501c9382d072014e0aa8a816064fc78ae07b36b/src/focus-visible.js#L200)
```
Uncaught TypeError: can't access dead object
    c focus-visible.js:207
    e focus-visible.js:196
```

---

As an aside, you should also fix this CORS issue with your homeserver. You just need to do as it says. Add the `Access-Control-Allow-Origin: *` header when serving the `https://mend.is/.well-known/matrix/client` file.

```
Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://mend.is/.well-known/matrix/client. (Reason: CORS header ‘Access-Control-Allow-Origin’ missing). Status code: 301.
```
