### ISSUE TITLE
Unread message/mention comes back after closing the browser and re-opening

### ISSUE THREAD

**Issue by MomentQYC** [vector-im/element-web#23847]
### Steps to reproduce

When a message is last sent by a contact with a mention/response after logging in or after closing the client/browser and reopening it, it will still show up as an unread messages even if the message was read before.

#### What did you expect?
Normal use.

#### What happened instead?
There is a problem with the display.

### Operating system

Ubuntu (Actually all clients have this problem)

### Browser information

Edge 107.0

### Application version

Element Web/Desktop 1.11.15 Element iOS 1.9.12

### Homeserver

Synapse 1.72.0

### Will you send logs?

No

**Comment by MadLittleMods** [comment]
@MomentQYC `matrix-js-sdk` only persists `/sync` data to IndexDB [every 5 minutes](https://github.com/matrix-org/matrix-js-sdk/blob/c3d7a4977afadb032867775120d0f571ee087b29/src/store/indexeddb.ts#L40) so it's possible you see the mention, close the app before 5 minutes has passed and when you open the app again, the app re-syncs and you see the notification again.

**Comment by MomentQYC** [comment]
> @MomentQYC `matrix-js-sdk` only persists `/sync` data to IndexDB [every 5 minutes](https://github.com/matrix-org/matrix-js-sdk/blob/c3d7a4977afadb032867775120d0f571ee087b29/src/store/indexeddb.ts#L40) so it's possible you see the mention, close the app before 5 minutes has passed and when you open the app again, the app re-syncs and you see the notification again.
> 
> 
> 
> Does this sound accurate to your scenario?
> 
> 

No.
This problem still occurs when reopening after a long period of time without closing.It is known that Desktop client and iOS client (Android client I have not tested) will also have the problem, and, for example, the problem will still occur when opening Element Web B when Element Web A is open for a long time.

**Comment by ThoreKr** [comment]
Not sure if this is related or a separate issue, but were observing very similar issues with Element Web/Desktop 1.11.15 and since updating to 1.11.14.

However, the issue is somewhat inverted, as the unread message notification count status (icon in the room list, favicon indicator) resets about every 5 minutes. It goes away when klicking at the room again, but other clients won't notice.

Synapse is version 1.72.0 as well. 

When opening the rooms in element android or with cinny, they are properly considered as read on all devices.
