### ISSUE TITLE
Restore from backup prompts for security key twice

### ISSUE THREAD

**Issue by germain-gg** [vector-im/element-web#23929]
### Steps to reproduce

1. Go to settings, click restore from backup
2. Enter your security key
3. Wait for all the keys to be fetched
4. See you're prompted to enter your security key again
5. Enter the same one as in step 2

#### What did you expect?

To not even be asked to enter my security key, as I already did it in step 2

#### What happened instead?

It asked me to enter my security key, and on top of that told me there was a mismatch...
But all the messages now seem to decrypt in the background, so i don't even know what this step is doing

### Operating system

*No response*

### Application version

*No response*

### How did you install the app?

*No response*

### Homeserver

*No response*

### Will you send logs?

No

**Comment by turt2live** [comment]
I suspect this is related to https://github.com/vector-im/element-web/issues/23931

**Comment by richvdh** [comment]
I wasn't able to reproduce this exactly as phrased: whenever I click on "Restore from backup", the key is already cached and it just tells me that it successfully restored the keys.

However I was able to reproduce something very similar as follows:

1. Start a new session
2. Do *not* verify the new device or enter the security key/phrase. Ignore the dire warnings and click "I'll verify later".
3. On the settings panel, click "Connect this session to Key Backup"
4. Enter your security key
5. Wait for all the keys to be fetched
6. See you're prompted to enter your security key again [Note: in this case it prompts for your *key*, implying the security *phrase* is insufficient

It turns out that if you skip over the prompt at step 6 then everything works fine.

I'll investigate this as part of my work in wiring up Key Backup in element R (https://github.com/vector-im/element-web/issues/24828)

**Comment by richvdh** [comment]
Closing this in favour of #26247
