### ISSUE TITLE
Stuck notification in thread

### ISSUE THREAD

**Issue by robintown** [vector-im/element-web#23921]
### Steps to reproduce

Unclear, but this is what happened:

1. Go offline
2. Have someone start a thread in a room where you receive notifications, and then edit their threaded message
3. Go online
4. Open the thread

#### What did you expect?

The notification count should go down from 2 to 0

#### What happened instead?

The notification count went down from 2 to 1, and the thread remained marked as unread in the thread list. Restarting the client was necessary to clear the notification.

### Operating system

NixOS unstable

### Browser information

Firefox 107.0.1

### URL for webapp

develop.element.io

### Application version

Element version: c473cb6e773f-react-9914b0bafd23-js-ccab6985ad55 Olm version: 3.2.12

### Homeserver

Synapse 1.72.0

### Will you send logs?

No

**Comment by gaelgatelement** [comment]
I reproduced this issue in the Delight room.

The room shield appears as red.

The notification counter appeared as grey. Selecting the thread did not reset the counter. 

When talking into the room, it seems that the notification disappeared.

**Comment by t3chguy** [comment]
One cause of this is when the edit event is the latest thing in the unread thread, I wonder if the load-thread-from-server API doesn't include the edit event and thus it not being in the timeline results in the RR being set on the wrong event (the original event ID rather than the ID of the edit event)

![image](https://user-images.githubusercontent.com/2403652/208697603-847e8ce2-ae61-432e-b06a-fa03eb686de0.png)

I have show hidden events enabled.

Given how frequent edits are, this will be happening whenever the latest event in a thread is an edit. And entirely destroys productivity by wedging an unread dot on the space, the room and the thread in the room list.

![image](https://user-images.githubusercontent.com/2403652/208697822-b3d9ebf1-828a-4978-8fcb-72c80643d7d6.png)
![image](https://user-images.githubusercontent.com/2403652/208697841-854d954e-3d9e-46e6-8b15-99f2a949cb83.png)
<img width="66" alt="image" src="https://user-images.githubusercontent.com/2403652/208697867-73aa85f7-d1b0-4aef-a39b-e07d9bbefee7.png">

**Comment by t3chguy** [comment]
The client seemingly has no way to know the real latest event id in the thread as the server doesn't give it a total order list of all the events, only the 1st-order related events (thread responses), edits and other 2nd-order relations are bundled inside the 1st-order relations' unsigned fields.

**Comment by gsouquet** [comment]
This has been regressed by https://github.com/matrix-org/matrix-js-sdk/pull/2856 

The `canContain` function in `addEventToTimeline` calls `eventShoudLiveIn`, and it does not figure out the `threadId`. It then incorrectly filters out the `m.replace` event...

**Comment by t3chguy** [comment]
@gsouquet does that apply for threads entirely loaded from the server? I doubt the full m.replace event will be received in those cases
