### ISSUE TITLE
Linux Mint: crashes all the time

### ISSUE THREAD

**Issue by et-the-extra-terrestrial** [vector-im/element-web#23944]
### Steps to reproduce

1. Where are you starting? What can you see?

I open the app.

3. What do you click?

I don't do anything.

5. More steps…
After around 30 seconds of being opened, it crashes.

#### What did you expect?

Expect the app not to crash and stay open.

#### What happened instead?

It crashes and shuts down.

### Operating system

Linux Mint

### Application version

1.11.16

### How did you install the app?

Software center

### Will you send logs?

No

**Comment by michel-slm** [comment]
It keeps crashing on Fedora 37 too (installed from Flatpak). I have not used this laptop for a few days and it used to be stable before that.

**Comment by t3chguy** [comment]
Please report issues with the Flatpak to https://github.com/flathub/im.riot.Riot/ - it is community maintained

Maybe https://github.com/flathub/im.riot.Riot/issues/309 or https://github.com/flathub/im.riot.Riot/issues/280

**Comment by andrewschott** [comment]
The fix for me was disabling the search indexing.  Not sure which file to edit, but its in the Security & Privacy tab.  You need to get at it before the client crashes.  

Hth.  Took me a few days to figure out.  Both my flatpak and rpm installs were doing this.  Web GUI I have on my webserver does not, as it does not support this feature.

![image](https://user-images.githubusercontent.com/14102747/208304751-73d9f07b-cc3d-4414-8602-2f6b73d7b0d2.png)
