### ISSUE TITLE
Access token overflows the box

### ISSUE THREAD

**Issue by waclaw66** [vector-im/element-web#24023]
### Steps to reproduce

1. Go to Settings / Help
2. Expand access token
3. See the old token overflowing the box
![obrazek](https://user-images.githubusercontent.com/15554561/207857781-713e41e7-66e6-45c8-bee9-0d32da1ee110.png)

#### What did you expect?
Access token wrapped to the box.

#### What happened instead?
Access token outside the box.

### Operating system

Windows 10

### Browser information

Firefox 108.0

### URL for webapp

self hosted

### Application version

Element version: 1.11.17-rc.1 Olm version: 3.2.12

### Homeserver

self hosted Synapse 1.73.0

### Will you send logs?

No

**Comment by aushwin** [comment]
Hi @waclaw66 is this issue fixed ?

**Comment by hasthik** [comment]
it looks like it is fixed!!

**Comment by AFZL210** [comment]
@aushwin yes its fixed now

**Comment by waclaw66** [comment]
@aushwin Cannot confirm, I have no longer that session available. I was forced to re-login due to another errors.

**Comment by t3chguy** [comment]
Still overflows for me.

**Comment by t3chguy** [comment]
@sbjaj33 I suggest waiting for one of the assigned reviewers to get to it, shouldn't be long

**Comment by sbjaj33** [comment]
Oh Okay, Thanks! @t3chguy

**Comment by Adesh-Pandey** [comment]
It still does occur. I found a solution to solve this. Although it is being worked on, I feel the approach could be more simpler. 
The only problem is, I cannot run all the tests on my local machine with 4gb ram it gives up instantly as matrix has a lot of tests. On the live sample of element web it works phenomenally. Would you suggest me anything @t3chguy

**Comment by Adesh-Pandey** [comment]
Anytime i am adding a component (div, span, section), I am failing a lot of test why is it so?

**Comment by t3chguy** [comment]
Tests might need updating, given you are making changes.

**Comment by Adesh-Pandey** [comment]
I found the issue. When I add a div I fail test as I think the tests are designed for the particular layout. When ever i modify css it does not create any failure . But it is not possible to solve this issue without changing the structure (adding a simple small div to wrap the access token ). Either the token should have definite character so that it never overflows (syt_43_character), or to add a new div so that the copy button is not compromised.
![component before any change](https://user-images.githubusercontent.com/75557670/220241730-242eb9a7-0bae-4f17-8da1-519d8c4350a5.png)
![after change](https://user-images.githubusercontent.com/75557670/220241757-08dbde31-c05e-4ad2-b4fa-4fefc58049e3.png)
![CSS chnage](https://user-images.githubusercontent.com/75557670/220241770-2ee2eba0-380a-4cda-8c1f-6b4ac3eefb26.png)
![issue in site](https://user-images.githubusercontent.com/75557670/220241806-8c650790-e6e3-4f54-a653-8cdd5c1a93e4.png)
![visible issue after resolved](https://user-images.githubusercontent.com/75557670/220241833-efe837fe-9736-420d-aa58-8c9afacc205b.png)
