### ISSUE TITLE
E2E devices may lull users into a false sense of security in the face of cloned devices

### ISSUE THREAD

**Issue by ara4n** [vector-im/element-web#2413]
By making an effort to model each device separately and applying verification/blocking per-device, we are ignoring attacks where someone clones a device by stealing all its key data.  I wonder if we are lulling people into a somewhat false sense of security there, compared to models where there is one identity key that is trusted across an opaque set of devices...

**Comment by ara4n** [comment]
@richvdh is this actually a valid concern? does Olm somehow stop cloned devices (i.e. where someone has taken a copy of the full local state of the client), given there will be some kind of race the next time the Olm DH ratchet advances?

**Comment by Zenexer** [comment]
Can technologies such as TPM reasonably be used to mitigate this issue, at least on some platforms?  Chrome OS does make extensive use of TPM.  For example, [the documentation on Chrome OS TPM usage](https://www.chromium.org/developers/design-documents/tpm-usage#TOC-Protecting-Certain-User-RSA-Keys) says:

> Also, any keys generated using the Webkit ‘keygen’ tag will use the TPM-backed token by default.

At the same time, [MDN says that the tag is deprecated](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/keygen), including in Chrome 49+.  The currently favored alternative seems to be using [SubtleCrypto.generateKey()](https://developer.mozilla.org/en-US/docs/Web/API/SubtleCrypto/generateKey).  You can check [CryptoKey.extractable](https://developer.mozilla.org/en-US/docs/Web/API/CryptoKey/extractable) to ensure that the key actually resides within TPM.

**Comment by richvdh** [comment]
> @richvdh is this actually a valid concern? does Olm somehow stop cloned devices (i.e. where someone has taken a copy of the full local state of the client), given there will be some kind of race the next time the Olm DH ratchet advances?

Yes, Olm should repair itself. If Bob's device is cloned, the next time Bob sends an Olm message, the attacker will get left out of the conversation. (Of course, if the attacker can send a message making it look like Bob is sending it, Bob gets left out of the conversation, which is problematic.) 

Megolm, of course, does not repair itself in this way; once Bob's device is cloned, the attacker can read everything Bob can until the next Megolm session starts. One more reason to make sure we replace megolm sessions semi-regularly.

In any case, I'm not sure how we are lulling users into any more of a false sense of security than we would be with a single signing key across all devices.

**Comment by richvdh** [comment]
> Can technologies such as TPM reasonably be used to mitigate this issue, at least on some platforms? 

As in, reduce the likelihood of a device being cloned in the first place? Sure, and at some point we will investigate how to make better use of the TPM. That's some way off at the moment, however.

**Comment by richvdh** [comment]
@ara4n: I don't feel this bug is particularly actionable. Can we close it?

**Comment by ara4n** [comment]
i opened it more for discussion (and to gather useful stuff like @zenexer's comment); can we let the convo play out first?

The reason I feel that it lulls users more into a false sense of security than a shared ID key is because in the UX we make a big deal of saying "with Matrix who you know who are talking to! verify the device!", implying that somehow the device itself has been uniquely verified. Whereas on a traditional ID key based e2e system like Signal or whatever, common sense says that whilst a user controls the ID key at the point they are verified, the key may be stolen.

I suspect we can mitigate this in the verification verbiage: "NB that verifying a device does not protect from an attacker cloning the device" or whatever.

Seperately, should we not have a mechanism that warns the user if someone has cloned their device (and to let them be the one to reclaim control of their Olm sessions, rather than risk being hijacked by the attacker in the manner you suggest?)

**Comment by spacekitteh** [comment]
I think the key should depend on items such as hardware serial numbers, IMEIs, USSIDs, IMSIs, and MSISDN. Of course, such items should never be transmitted; at most only a hash of them. 

An example might be a user's encryption key being xor'd with the hash of various hardware identifiers (no idea if that's cryptographically secure or not, but I suspect it might be?). Alternatively, it might be used as a salt.

**Comment by Zenexer** [comment]
@spacekitteh An attacker with access to the key also likely has access to hardware identifier, so that's unlikely to have any security benefit.  Generally, anything you can read has no benefit beyond the threshold we're looking to cross here.  You need a write-only crypto device.  Here's how they typically work:

1. Ideally, keys are generated on the secure device (smartcard, etc.).  In some cases it may also be acceptable to generate keys on insecure hardware (such as a CPU), write them to the secure device, and immediately erase them from the insecure device.
2. The secure device is write-only, meaning that once the keys are generated/written, they can never be retrieved.
3. All cryptographic operations requiring use of the keys must be performed on the secure device.
4. The secure device has a "secure element" that will fry its internals if physically tempered with, erasing the keys.

In a traditional approach, you might see a secure device used to encrypt an AES key with RSA.  In order to retrieve the AES key, the secure device has to be physically present; however, once it's retrieved, software on an insecure device can perform encryption without going through the secure device.  The software must then handle the AES key very carefully by protecting its memory and avoiding writing it to disk, although there's always the possibility of malware reading it somehow.

In an ideal approach, the AES key is stored on the secure device, either in place of the RSA key or alongside it.  This requires that all cryptographic operations continue to go through the secure device, which may not be practical or widely supported.

The key differences between RSA and AES here are:

1. AES is symmetric, while RSA is asymmetric.
2. AES is more commonly used to encrypt arbitrarily large amounts of data, while RSA is more often used to encrypt a fixed-size payload (such as an AES key).

Even with the less secure approach whereby the AES key is transferred to the software, the secure device must still be consulted for signing and authentication, as RSA would be used for that over AES.  Therefore, someone able to read the AES key from memory would be able to decrypt communications, but not authenticate as the user or produce signed messages.

**Comment by dbkr** [comment]
Since the convo has had nearly 4 years to play out, I'm going to venture forth & close this.
