### ISSUE TITLE
> 5.500 sync requests after login

### ISSUE THREAD

**Issue by weeman1337** [vector-im/element-web#24167]
### Steps to reproduce

1. Have an active session (~ 150 rooms / DMs) and the client open
2. Login in with another app/browser
3. Wait for initial loader to disappear
4. Choose verify with other session
5. Verify
6. Look at the network log

#### What did you expect?

A number of initial requests. Then „normal sync requests“.

#### What happened instead?

Large number of requests happening in a short time.
Had to stop after 5.666 requests because the log crashed.
Requests continue after reloading.

From the logs I can read, that the existing session is sending key requests

Sending logs from both sessions

### Operating system

Ubuntu 22.04.1 LTS

### Browser information

Firefox 108.0.1

### URL for webapp

https://app.element.io/

### Application version

Version von Element: 1.11.17 Version von Olm: 3.2.12

### Homeserver

element.ems.host

### Will you send logs?

Yes

**Comment by richvdh** [comment]
This was caused by https://github.com/matrix-org/matrix-js-sdk/pull/2921, and fixed by matrix-org/matrix-js-sdk#3029. It's worth noting that, by the time you've been bitten by that issue, it has already done its damage, and the affected client has already re-queued hundreds of thousands of key-share requests; upgrading to a version of element-web with the fix won't do much - you just have to wait for all the requests to work their way through the system :(.
