### ISSUE TITLE
"Mark as read" doesn't take into account thread activity

### ISSUE THREAD

**Issue by clokep** [vector-im/element-web#24229]
### Steps to reproduce

1. Have a room that has threads unread (but the main timeline is completely read).
2. Decide you don't care about catching up on that room.
3. Right click and try to mark as read:

![image](https://user-images.githubusercontent.com/517124/212333155-58899fea-946d-42a7-ae52-846c17df9215.png)

#### What did you expect?

There's a mark as read option.

#### What happened instead?

There's no mark as read option.

### Operating system

macOS

### Application version

Element Nightly version: 2023011301 Olm version: 3.2.12

### How did you install the app?

:shrug:

### Homeserver

matrix.org

### Will you send logs?

No

**Comment by clokep** [comment]
@gsouquet Any idea if this would be easy to fix? I wonder if we're only checking unread counts instead of room activity?

**Comment by clarkf** [comment]
I think this isn't too bad.

The problem seems to be that room state is computed differently [for the notification badge](https://github.com/matrix-org/matrix-react-sdk/blob/a63da74f06c923117465666f41f4cbf820c2af3c/src/stores/notifications/RoomNotificationState.ts#L112-L170) and [for the 'hide unread' button](https://github.com/matrix-org/matrix-react-sdk/blob/a63da74f06c923117465666f41f4cbf820c2af3c/src/hooks/useUnreadNotifications.ts#L55-L90). They function similarly, but produce subtly different results. The result is the sidebar believing that a room has unreads, while the context menu believes you're all caught up.

I'm going to take a stab at this one.

**Comment by jplatte** [comment]
Same problem here today. I have the Mark Read context menu item, but it doesn't do anything.

Notifications debug
Raum-ID: !muWFoAazesOnQSqwHZ:matrix.org
Raumstatus
- Room unread status: Fett
- Notification state is mentions_only
- Room is encrypted ✅
Hauptverlauf
- Insgesamt: 0
- Höhepunkt: 0
- Punkt: false
Thread-Verlauf
- Thread-ID: $03U_BYqB9U4jnIsSsC7UHloXcGNB_LeDYDqUw2d6BMA
  - Insgesamt: 0
  - Höhepunkt: 0
  - Punkt: true
  - Der Benutzer hat gelesen bis: Keine Bestätigung gefunden
  - Neuestes Ereignis:
    - ID: $wdz2_cAvf7KEZMkPxufLeOmmXmA-SJImMj5_pmsHqh4
    - Typ: m.room.message
    - Absender: @mauro.romito:element.io

(not sure why this devtools thing is translated...)

**Comment by t3chguy** [comment]
Looks like this is due to us implementing unread_thread_notifications not according to the spec

![image](https://github.com/vector-im/element-web/assets/2403652/693b326e-b621-42d3-9a78-fcc1e654e23a)
![image](https://github.com/vector-im/element-web/assets/2403652/d7468341-f0ea-4077-8b38-df1f4aa710c7)

**Comment by t3chguy** [comment]
This looks like it is due to `Unread::doesRoomOrThreadHaveUnreadMessages` having to way to factor in unthreaded read receipts, given those cannot be associated into thread timelines by clients.
