### ISSUE TITLE
Element has memory leak (previous report was deleted)

### ISSUE THREAD

**Issue by JeanPaulLucien** [vector-im/element-web#24236]
### Steps to reproduce

1. Use various Element Desktop features.

#### What did you expect?
Element is not computing powers and electric energy vamp. Freedom of speech, use nickname "Element has memory leak".

#### What happened instead?
Element is computing powers and electric energy vamp. Banned in everyone Matrix and Element rooms and spaces for nick with reason "Help vamp".
![Element memory leak 2023](https://user-images.githubusercontent.com/24779886/212490876-3036c72f-5e59-46d2-81da-6fce85756774.jpg)

### Application version

1.11.17

### Will you send logs?

No

**Comment by dbkr** [comment]
Have you found any specific things that cause the memory leak? This doesn't really contain much that we could use to investigate. https://github.com/vector-im/element-web/issues/24237 is an example of a great, actionable bug report (perhaps this is the bug you're experiencing?)

**Comment by clarkf** [comment]
While looking into something completely unrelated, I noticed a stray `console.error` from React:

```
Warning: Can't perform a React state update on an unmounted component. This is
a no-op, but it indicates a memory leak in your application. To fix, cancel
all subscriptions and asynchronous tasks in the componentWillUnmount method.
RoomView@webpack-internal:///2010:321:5
```

I have no idea how to interpret that line number (thanks, webpack!), but I *think* it has something to do with one of the many [subscriptions created in the constructor](https://github.com/matrix-org/matrix-react-sdk/blob/a63da74f06c923117465666f41f4cbf820c2af3c/src/components/structures/RoomView.tsx#L422-L470) firing before the component is fully mounted.

I seem to recall that effectful stuff isn't supposed to happen in constructors, since React makes no guarantees about `componentWillUnmount` being called unless `componentDidMount` was called. In theory, React could created new instances of `RoomView` and never mount them, hence the leak.

This pattern seems to be somewhat common, e.g:
* [`<MessagePanel />`](https://github.com/matrix-org/matrix-react-sdk/blob/a63da74f06c923117465666f41f4cbf820c2af3c/src/components/structures/MessagePanel.tsx#L292-L296)
* [`<ThreadView />`](https://github.com/matrix-org/matrix-react-sdk/blob/a63da74f06c923117465666f41f4cbf820c2af3c/src/components/structures/ThreadView.tsx#L102-L104)
* [`<DateSeparator />`](https://github.com/matrix-org/matrix-react-sdk/blob/a63da74f06c923117465666f41f4cbf820c2af3c/src/components/views/messages/DateSeparator.tsx#L66-L72)

No idea if this is *the* leak, but cleaning these up couldn't hurt. Worth a PR?

**Comment by t3chguy** [comment]
> but cleaning these up couldn't hurt. Worth a PR?

Sure, always appreciated!

**Comment by JeanPaulLucien** [comment]
> Windows 7 is no longer a supported environment - https://github.com/vector-im/element-web#supported-environments
