### ISSUE TITLE
Chat export contains an '[object Promise] ' after every line.

### ISSUE THREAD

**Issue by neilisfragile** [vector-im/element-web#24272]
### Steps to reproduce

Export a room chat
Open it up
After everyline of chat there is a new line with '[object Promise]' every line

#### What did you expect?
[object Promise] is spurious and should be not be visible. 

### Operating system

macOS

### Application version

Element Nightly version: 2023011701 Olm version: 3.2.12

### Homeserver

matrix.org

### Will you send logs?

Yes

**Comment by Abhijrathod** [comment]
In order to troubleshoot this issue, it would be helpful to have access to the logs from your browser and the Element webapp. You can send these logs to the developers of Element by following these steps:

Open the browser developer console by pressing F12 or Cmd + Opt + I on Mac.
Reproduce the issue by exporting the chat room and observing the "[object Promise]" lines.
Take a screenshot of the console and send it to the Element developers.
Also send them the chat export file and the version of the Element and Olm.

**Comment by neilisfragile** [comment]
@Abhijrathod as per the report, I submitted logs at the time.

**Comment by clarkf** [comment]
Opened a PR to fix this.

Looks like this issue was introduced in https://github.com/matrix-org/matrix-react-sdk/commit/030b7e90bf8ba09648f539dd378c0909f8773f86, so it wasn't ever released.

Only the HTML export was affected, but pretty much every HTML export should've contained `[object Promise]`.
