### ISSUE TITLE
Incorrect note displayed on room creation

### ISSUE THREAD

**Issue by NeoTones** [vector-im/element-web#24277]
### Steps to reproduce

Create a new room which is set to private and encrypted.
"disable_guests": true, set in config.json

#### What did you expect?

I expect the shown notes on room creation to reflect that guests are not allowed.

#### What happened instead?

On room creation the following notes are displayed in room:
 ```
name joined the room
name made the room invite only.
name made future room history visible to all room members.
name has allowed guests to join the room.
```

### Operating system

Ubuntu 20

### Browser information

Version 108.0.5359.126 (Official Build) (64-bit)

### URL for webapp

1.11.19

### Application version

1.11.19

### Homeserver

Synapse 1.75.0+focal1

### Will you send logs?

No

**Comment by weeman1337** [comment]
Thanks for reporting the issue @NeoTones . The [config setting `disable_guests`](https://github.com/vector-im/element-web/blob/develop/docs/config.md#customisation--branding) does something else.

If you want to disable guest access for your home server, you should check whether this is supported there (e.g. [synapse](https://matrix-org.github.io/synapse/latest/usage/configuration/config_documentation.html#allow_guest_access)).

For the „has allowed guests to join…“ message, this issue exists: https://github.com/vector-im/element-web/issues/9121

I am closing this issue now. If you think your problem is different, please leave a comment.
