### ISSUE TITLE
Incorrect message scaling for verification request when information side panel is opened

### ISSUE THREAD

**Issue by eNkKVS4HxHc9jaq** [vector-im/element-web#24304]
### Steps to reproduce

1. Where are you starting? What can you see?
I'm in a chat and the other user sent me a verification request. On the desktop version of the client, when opening the information from the Info icon, the message is scaled to an unreadable state when aligned vertically in a single column.
2. What do you click?
The Info icon for the side panel.
4. More steps…

#### What did you expect?
The message to normally be scaled.
#### What happened instead?
The message was scaled in a single vertical column to become unreadable when the side panel was open.

### Operating system

Windows

### Application version

Element version: 1.11.20 Olm version: 3.2.12

### How did you install the app?

https://element.io/get-started
![Capture](https://user-images.githubusercontent.com/71072643/214179700-30975d30-96f7-4af4-9e35-b64f0a9c31c3.png)

### Homeserver

matrix.org

### Will you send logs?

No

**Comment by KartikSingh023** [comment]
Can someone please elaborate more on this issue

**Comment by Sanket-777** [comment]
Any tips how can i solve this issue ?

**Comment by 456535688765** [comment]
please assign me this issue

**Comment by varunlmxd** [comment]
I am interested in taking up this issue, can you please assign me this issue?

**Comment by t3chguy** [comment]
@varunlmxd sorry no as per https://github.com/vector-im/element-meta/wiki/Guidance-on-assigning-issues#for-external-contributors-and-potential-interns

**Comment by GH-aditya** [comment]
Assign me this issue

**Comment by t3chguy** [comment]
@GH-aditya read my comment above.

**Comment by ABHIXIT2** [comment]
This issue is I think has the same problem
Issue#24183:https://github.com/vector-im/element-web/issues/24183
I don't think our site is really responsive, I mean some features work but not others
![cba7df89-7c69-49f7-8bc6-3abd45ee4638](https://user-images.githubusercontent.com/114552982/222525971-c80b6402-cc59-4b2b-b377-98d57e6edf21.jpg)
what i have gathered is that this(responsiveness) is causing this problem when we change the size of the window.
So can anyone please comment on it what they think .
**I am thinking of working on it like making the website responsive(work on pre-exsisting features) but I desperately need a Mentor who knows the whole system well and can help me and guide me.
@t3chguy @SimonBrandner

**Comment by luixxiul** [comment]
> I am working on it by making the website responsive

Since [hydrogen](https://github.com/vector-im/hydrogen-web/#goals) pursuits implementing mobile browser support, I think it is not great idea to try to fix this issue by making the website (UI?) responsive.

**Comment by ABHIXIT2** [comment]
> > I am working on it by making the website responsive
> 
> Since [hydrogen](https://github.com/vector-im/hydrogen-web/#goals) pursuits implementing mobile browser support, I think it is not great idea to try to fix this issue by making the website (UI?) responsive.

Thanks for replying I wasn't sure about that either that's why I thought of consulting.
I think we can make some changes in CSS? what do you think?

**Comment by GithubUser96** [comment]
> > I am working on it by making the website responsive
> 
> Since [hydrogen](https://github.com/vector-im/hydrogen-web/#goals) pursuits implementing mobile browser support, I think it is not great idea to try to fix this issue by making the website (UI?) responsive.

As far as I know, Hydrogen is a completely separate lightweight version of Element Web. It is not a replacement for the standard. Making the UI responsive is the actual solution. Also I believe Hydrogen is a fork and so responsivness of the base should easily be implementable in Hydrogen as well. Furthermore making this issue worth fixing.

**Comment by luixxiul** [comment]
My comment is directed to https://github.com/vector-im/element-web/issues/24304#issuecomment-1452420086, which seems to claim to solve the issue by making the whole UI (`website`) responsive, which is actually not pursued.

I agree that the issue can be fixed by making UI component responsive, and I've fixed some similar issues by doing so.

**Comment by ABHIXIT2** [comment]
> My comment is directed to https://github.com/vector-im/element-web/issues/24304#issuecomment-1452420086, which seems to claim to solve the issue by making the whole UI (`website`) responsive, which is actually not pursued.
> 
> I agree that the issue can be fixed by making UI component responsive, and I've fixed some similar issues by doing so.

By website I meant Element-web's website only. Please mention which similar issue you solved, It might help.
If you all think we should opt for this approach please explain a little bit about what should be the solution implementation.

**Comment by ABHIXIT2** [comment]
I was searching for solution and I found potential solution on gmail website.
I am not putting any screen recording due to privacy reasons.
Ways to Produce:
1)Open the gamil.com in a smaller window rather than fullscreen window.
2) Try to decrease the size of the window vertically and horisontally lesser than half of your screen size.

What you will notice:
The size of the content is not decreasing after a certain point it becomes static which actually doesn't look that bad.
Considering the fact that our website is used to connect through messaging and calls we actually implemant this because too small window wouldn't help any way.

Please give your opinions and also I think it's an very imporatant issue.
**I have seen half a dozen issues related to this issue**
