### ISSUE TITLE
Jitsi server preference not respected

### ISSUE THREAD

**Issue by lu-ka** [vector-im/element-web#24314]
### Steps to reproduce

With the guide form https://github.com/vector-im/element-web/blob/develop/docs/jitsi.md I've tried setting things up that Element Desktop uses my own Jitsi server instead of meet.element.io. I've tried both `~/.config/Element/config.json` as well as `matrix.DOMAIN.TLD/.well-known/matrix/client`, both with no success. Depending on which source you look at sometimes its `preferred_domain`, sometimes `preferredDomain` ,  sometimes `jitsi` and sometimes `im.vector.riot.jitsi`. I've tried all combinations with no success.

~/.config/Element/config.json
```json
{
    "jitsi": {
        "preferredDomain": "meet.DOMAIN.TLD",
        "preferred_domain": "meet.DOMAIN.TLD"
    },
    "im.vector.riot.jitsi": {
        "preferredDomain": "meet.DOMAIN.TLD",
        "preferred_domain": "meet.DOMAIN.TLD"
    }
}
```

from my nginx configuration on my homeserver
```
...
        location /.well-known/matrix/client {
                default_type application/json;
                add_header Access-Control-Allow-Origin *;
                return 200 '{ "m.homeserver": { "base_url": "https://matrix.DOMAIN.TLD" }, "jitsi": { "preferred_domain": "meet.DOMAIN.TLD", "preferredDomain": "meet.DOMAIN.TLD"}, "im.vector.riot.jitsi": { "preferred_domain": "meet.DOMAIN.TLD", "preferredDomain": "meet.DOMAIN.TLD"}}';
        }
...
```

I'm checking where the requests go to via the Dev Tools inside the Element desktop client.

Edited:
I found out that if you used Flatpak to install the client, the config file is at `~/.var/app/im.riot.Riot/config/Element/config.json` and **not** `~/.config/Element/config.json`. That should be documented somewhere. But the client still does not use my configured Jitsi server.

### Outcome

That element-desktop would use my confugred Jitsi server. 

### Application version

Element Desktop 1.11.17

### How did you install the app?

Flathub

### Will you send logs?

No

**Comment by krassle** [comment]
> That element-desktop would use my confugred Jitsi server.

1. This appears to work as intended - according to the [guide](https://github.com/vector-im/element-web/blob/develop/docs/jitsi.md) you've mentioned above.

`Note: The widget URL will point to a jitsi.html page hosted by Element. The Jitsi domain will appear later in the URL as a configuration parameter.`

Element-Desktop should still be using **your.jitsi.example.org** server for conference calls by simply framing it inside `element.io`. 
The URL looks like this:
`https://app.element.io/jitsi.html#conferenceDomain=your.jitsi.example.org&conferenceId=Jitsi[...]`

2. What I don't understand is: **Why is this `framing inside an external domain` behavior even necessary?**

Both Element-Web and Element-Android handle this *correctly* by framing inside the "preferredDomain"!
The URL looks like this:
`https://your.jitsi.example.org/jitsi.html#conferenceDomain=your.jitsi.example.org&conferenceId=Jitsi[...]`

This behavior has also a security implication...
Jitsi server admins are being **forced** to compromise on their *security policies* by changing a strict *Content Security Policy* directive from `"frame-ancestors 'self'"` to `"frame-ancestors 'self' *.element.io"` __in order to allow an external domain__ to frame their jitsi instance! Otherwise Element-Desktop refuses to work with their own jitsi server and throws out the following *error message* after trying to start a conference (Dev-tools-_LOG_): 
`Refused to frame 'https://your.jitsi.example.org/' because an ancestor violates the following Content Security Policy directive: "frame-ancestors 'self'.`
   
I've opened an [issue](https://github.com/vector-im/element-web/issues/23884) about this odd behavior a few weeks ago, but sadly no response so far. As a potential security issue this should be handled with more urgency, imo.

**Comment by lu-ka** [comment]
So I've managed to solve this problem. Video rooms created before you set a custom Jitsi URL will always use `meet.element.io`. This makes sense since from my testing, a video room will always use the same Jitsi conference ID/URL even if all participants leave and come back into the video room the next day. So the Jitsi instance of a video room is tied to the `preferredDomain` that is used when creating the room. I would suggest to add this to the docs.

**Comment by raphael-walther** [comment]
We have deleted and then created the widget and then it works with our own server.

**Comment by erinarbleizez** [comment]
problem still exist with video rooms... from what I see, they don't seems to use html frame and even when creating a new video room after changing the .well-known/matrix/client the video room still use meet.element.io.

problem appear both with element-desktop and app.element.io (I don't have my own element-web installed on my server).

for the test I created a space on my personal server and I logged in onto my server through element-desktop and app.element.io.
I created a experimental video room from element-desktop and from element-web.
I join both room from app.element.io (in order to use the devtools to check the url called)

each time it's meet.element.io that appear instead of my jitsi server.

the .well-known/matrix/client I use:

```
{
  "m.homeserver": {
    "base_url": "https://DOMAIN.TLD/"
  },
  "im.vector.riot.jitsi": {
    "preferredDomain": "meet.DOMAIN.TLD"
  }
}
```

**Comment by crjo** [comment]
same issue, using configuration 
![image](https://github.com/element-hq/element-web/assets/5144838/7df068b6-3f2f-4dd6-a24e-896c45f33c48)
configured like that on my nginx :
```
                location /.well-known/matrix/client {
                        add_header Access-Control-Allow-Origin "*";
                        add_header Content-Type "application/json";
                        return 200 '{"im.vector.riot.jitsi": {"preferredDomain": "your.jitsi.example.org"}}';
                }
```
i see the request going to my homeserver when starting Element desktop:
`"GET /.well-known/matrix/client HTTP/2.0" 200 70 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Element/1.11.53 Chrome/118.0.5993.144 Electron/27.1.2 Safari/537.36"`
