### ISSUE TITLE
Stuck unread with reaction + start thread

### ISSUE THREAD

**Issue by weeman1337** [vector-im/element-web#24394]
### Steps to reproduce

1. Have two users A and B in a room
2. Send a message with A
3. React to this message with B
4. Start a thread from the message with B
5. Look at thread as A

#### What did you expect?

Unread count cleared

#### What happened instead?

Stuck with (1) unread for the room as user A

### Browser information

Seems unrelated, happens on Desktop + Web

### Application version

Element Nightly version: 2023013101 Olm version: 3.2.12

### Will you send logs?

Yes

**Comment by gsouquet** [comment]
I have investigated this issue and here are a few thoughts that I'm writing down so that this does not get lost. I have not yet managed to write a fix for this, and this will probably happen over a handful of pull requests

The fundamental issue causing this bug is that we do not insert the events in the thread timeline in the order of the DAG

-----

# Events related to the thread root should be ignored when sending read receipts from a thread timeline 

Thread events are paginated from the `/relations` API. This fetches only the `m.thread` and the 1st degree relations to those events.
But in order to achieve the desired UX, the Element client will insert the relations to the root event (annotations, redactions, ...) in that timeline too.

This is problematic as the timeline code only inspects the last event of a thread and sends a read receipt against that event. Instead the logic should inspect the events from most recent to oldest until it find a suitable one.

# `replayEvents` breaks the DAG ordering

This patch was added as threads can be discovered either via `/sync` or via `/relations`. Sometimes a thread will come down all at once via a `/sync` response, and in those cases the client will get confused when it has to apply message edits as it hasn't fully determined yet where the original message belongs (in a thread or in the main timeline).

For that reason we have added the concept of `replayEvents` in the thread model, that replays and applies the edits once the thread has been fully initialised and when we can know for certain whether those edits are in the correct context.

The timeline only allows to append or prepend events, but the approach described above would require having a way to slice those events into place, otherwise the DAG order is not respected and we run the risk of having stuck notifications.

**Comment by weeman1337** [comment]
@gsouquet is it correct, that this issue also covers message edits in threads?

![image](https://user-images.githubusercontent.com/6216686/217800613-f8ef193f-5f86-49e3-9708-b20707e90712.png)

**Comment by gsouquet** [comment]
the symptoms appear a bit more often with reactions, but also with edits.

The issue occurs when they end up out of order compared to the real order that synapse holds.

I'm working on a fix at the moment

**Comment by 8227846265** [comment]
It seems the `Stuck Notifications` are increasing. On my end from 2 stuck notifications. It's now 6 stuck notification in a span of 3 days :(
