### ISSUE TITLE
Dear Element-web developers...

### ISSUE THREAD

**Issue by rwjack** [vector-im/element-web#24418]
### Steps to reproduce

Dear Element-web developers, don't be shy.

Just copy your main competitor's UX.
Not blatantly, but you get the idea.
Make Element as smooth, that's what it really needs, just a little bit of attention.

Then you win in every single fight against them.
You were first in the encryption game, 
you have no "debts" to pay,
you are free as in freedom.

The bigger you grow, and the more free you become,
The greater your position becomes, within the heart of the community.

Thank you.

#### What did you expect?
I expected fast, smooth, snappy, colors easy on the eyes
#### What happened instead?
The present moment happened. 😯

### Will you send logs?

Yes

**Comment by robintown** [comment]
Thank you for your feedback. Improving the user experiences that people have with our products is our primary focus as a company, but we cannot do this without specific feedback. The general issue of Element's performance is something we're very much aware of, and are working to improve through ongoing projects such as Sliding Sync, as is the issue of Element's UI being burdened by design debt, which we're working on by refining our design systems and guiding design principles.

Because of Element's unique goals and technical challenges, this takes time—it's not as simple as "copying" another product's design (ignoring the copyright and product identity issues this would create). I would encourage you to use this issue tracker to record more specific usability issues, or interactions that trigger performance problems. This is what helps us out the most at this point in time.
