### ISSUE TITLE
Olm session seems to change in storage

### ISSUE THREAD

**Issue by uhoreg** [vector-im/element-web#24450]
I've seen a rageshake where an olm session seems to have a different description when it gets saved than when it gets loaded later on to try to decrypt a message.  e.g.

```
I Saving Olm session ... with device ...: sender chain index: 2 receiver chain indices: 2 skipped message keys:
```

and then later

```
I decryptMessage: Olm Session ID ... from ...: sender chain index: 0 receiver chain indices: 1 2 skipped message keys:
```

with no other logs referencing that session ID in between the two.

**Comment by t3chguy** [comment]
@uhoreg the user is on Web, could this be an issue of running the app in multiple tabs? @kittykat do you run multiple tabs of EW?

**Comment by kittykat** [comment]
Yes, I do at some point most days

**Comment by richvdh** [comment]
> I've seen a rageshake where an olm session seems to have a different description when it gets saved than when it gets loaded later on to try to decrypt a message

So this looks like expected behaviour to me. If another tab receives messages on the Olm session, it will update the Olm session in indexeddb.

This *should* all work out in the end, because that other tab will receive the megolm key and store the megolm session in indexeddb where it can then be used by all tabs.

Of course there are various ways this might go wrong in practice - and in particular the automated olm session unwedging will unnecessarily force a new olm session which itself might break. But the fact the Olm session changed isn't itself a problem.

@kittykat if you see similar problems in future, could you try to do a rageshake from any other EW tabs you happen to have open as well?
