### ISSUE TITLE
A small box has appeared in the lower right corner of blocks in settings

### ISSUE THREAD

**Issue by turt2live** [vector-im/element-web#24632]
### Steps to reproduce

1. Open Help & About in user settings

#### What did you expect?

Not a box.

#### What happened instead?

![image](https://user-images.githubusercontent.com/1190097/220985748-44997d11-7605-412d-805b-d288c51cd34d.png)

### Operating system

Windows 10

### Application version

Element Nightly version: 0.0.1-nightly.2023022301 Olm version: 3.2.12

### How did you install the app?

The Internet

### Homeserver

t2l.io

### Will you send logs?

No

**Comment by Adesh-Pandey** [comment]
@turt2live this issue was resulted when https://github.com/matrix-org/matrix-react-sdk/pull/10069 PR was merged. The addition of property overflow scroll resulted in the appearance of the small box. This was solved by my PR https://github.com/matrix-org/matrix-react-sdk/pull/10227 as overflow auto solves this. So this issue has been resolved.

**Comment by weeman1337** [comment]
:heavy_check_mark: tested with yesterday's nightly.
The issue does not appear on https://develop.element.io/
