### ISSUE TITLE
Feature request: collapsible images

### ISSUE THREAD

**Issue by 0xD9** [vector-im/element-web#2466]
Please add a feature to collapse / minimize images that are attached in-line in the chat log. The ability to hide an image that someone has posted would be very useful.

**Comment by ArdaXi** [comment]
I was just looking at how to implement this. I've seen other chat clients that solve this by having an "uploaded an image" line above the actual image, with an arrow next to the line that can be clicked to toggle a collapse state.

In matrix-react there is such a line in EventTile, but that only works if the first message someone sends is an image, ie. that line does not appear above _every_ image, only the first someone sends if they didn't send text first.

Would it be an idea to either move that line to the MFileBody/MImageBody, or to move the download link to the top instead of the bottom and adding it onto that? Mostly looking for UI/UX feedback.

**Comment by aidalgol** [comment]
This would be extremely useful for when at work (or school, or out in public on a laptop) and someone posts an even vaguely inappropriate image.

**Comment by lnxwalt** [comment]
**Is your suggestion related to a problem? Please describe.**
_A clear and concise description of what the problem is. Ex. I'm always frustrated when [...]_

I was in a room where someone posted a very inappropriate image. I discovered that I had no way in Riot-web to hide the image or the message which contains it. It was frustrating to have to wait for the user to delete their post or an admin/mod to intervene. Please add this on the client level.

Fortunately, after myself and another person in the room requested its removal, the original poster deleted their post.

**Describe the solution you'd like**
_A clear and concise description of what you want to happen._

I would like every post and attachment to be displayed with the tools that allow the viewer to hide that post or attachment. "Ignore User" is not always the correct answer if one only wishes to hide a single post or image by that user. Clicking the "..." would allow access to the hiding function.

**Describe alternatives you've considered**
_A clear and concise description of any alternative solutions or features you've considered._

None.

**Additional context**
_Add any other context or screenshots about the feature request here._

None.

**Comment by weeman1337** [comment]
I investigated on this one. Also regarding the existing PR.

Why not just do it like another popular messaging app? Here are some screenshots:
* [2021-01-17_10-23](https://user-images.githubusercontent.com/6216686/104836686-f5207c00-58af-11eb-8d24-f8c34f27e120.png)
* [2021-01-17_10-24](https://user-images.githubusercontent.com/6216686/104836692-f8b40300-58af-11eb-9b9d-c562c2b8c3b0.png)

If changing the element order (by putting the name at the top and add the collapse function while keeping the download link) maybe this one should clean up the image view a bit more. For example it is very confusing to me to click "decrypt" if I can already see this image and then have a "download" action.

My suggestion would be:

[2021-01-17_10-33](https://user-images.githubusercontent.com/6216686/104836759-71b35a80-58b0-11eb-9ccc-20639551217f.png)

Notes:
* In my opinion the download functionality collides with the collapse function
* Maybe the "download" action should be added to the "actions" either a) or b)
* Why not combinding "decrypt" and "download" transparently and just name it "download"?
  * As mentioned above: I already see the image; what is the point of "decrypting" it? It is just confusing.
* Then the image name could be moved above the image and can work as a collapse toggle
* → doesn't require more space and adds the requested feature while having a proper usability

**Comment by keremgocen** [comment]
I'd like to help on this one but it does not seem clear yet what should be the implementation? Is this still being discussed, or is there a flight checklist an outsider like me can look at and implement without help?

**Comment by SimonBrandner** [comment]
@keremgocen, there already is [a PR](https://github.com/matrix-org/matrix-react-sdk/pull/4349) to fix this. I believe it's blocked on design or similar

**Comment by turt2live** [comment]
Per [my comment on the PR](https://github.com/matrix-org/matrix-react-sdk/pull/4349#issuecomment-1119134214), we believe the core concerns raised here have been resolved through other changes. If folks feel that is untrue or would still like to see this, then please open a fresh issue so we can engage the design and product teams more efficiently. Thank you.
