### ISSUE TITLE
Run Percy less frequently

### ISSUE THREAD

**Issue by Johennes** [vector-im/element-web#24731]
We currently exceed our Percy quota about halfway through a monthly cycle. This is suboptimal because we're getting no value out of this tool half of the time.

To mitigate this, let's reduce the frequency at which we run Percy. Currently we have ~150 monthly commits or ~5 a day. I propose that we start out with 2 runs a day and see how far this gets us.

The current cycle ends on the 20th of March. So ideally we'd have this in place by that time.

**Comment by luixxiul** [comment]
I'm sorry if I get it wrong, but IMHO setting up a bot to let it run a Percy test only with a command issued on PRs labelled with `X-Needs-Percy` probably might work here without slowing down development which needs Percy tests, since it is said that using Percy is preferred to checking CSS styles with `.should("have.css", ...)`.

https://github.com/matrix-org/matrix-react-sdk/pull/10232#discussion_r1118156759, https://github.com/matrix-org/matrix-react-sdk/pull/9065/files#r923415568
> This check should be captured by a percy snapshot, not explicitly checking the style. These e2e tests should be testing from the POV of the user to see that 1) things work as expected and 2) look as expected.

**Comment by Johennes** [comment]
We actually have that logic of running Percy only on PRs that have the `X-Needs-Percy` label already. This issue is about reducing the frequency at which we run Percy on `develop` because it's making us exceed our quota half-way through a monthly cycle already.

**Comment by luixxiul** [comment]
Right, I did not notice that Percy ran on develop branch too, which in fact is documented here: https://github.com/matrix-org/matrix-react-sdk/blob/develop/docs/cypress.md#percy-visual-testing

**Comment by t3chguy** [comment]
We did this
