### ISSUE TITLE
Display a default user pill when the matrixId is unknown

### ISSUE THREAD

**Issue by giomfo** [vector-im/element-web#24782]
### Steps to reproduce

Send in a room the following permalink : "https://matrix.to/#/@sddfshfjkashfk:matrix.org" with an unknown matrixId

#### What did you expect?
<table>
<tr>
<td> a pill with the user's name and profile picture if any. Like this:  
<td> <img width="90" alt="Screenshot 2023-02-21 at 18 09 52" src="https://user-images.githubusercontent.com/89144281/220425468-eb3ac738-e005-473b-85e6-4fd182d49a2c.png">
<tr>
<td> If the matrix id is unknown, the pill should show the default user icon and "User" (the mxId is visible in overlay) : 
<td> <img width="58" alt="image" src="https://user-images.githubusercontent.com/8969772/224039520-e5d69817-da20-495d-8032-f7e3adee632a.png">
</table>

#### What happened instead?
A pill with the mxId is displayed:
<img width="350" alt="image" src="https://user-images.githubusercontent.com/8969772/223167490-e9cf9123-a9e2-48c7-b306-bcdbf9c5fef4.png">

### Will you send logs?

No

**Comment by MadLittleMods** [comment]
> If the matrix id is unknown, the pill should show the default user icon and "User" (the mxId is visible in overlay) :

@giomfo Why is this expected for you? I would much rather prefer to see the MXID pill for someone we can't pull the display name/avatar information for.

It will get hard to disambiguate when there are multiple unknown "User" showing up everywhere.

**Comment by t3chguy** [comment]
It'd also be impossible to disambiguate from someone in the room called `User` with that specific avatar

**Comment by daniellekirkwood** [comment]
We had push back on showing the avatar and display name/ mxid for users that you're not familiar with because what if they're abusive... If someone references a user that's "@explitive:rude.com" the solution you're suggesting would reveal that to all users in the room. Our solution hides it and shows "User" whilst giving folks the ability to click/hover and see the MXID if they choose to. 

The reason we're not just rendering the MXID username and avatar is to cover the abuse cases - I want to make sure we're not leaving that same method open with your suggestion.

**Comment by weeman1337** [comment]
@giomfo can you confirm that we now decided to still display the MXID instead of »User« ?

**Comment by MadLittleMods** [comment]
The [discussion being referenced above](https://matrix.to/#/!GUMgJVREVreXOrrahw:matrix.org/$rtDa8RR2Sxf1RTlLhQ3vulED3Ehw799kNYcuICacm2s?via=matrix.org&via=element.io&via=one.ems.host) happened out of band in an internal room and a meeting which I don't have context for.

The conclusion from the discussion was:

> Let's go for the mxId with default user icon

Which seems to be how we already handle things today.

Closing the issue ⏩
