### ISSUE TITLE
username highlight disappeared from this /me action message when refreshing

### ISSUE THREAD

**Issue by AmandineLP** [vector-im/element-web#2493]
Highlights remain in normal messages. Raised by Trevor

**Comment by ara4n** [comment]
I'm assuming this means that a `* Matthew hit Trevor` message was shown in red when it first arrived, and then after hitting refresh it went black.

**Comment by progserega** [comment]
I think that will be very nice if '/me text' will be shift to left and has font style italic, and nick will be bold.
Today I see that '/me' not use anybody because it look like as simply typing text such: "*progserega text". Otherwise in irc '/me' command used very often.

Such:
![2018-12-14_14-34-41](https://user-images.githubusercontent.com/1297163/50004127-d2954800-fff1-11e8-9035-cb57d0543327.png)

js style:
```
.mx_MEmoteBody {
margin-left: -12px;
font-style: italic;
}

.mx_MEmoteBody_sender {
font-weight: bold;
}
```
