### ISSUE TITLE
d3dcompiler_47.dll of Element Desktop flagged as virus / trojan

### ISSUE THREAD

**Issue by visubesy** [vector-im/element-web#25003]
%HOMEPATH%\AppData\Local\element-desktop\app-1.11.26\d3dcompiler_47.dll is flagged as virus, see: [VirusTotal - d3dcompiler_47.dll](https://www.virustotal.com/gui/file/5653bc7b0e2701561464ef36602ff6171c96bffe96e4c3597359cd7addcba88a)

Maybe, Element was attacked like 3CX where d3dcompiler_47.dll contained malware? See [Hackers compromise 3CX desktop app in a supply chain attack](https://www.bleepingcomputer.com/news/security/hackers-compromise-3cx-desktop-app-in-a-supply-chain-attack/).

Version of Element: 1.11.26
Version of Olm: 3.2.12

**Comment by justjanne** [comment]
Those are false positives – it looks like some AV vendors are a little bit too careful and just matching by filename.

Element uses [this version](https://www.virustotal.com/gui/file/5653bc7b0e2701561464ef36602ff6171c96bffe96e4c3597359cd7addcba88a/details) of d3dcompiler_47.dll.

As you can see, this file has a valid signature from microsoft.

For comparison, [this is the file used in the attack](https://www.virustotal.com/gui/file/11be1803e2e307b647a8a7e02d128335c448ff741bf06bf52b332e0bbf423b03/details)

The malware used in the supply-chain attack has no valid signature and is much larger than the genuine file (due to containing hidden shellcode).

**Comment by justjanne** [comment]
I'll close this issue, as this is just a false positive. But in the future, if you find something that you believe might be a security issue, please contact our security team instead of opening an issue: https://github.com/vector-im/element-web/security/policy

**Comment by visubesy** [comment]
OK, thank you. Good to know that it is a false positive.
