### ISSUE TITLE
voip calls fail with no explanation if mic access fails

### ISSUE THREAD

**Issue by richvdh** [vector-im/element-web#2504]
We just see 'user ended the call'

**Comment by richvdh** [comment]
console log:
```
CallHandler.js:103Error: Couldn't start capturing media! Is your microphone set up and does this app have permission?
    at callError (call.js:1049)
    at MatrixCall._getUserMediaFailed (call.js:727)
    at call.js:1188
    at Object.webRtc.getUserMedia (call.js:1246)
    at MatrixCall.answer (call.js:375)
    at Object._onAction [as ID_1] (CallHandler.js:319)
    at MatrixDispatcher._invokeCallback (Dispatcher.js:198)
    at MatrixDispatcher.dispatch (Dispatcher.js:174)
```

**Comment by ara4n** [comment]
i've seen several folks bitten by this.

**Comment by turt2live** [comment]
On the receiving end of a call, this results in a similar error and the "Active in call" banner flashing briefly. In my case it was due to lack of a microphone on the system.

Maybe use a series of fallbacks?
* If no video, don't show video button (join or start)
* If no mic, warn user that they can't speak
* If neither, "A conference is in progress, but you don't appear to have any microphone or webcam set up"

**Comment by carlokok** [comment]
Screen sharing (ctrl+shift video call icon)  also fails like this when there's no mic available.

**Comment by SimonBrandner** [comment]
@richvdh, it looks this isn't an issue anymore:
![Screenshot_20210222_184223](https://user-images.githubusercontent.com/25768714/108747417-b54b5500-753d-11eb-94bf-0d36e25e6494.png)

**Comment by richvdh** [comment]
probably!
