### ISSUE TITLE
Replace hard-coded values for spacing with variables specified on `_spacing.pcss`

### ISSUE THREAD

**Issue by luixxiul** [vector-im/element-web#25070]
#### What would you like to do?

Replace hard-coded values for spacing with variables specified on `_spacing.pcss`.

#### Why would you like to do it?

Because the [style guide](https://github.com/vector-im/element-web/blob/1ebe574ab1bc3dd55489dfd0ca5ff02e918d976e/code_style.md?plain=1#L288) suggests you to use a variable for a property related to spacing. It should also help us to maintain the themes' consistency.

#### How would you like to achieve it?

Search padding and margin values and replace them.

### Additional context

This should be conducted along with https://github.com/matrix-org/matrix-react-sdk/pull/10552 for https://github.com/vector-im/element-web/issues/21656.

**Comment by richvdh** [comment]
So, I discussed this with the rest of the team, with conclusions as follows:

Let's not do this: it seems like a lot of work for both authors and reviewers, for no tangible benefit. 

There is debate over whether the current `$spacing-` variables offer any value at all (see https://github.com/matrix-org/matrix-react-sdk/pull/10686), but even if we *do* want to use them going forward, we don't think a wholesale replacement of existing values offers any value at all.

In the longer term, we'd like to use components based on our ["Compound"](https://compound.element.io) design system, which will use semantic variables rather than hardcoding particular px values, but that requires design input and updating legacy components is not a priority for the design team.
