### ISSUE TITLE
Introduce a GA Action or linter to track CSS usages

### ISSUE THREAD

**Issue by luixxiul** [vector-im/element-web#25149]
#### What would you like to do?

I think GA Action or linter to track CSS usages and alert if a style rule becomes no longer referred should help us to keep the style rules updated.

#### Why would you like to do it?

During creating E2E test for General user settings tab, I coincidentally found style rules which have not been used since around four years (https://github.com/matrix-org/matrix-react-sdk/pull/10659). As the project gets matured, the chance of getting such obsolete rules which would make the CSS codebase bloated should increase without a tool to track the CSS usage.

#### How would you like to achieve it?

I am not sure. If there is an existing tool, we would be able to start using it. If there is not, we would have to create one by ourselves, unfortunately.

### Have you considered any alternatives?

Maintaining style rules on a ts file would also help us to keep the style rules maintained, though I am not sure if this would be possible.

**Comment by weeman1337** [comment]
Hello @luixxiul ! I basically like the idea. But in my opinion this can be challenging because there are generated CSS classes. I wonder how a linter can recognise them. Maybe through some kind of special annotation. If we write our own linter, it needs to understand all the ways of defining classes in React.

**Comment by weeman1337** [comment]
Hi @luixxiul . As a result of a discussion with the others of the Web App team no one is aware of a reasonable way to automatically find unused CSS classes. There are some options such as using Cypress test coverage for it. However, based on past experience with these tools, they will generate a huge list of false positives.

To conclude this:
- If you know a good way of finding dead CSS automagically, leave a comment here
- If you find unused CSS code, we would appreciate any pull request from you to clean it up

Furthermore, with the upcoming [design compound](https://compound.element.io/?path=/docs/overview--docs), this should hopefully be less of a problem in the future.

I am closing this issue because of ↑

**Comment by weeman1337** [comment]
@luixxiul I would recommend you to bring this topic up in the [Compound tracker](https://github.com/vector-im/compound/issues): There may be things we can do better in the new and shiny design compound world to prevent dead CSS from happening again or at least make it more discoverable.
