### ISSUE TITLE
Rich text editor doesn't work with more sophisticated input methods

### ISSUE THREAD

**Issue by robintown** [vector-im/element-web#25247]
### Steps to reproduce

1. Use an input method which takes multiple key presses to compose a single character, such as Anthy for Japanese, or just a plain old English keyboard with a compose key
2. Type stuff into the rich text editor

Specifically, I'm using IBus to reproduce this.

#### What did you expect?

The behavior of the current composer:

[Screencast from 2023-05-01 14-08-11.webm](https://user-images.githubusercontent.com/48614497/235503645-1df3f697-2ad4-415d-83da-6b4d4e5a83d9.webm)

#### What happened instead?

The rich text editor breaks these input methods:

[Screencast from 2023-05-01 14-09-53.webm](https://user-images.githubusercontent.com/48614497/235503779-69be2246-8f5e-4be0-bf14-ec7f45251fd2.webm)

### Operating system

NixOS unstable

### Browser information

Firefox 112.0.1

### URL for webapp

develop.element.io

### Application version

Element version: a722b71b6c6e-react-58c942be4539-js-3e0f9f582e86 Olm version: 3.2.14

### Homeserver

Not relevant

### Will you send logs?

No

**Comment by luixxiul** [comment]
The issue is reproduced with combination of `Fcitx` + `Mozc` as well.

Current composer:

https://user-images.githubusercontent.com/3362943/235742106-6aae2386-1680-4135-82b7-cce0dc0daffe.mp4

Rich Text Editor:

https://user-images.githubusercontent.com/3362943/235742126-4d06bdd6-f5bd-4e9e-b912-760861285c4c.mp4

Since `Fcitx` is IME used for Chinese as well, RTE is unusable for Chinese language too.

**Comment by luixxiul** [comment]
It works if formatting is hidden. Please check the video below:


https://user-images.githubusercontent.com/3362943/235976786-dc3e2579-b7b6-479d-9ebd-90e80f91bb2e.mp4
