### ISSUE TITLE
User directory search says you can search by email address even when an identity server is not configured

### ISSUE THREAD

**Issue by lampholder** [vector-im/element-web#25571]
### Steps to reproduce

It also encourages you to set an identity server which is not appropriate in all circumstances (non-federating installs, for example).

### Will you send logs?

Yes

**Comment by t3chguy** [comment]
This is intentional, it'll help you connect to an IS if you try to send an email invite.

> It also encourages you to set an identity server which is not appropriate in all circumstances (non-federating installs, for example).

Indeed, that's why you can disable IS UI, https://github.com/vector-im/element-web/blob/develop/docs/config.md#ui-features

Don't think there's anything else to do here, @lampholder feel free to reopen if you disagree
