### ISSUE TITLE
Offline presence icons are effectively invisible on dark theme

### ISSUE THREAD

**Issue by turt2live** [vector-im/element-web#25792]
### Steps to reproduce

1. Have a presence-enabled homeserver
2. Have people offline

#### What did you expect?

Noticable presence indicators

#### What happened instead?

![image](https://github.com/vector-im/element-web/assets/1190097/a1f08964-3b56-44ea-ace2-2ac1d7711a4e)

### Operating system

Windows 11

### Application version

Element Nightly version: 0.0.1-nightly.2023071301 Olm version: 3.2.14

### How did you install the app?

The Internet

### Homeserver

t2l.io

### Will you send logs?

No

**Comment by janogarcia** [comment]
@germain-gg The usage shown in the screenshots is actually breaking the contract for the purpose of the `on-solid` token.

`on-solid` would be for any solid color that it's not the canvas color or a subtle one.

That badge is part rendered on top of the colored background and part on top of the canvas, that's why it's not fitting that purpose/context.

I would recommend setting it to `color.icon.primary` instead, which is not a bad idea/semantics after all.
