### ISSUE TITLE
Message bubble layout has broken with the new look

### ISSUE THREAD

**Issue by amshakal** [vector-im/element-web#25818]
### Steps to reproduce

1. Turn message bubbles layout on in appearance settings
2. View the timeline of any room
3. Avatar, username and bubble are not overlapping anymore. 

#### What did you expect?
The avatar, username and bubble to be overlapping like designed
### Operating system

Macos Ventura Version 13.4.1

### Application version

Element Nightly version: 2023071601
Olm version: 3.2.14

### How did you install the app?

Using the link on Element.io

### Homeserver

Matrix.org

### Will you send logs?

Yes

**Comment by t3chguy** [comment]
@amshakal any chance of a screenshot?

**Comment by amshakal** [comment]
Done!

**Comment by t3chguy** [comment]
Perfect, thanks!

**Comment by germain-gg** [comment]
This seems to be broken again

**Comment by manancodes** [comment]
Can somebody share a screenshot/wireframe of the desired design so that I can get started on this?

**Comment by amshakal** [comment]
Here is the desired design for the message bubble avatar composition. :)
<img width="607" alt="Screenshot 2023-10-12 at 1 03 10 pm" src="https://github.com/vector-im/element-web/assets/85162587/2acf890e-15ec-4160-8368-06796f45df01">

**Comment by manancodes** [comment]
Hi @amshakal , thanks for the design.

The name also needs to be repositioned. In the desig "y" is almost touching the message bubble below. 

Before:
<img width="686" alt="Screenshot 2023-10-12 at 10 48 19 PM" src="https://github.com/vector-im/element-web/assets/54790263/20aa0497-4854-4e80-8b3d-075fbe5ec976">

After:
<img width="620" alt="Screenshot 2023-10-12 at 10 47 55 PM" src="https://github.com/vector-im/element-web/assets/54790263/7db4660b-f322-4dcb-8d81-f213f93d6cb7">

A few other questions that I have:

1. The image is smaller than the design, should I increase that?
2. What is the desired size of the image?
3. if you look closely, there is a border between the image and the message. Should it be added?

Please clarify the requirements so that I can draft a PR for this.

**Comment by amshakal** [comment]
I think we can keep the image size and text position as is and I can test the PR and make calls.

It would be nice to add a white border around the image though yes.

**Comment by manancodes** [comment]
Sure. I will get started on this. Thanks

**Comment by manancodes** [comment]
I have opened a PR for this. Please take a look.

The border around the image is not looking very good if the message is highlighted. What's your opinion?

**Comment by amshakal** [comment]
I would suggest that when highlighted, we should change the stroke colour to the background colour

**Comment by manancodes** [comment]
> I would suggest that when highlighted, we should change the stroke colour to the background colour

Done.

I have also fixed it for Highlighted messages. Although the contrast is quiet not right. 
<img width="250" alt="Screenshot 2023-10-17 at 9 28 32 PM" src="https://github.com/vector-im/element-web/assets/54790263/9f0c4a7f-a47a-4224-8901-72a12236d30a">
