### ISSUE TITLE
Element-Web causes extreme usage in CPU for synapse due to presence

### ISSUE THREAD

**Issue by MTRNord** [vector-im/element-web#25874]
### Steps to reproduce

Not entirely sure. Just opening develop.element.io seems to be enough for me.

#### What did you expect?

Maybe a tiny increase but usually negligible.

#### What happened instead?

![image](https://github.com/vector-im/element-web/assets/1374914/b3108d4b-807c-4f28-84f6-b6ccf93c111b)
![image](https://github.com/vector-im/element-web/assets/1374914/cf035a3a-23f8-410d-a4ed-3bf41629e1d8)

### Operating system

Fedora Silverblue 38

### Browser information

Firefox 115.0.2 (64-bit)

### URL for webapp

develop.element.io

### Application version

Version von Element: 5644c4e17555-react-1f3d99c25c70-js-fd0c4a7f5697 Version von Olm: 3.2.14

### Homeserver

matrix.midnightthoughts.space

### Will you send logs?

Yes

**Comment by MTRNord** [comment]
Little more info: The peaks line up exactly with then I opened up my ele-web.

**Comment by t3chguy** [comment]
Element doesn't even use the presence API anymore. 

![image](https://github.com/vector-im/element-web/assets/2403652/2a5c1579-7b23-4993-b8cc-da728b5c40a2)

Your log has a bunch of syncs which implies your server is sending you lots of data, each sync has a set_presence param specified `/_matrix/client/r0/sync?filter=xxx&timeout=xxx&set_presence=xxx&since=xxx` - sounds like Synapse's set_presence implementation is poor. Not an Element issue for following the spec on how to use `/sync`.
