### ISSUE TITLE
feature_exploring_public_spaces: "Show spaces" should probably be checked by default

### ISSUE THREAD

**Issue by gabrc52** [vector-im/element-web#26005]
#### What would you like to do?

Users should be able to see spaces in the public directory by default

#### Why would you like to do it?

Because spaces are valuable too

#### How would you like to achieve it?

By checking the "Show spaces by default"

### Have you considered any alternatives?

An alternative design may be needed, since the tooltip says "Explore rooms"

**Comment by gabrc52** [comment]
https://github.com/gabrc52/matrix-react-sdk/commit/25d2cd5db60dae2269a64d75fbe7615b514c9471

**Comment by t3chguy** [comment]
https://github.com/matrix-org/matrix-react-sdk/pull/11423 iterates on the UX and removes this checkbox entirely.

**Comment by gabrc52** [comment]
Ahh I see, thanks a lot for working on this! 

---

I think this hides the ability to find spaces behind having to delete the "Public rooms" chip, scrolling down and then clicking on "Public spaces".

One possible suggestion could be to add an "Explore spaces" button next to the "Explore rooms" button.

And a small tidbit: 

![image](https://github.com/vector-im/element-web/assets/24363938/6cb9c296-c38d-492e-be63-8f0f91badf62)

It still says "rooms" in here

**Comment by t3chguy** [comment]
> I think this hides the ability to find spaces behind having to delete the "Public rooms" chip, scrolling down and then clicking on "Public spaces".

Not really... 

1. shortcut from `+` on spaces
![image](https://github.com/vector-im/element-web/assets/2403652/33c8d155-a5f5-4a8d-ae8a-7c8830daf48c)

2. Click `Search` top of room list, `Public Spaces` is above `Public Rooms`
![image](https://github.com/vector-im/element-web/assets/2403652/2ca2f0e9-7e47-416b-8973-ba8dd0112496)


> It still says "rooms" in here

Yup because they technically are, not touching that bit right now
