### ISSUE TITLE
ElementR: Unable to verify a user

### ISSUE THREAD

**Issue by florianduros** [vector-im/element-web#26245]
### Steps to reproduce

Two rust crypto users

1. In a room, open the information panel of a user
2. Click on verify

https://github.com/vector-im/element-web/assets/2621378/58856935-c430-4896-9930-4dbeccca86d8

#### What did you expect?

I'm expecting the verification process to be launched between the two users

#### What happened instead?

Nothing happen on the receiver side

### Will you send logs?

Yes

**Comment by richvdh** [comment]
There is something wrong with the display of the verification events, which isn't helping:



![Image](https://github.com/vector-im/element-web/assets/1389908/7a4b34a7-325e-4fd1-a05a-e1463d18f1e8)

**Comment by nao9797** [comment]
I have been having a problem perhaps similar or of the same type with verification functions for more than 2 years of using Element. I thought it was my android phone version, then later I noticed the problem was on my desktop element. I decided to wait at least a year since it seemed like an issue that would severely affect Element and what it's supposed to offer. I have been very idle about this issue, but I feel like now it has been way too long of an ongoing problem. I searched this in the issues and haven't seen a lot of relevant information (at least not in the open issues) and I have been wanting to make a new issue but I feel like it will take a long time to point out something that should have been pointed out long ago by many others. I will eventually do this but I can't help but wonder now if the devs are doing ok, maybe they've bumped into a major obstacle? iduno

**Comment by richvdh** [comment]
@nao9797 your issue sounds unrelated. We are replacing the crypto code in Element-Web (https://github.com/vector-im/element-web/issues/21972), so it's possible your problem will be solved anyway, but feel free to open a separate issue explaining your symptoms.

**Comment by richvdh** [comment]
> There is something wrong with the display of the verification events, which isn't helping:

Whilst this is true (and it's due to the fact that we're not populating `MatrixEvent.verificationRequest`, it's not the root of the problem here, and is probably less of a blocker.

The real problem is the absence of a `CryptoEvent.VerificationRequestReceived` when the event is received.
