### ISSUE TITLE
Messages sent to a thread aren't visible in EW but appear in previews

### ISSUE THREAD

**Issue by ara4n** [vector-im/element-web#26254]
### Steps to reproduce

1. See a thread on EX
2. Reply to a message in it
3. View the same thread on EW
4. Your replies are missing entirely from the thread:

EW shows:

<img width="538" alt="Screenshot 2023-09-28 at 09 53 10" src="https://github.com/vector-im/element-web/assets/1294269/53a9ec59-3df8-422a-9c8e-d0670fc4547a">

EX shows:

![IMG_3108](https://github.com/vector-im/element-web/assets/1294269/08eca508-9304-45bb-9e87-ce9205f098f6)

Unclear on whether this is an EX or EW or Synapse bug.

Will rageshake on both platforms with msg IDs.

#### What did you expect?

Messages should never disappear.

#### What happened instead?

Messages disappeared.

### Application version

Element Nightly version: 2023092701 Olm version: 3.2.14

### Homeserver

matrix.org

### Will you send logs?

Yes

**Comment by t3chguy** [comment]
<img width="426" alt="image" src="https://github.com/vector-im/element-web/assets/2403652/bd77fffb-e5a1-456e-9987-c2c41ec4f214">

Cannot reproduce

**Comment by ara4n** [comment]
unsurprised. hopefully my EW rageshake might reveal what's going on. (also, hello nunito!)

**Comment by ara4n** [comment]
looks like it's not only my messages. just found a threaded message for another room which shows in the room preview, but isn't visible anywhere in the actual room, or the thread it was a member of.

**Comment by ara4n** [comment]
having restarted the client, the missing messages are now visible.

**Comment by andybalaam** [comment]
I see a missing message this morning:

![image](https://github.com/vector-im/element-web/assets/76812/facbe752-bd7f-4b39-aab9-1a8c394e7f56)

It's visible in the main timeline, but not the thread.

**Comment by andybalaam** [comment]
^ Rageshake added.

**Comment by andybalaam** [comment]
Treating this as a "fire" i.e. something that we immediately work on.

**Comment by andybalaam** [comment]
Theory so far: maybe the message never got added to the thread timeline, maybe because it was not in the order we expected.

Ideas here: https://github.com/matrix-org/matrix-js-sdk/pull/3782

Next: figure out whether the missing messages arrived via sync and/or `relations` api.

**Comment by andybalaam** [comment]
In my example, the messages were sent from Element Desktop.

**Comment by andybalaam** [comment]
OK, I have hatched a plan. We suspect that the problem is messages being dropped in [Thread::addEvent](https://github.com/matrix-org/matrix-js-sdk/blob/develop/src/models/thread.ts#L326), and the main suspect of why they might be dropped is due to their `localTimestamp` being inconsistent with the order we receive them. This could happen for example if some messages arrived via sync and others via the relations API.

Until we have MSC4033, we can't definitively solve the message-ordering problem, but we can see some problems in `addEvent` that we can handle in a way that might be better.

We need to be very cautious around this area because if we change the order of messages we can trigger new forms of the [Stuck Notifications](https://github.com/vector-im/element-web/issues/24392) bug.

So the plan is:

* Add a warning message when we drop events in this code, providing the information about why we dropped them.
* Prepare a PR that improves the behaviour of `addEvent` to remove use of `localTimestamp` (which we think is simply wrong) and insert every message, relying on server timestamps to put them in the "right" order (See https://github.com/matrix-org/matrix-js-sdk/issues/3325).
* Merge this PR after the next release candidate so we can observe whether people experience more stuck unreads, and back it out if they do.

**Comment by grati-cule** [comment]
Hi, I've noticed in one of my rooms that I'm not receiving some individual messages on Element (Windows and Android) which _are_ appearing on Element X (Android)

I've submitted feedback via Element on my laptop but am providing screenshots here...

![Screenshot_20231010-094840~2](https://github.com/vector-im/element-web/assets/98021030/84603881-9cac-4937-b781-815777b1143d)
![Screenshot_20231010-094940](https://github.com/vector-im/element-web/assets/98021030/89c863eb-bacd-4c36-b15c-4c803b22e3f2)

**Comment by andybalaam** [comment]
We believe this is fixed (planned for the release in early November, probably Element Web v1.11.48). If you see any examples of it, please re-open this issue or create a new one if the behaviour is different.
