### ISSUE TITLE
ElementR: After a successful gossip of the key backup decryption key, UTDs in history are not automatically fixed

### ISSUE THREAD

**Issue by BillCarsonFr** [vector-im/element-web#26312]
### Steps to reproduce

Depends on a webR with that fix https://github.com/matrix-org/matrix-js-sdk/pull/3778

1. Create a new login (account with some e2ee rooms with messages), and verify using emoji/QR

#### What did you expect?

After the verification, the new session will get the backup decryption key, therefore should decrypt history automatically.
Currently only partial history is decrypted (due to key requests).

Notice that if you verify with passphrase, a call is made to download all keys from backup. But it's not done by js-sdk, it's done by the react-sdk (by a promise in `usePassPhrase()` of `SetupEncryptionStore.ts`.

#### What happened instead?

You have to manually go to settings and tap on restore.

### Will you send logs?

No

**Comment by weeman1337** [comment]
With Element R would this also fix https://github.com/vector-im/element-web/issues/23333 ?

**Comment by BillCarsonFr** [comment]
Removed the blocker label as you will recover your history on a session per session basis (not a full import)

**Comment by richvdh** [comment]
I'm a bit unclear on what exactly is going on in this issue. Is the problem:

1. The (full) key backup is not automatically downloaded once the backup decryption key is received? (This might be deliberate, since there is currently no sensible way to paginate key backups?) Or:
2. Individual keys are not downloaded once the backup decryption key is received? (This is presumably because we only request key backups at decryption time, and there is no attempt to re-decrypt once the backup decryption key is received.) Or:
3. Keys are downloaded fine, but the screen is not updated?

Or something else?

**Comment by richvdh** [comment]
Seems like a combination of 1 and 2. Unclear how we proceed here. (What did legacy crypto do?)
