### ISSUE TITLE
Margins in new right bar are inconsistent

### ISSUE THREAD

**Issue by MTRNord** [vector-im/element-web#26410]
### Steps to reproduce

1. Check the various submenus

#### What did you expect?

Consistent margins

#### What happened instead?

Cut off on the right or directly touching the end of the page. 0 margin

![image](https://github.com/vector-im/element-web/assets/1374914/f0f2eaca-9c00-410c-9955-800b74d42e48)
![image](https://github.com/vector-im/element-web/assets/1374914/414417e4-cdd1-4e56-9138-d07494bae4ba)

Margin on the left larger than on the right:

![image](https://github.com/vector-im/element-web/assets/1374914/74eb2d62-1adf-4ac9-a826-e35b0386597a)

### Operating system

Fedora Silverblue 38

### Browser information

Firefox 118.0.1 (64-bit)

### URL for webapp

develop.element.io

### Application version

Version von Element: 80ba22a-react-f784a085fdfc-js-c0264954eda2 Version von Olm: 3.2.14

### Homeserver

matrix.midnightthoughts.space

### Will you send logs?

No

**Comment by germain-gg** [comment]
Thank you for the scrutiny. Have opened a PR to fix the tiny mistake with the invite button at the top.

The other issues raised will remained as is, as some were pre-existing and out of scope of the changes of the ticket, but more importantly because we are replacing those views soon and paying properly the sins of the past in terms of layout / UI.
