### ISSUE TITLE
Verification events are not shown in the timeline

### ISSUE THREAD

**Issue by weeman1337** [vector-im/element-web#26450]
### Steps to reproduce

1. Enable Rust Crypto
2. Start a verification with a user
3. Open DM room with that user

#### What did you expect?

Verification events in timeline

#### What happened instead?

Verification events in timeline are empty

![veri](https://github.com/vector-im/element-web/assets/6216686/295af856-ba93-4970-8295-d8c71ae92f57)

### Operating system

Ubuntu 22.04.3 LTS

### Browser information

Firefox 119.0

### URL for webapp

https://develop.element.io/

### Application version

Version von Element: 16ec8edd5867-react-5e8d2748e069-js-73a87652fe98 Version von Olm: <not-enabled>

### Homeserver

matrix.org

### Will you send logs?

No

**Comment by richvdh** [comment]
Per my notes on https://github.com/vector-im/element-web/issues/26258:

I think we need to reconsider how this bit of the UI works rather than try to replicate the current behaviour.

The two tiles [[MKeyVerificationRequest](https://github.com/matrix-org/matrix-react-sdk/blob/develop/src/components/views/messages/MKeyVerificationRequest.tsx#L39) and [MKeyVerificationConclusion](https://github.com/matrix-org/matrix-react-sdk/blob/develop/src/components/views/messages/MKeyVerificationConclusion.tsx)] behave very strangely in the face of repeated/cancelled verification requests, and page reloads, under legacy crypto.

And yes, we only keep a record of the current `VerificationRequest`, so we aren't going to be able to replicate the old behaviour exactly anyway.

**Comment by andybalaam** [comment]
My summary of the conclusion of the various linked discussions:

In both legacy and Rust Crypto, we should render `MKeyVerificationRequest` and `MKeyVerificationConclusion` in the timeline as simple messages like "X made a verification request" and "Verification with X was completed" that can be rendered purely based on the information within the events.

@richvdh am I right?

**Comment by richvdh** [comment]
Yes, I think so.

Currently the `render` methods for those components inspect `mxEvent.verificationRequest`. That property is not populated in Rust Crypto (not least because we no longer use the `VerificationRequest` class), which is why this isn't working at all at the moment.

There is also a `MKeyVerificationConclusion.shouldRender` method which doesn't work for the same reason.

I think we should rip out all that magic and replace the components with something very simple.
