### ISSUE TITLE
Voice call request CSS bug

### ISSUE THREAD

**Issue by ghost** [vector-im/element-web#2683]
<img width="1110" alt="screen shot 2016-12-03 at 23 39 25" src="https://cloud.githubusercontent.com/assets/20953825/20862684/f19b7c34-b9b1-11e6-886a-5ffb4e0b032a.png">
<img width="1103" alt="screen shot 2016-12-03 at 23 39 55" src="https://cloud.githubusercontent.com/assets/20953825/20862687/f7f75cf6-b9b1-11e6-9aea-f02a2d65780d.png">

Hello,

as you can see, the CSS of voice call request is hidding "accept" and "decline" buttons, it's really disturbing

Thanks

**Comment by AmandineLP** [comment]
reproduced by zak on Mac desktop app https://riot.im/download/desktop/install/macos/Riot-0.9.0.dmg

**Comment by ara4n** [comment]
I just tried to reproduce this on 0.9.1.dmg and failed.  @PegasusGo are you still seeing this?

**Comment by vagnum08** [comment]
Hi, I've seem to have the same issue.
Tested on three different monitors with the following resolutions: 1280x800, 1280x1024, 1920x1080. It only occurs on the 1080p monitor. It shows up again when I change the dimensions of the window.

**Comment by ara4n** [comment]
i have absolutely no idea what's causing this. @vagnum08 how many rooms are you in? how tall is the roomlist on the leftpanel when it's open?

**Comment by vagnum08** [comment]
I have 9 rooms in total. Checked the window dimensions when the popup appears again and it was 1280x900 (pic 1). Probably related to #2884 based on the last comment. It appears sooner if the rooms list is not expanded (pic 2).

Forgot to mention earlier, but I can bring the call popup up if I switch to another room (pic 3). 

Lastly, when I am at the same room instead of an accept and decline button I have only upload and hangup (pic 2), which I think is related to this #2781.

![scaled_to_1280_900](https://cloud.githubusercontent.com/assets/16070176/23415484/396cae8e-fdd7-11e6-8cc1-0bb688aac939.png)
![split_stack_v1](https://cloud.githubusercontent.com/assets/16070176/23415486/396eaf5e-fdd7-11e6-897b-c8ec9f7b646b.png)
![another_room_1080p](https://cloud.githubusercontent.com/assets/16070176/23415485/396db00e-fdd7-11e6-8843-c746be7b3e10.png)

**Comment by ara4n** [comment]
@vagnum08 i'm a bit confused - none of your screenshots seem to show the bug (of the hidden 'incoming call' notification)? 

the lack of call accept in the bottom right is a separate issue (#2781)

**Comment by vagnum08** [comment]
@ara4n The above screenshots were taken while I was getting a call. As you can see the 'incoming call' notification is not visible always, but it depends on the window's dimensions and left or right panel's layout. 

Since the problem is that the notification is not easily visible  I posted the rare occasions where the notification can be seen. Specifically on the second screenshot (pic2 /left side)--although someone is calling me--there's no notification until  you expand the leftpanel (pic 2/right side) when it appears again.

 Worth mentioning, that the sound notification works as expected.

**Comment by na-Itms** [comment]
Hello. While trying to have a voice call with another person, we both had the issue. We were both using unregistered accounts, as it was the first time both of us used riot.

We were able to "start" a voice call, but the buttons for answering disappeared whenever the mouse hovered them, thus making the actual call impossible.

I am personally using Firefox Nightly on Fedora 27, my screen is 1366x768 pixels (not sure whether that is useful information).

**Comment by turt2live** [comment]
I think we fixed this prompt in the new room list
