### ISSUE TITLE
When sending an HTML message which is larger than 65K, the CSS doesn't go red when sending fails

### ISSUE THREAD

**Issue by ara4n** [vector-im/element-web#2728]
Looks like triple-backtick block CSS overrides the red unsent warning

**Comment by erikjohnston** [comment]
This was in an e2e room too. It was very confusing since it also had a green padlock.

**Comment by kittykat** [comment]
I'm going to close this issue for now since the UI has changed significantly and there is an error message which clearly states that the message has failed to send:

![Screenshot from 2021-11-03 11-20-57](https://user-images.githubusercontent.com/51663/140052821-125ebcc3-81e4-4f21-863e-d03deb985b0d.png)

There are improvements which could still be made, but it would be worth opening a new issue with clearly defined acceptance criteria that designers could work with
