### ISSUE TITLE
release (web client) as (debian|ubuntu) packages

### ISSUE THREAD

**Issue by 4nd3r** [vector-im/element-web#2777]
right now updating riot-web is manual process (okay, I have a script for that).

``apt-get update && apt-get upgrade`` would be awesome.

**Comment by select** [comment]
This is already possible with the repo linked at https://riot.im/desktop.html. I guess only the documentation how to do it is missing currently. Someone posted a the docu for that in the matrix HQ chat. If I can find it I'll post it here.

**Comment by select** [comment]
http://data.agaric.com/how-install-riot-desktop-matrix-client-debian-based-systems see also the issue #2804

**Comment by 4nd3r** [comment]
sorry, i was meaning web client, not desktop.

**Comment by select** [comment]
yes, I see that would also be great

**Comment by uhoreg** [comment]
FWIW, I have a script to convert a Riot tarball to a deb package at https://gitlab.com/snippets/1666923, and set up a repo at `https://debian.uhoreg.ca/experimental/riot-webapp/`.  I'll try to maintain that repo with the latest version (until something official comes up), but it may lag a bit from the official releases.  To add the repo to apt, add "`deb http://debian.uhoreg.ca/experimental/riot-webapp ./`" (or use https if you have apt-transport-https installed) to your `/etc/apt/sources.list`, and run "`finger uhoreg/key@db.debian.org | sudo apt-key add -`" to add my GPG key to apt.

**Comment by NikkyAI** [comment]
so i assumed that rit-web would mean it hosts the riot website..
am i mistaken ?
after installing `apt-get install riot-web`
and running it `riot-web` nothing happens

or do i have to set this up with nodejs and there is no ready use package for servers ?

**Comment by t3chguy** [comment]
`riot-web` debian package is the electron build of the `riot-web` repository. @NikkyAI

**Comment by NikkyAI** [comment]
so to host the website i have to do something else ?

**Comment by t3chguy** [comment]
@NikkyAI download https://github.com/vector-im/riot-web/releases/download/v0.11.4/riot-v0.11.4.tar.gz and extract it to any webhost, its a bunch of static files.

**Comment by monkz** [comment]
ran in this too - riot-web as packagename is misleading. I didn't expect electron there -  thankfully i was able to cancel the installation, otherwise a full gnome installation for my headless server would have occurred.

**Comment by 4nd3r** [comment]
> riot-web as packagename is misleading

this. electron version should be named **riot-desktop**.

**Comment by stephanlachnit** [comment]
Is there any way I can help? It should be possible to provide a minimum deb which just copies the release files to a webroot dir (e. g. `/opt/element-web`), like the Debian Matrix packaging team did with hydrogen (see https://salsa.debian.org/matrix-team/matrix-hydrogen).

I'm not sure if element-web needs to write to it's webroot. If that is the case, then this is much more difficult of course.

**Comment by elsiehupp** [comment]
I was curious what the issue was with including Element in the Debian PPA repositories, and it appears that Debian, at least, has strict requirements around minified JavaScript, which is apparently an issue with React and Electron, idk. You can read the issue thread on the Debian side [here](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=866502).

If inclusion in the Debian, Ubuntu, Elementary, etc., PPA repositories is going to remain off the table for the immediate future, several possible alternatives (in addition to the existing Riot PPA) could be: 
1. offering Element Desktop as a [Debian binary package](https://wiki.debian.org/Packaging/BinaryPackage) (though I don't know how updates work with that),
2. packaging Element Desktop as an [AppImage](https://appimage.org/) (though, again, updates might be a problem) [[existing issue](https://github.com/vector-im/element-web/issues/4766)],
3. distributing Element Desktop as a [Flatpak](https://docs.flatpak.org/) through [Flathub](https://flathub.org/) [[existing issue](https://github.com/vector-im/element-web/issues/3718)], and
4. distributing Element Desktop as a [Snap](https://snapcraft.io/docs/snapcraft-overview) through [Snapcraft](https://snapcraft.io/) [[existing issue](https://github.com/vector-im/element-web/issues/6822)].

Snap and Flatpak seem roughly competitive in terms of functionality, but Flatpak seems to have wider adoption on (and better app selection for) desktop Linux, while Snap seems to have wider adoption on (and better app selection for) server Linux.

I've gone through a little bit of [the process with Flatpak/Flathub](https://github.com/flathub/flathub/blob/master/CONTRIBUTING.md) before, and it seems fairly feasible. Additionally, like Snap, Flatpak eliminates a lot of the complexity around targeting multiple Linux distributions, and both Flatpak and Snap feature automatic updates.

**Comment by lnicola** [comment]
I think this issue was originally about the web, not desktop client, which makes any discussion about Electron moot.

Also, that linked bug is about the official repositories. A PPA can package anything.

**Comment by elsiehupp** [comment]
> I think this issue was originally about the web, not desktop client, which makes any discussion about Electron moot.

The fact that there isn't a separate issue tracker for [Element Desktop](https://github.com/vector-im/element-desktop) is kind of a problem...

> Also, that linked bug is about the official repositories. A PPA can package anything.

Yes. The fact that [the official way to get Element on Debian or Ubuntu](https://element.io/get-started) involves adding a third-party repository is kind of user-hostile (e.g. because it doesn't just show up in GNOME Software), which was kind of the point of my comment.

...

Anyway, apparently there's [an unofficial Element Desktop Flatpak on Flathub](https://flathub.org/apps/details/im.riot.Riot) that just isn't mentioned in [the official install instructions](https://element.io/get-started), because, of course, why would they make it that easy?

It doesn't look like there's been any sort of issue opened on [on the element.io issue tracker](https://github.com/vector-im/element.io/issues) regarding adding a reference to the Flatpak, though, so that might be where I go next.

**Comment by jryans** [comment]
As mentioned above, this issue is about having a Debian package for the web version that you might use on your web server. It is not related to desktop, so I'll hide these desktop bits to keep the issue focused.

> The fact that there isn't a separate issue tracker for Element Desktop is kind of a problem...

We track all Element Web and Desktop things here in this repo, as there's usually a lot of cross-over. There are already many desktop issues here, so feel free to file another if needed.

**Comment by hwittenborn** [comment]
Is there help needed to package a Debian package for the webserver version? I'd be glad to give some assistance if needed.

**Comment by MartinDelille** [comment]
I come to the news: is there a apt package for element-web ?

**Comment by t3chguy** [comment]
@MartinDelille no, otherwise this issue would be closed. It is coming.

**Comment by weeman1337** [comment]
Is this really done? Looks like the workflows are failing:
https://github.com/vector-im/element-web/actions/runs/6848729117

**Comment by t3chguy** [comment]
Should be fixed by https://github.com/vector-im/element-web/commit/ccaef6f14b5175fc27aedc88469f3a92415850a4

**Comment by t3chguy** [comment]
Working! https://github.com/vector-im/element-web/actions/runs/6888819804

**Comment by t3chguy** [comment]
Will be available on packages.element.io based on the same instructions as https://element.io/download#linux but with package name `element-web` starting from `v1.11.50`

**Comment by weeman1337** [comment]
ty :tada:
