### ISSUE TITLE
scroll handle in unknown devices dialog can be tiny

### ISSUE THREAD

**Issue by uhoreg** [vector-im/element-web#3165]
The scrollbar handle is about 1px high (since there are so many unknown devices), which is too small to be useful.  Vertical scrollbar handles should probably have a minimum height, and horizontal scrollbar handles should probably have a minimum width.
![image](https://cloud.githubusercontent.com/assets/1012976/22703165/34805e36-ed31-11e6-9890-35522c238f48.png)

**Comment by ara4n** [comment]
This is irritatingly invasive to do.  GeminiScrollbar positions the thumb as a translation calculated as a % of its height, given its height is meant to represent the size of one page of the scroll-buffer.  So if the buffer is 2000px high and the window is 200px high and the user is scrolled to the bottom, the thumb is translated by 900% (the offset when scrolled to bottom being 1800px).

To fix this, we'd need to calculate the translations in terms of the theoretical height of of the thumb rather than the actual height and express them as an absolute value.  It's not hard, just a bit faffy, and requires extending our gemini fork.

**Comment by t3chguy** [comment]
We killed off the UDD
