### ISSUE TITLE
Failed password on sign-in should focus the password field after warning

### ISSUE THREAD

**Issue by ara4n** [vector-im/element-web#3287]
Atm it does silly CSS animation but doesn't focus the field :(

**Comment by lukebarnard1** [comment]
Isn't there subtly in the fact that either the username or the password could be wrong? So focusing on either might be problematic.

**Comment by pafcu** [comment]
@ara4n It seems like the field that you were typing in keeps focus. In practice this is probably mostly the password field. If you mistyped your username, you would go back to that field, and if you mistype it again, it makes sense that you get to keep trying, rather than focus suddenly moving.

IMHO the current behaviour is the logical one.
