### ISSUE TITLE
Tooltips/popovers get cut off if there is not enough room

### ISSUE THREAD

**Issue by turt2live** [vector-im/element-web#3429]
### Description

This is probably not very high on the fix it list, but here we go:

Tooltips/popovers get cut off instead of switching sides. This is best revealed when using Riot on a portrait monitor (1200x1920) and the right sidebar collapsed. If the right sidebar is not collapsed, the popover appears normally (see screenshots).

### Steps to reproduce

- Have an unconventional shape of screen such that the right edge of the message is the edge of your browser
- Open a popover next to the message (context menu)
- Note that it is cut off on the right edge

I would have expected it to flip to the other side, instead of overflowing. Granted, this is affecting a very limited number of people (me).

Log: not sent    

![image](https://cloud.githubusercontent.com/assets/1190097/23908941/056a9618-089b-11e7-8a1b-826e97da9372.png)

*Note: GitHub does not show the white bar on the right of the image - this is the boundary between Chrome and my other monitor*

### Version information

- **Platform**: web (in-browser)
- **Browser**: Chrome 56
- **OS**: Windows 10
- **URL**: riot.im/develop

**Comment by uhoreg** [comment]
A similar thing happens when you click on the menu button on the bottom message in an e2e room -- the last menu item ("Quote") gets cut off.
![image](https://cloud.githubusercontent.com/assets/1012976/23955649/e7eb917e-0970-11e7-8514-897086379182.png)
Everything is fine in a non-e2e room, because there the menu doesn't have the "View Decrypted Source" menu item, so it all fits.
For this issue, I think it might make sense to shift the menu up to fit it all.

**Comment by lampholder** [comment]
Agreed - I think in both cases this only affects E2E rooms (due to the wider link text on 'View Decrypted Source' and the longer list of items in the case of the menu button on the bottom of the page).

**Comment by turt2live** [comment]
Bridged messages that also set the source URL can be cut off. Here's an example of the menu:
![image](https://cloud.githubusercontent.com/assets/1190097/23958691/86cd7fcc-0968-11e7-8b5f-4da4f3e5762d.png)

**Comment by uhoreg** [comment]
Also happens with the room menu when the room that you want to change is near the bottom of the window.  This can make it impossible to modify a room that is at the bottom of your list.
![image](https://cloud.githubusercontent.com/assets/1012976/24829174/0ba55974-1c3b-11e7-9050-83ddec5f9fe4.png)

**Comment by lampholder** [comment]
I think we should track the message popup (#3429) separately from the room menu popup (#3792). Obviously they're thematically closely linked - I think #3792 is higher priority, but there's a good chance we might be able to tackle #3429 at the same time.

**Comment by Nostradamos** [comment]
Any hints how this could be solved? Would give it a try, but not sure how to do it. Maybe with some calculation, x/y pixel position, window height/width? Or what would be the proper way to do solve this?

**Comment by t3chguy** [comment]
Yeah calculate an offset to ensure that at worst the bottom of the menu is at the bottom of the window

**Comment by turt2live** [comment]
@rxl881 @lampholder Just a head's up: this now affects sticker packs:
![image](https://user-images.githubusercontent.com/1190097/38266443-eda09ecc-3735-11e8-8889-8792c09b5cd4.png)

**Comment by lampholder** [comment]
I've bumped the priority of this - even though sticker packs should now be fixed with an independent change, the original problem has gotten worse as more (and perhaps more commonly desired) functionality lurks behind that context menu.

I'm thinking primarily about replies - since 'Reply' is the bottommost option, and since you're quite likely to want to reply to the message that was most recently sent (esp. when testing replies as it turns out), it's pretty annoying not to be able to reach that option in the context menu.

As an aside, we might also consider reordering the options in the context menu such that the most commonly used appear first.

**Comment by rxl881** [comment]
@turt2live - It is not the long term solution, but hopefully this really has been fixed / made better for sticker packs at least in https://github.com/matrix-org/matrix-react-sdk/pull/1903.

**Comment by turt2live** [comment]
Yup! Sticker packs fixed, now we just need the long-term wider fix 😇

**Comment by richvdh** [comment]
This is quite annoying.

![angrypanda](https://user-images.githubusercontent.com/1389908/41291627-1afbe93c-6e48-11e8-9c8c-dfa15a2347d9.gif)

**Comment by turt2live** [comment]
🎉 THANK YOU

**Comment by lukebarnard1** [comment]
Hm. The original issue was for the menu flowing to the right instead of left when it gets cut off. I took this issue to be mostly about downwards ctx menus. Classic case of the issue becoming more generic, which is fine.

@lampholder, should we track the original issue with the original triage?

**Comment by lampholder** [comment]
Yeah, I think this goes back to a P2 Minor now - even with the widest possible context menu content (view decrypted source) it's still _usable_ when it slips off the right hand side of the screen.

**Comment by t3chguy** [comment]
Not all cases are fixed, only the vertical is. The following still remains:
![image](https://user-images.githubusercontent.com/2403652/42088854-ede168d4-7b92-11e8-9a5b-2ebf14d8ecfa.png)

**Comment by aaronraimist** [comment]
Same for the key share ? tooltip near the bottom of the screen ![Screen Shot 2019-05-22 at 5 27 02 PM](https://user-images.githubusercontent.com/5855073/58213251-09653d80-7cb7-11e9-974b-0303caebda0a.png)

**Comment by jryans** [comment]
> Not all cases are fixed, only the vertical is. The following still remains:
> ![image](https://user-images.githubusercontent.com/2403652/42088854-ede168d4-7b92-11e8-9a5b-2ebf14d8ecfa.png)

This case is now fixed by https://github.com/matrix-org/matrix-react-sdk/pull/3087. It's unfortunately specific to that menu, so any other instances are still valid issues for now.

**Comment by passw0rd123** [comment]
Same for the encryption status icon in the textfield. It gets cut off by the browserwindow on the bottom because the content has to many lines. It's only possible to read it's content if you have several linebreaks in the textfield.

<img width="328" alt="tooltip-cut" src="https://user-images.githubusercontent.com/16052268/77821006-eb424800-70e6-11ea-94c8-f6027c70ae72.png">
<img width="387" alt="tooltip-visible" src="https://user-images.githubusercontent.com/16052268/77821008-ec737500-70e6-11ea-8d1e-5fcb9910e326.png">

**Comment by robintown** [comment]
This has been fixed by https://github.com/matrix-org/matrix-react-sdk/pull/7863, https://github.com/matrix-org/matrix-react-sdk/pull/5644, and https://github.com/matrix-org/matrix-react-sdk/pull/8219
