### ISSUE TITLE
In 'all rooms' search, room names are a bit misplaced

### ISSUE THREAD

**Issue by dbkr** [vector-im/element-web#3540]
Search is designed so that it scrolls chronologically the same as a room does, ie. most-recent-at-bottom and you scroll upwards, but when searching all rooms, the room name is displayed as a title above the results from the respective room, meaning you only see it when you reach the top of the results for that room.

**Comment by lampholder** [comment]
I agree this is a bit confusing.

We could implement a bit of 'stickly' UI that shows what room you're currently seeing the history for all the while you're looking at those message (rather than a title at the top it would be a title at the side).

Alternatively, we could look into different results-ordering options to sidestep this problem.

**Comment by turt2live** [comment]
I believe it's clear enough now, though if folks disagree then a new issue for the design team to consider would be appreciated.
