### ISSUE TITLE
Consider removing ConstantTimeDispatcher for either direct dispatch on refs or EventEmitter

### ISSUE THREAD

**Issue by ara4n** [vector-im/element-web#3659]
See https://github.com/matrix-org/matrix-react-sdk/pull/807#issuecomment-295211908.  We're landing the PRs with CTD intact given it works, and filing this as a maintenance bug to remove it down the line as needed

**Comment by dbkr** [comment]
I think this is an aspect of a larger problem in that because our only store is the js-sdk, we essentially have no store for data that only exists within the app, eg. what room is currently selected. We may want to put some proper infrastructure in place for this, as this is one thing that ConstantTimeDispatcher is currently used for is propagating the currently selected room from RoomLists state to the individual RoomTiles so they can render with the appropriate CSS classes, but bypassing props to avoid having to re-render (or decide they don't need to re-render).

Another thought is that the 'currently selected item' seems to me like a pathological case for the react architecture, in that normally, whether it's done via props or via flux data stores, any view interested in that data would listen for the event and update itself when the data changed, which, for RoomList, means if you have 2000 rooms, 1998 of them need to wake up, decide they're still not selected, and do nothing.

One idea might be to just add more specific data events where we need them, ie. for the case of what item is currently selected, it would be quite a fine-grained event listener pattern of, "I am a tile for room x, tell me when my selected state changes", and have a dedicated store for that data that emits these events.

**Comment by turt2live** [comment]
as far as I can tell, it's gone.
