### ISSUE TITLE
Samsung TV

### ISSUE THREAD

**Issue by swift11** [vector-im/element-web#3705]
Could you add riot-web in the Samsung TV app store, please: the web runtime of 2017 (and all future) models is Chrome, so even voice and video should work without any modification ;)
http://developer.samsung.com/tv/develop/specifications/general-features

**Comment by lampholder** [comment]
This is an interesting idea, but I don't think it represents the best use of our limited time at the moment (adding another distribution platform with a relatively low active user base).

That said, Microsoft pulled Skype support from my Samsung TV and there's been nothing to fill that void (and my smart tv compatible webcam has sat there ever since gathering dust).

If lots of people expressed interest in this it might be worth considering.

As an additional hurdle, the website to register with a Samsung TV developer account seems only to be in Korean: https://account.samsung.com/account/signUpSelected.do :\

**Comment by swift11** [comment]
*"low active user base" is an argument which often used for TV apps but Samsung sells 60 million TVs/year, so even a low % is an important user base
* the cost of adding riot-web on TV is negligible: it will run on TV without any modifiaction
* the correct link to submit an app is mentioned on this page: Seller Office http://developer.samsung.com/tv/distribute

**Comment by t3chguy** [comment]
This will not be happening due to it not being a supported environment - https://github.com/vector-im/element-web/#supported-environments

Element makes use of very modern Web APIs
