### ISSUE TITLE
selecting room triggers focus_composer twice

### ISSUE THREAD

**Issue by t3chguy** [vector-im/element-web#3725]
focus_composer, user_activity, view_room, focus_composer, user_activity_end are triggered on a single press, surely the first can be streamlined out

**Comment by t3chguy** [comment]
https://github.com/matrix-org/matrix-react-sdk/blob/1ff443956605ca818b212072767a1f6e515994b5/src/components/structures/MatrixChat.js#L306 first
https://github.com/matrix-org/matrix-react-sdk/blob/1ff443956605ca818b212072767a1f6e515994b5/src/components/structures/MatrixChat.js#L892 second

**Comment by lampholder** [comment]
These commits were both made by @dbkr on separate occasions:
- Focus the text box at appropriate times: https://github.com/matrix-org/matrix-react-sdk/commit/b31794cda5a1c3b3dd75f7a63b0d52862c708e65
- focus message composer when window gets focus: https://github.com/matrix-org/matrix-react-sdk/commit/00dd1e180a9bc693382e8693695c9f158308c657

So it certainly looks like the latter was either introduced to handle the window-focus case or because there was a bug in the former.

Right now (since I don't know what sort of problems this is causing) I'm going to put it as a p3 bug  ('cause it looks at least like there's some scope for refactoring) - please let me know if there's a reason to bump it higher :)

**Comment by ara4n** [comment]
I wonder whether this may be related to the problem (unfiled?) that the e2e disclaimer nag dialogbox never gets keyboard focus when shown (which is very annoying as you have to faff with the mouse to dismiss it)

-- 
Matthew Hodgson
Matrix.org

**Comment by t3chguy** [comment]
This got fixed
