### ISSUE TITLE
Search on Matrix gives less results than search on matrix.org

### ISSUE THREAD

**Issue by AmandineLP** [vector-im/element-web#4067]
Searching 'blockchain' finds less results on Matrix than matrix.org:

![image](https://cloud.githubusercontent.com/assets/8582858/26561849/78477642-44b9-11e7-921f-5c7dccb80bbd.png)

![image](https://cloud.githubusercontent.com/assets/8582858/26561860/8fb18a02-44b9-11e7-89b7-420a49505063.png)

**Comment by lampholder** [comment]
I think you'd expect to see more results on `matrix.org` than `[m] Matrix`, because
- `[m] Matrix` is all of the matrix rooms on matrix.org
- `matrix.org` is all of the rooms on matrix.org, _including_ any bridged rooms (freenode rooms, mostly here)

_However_, what's up with #cosmos:matrix.org? That looks like a matrix room on matrix.org - why does in not appear in both? (Apologies @AmandineLP if this is specifically the point you were making).

**Comment by eMPee584** [comment]
Did this functionality change by the way? i can find nothing from the search on `[m] Matrix` ...

**Comment by t3chguy** [comment]
This is as expected, it is clearer today with the structured view which shows the relations.

![image](https://user-images.githubusercontent.com/2403652/144593787-ba466eaa-bc5c-4ccc-894c-6cddac281043.png)

`[m] Matrix` is now shown as a child of `matrix.org` which wasn't clear before
