### ISSUE TITLE
Default email notifs scare new users

### ISSUE THREAD

**Issue by lukebarnard1** [vector-im/element-web#4357]
I introduced Riot to a friend the other day with the standard failure modes. 
 - Failed to find Riot on the iOS app store (arguably not our fault but worth mentioning)
 - Registered without issue
 - Tried to find me on Riot - searched by email, phone number, user ID but nothing came up even after they joined HQ (under my instruction)
 - So I ended up searching for their user ID and found them instantly from my phone, started a 1:1
 - They then received a daily email recapping Matrix HQ and had zero idea what was going on and deleted the app.

**Comment by lampholder** [comment]
What's the rationale for the default settings' including the activity summary?

I guess it keeps Riot.im front of mind for users who are just dabbling with the platform. However an activity summary for matrix HQ is pretty full on for users who are interested in _using_ the platform rather than in the _development_ of the platform.

Is there a happy medium here?

**Comment by lukebarnard1** [comment]
I don't think emailing should be done by default but we should certainly consider emailing users who have become inactive.

**Comment by SimonBrandner** [comment]
This doesn't seem to be relevant anymore
