### ISSUE TITLE
ILAG: Landing on Riot with a narrow screen gives no hints as to how to continue

### ISSUE THREAD

**Issue by turt2live** [vector-im/element-web#4729]
### Description

Here's a screenshot of the sidebar:
![image](https://user-images.githubusercontent.com/1190097/28854364-03690b3e-76f4-11e7-8708-2b1d26f38b44.png)

### Steps to reproduce

- Be logged out & on the home page (ie: fresh landing)
- Narrow your browser so the LHS collapses

Log: not sent    

### Version information

- **Platform**: web (in-browser)
- **Browser**: Chrome 59
- **OS**: Windows 10
- **URL**: tang.ents.ca (based on https://github.com/vector-im/riot-web/releases/tag/v0.11.4)

**Comment by lampholder** [comment]
Unrelated to the bug, I find myself super excited to see a customised version of the home page :D 

Anyway, obviously it's rendering on a narrow screen is not particularly helpful - some sort of responsive handling of the same content would be better.

Setting P3 minor just because I don't expect it to come up as a problem often (feel free to haggle).

**Comment by kittykat** [comment]
This seems to have been resolved with a min sizes for the window and a different UI:
![Screenshot from 2021-08-24 11-44-41](https://user-images.githubusercontent.com/51663/130603544-36ac0a21-f917-49fa-9ac8-74a463a8d79d.png)

Please comment with clear acceptance criteria and @kittykat if you feel that this hasn't been resolved so that I can reopen the issue.
