### ISSUE TITLE
Flair is cached for too long

### ISSUE THREAD

**Issue by turt2live** [vector-im/element-web#5235]
### Description

After about 30 minutes, it seemed to updated. It should update in more real time.

### Version information

- **Platform**: web (in-browser)
- **Browser**: Chrome 61
- **OS**: Windows 10
- **URL**: riot.im/develop

**Comment by lukebarnard1** [comment]
Real-time updating would require a lot of networking (because the client has to poll the server for changes, the state isn't sent in the `/sync` response). We're willing to see if 5 minute polling would be too much for the load on the server (and it'd be beneficial for it to be low to begin with as we see more people joining and creating groups and expecting others to see those changes).

**Comment by ara4n** [comment]
i would very much caution against polling - even 'infrequent' polling is rapidly unpleasant at our current scale (e.g. the polled check to publish olm keys every 30s ended up with ~200Hz of checks on the server, and required its own synapse worker until we fixed it!).  Why can't we return it in /sync?

**Comment by lukebarnard1** [comment]
@erikjohnston says it's Hard to return it in `/sync`.

**Comment by ShadowJonathan** [comment]
Considering Communities are going away, can this issue be closed?
