### ISSUE TITLE
Replace mobile app install nag with smart app banner

### ISSUE THREAD

**Issue by ara4n** [vector-im/element-web#5380]
https://blog.branch.io/how-to-setup-an-ios-and-android-smart-app-banner-with-deep-linking-and-download-tracking/

**Comment by lampholder** [comment]
@ara4n when do people see this? Do you mean to replace the js alert when people navigate to https://riot.im/{app,develop} on their mobile device?

**Comment by MadLittleMods** [comment]
Related to https://github.com/vector-im/element-web/issues/9814

The nag screen is shown when you visit `app.element.io` on a mobile device. And most of the time "Go to the desktop site" is below the fold. Plus I expected more of a "Continue in browser" instead of asking for the desktop site:

![](https://user-images.githubusercontent.com/558581/132746195-061b189c-bfec-4944-b3cb-928f92b14dea.png)

**Comment by MadLittleMods** [comment]
Closing in favor of:

 - https://github.com/vector-im/element-web/issues/21763
 - https://github.com/vector-im/element-web/issues/24556
