### ISSUE TITLE
Communities-centered UX/UI overhaul

### ISSUE THREAD

**Issue by heyakyra** [vector-im/element-web#5384]
With the introduction of communities as an incredibly powerful organizational layer, the organization of riot's UI is now more cluttered and the UX more confusing than ever. Some of this will be addressed with adding more features on top of groups which will be good in the interim, but I think that Riot has reached a point where starting to build something from the ground up is necessary if it's to really compete with Slack, Discord, and even IRC in its simplicity. 

### Description

Since groups/communities are going to be the new focus (and necessarily so, since they will increase the number of rooms a user likely participates in to be much higher than manageable all at once), major elements of Riot will need to be redone, and so this presents a good opportunity to rethink everything. Ideally UI+UX *trained* individuals can be found to help do this through proper wireframing and prototyping. A list of improvements such as #2984 #4430 are again good in the interim but in the background a whole new foundation should be worked on. 

Why? "UX without UI means you’ve got a frame and structure to your house, but it’s not beautiful and cohesive. UI without UX is like splashing awesome colors and details throughout the house, but having your front door lead straight into a bathroom. You need both to create an awesome end to end experience." —via [user testing](https://www.usertesting.com/blog/2016/04/27/ui-vs-ux/)

### Resources

UX Crash Course:

- http://uibreakfast.com/1hour/
- http://thehipperelement.com/post/75476711614/ux-crash-course-31-fundamentals

Email lessons:

- https://hackdesign.org/
- http://userbehavior.ui-patterns.com/

Guided courses:

- https://www.uxapprentice.com/
- http://uxtree.io/
- https://www.springboard.com/learning-paths/user-experience-design/learn/
- https://www.thegymnasium.com/courses/GYM/103/0/about

Reading:

- https://alistapart.com/topic/user-experience
- https://www.uxpin.com/studio/ebooks/

**Comment by PureTryOut** [comment]
In my opinion this should have kind of a high priority. A proper group UX could get lots of people over from Discord, Slack and the like. I already got a few people interested when I mentioned Matrix would get "Discord-like servers", but what we have now is nothing alike. If participating in a room that is part of a community, there is nothing that shows it is besides a small entry in the room settings.

Anyone coming from instant messaging applications which already have community-like features will have no clue how to use the ones from Matrix, and that in my opinion is a *big* problem.

**Comment by lampholder** [comment]
@thekyriarchy thanks for sharing those resources - I'm going to take a look through them over the next few days (not, I add, with a view to turning myself into the UX expert Riot.im sorely needs, but the more UX awareness the better).

@PureTryOut agreed! We well understand the priority this needs; like every project, developing Riot is a balancing act and we're trying to divide our attention between delivering features, improving UX and scaling the homeserver to handle ever-increasing traffic. Hopefully we'll be better resourced soon so that we can progress _all_ of these important objectives more rapidly :D 

> Anyone coming from instant messaging applications which already have community-like features will have no clue how to use the ones from Matrix, and that in my opinion is a big problem.

What we have today in an in-development MVP, so I'm not surprised that people (especially people expecting an exact Discord analogue) don't immediately grasp it! It needs work, and it needs input from the community to shape it. To my mind, the final Matrix/Riot impl of communities _won't_ be an exact replication of Discord servers or Slack teams. Though ideally it would be possible to compose a Discord/Slack experience from Matrix building blocks, fundamentally Matrix is a larger, more open ecosystem so I expect the best Matrix clients always to have to balance maintaining the coherence of a community within a global messaging space.

**Comment by thedonquixotic** [comment]
I second this. 

I'm a professional UX Designer living in Austin TX (with some beginner-intermediate web dev experience), and I would gladly donate my time to this project if I could get onboarded to the process. 

Previous open source projects I have offered to contribute to were thankful, but expected me to plug in to their dev pipeline without any help. My work as a UX designer is largely conversational, interview focused, with fast non digital methods of iteration. I talk to stakeholders and establish what things need to be done. I don't exactly know how to do that in an open source context so I'll need some to kind of guide me in. I know a decent amount of frontend code etc, but I'm completely unfamiliar with any build process more complicated than running my SCSS through a pre-compiler or spinning up a wordpress installation on my portfolio website host. 

If you need to see my previous work etc you can check here: https://www.jackalope.tech/

**Comment by thedonquixotic** [comment]
@lampholder See my above message. I could help ya'll on this if you can get me up to speed on the process.

**Comment by WildYorkies** [comment]
I'm gathering all of the related issues here. @turt2live perhaps we can close some of the duplicates? Ultimately, they're all asking for a "communities focused UX overhaul" like this issue is describing.

- https://github.com/vector-im/riot-web/issues/4441
- https://github.com/vector-im/riot-web/issues/3843
- https://github.com/vector-im/riot-web/issues/5259
- https://github.com/vector-im/riot-web/issues/2454
- https://github.com/vector-im/riot-web/issues/5077

- [x] Communities on iOS
- [ ] Communities on Android
- [ ] Change the lefthand sidebar to group together communities instead of individual rooms so you don't have to name every room like `communityName_roomName`

**Comment by thedonquixotic** [comment]
Also asked this question on twitter and was linked this article and found it interesting: http://opendesign.foundation/articles/import-designers/

**Comment by heyakyra** [comment]
After https://medium.com/@dharmaone/redesigning-matrix-riot-chat-c7bffd9eb841

#7597 #7562 and other labels/redesign tickets seem to be aiming to address this

**Comment by tmikaeld** [comment]
Just tried the latest version, while it's a huge improvement on previous versions - there's simply no way to figure out how to get to the home screen. If I would put any client on this, they'd give up in the first 5 minutes.

**Comment by trosel** [comment]
@tmikaeld Wire still doesn't have proper username notifications unless you pay. 

But what difficulties are you describing? Rooms with one person in them are in the Direct Messages sidebar dropdown. Rooms with more than one person are in the Rooms dropdown. And there's no need for a homepage in a messaging app. You're just looking at whatever convo you want to look at... Right?

**Comment by tmikaeld** [comment]
@trosel If i go into a room at the start of the app, I get to the room - but, what about all my contacts that are not in a room? How do i see the list of contacts? How do i find people to talk to now that I'm in a room, how do i get out of the room? None of these are answered in the app when you're in a room.

**Comment by trosel** [comment]
@tmikaeld Can you see the left sidebar when you're in a room? All your direct messages and rooms are on the left there.

**Comment by SimonBrandner** [comment]
Spaces are now in beta
