### ISSUE TITLE
Initial icon highlighting is missing in multiple places

### ISSUE THREAD

**Issue by pafcu** [vector-im/element-web#5427]
Icons are used throughout the UI to select what information to show. Once selected, the icon becomes highlighted. However, the highlighting is only set after a click, and does not reflect the default view. E.g in communities, by default, rooms are show in the right sidebar, there is a bar under the icon to show that this is the currently selected option, but the icon itself is not highlighted.

Initial:
![image](https://user-images.githubusercontent.com/62835/31984373-aa910a38-b961-11e7-8a63-bd5a69424174.png)

After click and also expected before click:
![image](https://user-images.githubusercontent.com/62835/31984348-91bc29b6-b961-11e7-9ba5-cf7e1a94d24b.png)

This also applies to other parts of the UI, e.g. when viewing a room the icon for showing room members is not initially highlighted.

Tested on Firefox 52

**Comment by lukebarnard1** [comment]
This is due to the quick CSS we used to highlight anything with `:active`. Of course, once you click somewhere else, the element loses it's `:active` and returns to normal.

One solution would be to apply the same highlight (which is actually a reduction in opacity) to the element when this section of the panel is selected.

**Comment by kittykat** [comment]
I'm going to close this for now as the UI has changed :+1:
