### ISSUE TITLE
Limit the number of URL previews.

### ISSUE THREAD

**Issue by turt2live** [vector-im/element-web#5433]
[![Bountysource](https://api.bountysource.com/badge/issue?issue_id=50756358)](https://www.bountysource.com/issues/50756358-limit-the-number-of-url-previews?utm_source=50756358&utm_medium=shield&utm_campaign=ISSUE_BADGE)

### Description

![image](https://user-images.githubusercontent.com/1190097/32004858-07f0bc5c-b960-11e7-9470-244d1d125233.png)
https://matrix.to/#/!UcYsUzyxTGDxLBEvLz:matrix.org/$1508940221476bTcDp:berigora.net
(#offtopic)

### Version information

- **Platform**: web (in-browser)
- **Browser**: Chrome 62
- **OS**: Windows 10
- **URL**: riot.im/develop

**Comment by lampholder** [comment]
:scream: :scream_cat: amazing :grimacing: 

Yeah, I guess limiting it to... actually maybe limiting it to one would be good (and easy to remember). Maybe something like: 

![image](https://user-images.githubusercontent.com/1922197/32043993-3c75e5b8-ba34-11e7-8e37-c55488ed5714.png)
(That's actually ugly as hell, but, you know, something _like_ that). It could even optionally click to expand.

**Comment by turt2live** [comment]
I kinda don't mind that, would something like this also work?
![image](https://user-images.githubusercontent.com/1190097/32060928-7bde6a10-ba2d-11e7-87a2-aae530084fec.png)
(please ignore the fact that I was too lazy to get the color code for riot text - it should be Riot green)

Showing 2 previews seems reasonable, as it isn't too bad on the timeline. 3 would probably be too many though. The only other significant things I changed were the text (to give the user a hint as to what clicking it does) and disconnected the left edge from the preview itself.

**Comment by lampholder** [comment]
Yeah, I like that. The reason I chose one rather than more-than-one was because I thought it would be super easy for people to remember - if they want to post three links with URL previews that's going to be three individual messages.

I'm not super wedded to that though - anything which puts a reasonable limit on it and lets people expand to see the full list is good I think.

The risk with expanding/contracting timeline items is that they leave you in a place in the timeline tha you didn't expect to be pre/post expansion/contraction - if we can impl a solution for this _without_ falling into that trap, I think this would be a good thing to do :)

**Comment by turt2live** [comment]
Updated original post for the bounty :)

**Comment by t3chguy** [comment]
I think I'll take this on, I personally prefer 2 but I'll do it in a way where the number is just a const atop the file for easy tweaking l8r
