### ISSUE TITLE
UX: Disabling group settings feels weird

### ISSUE THREAD

**Issue by turt2live** [vector-im/element-web#5435]
### Description

![image](https://user-images.githubusercontent.com/1190097/32008276-0d07fc74-b969-11e7-9b64-cf208f6311d7.png)

The UI feels like it is in a constant state of loading, and feels like it is partially behind the opacity layer. Instead, it may be better to disable/remove the fields you're not able to edit, like this:
![image](https://user-images.githubusercontent.com/1190097/32008495-8ed2f1c8-b969-11e7-9ed6-8db2da22c1f7.png)

### Version information

- **Platform**: web (in-browser)
- **Browser**: Chrome 62
- **OS**: Windows 10
- **URL**: riot.im/develop

**Comment by lampholder** [comment]
How we handle 'settings' you don't have the permissions/privileges to edit is an important part of our settings UX considerations going forward. It's no surprise that today we have a mixture of greyed out vs hidden across Riot's different settings UXes.

We chose to grey out here rather than hide because:
- there's nothing there that conceptually any group member shouldn't be allowed to see
- it's an education point where regular users can see the _sort_ of things that are available to change if you are a group admin

However, greyed out mightn't be the best way to represent this.

Ideally I'd like us to strike a balance between:
- making it clear what it is 'within the power' of any given user to modify
- educating everyone as to what options are available (both for the purposes of their running their own rooms/groups and so that they can understand why their experience of a room/group is a certain way and potentially lobby the admin for change)
- not blowing regular/new users' minds with a spaceshuttle control board of meaningless switches and dials

**Comment by turt2live** [comment]
I agree that the user should see settings that are modifiable for their own education, but without the spaceship feeling. The mockup I gave is subtle, and I should have explained it a bit more:
* The general headers/components are brought into view for the user to see
* The long description is disabled, implying that you can't edit it, but it exists
* The "add room" button is removed, but the room list is maintained. This is to show the user that you can control the rooms linked from your group, but the user themselves doesn't need to to see a disabled button for adding. The add button is discoverable for their own group.

The kind of UI I was shooting for was essentially to show the user that some fields exist, but the actual switches and knobs can be removed if there's suitable surrounding information (like the hint that you can control the room list via the edit group page).

The other suggestions I'd make would be throwing a bit of personalization into the headers. For example, instead of "Community Member Settings", make the title "Your Settings".

**Comment by trosel** [comment]
I'll add to this:

![image](https://user-images.githubusercontent.com/1299322/65835476-88e1c980-e2b4-11e9-9c11-d479c0cf6f25.png)

If I don't have permissions to change things in a room, then when I click the name of the room, all I'm looking for is the full **room topic**, room aliases, etc. I don't care to see a full breakdown of room settings, I'm just looking for information. If I have questions, I can ping an admin or mod or just read the room topic *which should contain the answers I'm looking for*

**Comment by turt2live** [comment]
This doesn't really have a purpose in today's spaces world.
