### ISSUE TITLE
We use group IDs when removing rooms from groups

### ISSUE THREAD

**Issue by ara4n** [vector-im/element-web#5526]
The dialogs all say "do you want to remove Room Name from +group:matrix.org" rather than naming the group by its.... name.

**Comment by lampholder** [comment]
I think we only present the dialogue when we remove the room (rather than change visibilty; that seems to happen without confirmation) so I'll update the title accordingly.

Also, perhaps controversially I changed the word 'leak' to 'use' - I don't think this is the same as our leaking room ids - group ids are (unfortunately from a naming perspective) closer in form and function to room _aliases_ than ids, and hence are not (as I understand it) something we worry about leaking. We expect them to be used for discovery and disambiguation.

**Comment by SimonBrandner** [comment]
Spaces are now in beta
