### ISSUE TITLE
Remove/disable save group button if you're not able to save the group

### ISSUE THREAD

**Issue by turt2live** [vector-im/element-web#5595]
### Description

![image](https://user-images.githubusercontent.com/1190097/32793579-9830cc58-c923-11e7-9607-fd0d3fd22364.png)

As shown, this user does not have permission to do anything but leave & publish flair. Considering both of these actions are instantaneous, the save button is not needed. 

### Version information

- **Platform**: web (in-browser)
- **Browser**: Chrome 62
- **OS**: Windows 10
- **URL**: riot.im/staging

**Comment by lampholder** [comment]
This is another expression of the problems we encounter due to inconsistent settings persistance paradigms :(

Groups settings has two different persistence models:
- direct manipulation:
    - publish this community on your profile checkbox
    - add rooms
- delayed persistence (persist on clicking 'save'):
    - name, description, avatar, long description

We're working on this code right now. The 'right solution' is for everything on the page to behave in line with direct manipulation (so the save button does not have a long future). This requires some changes to be made to the input box/text area components so that they do something neater than persist changes onblur.

Until then, we might consider modifying the 'publish this community...' checkbox to be delayed persistence rather than direct manipulation, but I'm not certain that it's worth it.

**Comment by turt2live** [comment]
ftr, I'm still working on the tabbed settings thing, although spare time to work on it is a bit lacking. I plan to also address groups and rooms as part of that, although that's further down the road. A quick fix for this particular issue (and other similar ones) would be greatly appreciated, at least as a stop-gap.

**Comment by turt2live** [comment]
This is particularly bad now that the only thing you can do in there is leave:
![image](https://user-images.githubusercontent.com/1190097/34309205-1d23694a-e70e-11e7-9d61-3d289c1b797a.png)

**Comment by robintown** [comment]
Spaces are now in beta
