### ISSUE TITLE
Split autoplay gifs and videos in to different settings

### ISSUE THREAD

**Issue by Qwertie-** [vector-im/element-web#5771]
I want to auto play gifs but not videos which I cannot do because they are both toggled by the same checkbox. Personally I don't see why anyone would want to autoplay videos without sound but that seems to be a popular trend. However allowing video autoplay to be disabled while still autoplaying gifs should disrupt no ones workflow.

**Comment by lampholder** [comment]
I agree, but I'm reluctant to add yet another configurable toggle :smile: 

Let's see if this gets lots more +1's and then consider it.

**Comment by Spunkie** [comment]
Here's my use case notes on this suggestion from a duplicate issue, #18830.
___
### Your use case

### What would you like to do?

This setting should be split into two separate options.
1. Autoplay videos -- Which defaults to off
2. Autoplay GIFs -- which defaults to on  

### Why would you like to do it?

Every time I write this section out it feels like I'm getting on some kind of soap box. So I'll try and keep it short and simple.

GIFs are not videos and should not be conflated as such. The only reason GIFs are even relevant today is because the internet has traditionally treated them as images, not videos. 

While autoplaying videos outside of streaming/video sites has generally been regarded as a cancer on the internet. Autoplaying GIFs on the other hand has been the norm for many decades.
___
As for the defaults, I've seen more less technically minded friends than I would like to admit that upload or a receive an animated GIF that does not autoplay and they just assume it's bugged/broken and move on.
