### ISSUE TITLE
Feature request: Request to join community channels which are invite-only.

### ISSUE THREAD

**Issue by 5chdn** [vector-im/element-web#5788]
### Description

Feature request: Allow community members to request to join community channels which are invite-only.

### Steps to reproduce

- If you are a community member, go to your community
- Find a room you are not in yet, that is invite-only
- Open it and click the join-room button
- Face an error message "invite only foo bar"

It would be nice that this creates a join-request that the room owner can approve or deny instead of creating an error message for the user. That would make listing channels more useful by the way.

An alternate idea would be to allow invite-only community channels to be joined by approved community members.

### Version information

- **Platform**: web (in-browser) and web (in-rambox)

For the web app:

- **Browser**: Chrome
- **OS**: Arch Linux
- **URL**: riot.im/app

Thanks. :heart:

**Comment by lampholder** [comment]
> An alternate idea would be to allow invite-only community channels to be joined by approved community members.

This is certainly the desired direction - we want to be able to set room access ACLs based on group membership.

> It would be nice that this creates a join-request that the room owner can approve or deny instead of creating an error message for the user. That would make listing channels more useful by the way.

This would be a nice feature to have generally, modulo avoiding non-members' being able to spam a room through repeated/coordinated requests to join. We've discussed this feature (and it's counterpart 'request-to-join-community' in the past and referred to it as 'knocking', but quickly searching the github issue list isn't finding anything relevant.

**Comment by 5chdn** [comment]
> if we can avoid non-members' being able to spam a room through repeated/coordinated requests to join

Yeah, I explicitly want to allow members of the community only to request access. This will prevent "guests" from spamming internal channels.

**Comment by matthijskooijman** [comment]
I would actually like to see this more broadly, also for rooms which are not part of a community or even listed in the directory. The usecase I have in mind is:
 - I create an invite-only room
 - I send some people (who might not be on riot yet) the link
 - Have those people register on Riot (possibly as a guest), open the link and click "request to join" or something similar.
 - In Riot, I can then approve the join of these people

Currently, doing this involves asking people to register, tell them how to find their username, ask them to send me their username and then invite them, which is a bit more cumbersome (especially when dealing with new users).

I guess there is a risk of getting flooded with invite requests, but for a room that is not listed in the directory, this should probably be ok. For group rooms, adding an optional limtation to only allow group members to request to join would also make sense, as suggested before.

**Comment by TrechNex** [comment]
Adding a vote in favour of this feature too.

At the moment with my own project we regularly have people who don't like the fact we've forked GNU Image Manipulation Program joining our channel to spam it or harass our users.

If we go invite-only then we close of our comms channels to anyone that doesn't follow us outside of Matrix. If we stay fully public, then we're forced to be constantly reactive because we can't preemptively ban people (new feature suggestion I just added at #10516)

**Comment by BloodyIron** [comment]
There's plenty of Slack rooms that are invite only, and we need a way to be able to join those, otherwise it really defeats a core aspect of Matrix/Riot, that being bridging the communication platforms.

**Comment by TrechNex** [comment]
For those who are interested in the way our project went, we made all but one channel invite-only, then used "Server ACLs" to block "known bad" name servers on the public channel.

This is still sub-optimal as we basically have to remind people to ask us to join the invite-only channels and follow community groups to figure out which name servers we have to pre-emptively ban.

**Comment by kettenfett** [comment]
adding my vote for this.

**Comment by SimonBrandner** [comment]
Will be fixed by https://github.com/matrix-org/matrix-doc/pull/2403

**Comment by hex-m** [comment]
> Will be fixed by [matrix-org/matrix-doc#2403](https://github.com/matrix-org/matrix-doc/pull/2403)

The spec change is merged and the [implementation in Synapse](https://github.com/matrix-org/synapse/pull/6739) is merged too. What's missing is the client-side.

**Comment by ShadowJonathan** [comment]
Wouldn't this then become a dup of whatever issue exists now for "implement UI for knocking"?

**Comment by hex-m** [comment]
It would - but I didn't find one so I assume this is the issue for "implement UI for knocking".

**Comment by t3chguy** [comment]
Knocking is being worked on but not as part of Spaces

**Comment by Mikaela** [comment]
I think something like this is being worked on at https://github.com/matrix-org/matrix-doc/issues/3297 and https://github.com/matrix-org/matrix-doc/pull/3386.

**Comment by mimtud** [comment]
I do not understand the last comments, so maybe this is redundant, but is the following already considered (should I create a new issue? here or in matrix-synapse?)?
There is the (often reported) issue, that we have to make encrypted rooms invite-only so that new members can read the message history (despite the fact that the settings make you believe that you can allow space members to join the room and they would see the history then). 
On top of that, Space members cannot see any of the invite-only rooms on the space home page (which, reading the OP here, was possible with "communities" before?).
So to achieve the original request, at least listing the invite-only rooms on the space home page would be necessary. Which would also allow for a new nice setting: Allow knocking only for space members. 
(@t3chguy maybe?)

**Comment by turt2live** [comment]
Closing in favour of #18655
