### ISSUE TITLE
keyshare request UX is alarming when idle devices see a UISI which triggers a keyshare req

### ISSUE THREAD

**Issue by ara4n** [vector-im/element-web#5828]
I'm on my phone; nowhere near my laptop. (My laptop may even be asleep, which on MacOS means in practice it wakes up every few hours for a few minutes).  Suddenly I receive a keyshare request from a riot/web on my mobile.  It looks incredibly scary because I know i'm not using my laptop or deliberately requesting keys from other devices.  But in practice, it's just my laptop /syncing a message, getting a UISI for whatever reason, and asking for help.  The solution is probably to improve the wording of the keyshare request message - suggestions welcome... @lampholder any ideas?

**Comment by lukebarnard1** [comment]
Related: https://github.com/vector-im/riot-web/issues/5809

**Comment by lampholder** [comment]
The objective is to reassure people that their key sharing requests are legit.

![screen shot 2018-01-11 at 11 22 32](https://user-images.githubusercontent.com/1922197/34823305-ce4114ee-f6c1-11e7-8610-89f42ac0993f.png)
The limited identification data included (os, browser) is just about sufficient when closely coupled with actions I've taken that are fresh in my memory (I just navigated to riot.im/app in firefox on my mac), but any delay will, I expect, introduce fear from uncertainty.

Options:
- add more words "don't worrry if this key request is unexpected; it's probably just your laptop waking up between sleep cycles!
    - this is a _terrible_ idea as it teaches people to be less wary
- only make key requests in response to explicit user actions
    - very clear and trustworthy, but you have to wait for your keys to be shared when you want them, and loses the advantage of multiple devices actively syncing keys simultaneously (if you have to actively request keys but only have one device active at a time, it feels like key requests will take a long time to resolve)
- make the session identifiers more reassuring, perhaps by encouraging/forcing the user to give each session a memorable name (and perhaps also a picture - my mbna bank account made me type a name and pick a picture from a random shortlist to avoid phishing). Then key sharing requests could look like: ![screen shot 2018-01-11 at 11 41 51](https://user-images.githubusercontent.com/1922197/34823981-829dbe40-f6c4-11e7-9f5c-acde80c24832.png)
    - This might work well; we'd have to trial the idea on some realistic users to see whether it is more baffling than reassuring
- maintain a log of key sharing requests so that you can validate authenticity with the requester if you're concerned
    - This would take a modest investment of effort to make something usable

**Comment by turt2live** [comment]
We don't have this dialog anymore.
