### ISSUE TITLE
Can't cancel pending channel invite

### ISSUE THREAD

**Issue by BloodyIron** [vector-im/element-web#5906]
I invited someone to my channel earlier (set to private), and noticed I had no way of cancelling the invite. This would be particularly frustrating if I accidentally invited someone offline, as I have no way of undoing that until they accept.

**Comment by turt2live** [comment]
This is only an issue when the invited user is also an admin (or the same power level as you?). Ie: 1:1 chats.

Here's the member info in a "regular" room:
![image](https://user-images.githubusercontent.com/1190097/34512177-d7137b84-f01d-11e7-9dce-e97bb9df6ce0.png)

And here it is in a 1:1:
![image](https://user-images.githubusercontent.com/1190097/34512182-e1af5e1e-f01d-11e7-9eb9-44e627ab877e.png)

**Comment by BloodyIron** [comment]
In my instance, it was for a test channel, not direct conversation. I am the only admin, and I invited someone who created a brand new matrix account, so they should have no special privileges. What I observed was that clicking on the user (that was listed under the "invited" section on the right), did not bring up a control panel like you are presenting here. Clicking on them did not seem to do anything (while they were in the invite pending state).

**Comment by lampholder** [comment]
Do you know if it is a 3pid invitation?

If you invite via email address (and the invitee hasn't associated that email address with their matrix account) then matrix will send the user an email invitiation, and the invite will appear in the right hand side as an email address rather than a mxid or display name.

Sadly if you click on that type of invite, the UX doesn't do anything, and there's no way to rescind the invite 3pid invites (https://github.com/vector-im/riot-web/issues/2098).

Is that what's happening here?

**Comment by delbonis** [comment]
Any update on this?

**Comment by SimonBrandner** [comment]
@BloodyIron, are you still seeing this?

**Comment by BloodyIron** [comment]
I haven't tried this since then, so I'm not sure if the issue persists. That was 2.5 years ago so I'm also unsure which channel it was for, sorry!

**Comment by SimonBrandner** [comment]
Ok, since we don't have a repro, let's close this now, let me know if you ever see this again
