### ISSUE TITLE
UX: Enabling flair is hard

### ISSUE THREAD

**Issue by turt2live** [vector-im/element-web#5957]
### Description

Almost everyone I've seen create a group has struggled with getting flair enabled. Most people expect that when they create/join a group, it'll automatically flair them up it seems. Further, people aren't looking in the user settings to publish said flair - they're waiting for it to magically happen.

I'm not sure how to solve the UX problem though. Maybe it's as simple as a default on setting for "Enable flair when I join/create a group"?

### Version information

- **Platform**: web (in-browser)
- **Browser**: Chrome 63
- **OS**: Windows 10
- **URL**: riot.im/develop

**Comment by lampholder** [comment]
Yeah, it's a shame this is proving tricky.

A default on setting to 'enable flair on join/create group' sounds good if that makes the system more usable for relatively little effort.

We might instead consider a confirmation box when joining a group (since this is expected to be a relatively infrequent action) asking users whether they want to show a group's flair on join - this could also default to 'on'.

**Comment by Avamander** [comment]
Just encountered this, I have to say it's not very intuitive. The very least it could be a nice prompt.

**Comment by novocaine** [comment]
Wont fix - this is specific to communities, deprecated in favour of spaces.
