### ISSUE TITLE
Can we have hints on the registration page for what are email and username used for?

### ISSUE THREAD

**Issue by AmandineLP** [vector-im/element-web#609]
I find it confusing to have to enter both. And exposing matrix IDs is not great. But we agreed that using email to disambiguate is not nice in terms of privacy.

If people complain I'd suggest hiding the username field with the server settings and auto-generate nice IDs. But let's start by keeping both fields.

In the meantime it would be nice to have small hints saying that:
- Email: We will only use your email to identify you when people invite you to chat using your email address and to send you notifications when you're being invited. 
- Username: We will use your username to create an ID allowing to disambiguate you from others with the same display name. It will allow us to keep your email confidential.

I don't consider it blocking for v0, I'm setting it to that milestone in case it can fit before the Private preview, but I'm (a bit) flexible

**Comment by pafcu** [comment]
Old issue, but a user complained about this recently. It is not clear what the username is actually used for when you sign up.

**Comment by Mikaela** [comment]
I was hit by this a week ago when Matrix.org was down for the hack as this issue makes Vector.im a single point of failure having prevented me from registering on Feneas.org due to my mistake of providing Riot my email address without any idea it would be sent to Vector.im without my permission (violating GDPR?) and used for more than just password resets.

* [Fenas GitLab: Unable to register on chat.feneas.org](https://git.feneas.org/feneas/association/issues/51#note_5618)

**Comment by kittykat** [comment]
The current login screen mentions how email will be used:

![Screenshot from 2021-08-17 09-50-39](https://user-images.githubusercontent.com/51663/129695018-8edd84f1-35c3-4047-be8f-ec7750bdb15a.png)

It does not mention username but I feel like that is relatively self-explanatory given that the use of usernames to uniquely identify users is fairly ubiquitous.

@AmandineLP does this resolve the issue to your satisfaction? We will close the issue in a week if we don't hear back.

**Comment by kittykat** [comment]
Closing as the issue appears to be resolved. Please reopen with acceptance criteria if you feel that it isn't fixed yet.
