### ISSUE TITLE
Erik's thoughts on TagPanel UX

### ISSUE THREAD

**Issue by lukebarnard1** [vector-im/element-web#6261]
@erikjohnston has pointed out that:
 - Selecting a range in the TagPanel makes little to no sense
 - Clicking on a single selected tag if it's the only tag selected should deselect it

**Comment by erikjohnston** [comment]
(I was quite confused when first attempting to interact with that panel. I don't know whether I'm just used to the way grafana does it)

**Comment by lukebarnard1** [comment]
>the way grafana does it

specifically, [de]selecting series in the legend of a plot.

**Comment by lampholder** [comment]
This UX was designed to mirror established multi-select language of finder/nautilus/file explorer. Interestingly, file explorer and finder don't agree on what to do if you select a number of items  and then click one of them (finder does nothing, file explorer selects it to the exclusion of all others).

> - Selecting a range in the TagPanel makes little to no sense

This mirrors a fairly universal multiselect paradigm (from file explorers to html <select>). I have all four of the supporters groups next to each other so I can select the first and shift-click the last. Perhaps this wouldn't make any sense in grafana where you don't have any choice about the order in which your items appear?

> - Clicking on a single selected tag if it's the only tag selected should deselect it

Maybe, but that could also itself be confusing - clicking a selected item would then do something different depending on whether one or more items were selected. Grafana does do this (all though the UX there reinforces more of a 'select all' then 'deselect' idea) and it feels fine.

Fundamentally it's about picking the paradigm that will feel most natural to most of our users, and provide enough around-the-edges reinforcement that recent arrivals from more different paradigms won't get confused :)

**Comment by erikjohnston** [comment]
> all though the UX there reinforces more of a 'select all' then 'deselect' idea

This I think is the crux of the issue. My mental model is much more aligned around the idea that we start with everything on, rather than starting off in a "non-filtered" mode and when you click something end up in a "filtered mode". A lot of the following ignores this.

---

> This UX was designed to mirror established multi-select language of finder/nautilus/file explorer. 

One thing that came out of yesterdays discussion is that a) web doesn't follow the standards of native apps otherwise, and b) there's a difference between filtering and multi-selection in terms of what they're trying to achieve, and are in some ways they are doing the opposite of each other.

A few key concrete differences:
- multi-selects default to nothing selected rather than everything selected
- a main user flow is to go back to everything selected; the fact that this requires an extra button at the top which multi-selects don't have seems like a fairly big flag
- multi-selects are mostly designed for you to make *some* selection, whereas filtering you often want to go back to the nothing filtered (i.e. everything selected).

There's also the fact that it feels like a long time since I last saw a multi-select, ignoring native apps. Things like github's multi select for e.g. assignees work entirely differently.

> I have all four of the supporters groups next to each other so I can select the first and shift-click the last.

In a fully featured tag panel world, would this not be a single button with the four supporter rooms in it?

> Clicking on a single selected tag if it's the only tag selected should deselect it. Maybe, but that could also itself be confusing - clicking a selected item would then do something different depending on whether one or more items were selected

I'd argue there isn't that much of an inconsistency here, and besides, if you have multiple things selected you're already somewhat in power user mode.

> Fundamentally it's about picking the paradigm that will feel most natural to most of our users, and provide enough around-the-edges reinforcement that recent arrivals from more different paradigms won't get confused :)

In the current set up─and even in the grafana-like set up─I think the multi selection stuff is hidden away from any but power users. Is this desirable? Should we be doing multi selection by default (rather than hiding it behind control)? E.g.:

- When everything is selected, clicking on an item causes only that item to be selected
- Otherwise, when an item is clicked it gets selected or unselected like a multiselect
- If the the last selected item is unselected, so that nothing is selected anymore, everything goes back to being selected again.

Yes, this behaviour would be somewhat surprising at times, but greatly increases the chance of discovery of multiselect. There's a trade-off here in terms of focusing on having one group selected at a time, vs multiple groups.

**Comment by t3chguy** [comment]
The TagPanel is in its grave
