### ISSUE TITLE
Simplify the CSS generated by computedStyle for iframe'd download links

### ISSUE THREAD

**Issue by Crystal-RainSlide** [vector-im/element-web#6418]
### Description
There are 150+ inline css code for every massage. That's really massive.
...Pick a element to reproduce it.

And low performance devices may display large base64-encoded pictures in new browser tab instead of load them and get stucked, which is my suggestion for: https://github.com/vector-im/riot-web/issues/2678

**Comment by uhoreg** [comment]
I'm not seeing any inline CSS on messages here.  Can you post a screenshot of your inspector to show what you're talking about?

**Comment by ara4n** [comment]
i’d assume this is viewing the contributed CSS for a message tile rather than inline CSS? i’d have expected the browser to be caching the computed result rather than actually slowing down rendering it for every cell.

that said, there is definitely something wrong on CSS perf, but my hunch is that it might be the amount of flexbox with unbounded size restrictions meaning that the flexbox solver has to work overtime. Someone needs to profile the CSS engine - i’d imagine Quantum might have some good metrics?

**Comment by Crystal-RainSlide** [comment]
Well, they are on the green
Download Image
button.

I'd better take a screenshot instead of copy the code here.

**Comment by Crystal-RainSlide** [comment]
![default](https://user-images.githubusercontent.com/16851802/38181187-1fd409b0-3664-11e8-817a-83f3fab2927f.png)

**Comment by Crystal-RainSlide** [comment]
So, it should be in the https://usercontent.riot.im/v1.html

**Comment by ara4n** [comment]
Good catch. Turns out that this ridiculous style is calculated at https://github.com/matrix-org/matrix-react-sdk/blob/07b691a45d14fa817fe9d08d8ed1ecc2886b313c/src/components/views/messages/MFileBody.js#L168 - the problem being that the style of the download link which is rendered in the iframe (as a blunt but effective manner of cross-site sandboxing) has to match that of the parent website.

Looks like the style calculation was done in the bluntest way possible rather than just applying the 'correct' style needed to render the link in the right colour & font :/

However, this only impacts the download links for files sent in e2e encrypted rooms, so the original description of:

> There are 150+ inline css code for every message.  That's really massive.
> ...Pick a element to reproduce it.

is quite an exaggeration.

**Comment by ara4n** [comment]
A better solution would be to kill off usercontent.riot.im entirely, as per https://github.com/vector-im/riot-web/issues/6173

**Comment by Crystal-RainSlide** [comment]
Thanks for the informing~
