### ISSUE TITLE
avatar image missing after redacting display name change

### ISSUE THREAD

**Issue by ghost** [vector-im/element-web#6419]
### Description

Changing the display name causes the account's avatar image to no longer display. It continues to not display even after being re-uploaded.

### Steps to reproduce

* first ensure you have an avatar uploaded and that it displays properly
* create a room (or access an existing one)
* enable e2e (not sure if this even matters)
* open the account settings and change the "Display name"
* reenter the room and remove the activity concerning the display name change
* type a message
* you should see that the avatar image has reverted to a default circle with the first character of the display name
* open settings (the correct avatar image is still there)
* try uploading the original avatar image again
* go back to the room and type something (still no avatar image)

NOTE: this will not effect previous messages in the room which occurred prior to changing the display name, only those subsequent to the change and in the room member list.

### Version information

Riot Desktop on Linux
riot-web version: 0.13.5
olm version: 2.2.1
Homeserver is https://matrix.org
Identity Server is https://vector.im

**Comment by turt2live** [comment]
I can't reproduce this. 
![image](https://user-images.githubusercontent.com/1190097/38118942-a08da732-337b-11e8-9054-9185fc614c3b.png)

Is it possible the X highlighted in pink below was accidentally pressed?
![image](https://user-images.githubusercontent.com/1190097/38118964-c288991e-337b-11e8-828a-5c056c76d45a.png)

**Comment by metasintactic** [comment]
I left something out. I also deleted the activity in the room mentioning that the display name had been changed. apparently rooms where I didn't do so remain unaffected.

**Comment by turt2live** [comment]
Ah, that's a "feature". By removing the display name change event, the client thinks you want your previous avatar which may have been nothing. 

The best issue I can find to relate this to would be https://github.com/vector-im/riot-web/issues/3214 based on it's references to https://github.com/vector-im/riot-web/issues/2869 which describes confusing behaviour.

**Comment by metasintactic** [comment]
hmmm. that's strange. because when I remove the display name change, I literally just want to remove the display name change. do you know of a way to replace the avatar?

tbh, I personally feel it's only a minor issue, because it's purely cosmetic, but it strikes me as rather silly to interpret one action as indicative of what seems to me like an entirely unrelated action. very misleading.

**Comment by turt2live** [comment]
There's not currently a way to change your display name or avatar without an event showing up in every room you're joined to. This is more of a limitation on the matrix side of things at the moment.

The 'Remove' button doing more than you expected is also due to how Riot works under the hood. "Removing" events is also known as "redacting", where the intended action is to redact the event from the timeline, ripping it from the history. It's not very clear, however features like #5649 would help with the clarity (hopefully).

**Comment by metasintactic** [comment]
okay. if I understand what you're saying (not having looked under the hood as yet), when you change your display name, it actually creates a new name with a new associated avatar in each room separately, and then announces the change?

if this is all something which occurs on the matrix side, perhaps it's an issue I should address with the matrix team instead. n'est pas? it just seems more than a bit un-intuitive for simply announcing/redacting to the room that a display name has changed to be this inextricably linked to which avatar is presented.

**Comment by turt2live** [comment]
The matrix team will surely see this, so no need to go bug them elsewhere. Just to clarify though: is your intended behaviour to just hide the change from the timeline? If so, should it hide it from everyone or just yourself?

**Comment by metasintactic** [comment]
preferably it would (at least optionally) remove the announcement of the change for everyone in all rooms. it would be nice to have the option to mute that activity across the board, because it just creates noise, especially if just monkeying around with settings repeatedly. apart from drawing attention to the user unnecessarily, it almost seems like spam to me.

**Comment by uhoreg** [comment]
The key to this issue seems to be removing the display name event, so I've updated the issue title to reflect this.  If hit the "clear cache and reload" button in your user settings in Riot, it may fix the issue for you, though it certainly is a bug that the avatar gets messed up to begin with.

As far as hiding the display name change from others, Riot has a setting to hide display name/avatar changes, which users can set for themselves.  I personally like to see display name changes as it allows me to know that the person that i was talking to ten minutes ago is the same person that I'm talking to right now, even though the display name is different.  There could be ways in which this could be improved (e.g. there have been suggestions to hide display name changes for people who haven't talked in a room yet), but in general, IMHO users should be allowed to decide for themselves whether they want to see display name changes or not.

As for your concern about monkeying around with settings repeatedly, I believe that Riot now collapses multiple display name/avatar changes, so if you do change your display name repeatedly, then Riot should just display one line (unless some other event happens in between your display name changes).

**Comment by lampholder** [comment]
It's not clear from my reading of the issue, but if in the sequence of events @ghost:
- changed their avatar
- redacted the event containing the avatar change

then reverting to the previous avatar (or to no avatar if there wasn't a previous avatar) is the correct behaviour.

If the above is true, then the bug here is that it's not intuitive that the event in the timeline _is_ the change of avatar, and that redacting it will have consequences. If we don't have a warning here maybe we should?

**Comment by uhoreg** [comment]
My understanding of the issue (maybe @ghost can confirm) was that the sequence of events was:

  * they changed their display name (not their avatar)
  * redacted the event containing the display name change
  * this resulted in their avatar reverting to the default avatar
