### ISSUE TITLE
room names aren't upheld in group room list in rightpanel

### ISSUE THREAD

**Issue by ara4n** [vector-im/element-web#6512]
if i add #matrix-fr:matrix.org to +community:matrix.org it turns up as 'Unnamed room' in the rightpanel, rather than correctly falling back to being shown by its alias as per the LeftPanel

**Comment by t3chguy** [comment]
This is due to `-fr` not having a Canonical Alias set it seems
![image](https://user-images.githubusercontent.com/2403652/41822774-e7ea82a2-77ec-11e8-8c6c-5596a09c578d.png)
and as per the Groups API draft we don't get any non-canonical aliases:
https://github.com/matrix-org/synapse/blob/46f9d9719b4bfa265a22119191e9472127f62d13/synapse/groups/groups_server.py#L547
as per https://docs.google.com/document/d/1UxDgDYWzEYBpxMQmiZ_vTIrZHoZqlhi8fJKFE1HlGvE/edit#

**Comment by t3chguy** [comment]
This is fixed by Spaces landing in Beta in next Release
