### ISSUE TITLE
Custom link text can be used for phishing 

### ISSUE THREAD

**Issue by dbkr** [vector-im/element-web#6532]
Possibly even conditionally whenever link text is, "this", "here", "click here" etc

**Comment by lampholder** [comment]
So an option in settings that, when checked, auto-replaces any link posted with link text 'this', 'here', or 'click here' or similar and replaces it with the much-more-enlightening actual URL.

**Comment by lampholder** [comment]
I found myself wishing for this recently - the GDPR message text from the server notice room is particularly noisy with the URL previews.

Talking it through with @lukebarnard1 we concluded that perhaps this could be implemented (on the rendering side) by adding a custom attribute to the HTML of the link in the `formattedBody, something like `data-mx-preview=false`.

This would allow any clients who submit a formatted body to supress the preview - the question then is how to provide the UX for this. Something like discord's &lt;url&gt; _could_ work, but it doesn't play very nicely with established markdown conventions.

**Comment by t3chguy** [comment]
@lampholder I don't think thats what this issue is

**Comment by t3chguy** [comment]
@lampholder I think you want https://github.com/vector-im/riot-web/issues/6632

**Comment by lukebarnard1** [comment]
._. I self-assigned? ... I don't remember doing that ...

**Comment by lampholder** [comment]
How did I... 😕 

/me puts his comment on the right issue.

**Comment by lampholder** [comment]
Ah, you already did - thanks :D

**Comment by lampholder** [comment]
I'm going to tidy this bug up now - thanks for your vigilance, @t3chguy

**Comment by Twi1ightSparkle** [comment]
<img width="630" alt="Screen Shot 2020-08-17 at 11 45 49 AM" src="https://user-images.githubusercontent.com/19155609/90388152-49b09880-e07f-11ea-8fe4-9dbc4edada4a.png">


Including for example

`/html`
```html
<a href="https://google.com">https://bing.com</a>
```

`markdown`
```markdown
[https://bing.com](https://google.com)
```

Another solution is something similar to what Discord is doing. When you click a link they ask you if you trust the domain and you can allow once or always allow.

**Comment by Twi1ightSparkle** [comment]
The solution in Element iOS is very nice: 
![IMG_0379](https://user-images.githubusercontent.com/19155609/90391368-ef1a3b00-e084-11ea-9297-b6fba4f828b2.png)

**Comment by babolivier** [comment]
ftr that's what Thunderbird also does:

![Screenshot from 2020-08-17 14-09-40](https://user-images.githubusercontent.com/5547783/90399725-53dc9200-e093-11ea-87f9-8af4532e0875.png)

**Comment by HarHarLinks** [comment]
Depending on your browser, hovering a link shows the target in some status bar, e.g. down below here:
![image](https://user-images.githubusercontent.com/2803622/142208008-82537302-23db-4819-a064-aeddc12876fb.png)

On desktop, the only way I know how to preview a URL is to right click, which isn't good enough as it might be cut off after certain length.

In my opinion, a tooltip on hover is also more intuitive for most users. I would like to see that added.

Overall I am sad to see this issue existed for 3.5 years now, and concrete suggestions to prevent clear phishing attempts by checking for url mismatch have been made over a year ago, but as far as I know nothing has been done. Especially since it seems both important (security-relevant) for a system that claims to bolster your privacy, and relatively simple.

**Comment by babolivier** [comment]
@turt2live 

> (please open a new issue with more detailed concerns - reopening this issue would be problematic for the processes in place)

Will do, thanks for the heads up. As a sidenote, I would think that if the processes in place prevent reopening an issue that's been incorrectly closed, then there's something wrong with said processes that needs to be fixed.

**Comment by babolivier** [comment]
I've opened https://github.com/vector-im/element-web/issues/22875 as continuation of this issue.
