### ISSUE TITLE
scrolling back via trackpad-scrolling breaks every time a new page is paginated

### ISSUE THREAD

**Issue by ara4n** [vector-im/element-web#6637]

**Comment by ara4n** [comment]
says @richvdh. i'm failing to repro.

**Comment by lampholder** [comment]
@ara4n this bug doesn't have enough information to triage! Can you describe how it breaks?

**Comment by lampholder** [comment]
Oh, my github hadn't refereshed. I'm failing to repro too - @richvdh ?

**Comment by richvdh** [comment]
1 try to two-finger scroll a room
2 nothing happens
3 click on message panel and try again
4 it works for a while, but then stops
5 repeat steps 3-4 until you throw your laptop out of the window

Of course, it's working fine today.

**Comment by richvdh** [comment]
it's somewhat intermittent. Certainly scrolling in HQ is not a fun experience (and not just because it's full of crap from Certain Users)

**Comment by pointhi** [comment]
HowTo reproduce:

1. go into long chat (which requires lazy-loading). Look into the most recent message
2. stick finger to screen on one of top messages and scroll down slowly
3. redo (2) until new page loads. You see the position in the message-list, you started with the scroll with your finger changes abruptly.

This bug makes working on touch-devices really annoying. Because you cannot reliably scroll up to older messages without losing track of history.

**Comment by t3chguy** [comment]
@richvdh are you still able to reproduce this?

**Comment by richvdh** [comment]
don't think so.

**Comment by ara4n** [comment]
(this was fixed with BACAT)
