### ISSUE TITLE
Reply pop-ups hide messages

### ISSUE THREAD

**Issue by SolarDrew** [vector-im/element-web#6794]
This is a very minor gripe, because I do like the new replies feature, but the pop-up showing the message you're replying to hides other messages at the bottom of the conversation. It would be good if it instead expanded the text box and displayed there, or something similar.

![image](https://user-images.githubusercontent.com/1914702/40501504-f7186a9e-5f7f-11e8-809e-39241a3b03d2.png)

Desktop, Arch Linux, 0.15.3

**Comment by t3chguy** [comment]
Its the same as Autocomplete and other concepts within the app already:
![image](https://user-images.githubusercontent.com/2403652/40502048-a873ab9a-5f81-11e8-8492-ec0c8f9ba266.png)

**Comment by SolarDrew** [comment]
Fair enough, but I feel like my usage of replies so far has mostly been during fast-paced conversations where what I'm responding to is no longer the most recent message. In that situation it's likely that more conversation is happening behind the pop-up, which isn't a problem in itself but is frustrating if they're saying the same thing I am and I don't realise until I send the message. Whereas I don't tend to use commands while I'm trying to keep up with that conversation to the pop-up isn't as much of an issue.

Anwyay, as I said it's a minor and pretty edge-casey nitpick, so thanks for taking the time to humour me :)

**Comment by lampholder** [comment]
We'll certainly consider this if we look to rework the autocomplete/replies popup feature more generally :)

**Comment by bkil** [comment]
This struck me as pretty unintuitive UX from the start and I still can't get used to it. Hence I try to avoid clicking the `reply` button as much as possible, but this is clearly not the solution.

Another drawback is if you are replying to someone who inserts line breaks after each sentence, and you it is difficult to have an overview of what the other is saying if I only see the last sentence.

There are lots of alternative solutions that could all work.

* Dynamically expand the composition box with the quote (as mentioned in the top post)
* Open a textbox just under the message to be replied to and make it automatically expand as needed. New messages should appear below it, at least as long as they fit on screen.
* Instead of displaying the quoted message, simply highlight it with a color background, borders, moving ants or whatever. If it goes out of sight, maybe stick it to the top of the screen?
* Support threads (Slack opens a non-overlapping pane on the right in such cases with the reply)
* A cheap hack, but not the best: align the bottom composition box to the right and make it take up less space, like 66%, so we could at least get a sense of how many replies have already been submitted or are being composed.

**Comment by turt2live** [comment]
This got fixed.

**Comment by SolarDrew** [comment]
Yeah, new version works great. Thanks for sorting this :D
