### ISSUE TITLE
SdkDefaults might be better off as a default config.json instead?

### ISSUE THREAD

**Issue by ara4n** [vector-im/element-web#6806]
Currently we hardcode a bunch of defaults into the app as JS.  This needlessly obfuscates them (e.g. I'd forgotten that we ship scalar as the default integration manager).  I think we might be better off instead including a default config.json with Riot which goes and spells out what those defaults are, whilst also providing a nice example of how to customise them.

**Comment by turt2live** [comment]
fwiw [Settings.js in react-sdk](https://github.com/matrix-org/matrix-react-sdk/blob/master/src/settings/Settings.js) also gives a ton of defaults (although *most* go into `settingDefaults` in the config.json).

**Comment by lampholder** [comment]
This would make wrangling riot instances so much simpler I think.

**Comment by t3chguy** [comment]
Having the defaults be outside of the app means everything becomes nullable or has to be duplicated into code. If a value is needed such as a brand string, we'd need to validate the config and throw an error if an option is missing, this makes upgrades more involved as automated upgrades may end up bricking the app due to missing required config vars. It also makes the config which has to be fetched during app load larger as it has to exhaustively include all defaults. Closing this as having more cons than pros.
