### ISSUE TITLE
Ability to shadow ban users

### ISSUE THREAD

**Issue by turt2live** [vector-im/element-web#6976]
I'm a bit surprised there isn't an issue for this yet (or my github searches suck). Opening on riot-web for visibility.

Shadow bans are where the person doesn't know they are banned, but no one besides them sees their messages. It's basically a room-wide ignore.

Would be nice to pair with https://github.com/vector-im/riot-web/issues/6819

Related: 
* https://github.com/matrix-org/matrix-doc/issues/789

**Comment by simbalion** [comment]
Shadow bans are a social cancer. Let users choose who they wish to ignore.

**Comment by davehayes** [comment]
If a room is marked as public, then I agree that shadow bans are immediately dishonorable. However, I can see this for a moderated room. 

I would love to mark my server's public rooms as immune to shadow bans in a way that users can be assured none of that is going on.

**Comment by simbalion** [comment]
A "Shadow Ban" is when a user is muted without their knowledge. 

It's an evil behavior perpetrated by bullies and holier-than-thous. 

Instead, something similar to IRC's +m and +v bits is completely adequate.

if riot adds shadowbanning as a feature then I will find a way to shadowban riot. Matrix is supposed to be different.

**Comment by davehayes** [comment]
I do understand and agree with much of your position, as I thought I made clear above. (see "immediately dishonorable"). To reiterate, I completely agree that a shadow ban is dishonorable _in a public room_. :) The concepts of "evil", "holier-than-thou", and "bully" are sufficiently subjective that I find myself unable to usefully comment on them in a technical forum such as this. 

I've observed that most of the confusion in this area of discussion comes from not understanding the definition of a **public room**. By the proper definition of this idea, no moderation should be done _at all_ in such a room. Thankfully, matrix leaves this to the decision of the room creator and (by consent and participation) the participants.

What I find to be unclear is whether such a ban should be made available as a tool in a room _clearly marked as moderated_.  As I generally refuse to participate in moderated fora, I'm missing the actual data as to whether a shadow ban in a moderated forum would be useful or not.

**Comment by simbalion** [comment]
I understand the difference between public and private rooms. When you say moderated room, what I think of is AMA style chats and interviews with celebrities. Obviously there are other use cases, such as development channels, but I think those aren't really "moderated" so much as they are "private, with open doors".

My point is a philosophical one. There's nothing wrong with just regular-banning people. The only argument against that model is that the troublemaker could create a new account or use a proxy or whatever to bypass the ban, but this is not as big of a problem as shadowbanners want us to believe, otherwise IRC would have been destroyed by exactly that behavior in the 1990s.

And yet IRC is getting along just fine without shadowbans. 

I've been using IRC for 20+ years and in my experience the best moderation is minimal. Disagreements between users can be solved with /ignore. In Weechat I use a custom /ignore script that replaces nasty people's text with anything I want (I use famous inspirational quotes). That way you don't see the toxic content, without losing track of the timeline. If we were to weigh the two approaches, /ignore wins. 99% of channel drama is inter-personal, and can be, and should be, handled by users' ignore lists. The only time channel moderators should ever exercise their power is to deal with trolls who are targeting the entire channel which is actually very rare. And in those cases, a regular ban is _fine_.

Shadowbanning is one of the things which has destroyed the site Hacker News. It was born on sites like 4chan which exist for the sole purpose of people acting like idiots and trolling each other. It's born of evil, it reeks of evil, and it shouldn't be considered at all for a community-centric project like Matrix.

**Comment by ara4n** [comment]
IRC's had shadowbans for at least the last 18 years; in unreal it's implemented as /shun, for instance - https://github.com/unrealircd/unrealircd/blob/02d69e7d835e40f0c3b53771587e8f697e8c5424/src/modules/m_tkl.c#L223-L246.

I'm inclined to agree that we should be able to see how far we can get without them in Matrix; i'd much prefer a more sophisticated reputation system where users can choose whose filters to align themselves with, rather than ignores being dictated by the room admin.

The main legitimate use case I can see here is if you wanted to silently discard spam from a bot without the spammer realising they're shouting into a void - especially to avoid high traffic levels from an attacker wasting resources.  Given that resources can be consumed quite quickly in Matrix (unlike IRC) this is a bigger consideration.  But this could be left as an exercise for the server admin (like /shun on IRC) rather than risk malicious admins abusing it and equally damaging rooms.

**Comment by simbalion** [comment]
> I'm inclined to agree that we should be able to see how far we can get without them in Matrix; i'd much prefer a more sophisticated reputation system where users can choose whose filters to align themselves with, rather than ignores being dictated by the room admin.

The key thing here is I don't want my /ignore preferences to be dictated by other people's interpersonal disputes, nor should my interpersonal disputes have any reflection on other people's ability to connect and communicate. Except in the most extreme of cases, **any moderation or muting should have the minimal impact** possible. Chatrooms are about bringing people together, not alienating them.

> if you wanted to silently discard spam from a bot without the spammer realising

The entire problem with shadowbans is the "without the person knowing" part. Sure your bot example sounds legitimate but so did the government's excuses for NSA spying. And in both cases they are always abused. There's no reason to be afraid of letting a person know they've been muted/banned. If it has any effect it's likely to teach them to alter their behavior.

And again, the obvious defense against what I just said is "but bots don't care and they might adapt their behavior based on the knowledge". And again the answer to that is, if that were true, IRC would have been destroyed by bot spam 20 years ago. In the real world it just doesn't play out that way. And in the real world shadow bans do significantly more social harm than good.

**Comment by ara4n** [comment]
great, i think we're agreeing :)

**Comment by davehayes** [comment]
> I'm inclined to agree that we should be able to see how far we can get without them in Matrix; i'd much prefer a more sophisticated reputation system where users can choose whose filters to align themselves with, rather than ignores being dictated by the room admin.

I completely agree with the idea of a user-driven system of filtering, since (for reasons I remain unable to fathom) people like to band together and tell others who and what to listen to.  Because of this, in a project I'm working on, I grant users the ability to maintain their own ignore lists and subscribe to others' ignore lists.  In giving users these tools, I now do not have to police and judge the trivially dramatic concerns of verbal conflict (which I am quite unwilling to do). 

> The main legitimate use case I can see here is if you wanted to silently discard spam from a bot without the spammer realising they're shouting into a void

A spammer (defined as someone with financial incentive to ensure their "message" is received by the widest audience) will expect some derision to come from the channel(s) they are spamming to; this is a clear indicator that the message is being delivered. Without this kind of feedback in said channel(s), many spammers will conclude they are being shadow banned and take actions which you are ostensibly trying to prevent despite the shadow nature of the ban. Thus, I find this use case a temporary measure at best.

**Comment by irelativism** [comment]
Agreed shadow bans are a dangerous thing, the best solution is to promote good behavior and incentivize it not the opposite by suppressing bad behavior. So then such actors are in a way more fluidly ignored by the community as a whole given they have lesser of a voice. In effect ban are cancer, but I understand the use of it in current reputation system.

**Comment by irelativism** [comment]
this might also be helpful it seams was censored by core team which is unfortunate /matrix-org/matrix-doc/issues/2811

**Comment by t3chguy** [comment]
https://github.com/matrix-org/synapse/pull/8028 has landed in parts
