### ISSUE TITLE
Email addresses are ending up in m.direct account data

### ISSUE THREAD

**Issue by turt2live** [vector-im/element-web#7484]

**Comment by lampholder** [comment]
So that's `m.direct` which is used to store a mapping of mxids to roomids for the purposes of telling highlighting existing 1:1 chats with a user when you try and create a new one with them, right?

Are the email addresses mapped to rooms containing people associated with that email address? Or is it just total garbage? From this height some clunky interplay between threepid invites and direct messages looks a likely cluprit.

**Comment by lampholder** [comment]
Also, am I right in thinking the negative impact of this (on a user's experience) is restricted to the mis-mapped 1:1 room not appearing in the 'existing chats with this user' UX?

**Comment by lampholder** [comment]
Probably the same problem as https://github.com/vector-im/riot-web/issues/7485

**Comment by turt2live** [comment]
yes

**Comment by turt2live** [comment]
This doesn't appear to be damaging anything and 2018 is hardly actionable. Closing.

**Comment by weeman1337** [comment]
Why not adapting the spec to the real world? I've heard from other client developers that they would be super happy if everything was more in line with the specification. This could done either by adapting the clients to the specification or by changing the specification.

**Comment by turt2live** [comment]
Opening an MSC is always an answer, but in 2018 this was categorically a bug. It's not 2018 anymore though :)

**Comment by giomfo** [comment]
@turt2live Can you confirm a new MSC is required? I would prefer to submit a PR in https://github.com/matrix-org/matrix-spec directly focused on the existing [m.direct.yaml](https://github.com/matrix-org/matrix-spec/blob/main/data/event-schemas/schema/m.direct.yaml)
