### ISSUE TITLE
[object Object] is ending up in m.direct account data

### ISSUE THREAD

**Issue by turt2live** [vector-im/element-web#7485]

**Comment by lampholder** [comment]
Glorious. Very likely the same culprit as https://github.com/vector-im/riot-web/issues/7484.

**Comment by cuibonobo** [comment]
I've noticed this in my `m.direct` as well. The culprit seems to have been when I moved some direct chats from my Rooms group to my People group (I'm not sure how they ended up in the Rooms group in the first place, but that's a bug for another day).

All of the folks that I moved to the People group via the UI ended up like this in the `content` key of `m.direct`:
```json
"[object Object]": [
      "!EQJgwxbLnWjDqlVKLl:matrix.domain.com",
      "!qfhDlraqeTFnGpoKxv:matrix.domain.com",
      "!eZFrmEPOAnKRHHxxYQ:matrix.domain.com"
 ]
```

As a result of this, the folks that I moved to the People group no longer show their avatars in the UI.

**Comment by turt2live** [comment]
This doesn't appear to be damaging anything, and 2018 is hardly actionable. Closing.

**Comment by jplatte** [comment]
It does: Fractal had to work around this and the same will be the case for ElementX because the event can't be parsed into Ruma's corresponding Rust type. It could be worked around in Ruma instead, but I'm not convinced that that's the best solution.

**Comment by t3chguy** [comment]
Well the issue is, it now has to be worked around/handled everywhere, because the user may never again use an updated Element Web which cleans it up

**Comment by jplatte** [comment]
I wonder whether Synapse could take care of cleaning this up 🤔

**Comment by turt2live** [comment]
If we ever figure out a cause, let's open a new issue please. 

For now, it seems like the parsing is a bit too strict on other clients and thus needs to be adjusted.
