### ISSUE TITLE
Registration SMS not delivered to Russia

### ISSUE THREAD

**Issue by im-kulikov** [vector-im/element-web#7494]
### Description

I want to register on default server, but registration sms with code not delivered

### Steps to reproduce

- Russian phone +7...
- Try to register
- Sms with code not delivered

Describe how what happens differs from what you expected.

I want register on default server, but I can't 

<img width="709" alt="register" src="https://user-images.githubusercontent.com/888650/46949592-a65d5980-d08a-11e8-804c-a89e8e1405f1.png">

### Version information

- **Platform**: web (in-browser), desktop and mobile

For the web app:

- **Browser**: Safari Version 12.0 (14606.1.36.1.9)
- **OS**: macOS 10.14 (18A391) / iOS 12.0.1
- **URL**: https://riot.im/app/#/register

**Comment by lampholder** [comment]
Hi @im-kulikov - sorry about this.

To cut a long story short, we've had some difficulties delivering SMS to Russia and I don't think that's going to change soon - you can always register without a phone number.

[The longer version](https://github.com/vector-im/riot-web/issues/3542): our SMS provider says that our connection _doesn't_ support SMS to Russia, so some time ago we turned off phone number registration entirely in Russia. However, some Russian users told us that SMS _had_ been working for them before we disabled it, so we _reenabled_ Russian phone number registration and some people have used it successfully.

So that explains our current situation. It's enabled, but not working for everyone. I expect it works for some carriers and not others, so it would be interesting to know what carrier you're on if you're happy to share. Sorry for the inconvenience!

**Comment by im-kulikov** [comment]
@lampholder Never mind. I just thought the problem was on my side.
my operator is Yota (Megafon). it is one of the most used (gsm) operators in Russia

**Comment by lampholder** [comment]
@im-kulikov thanks!

> it is one of the most used (gsm) operators in Russia

I think it's a question of what regulatory hoops the operator requires us to have been jumped through before permitting traffic (rather than operator capability). So my guess would be that Yota/Megafon are more strict about refusing to send messages with an unregistered alpha originator or UK mobile originator than other networks might be, and we haven't (yet) had the bandwidth to register ourselves with the Russian carriers directly.

**Comment by im-kulikov** [comment]
Oh.. mb you right

**Comment by 532910** [comment]
Looks like it should work now.

**Comment by kittykat** [comment]
OpenMarket [now covers Russia](https://www.openmarket.com/docs/Content/globalcoverage/country/russia.htm) so this should be fixed. Please open a new issue if you are experiencing any problems.
