### ISSUE TITLE
Invites to the temporary guest account created by ILAG don't get transferred to the created user

### ISSUE THREAD

**Issue by turt2live** [vector-im/element-web#7662]
This is a bit complicated to actually cause, and probably doesn't show up in day-to-day operations.

1. Enable server notices in synapse
2. Enable consent gathering in synapse
3. Enable gathering of consent from guests in synapse
4. Open Riot (pointing that homeserver)
5. Receive the server notices invite (automatic)
6. Try to accept and receive the "Set a username" prompt
7. Complete registration successfully
8. Receive "You are not invited to this room"

**Comment by lampholder** [comment]
UGH.

Is guess it is quite possible for a homeserver to be configured with all of those options. It's probably on Riot (as the party responsible for ILAG weirdness) to hide invitations to the guest account (since they don't make any sense in a riot context) but that does feel like Yet Another Hoop for Riot to jump through to maintain the ILAG experience :\

**Comment by turt2live** [comment]
ILAG got removed
