### ISSUE TITLE
Rejoin button doesn't work on develop

### ISSUE THREAD

**Issue by turt2live** [vector-im/element-web#7670]
particularly when rejoining from Historical

**Comment by MTRNord** [comment]
Happened for me with the TWIM Room. It tries to do this request: `https://matrix.ffslfl.net/_matrix/client/r0/join/!FPUfgzXYWTKgIrwKxW:matrix.org` instead of for example doing anything that might maybe be routable. 

Also the `No known servers` error that gets shown in this case is atleast for non tech people a very useless message about what happened.

**Comment by lampholder** [comment]
@turt2live Does it fail specifically on /develop or also on /app? I can think of any changes we've made recently that are likely to have caused this...

**Comment by turt2live** [comment]
I haven't tested /app. This is kinda a reminder that the matrix.to permalink routing didn't actually appear to magically fix this issue.

**Comment by ilmari** [comment]
FWIW, this is still happening both on /app and /develop.

**Comment by aaronraimist** [comment]
Still broken. Just had a user mention that they couldn’t re-join a room after being kicked by IRC bridge. They were getting the “No known server” error so I assume Riot was trying to join using the room ID instead of the alias.

**Comment by t3chguy** [comment]
Related https://github.com/vector-im/element-web/issues/9850

**Comment by t3chguy** [comment]
It empirically works for me but suffers from https://github.com/vector-im/element-web/issues/9850
