### ISSUE TITLE
Registration SMS not delivered to Italy - Vodafone

### ISSUE THREAD

**Issue by aaronraimist** [vector-im/element-web#7741]
### Description

`@stefano.renzi:matrix.org` is unable to receive the SMS message in Italy using a Vodafone number. He attempted to register his phone number on Mac and iOS but never got anything.

He was attempting this around 00:20 on 2018-11-24

https://matrix.to/#/!tDRGDwZwQnlkowsjsm:matrix.org/$1543014368237113ULRBE:matrix.org?via=matrix.org&via=disroot.org&via=riot.tenx.tech&via=intelfx.name

Log: not sent

### Version information

- **Platform**: web (and iOS but I'll just leave it here since that's where all the other SMS issues are)

Related: #5990 #7494 #7672 #13273
I'm not aware of other services having so many issues delivering SMS messages. What is being done differently here?

**Comment by lampholder** [comment]
It's an artefact of our SMS supplier - we're using a provider that is optimised for major enterprises arranging large-scale connectivity on a country-by-country basis rather than the sending of a relatively small number of verification messages globally.

As such, all the hurdles one might normally have jumped through (getting messages classified as informational/transactional rather than marketting, registering local short codes or alpha originators, having a local business entity, etc.) hasn't been done, so we occasionally collide with local quirks.

Without checking the routing profile for vodafone Italy, my guess would be that by default messages are being filtered by the network outside of sociable hours.

We are looking into our options, including addressing particularly problematic territories with our current provider - it's just (unfortunately) something that doesn't have anybody's undivided attention at this moment :(

**Comment by kittykat** [comment]
@aaronraimist @lampholder Could you please confirm if this is still causing issues?

**Comment by aaronraimist** [comment]
Haven't heard anything so closing
