### ISSUE TITLE
I want the ability to delete my account

### ISSUE THREAD

**Issue by AmandineLP** [vector-im/element-web#787]

**Comment by ara4n** [comment]
suspect we need this for legal compliance if nothing else

**Comment by tindzk** [comment]
Would this also remove all the data associated with the account (i.e. messages, uploads) from the server?

**Comment by Roboe** [comment]
Not at the moment, in my experience. I disabled my account at riot.im (I suppose vector.im's identity too) and currently have a lot of problems:
- My account is still accessible. People is reporting that they still can start a chat with me and talk without any informative note of the state of my account, and I won't answer (I'm a polite person, really! This is kind of confusing)
- My account is still part of group chats. Same problems as above. I cannot be kicked out of groups I was admin of (obviously, there are two other admins)
- I still receive e-mails when someone mention me or chat directly with me*. The subscription can be disabled with a link in the mail, but people shouldn't be able to reach me in the first place, and the mail won't be sent, then.

To me it feels like I've been blocked from accessing my account, but my account stills acts as a normal, live account. Weird. Confusing. Buggy.


*= As an unexpected secondary effect, I find e-mails notifications useful, because I can reach back persons who have contacted me on Riot, but I don't have control over my e-mail config anymore.

**Comment by ara4n** [comment]
There's currently a big discussion of this going on over at the synapse repository - https://github.com/matrix-org/synapse/issues/1941, https://github.com/matrix-org/synapse/issues/1853 and https://github.com/matrix-org/synapse/issues/2017.

We clearly need to :
 * [ ] Part all rooms when you deactivate your account
 * [ ] Somehow advertise that the account id deactivated when people try to invite it - this is related to https://github.com/vector-im/riot-web/issues/1597
 * [ ] Disable all notifications

@Roboe sorry for the mess here :(  (out of interest, why did you deactivate? just so I can check we have bugs covering whatever else went wrong for you)

**Comment by Roboe** [comment]
Oh, great! I will subscribe to those other issues, better.

@ara4n No problem so far, I was happy using Riot, but have a lot of communication channels and I signed off all of them except two or three. Eventually I needed to create a new account again on Riot for some matters, so I'm using it again, ironically. It would be awesome if I could enable my old account somehow, since no information was deleted, but I don't feel this is the space to talk about this.

**Comment by ara4n** [comment]
if you can provide proof of ownership of your old account we can reactivate it (at least until this bug is fixed!). feel free to ping me at @ matthew:matrix.org

**Comment by akhilman** [comment]
Same here. My deactivated account @akhilman:matrix.org still tries to take my nick name in IRC network.

I decided to move my account to less busy server because of lags in matrix.org.

**Comment by sanjabonic** [comment]
Lags on the IRC bridge and sometimes just whole messages not appearing made me deactivate but same problems as stated above. It appears to others as if I'm still there. The option to delete should be there - and already deactivated accounts should be deleted.

**Comment by sanjabonic** [comment]
Update after well over a month of no reply via email nor on the issue. If you want to get back control of your nickname in IRC, ghosting doesn't work (at least it didn't for me, still told me my nickname is in use).

These are the steps I took to get my nick back:

* identify yourself on IRC (assuming you're registered)
* /msg NickServ release $NAME (maybe that already did the trick, hard to debug now that it worked)
* /msg NickServ regain $NAME (not sure this was necessary)
* /nick $NAME (hooray! it works)

**Comment by ara4n** [comment]
@sanjabonic sorry for the lack of feedback on this - ironically we've been busy designing and implementing the feature here as part of GDPR preparation.  See https://github.com/matrix-org/synapse/issues/1941#issuecomment-384116450 for more details. I suggest folks use the synapse bug as the canonical one for this.

**Comment by sanjabonic** [comment]
@ara4n Thanks for the information! :)
 
Could you please reactivate my account so I can re-use it (sent email with more details on March 8)? Seems that account deletions will be made available but will need 2FA. Good way to solve it. Currently, I see Matrix (with IRC bridges) as the best option for open source communities and I want to use it more extensively.

**Comment by t3chguy** [comment]
Erasure is now an option, leaving this issue open to track the depth thereof

**Comment by sanjabonic** [comment]
@t3chguy Is there an option for already deactivated accounts? Because I can't log in and can't therefore erase anything.

**Comment by t3chguy** [comment]
@sanjabonic there is not. You must contact the operators of the homeserver you were using. (Riot is just an in-browser client)

**Comment by turt2live** [comment]
@lampholder we have account deactivation now - does this cover it?

**Comment by sanjabonic** [comment]
@turt2live Account deactivation was always there (at least according to the user interface) - but deletion isn't and currently deleted accounts are stuck. I'd really like my account either deleted completely or be able to get my username back.

**Comment by lampholder** [comment]
Unfortunately, the account deactivation is the best we have and it's the best we _can_ have unless/until Matrix moves away from the current model of matrix ids.

That said, the account deactivation we have now is a lot better than when @sanjabonic et al. tried to deactivate their accounts in the past. If you deactivate your account today, you will leave rooms and your email addresses will be disassociated from your (now disabled) account.

Fundamentally, we can't just delete/reallocate matrix ids: @ bob:matrix.org can't ever be deleted and reallocated because that user's messages and permissions etc. are _directly associated with the string "@ bob:matrix.org"_ - if that mxid were ever reallocated there would be no way to distinguish new bob from old bob, which could leak all sorts of private information.

@sanjabonic - please let me know your old matrix id and what symptoms you're still experiencing and I'll look into sorting it out.

**Comment by sanjabonic** [comment]
Sending an email, thanks @lampholder!

**Comment by harmancasvi** [comment]
Hello I recently had an issue with a bug that deactivated my account (see #5148 where I commented).

I'd like my username back (just to be sure), or my account permanently deleted. Can anyone please help me without using matrix or IRC?

**Comment by dbkr** [comment]
This case was presumably resolved, and since we have deactivation, I'm closing this. If we want to work out how to really erase accounts, that can get its own explicit issue.

**Comment by Roboe** [comment]
It was not, for me, but I desisted after two years.

**Comment by increasingawareness** [comment]
I'm confused why this issue is closed. The issue asks to delete the account, not to deactivate it. I believe it should be reopened.

I was surprised to learn that I could find an old deactivated account, with my profile picture and invite my deactivated account to a room. It's not clear upon deactivation that the account is still publicly listed and retains the profile photo.

**Comment by turt2live** [comment]
@increasingawareness what you're seeing sounds like a server-side bug, not an issue with the problem described by this issue. Please report the concern to the server (for matrix.org, this will be abuse@matrix.org via email).

Locking this issue as resolved because it's resolved.
