### ISSUE TITLE
Redesign: Nunito font limited to Latin only

### ISSUE THREAD

**Issue by marxo** [vector-im/element-web#7949]
- **Browser**: All
- **OS**: Any
### Description
Nunito font doesn't have glyphs for Cyrillic (I'm assuming other scripts too), leaving Cyrillic text in Arial or other sans-serif fonts.

### Steps to reproduce

- Use Cyrillic in your name, messages or any other place in the UI. Serbian, Russian, Bulgarian translation will manifest this issue.

Log: not sent

**Comment by archSeer** [comment]
Same here, the `ž` in my name will display with a different, much bolder font. Note that the diacritics (and therefore also `ž`) are included in the font: https://fonts.google.com/specimen/Nunito

But it seems it was subset to exclude those.

**Comment by jxcl** [comment]
See attached file for example

**Comment by jxcl** [comment]
Example boldness in Cyrillic font.

![Example](https://user-images.githubusercontent.com/108500/50454381-5b6e8680-0904-11e9-9d29-8d5c43e188b0.png)

**Comment by michaelnew** [comment]
This is just personal opinion obviously, but I'd like to vote against using the nunito font at all. Even outside of the missing glyphs, which is obviously a problem, it just looks a bit cartoonish.

**Nunito**
![image](https://user-images.githubusercontent.com/522101/50456638-d044bf00-090a-11e9-82f5-7c4347df64a0.png)
**Helvetica**
![image](https://user-images.githubusercontent.com/522101/50456697-316c9280-090b-11e9-9262-39fbddae4463.png)

**Comment by ara4n** [comment]
So Nunito has a proper cyrillic variant - we just need to hook it up. https://github.com/alexeiva/NunitoSans/releases/tag/v2.500

However, @michaelnew - your problem is something else; Nunito should not look cartoonish (which I agree it does there, due to the weighting and/or antialiasing being wrong). Precisely what desktop env are you using there, and which version of FF? Have you manually zoomed the window at all, or are you using some other window-rescaling behaviour?

For context, it should look like this:

<img width="2032" alt="screenshot 2018-12-27 at 01 08 07" src="https://user-images.githubusercontent.com/1294269/50461124-feaab480-0973-11e9-9463-3e10f8d9fe9f.png">

...which hopefully looks much less cartoony.

Even if I zoom things to roughly the same size that you have there, it should still look okay:

![screenshot 2018-12-27 at 01 13 02](https://user-images.githubusercontent.com/1294269/50461194-98726180-0974-11e9-9a9e-33613e9c78d1.png)

**Comment by michaelnew** [comment]
@ara4n Ha, that looks *way* better. Thanks for the screenshots. Turns out this was definitely on my end.

Apparently I had Nunito installed locally, but only bold/light/regular. I'm not sure what package was responsible for that, but deleting them from `/usr/share/fonts/TTF` fixed it. It only showed up this way in Firefox (not Chrome) for whatever reason.

Sorry for the noise. Maybe there's some commonly installed package that installs those fonts (I'm on Arch Linux using i3 in case that has anything to do with it), so if anyone else happens to have the same issue hopefully this helps.

**Comment by Ai-rin** [comment]
Example of japanese.
![screenshot_20190130_193035](https://user-images.githubusercontent.com/29887769/51996315-8466d600-24c5-11e9-93b9-ee1321273a6a.png)

**Comment by archseer** [comment]
Yeah, anything non-ASCII is broken, not just Cyrillic.

**Comment by ara4n** [comment]
fixed for cyrillic and vietnamese at least. there simply isn't a Japanese variant of Nunito, so someone will need to propose an alternative font to use there.

@Ai-rin how obnoxious is the one shown in your screenshot? Or should we fall back to Open Sans (the previous font) for non-Latin/Cyrillic/Vietnamese?

**Comment by archseer** [comment]
Noto Sans JP is probably a decent alternative. Or you could drop custom fonts and just use `system-ui` defaults in the design?

**Comment by Ai-rin** [comment]
@ara4n Honestly, the previous font was much easier for my eyes and I'd prefer to continue using it for everything (fonts setting in preferences?). So, i vote for Open Sans for now.

**Comment by vagnum08** [comment]
Greek is broken too.
It is somehow partially supported.
By partially I mean three letters (Delta, Sigma, Omega and only in capitals).

This leads to funny looking text like ![nunito](https://user-images.githubusercontent.com/16070176/52888063-29dea280-3172-11e9-81f4-44d72e7348bf.png)
With Open Sans it looked more like this ![open sans](https://user-images.githubusercontent.com/16070176/52888130-63171280-3172-11e9-99f6-b09ff31f08d9.png)

That said, I vote for Open Sans too.

**Comment by Ai-rin** [comment]
Noto Sans works even better: clean look and less eye strain.
I'm using it with riot.im now.

**Comment by dimkard** [comment]
In latest KDE Neon user edition, Nunito not-installed locally, greek letters μ and π are smaller than the other letters. e.g. :

![screenshot_20190224_165308](https://user-images.githubusercontent.com/5058312/53302932-005a0100-386d-11e9-89f7-531356c8b12e.png)

**Comment by gsbhasin123** [comment]
I recommend using Fira Sans (or Fira Go, it's fork with support for more languages instead of falling back to another font).

Very nice font, works great!
Or, at least allow the user to change their font.

I used to like Nunito but fira sans is just.. better

**Comment by turt2live** [comment]
We replaced the font with Inter.
