### ISSUE TITLE
Feature request: add option to have "community" with rooms without a community

### ISSUE THREAD

**Issue by PureTryOut** [vector-im/element-web#8013]
I'd like to have an extra fake "community" which just lists all rooms not in any community that I'm a part of. In my case I'd like to have this "community" instead of the "clear community selection" button currently in `/app`, so it should probably be an option.

**Comment by ashkitten** [comment]
i'm trying to bring a community over from discord right now and this is blocking me from doing what i want, because if i create a bunch of rooms to organize the community how i had before, it would mean flooding everyone's room list with rooms that only belong to that community and are only relevant there.

**Comment by t3chguy** [comment]
Metaspaces lab enables this
