### ISSUE TITLE
Avatars in typing notifications are off-center

### ISSUE THREAD

**Issue by turt2live** [vector-im/element-web#8162]
![image](https://user-images.githubusercontent.com/1190097/51397675-f242f300-1afe-11e9-8ba1-448daf114026.png)

The "A" should be centred

**Comment by kittykat** [comment]
It looks like they might not be centred so that it's easier to see the letters when the avatars are overlapped:
![Screenshot from 2021-09-15 14-38-36](https://user-images.githubusercontent.com/51663/133443966-953c9e39-23ea-43ee-9006-47c2f8436454.png)

They don't look that great centred (in Explore rooms) when stacked:
![Screenshot from 2021-09-15 14-40-20](https://user-images.githubusercontent.com/51663/133444142-badb7bac-8df6-4215-b7a5-fda9fb39c0f9.png)

**Comment by turt2live** [comment]
I feel we fixed this at some point, or I became blind to the issue. If people are still seeing this, please open a new issue with fresh information.
