### ISSUE TITLE
When I'm trying to type a message, suppress keyshare dialogs

### ISSUE THREAD

**Issue by turt2live** [vector-im/element-web#8270]
I was setting up a new device to test something and it naturally ran into a ton of undecryptable messages because it was new. I was then trying to continue my conversation in another device and was bombarded with randomly-timed dialogs, interrupting my typing. I gave up and switched accounts as a result.

**Comment by lampholder** [comment]
What metric to use?

- if you have any text in the composer, suppress keyshare dialogs?
- if the composer gained focus/changed state in the last 30 seconds, suppress keyshare dialogs?
- something else?

**Comment by turt2live** [comment]
I prefer option 4:
* Don't use a dialog and find a new way to get my attention. 

It's increasingly infuriating how often this happens in testing, to the point where I often rage-close the tab just because I don't want to deal with the prompt.

**Comment by jryans** [comment]
Yeah, I agree a modal dialog that comes up "seemingly randomly" (based on actions from other devices) like this is not great, since it blocks all progress on whatever else you were doing. 

Maybe we could instead do something like... put a notification marker on your account in the top left menu when the key share request is received, and then have a "Share keys to your other devices" option in the menu that then enters the sharing UI (which could still be the same dialog as today)? (Maybe it's a terrible idea, unsure.)

Anyway, a different UX that doesn't block progress would be much better.

**Comment by aaronraimist** [comment]
I just had it where someone, I guess accidentally, started the verification process and it popped up while I was typing. My first though was oh s*** someone got in to my account and was sending me a verification request from "my own" device. The user field never loaded, it was just a spinner but I opened the browser console and saw of course that it was from some other user.

It seems like this could be used as a mechanism for spam/annoyance so this is a pretty important bug because it's not just based on actions from your own devices, but also from other people.

**Comment by aaronraimist** [comment]
Related: #4908

**Comment by jryans** [comment]
These dialogs have been replaced with a different flow when cross-signing is used (https://github.com/vector-im/riot-web/issues/11904), so perhaps we can consider this (nearly) solved, though we probably want to keep this issue open to have a place to point people until cross-signing has been released.

**Comment by t3chguy** [comment]
Cross-signing has been released, the dialogs are gone.
