### ISSUE TITLE
get rid of ugly  **s from UISI  warnings

### ISSUE THREAD

**Issue by ara4n** [vector-im/element-web#8415]

**Comment by aaronraimist** [comment]
![screen shot 2019-02-10 at 9 15 34 pm](https://user-images.githubusercontent.com/5855073/52544837-033af900-2d79-11e9-8957-9d7bfa097da9.png)

This probably needs a new icon otherwise it just looks like any other unverified message

**Comment by anoadragon453** [comment]
![image](https://user-images.githubusercontent.com/1342360/61307368-1a798900-a7e6-11e9-985c-befa1c072825.png)

Additionally, it's currently quite easily to spoof this message yourself. Some suggestions for improvement are:

* Make the message highlighted. If the message isn't highlighted, since it likely doesn't include your name, it's probably not a real encryption error.
* Have a different way of presenting the error altogether. Surround some text in a red border or something.

**Comment by uhoreg** [comment]
see also https://github.com/vector-im/riot-web/issues/4563

**Comment by turt2live** [comment]
Closing in favour of https://github.com/vector-im/element-web/issues/20532
