### ISSUE TITLE
Don't warn about the effects of redacting state events when redacting non-state-events

### ISSUE THREAD

**Issue by NotAFile** [vector-im/element-web#8478]
### Description

#3470 added a dialog to warn about redacting state events when removing events. However, this is unnecessary and confusing for non state-events. This message should not be shown when deleting regular events.

### Version information

- **Platform**: web
- **Browser**: Firefox Nightly
- **OS**: Fedora
- **URL**: riot.im/develop

**Comment by lampholder** [comment]
This warning?

![image](https://user-images.githubusercontent.com/1922197/53005178-9be11100-342a-11e9-9718-45c915652c89.png)

I think we probably do want a confirmation dialogue for removing messages; I think the biggest problem with this message is that nobody ever reads it (I know I haven't). Maybe the solution is to have different dialogues - a bland confirmation one for regular events, and a warning consequence-alerty one for state events.

The optimal UX might be for removing regular events to be guarded with an undo rather than a confirmation dialogue, but I feel like the complexity and risks of that implementation probably outweigh its value.

**Comment by NotAFile** [comment]
agreed on your points. I think having two different dialogs is the way to go.
