### ISSUE TITLE
We should provide another way besides config.json to enable labs

### ISSUE THREAD

**Issue by turt2live** [vector-im/element-web#8498]
For people who run /app (or the desktop app) and really want features, understanding that they are labs. Alternatively, we just enable labs everywhere

**Comment by lampholder** [comment]
I don't think I agree - putting a feature into labs represents part of our conversation with our users, and to my mind being in labs on /app means something different to being in labs on /develop.

How I see it:

labs on /app == a stable but incomplete feature we'd like people to try out to give feedback on the feature set/ux design
labs on /develop == the above, + an unstable feature we'd like people to try out to give feedback on the stability/edge cases

**Comment by turt2live** [comment]
I'm not suggesting we enable everything or even make it easy. Just something for the power users to do to enable them.

Currently we ignore all settings for labs if they are disabled. One option is changing this to respect the account level setting regardless of labs enablement.

**Comment by Awoolyx** [comment]
One day, one day...

Having a toggle for experimental features instead of having to edit the config is very important for any app that respects every-day users. There's people that want access to experimental features that just don't want to bother modifying config files or download a special dev version.

Sure, it's easy, but it's still harder than pressing "I'm okay with labs" with a warning on top.

You can argue that you don't want labs in the settings easy to access, but you can also argue that there's users that just at least wanna check them out, or as prior mentioend, just don't want to bother with config files.

Like, this is just a UX thing. You don't need to make it *too difficult*, but also not too easy. That means, instead of a single switch of a button, you also have the user click a big red button that warns of bugs or issues.

Example:
![image](https://user-images.githubusercontent.com/57874862/153867007-6df85bf4-5d68-4f2e-bf38-f19d79a5d511.png)

**Comment by t3chguy** [comment]
The other issue is, getting lots of labs-related feedback when they're testing old versions wastes a lot of development time. If you're using features which change every day, you should be on develop/nightly otherwise you are more likely to have a buggy version.
