### ISSUE TITLE
Give back total number of room members in interface

### ISSUE THREAD

**Issue by MurzNN** [vector-im/element-web#8532]
In old design members button contains number of room members, in new design this number is disappear. So now not so easy to count exact number of room members.

I must count manually visible people in list by finger and sum it with `and XXX others` number on calculator. 

On large rooms list contains many items, but I have only 10 (20) fingers, so for count I need additional finders from friends ;-)

So, please give back number of room members to interface, or give me additional fingers =)

**Comment by jared2122** [comment]
I'd like to co-sign on this. The number indicator next to the rooms dropdown and the indicator for the total number of people in the room are very useful.

**Comment by DJCrashdummy** [comment]
i'm in general for a small improvement concerning the member-topic and the right panel (#8688)...

probably the number of members in the tool-tip would be nice, or even more obvious (at least if my suggestion gets implemented) would be to integrate the number of members into the default text of the filter: *"Filter XXX room members"* instead of just *"Filter room members"*

**Comment by t3chguy** [comment]
Fixed by https://github.com/matrix-org/matrix-react-sdk/pull/5167
