### ISSUE TITLE
Failing to join a room with history available to members only

### ISSUE THREAD

**Issue by AmandineLP** [vector-im/element-web#884]
access as guest
find a room with the right setting (guest allowed but history available to members only (whatever of the 3 options))
click join
set display name and click set
room is accessed but in preview mode (can(t type), history is visible

**Comment by AmandineLP** [comment]
Also: they don't see themselves joining and don't see latest events and messages (but other members have the join event in the timeline)

**Comment by dbkr** [comment]
I'm assuming you're testing this in with #testingGuest:matrix.org? It looks like this room has managed to get into a state that's confusing synapse. The last even I see is you disabling guest access, yet vector behaves as if it's allowed to join the room as a guest, and indeed the join request succeeds, yet no new member event appears in the room which is why vector never gives you a message composer or puts it in the recents (although I have once seen a guest user appear in the room whilst joined to it as @dave:matrix.org, but that join event never arrived on the guest in question's stream!)

**Comment by dbkr** [comment]
Filed as https://matrix.org/jira/browse/SYN-623

**Comment by AmandineLP** [comment]
agreed, dropping priority

**Comment by t3chguy** [comment]
Closing in favour of https://github.com/matrix-org/synapse/issues/1492
