### ISSUE TITLE
Riot doesn't load the right config file when using a fully qualified domain

### ISSUE THREAD

**Issue by babolivier** [vector-im/element-web#8858]
When using a fully qualified domain (e.g. webchat.kde.org. instead of webchat.kde.org), Riot won't find the right configuration for the requested domain and will therefore load a default one.

**Comment by lampholder** [comment]
Today I learned that FQDNs have a full stop on the end of them.

I wonder if Riot would do the right thing if the there were also a `config.webchat.kde.org..json` config file?

I'm going to give this a pretty low priority because I think that, even if this is tricky to work around, the likelihood of encountering it is very small.

**Comment by ara4n** [comment]
who would ever enter a DNS record FQDN with a trailing period?

**Comment by t3chguy** [comment]
> I wonder if Riot would do the right thing if the there were also a config.webchat.kde.org..json config file?

It would
