### ISSUE TITLE
Add icon to room tags or show the full name of the tag

### ISSUE THREAD

**Issue by aaronraimist** [vector-im/element-web#8870]
Just seeing the first letter of a tag isn't very helpful. I would be nice if you could choose to show the full name of the tag (at a small font size) or be able to add an icon to the tag to make it more recognizable.
![screen shot 2019-02-21 at 7 17 31 pm](https://user-images.githubusercontent.com/5855073/53213173-7ceea480-360d-11e9-9d3b-e381fa28f8d5.png)

**Comment by turt2live** [comment]
a bit of historical background: Avatars are hard because tags are determined based on the rooms and are not a citizen themselves. There's some argument in having metadata on one of the rooms (or maybe just the first one) to assist in the tag's rendering.

Also this isn't an excuse to not fix it, just a bit of information as to why this is hard under the current constraints. A MSC might be worthwhile for fixing this.

**Comment by aaronraimist** [comment]
Closing since spaces can do this
