### ISSUE TITLE
users who haven't accepted the system alerts room invite don't get MAU limit alerts

### ISSUE THREAD

**Issue by ara4n** [vector-im/element-web#8897]

**Comment by ara4n** [comment]
also, it doesn't seem that MAU alerts get sent to users who haven't joined the system alerts room yet?

**Comment by michaelkaye** [comment]
michael has an example of a user with a room who should have had an alert but didn't; matthew has a user who did get the alert at the same time.

**Comment by lampholder** [comment]
Allrighty. Couple things here:
- if the user is in the room but the room didn't get the message, that's a synapse bug. @michaelkaye is that what happened?
- @ara4n I've read your two statements a bunch of times and I can't see that they say anything different from each other. If you're not in the SA room (either because you've not accepted the invite, or you accepted it then left), you don't get the messages. This is a flaw in our initial design, and I suspect can only be resolved by making membership of the SA room mandatory (we may specialcase the room in Riot to allow users to _appear_ to leave it, but they need to be joined members if they are to receive down the sync the events that Riot is going to translate into warnings)

**Comment by t3chguy** [comment]
We now show it in the connection bar
