### ISSUE TITLE
Option to loop videos too

### ISSUE THREAD

**Issue by turt2live** [vector-im/element-web#8909]
for when people don't upload webp, etc and still want to loop their mp4. Might need a special flag on the event though?

**Comment by turt2live** [comment]
Duplicate of https://github.com/vector-im/element-web/issues/4546

**Comment by naimesedzou** [comment]
The existence of video auto-loop in Telegram resulted in me substituting video almost entirely for GIF.  This feature would be especially useful for self-hosting, since the far-more efficient video formats save server space, in addition to providing a better user-experience.  Not only is the quality much better, sending / receiving, generally faster, and playback, less laggy, but also user options, in terms of resolution, length, and, as a result, variety of applications for use, are substantially greater.  This is one of the features I most miss from Telegram.  This was particularly useful with Telegram because of the ability to use HEVC,¹ though it seems that iOS recently added support for VP9 over WebM playback, which does help to mitigate the need for HEVC support in iOS Element.  

────────────────────
¹	I'd also love to see HEVC support, but I believe that's already been discussed at length, and the developers said it was unlikely to be implemented, favoring eventual support for AV1 instead.  I used HEVC all the time with Telegram, since it was efficient and supported across devices, although, my usage was somewhat unorthodox I think—I'd generally encode on PC with x265 in 8bpc, 4:2:0, but with otherwise more demanding settings.  I noticed that, if these files were sent via the mobile Telegram app, they'd always be re-encoded (I believe to AVC) with substantially less-efficient settings, resulting in a larger (usually, substantially so) video file at lower quality (unless sent without compression, resulting in it being displayed as a small icon instead of a large, auto-looping video); however, if I instead sent the same file using the PC desktop client (just drag-drop), the full-quality original would be sent without re-encoding, but it would be displayed as large, auto-looping video, as though it were sent with the 'send as video' ("compressed") option instead of as a smaller icon, the way using the 'send file' ("without compression") option displays.  Further, these full-quality versions were displayed in this fashion across devices, and I never noticed any issues with playback (my testing has involved PC and Linux clients, iOS on an iPhone X, and several newer Samsung Android devices).  One more note, although I think this may have changed recently—at least on iOS, these videos would always have the 'GIF' text label by the video (like a GIF would have), but the video being displayed was the full-quality version, and I was able to confirm that the file being set was in fact the original by downloading it to the device, initially confirming the metadata was as expected, and then transmitting the file back to the PC (using some lossless channel, such as sFTP or samba), and confirming the hash value was identical.
