### ISSUE TITLE
Change misleading navigation in communities

### ISSUE THREAD

**Issue by LavenderTheGreat** [vector-im/element-web#8915]
As of right now, the layout for communities seems to be relatively difficult to navigate due to the following:
- Clicking a community icon in the sidebar seems to do nothing but put the rooms into focus on the side, I feel it should be something more noticeable like redirecting you the main page, that you usually do via the right click menu. Swapping them around could be a good idea. Below I have shown an idea for a before and after of the right click menu, alongside what I think clicking the community icon should do.

![image](https://user-images.githubusercontent.com/34808998/53297971-52276a80-381e-11e9-86ff-c929d96e1fdc.png)

![image](https://user-images.githubusercontent.com/34808998/53298023-3375a380-381f-11e9-8c45-bd7d51104f68.png)

- Alongside this, for management, I think the room addition icon, while in communities, should at least have a drop down allowing you to create rooms and automatically link them to the community, much like how it adds rooms to Discord guilds.

![image](https://user-images.githubusercontent.com/34808998/53298056-cf071400-381f-11e9-9e90-dd66541030dc.png)

Feel free to ask for any further clarification and voice your opinions on the idea.

**Comment by Croydon** [comment]
Somewhat connected: How can I unselect a community to display again all rooms/chats? I can't figure that out anymore since the re-design

**Comment by jryans** [comment]
> Somewhat connected: How can I unselect a community to display again all rooms/chats? I can't figure that out anymore since the re-design

You can do this by clicking in the empty space of the community bar where no communities appear. (It's quite hard to discover.)

**Comment by Powersource** [comment]
Yeah having to click the bar is horrible and impossible to discover.

**Comment by ell1e** [comment]
How about:

1. Removing communities as a filter entirely, and making them a dedicated tab as on discord
2. Remove "People"/"Room" separation and only show rooms when a community is selected, and add a DM button at the top of the community list like discord
3. Move the "View Community" button from the context menu above the room list/below the explore & search entry to make it very visible once inside a community
4. Only use community members as a way to list them on the view community tab and otherwise they're irrelevant now

Obviously this has downsides, like it'd no longer possible to do DM filtering by community, or to view rooms of multiple communities at once. But I've heard from people working at e.g. mozilla (who might benefit from this, or anyone with a more corporate separation needed anyway) that they tend to prefer separate accounts anyway for work/non-work. Also, every single person I ever saw try matrix was intensely confused by this, so I just don't think it is worth it and I think you should consider just letting it go.

All these changes combined would IMHO likely remove all of the confusion navigating around communities for the most part

**Comment by t3chguy** [comment]
> Removing communities as a filter entirely, and making each a dedicated tab as on discord
> Remove "People"/"Room" separation and only show rooms when a community is selected, and add a DM button at the top of the community list like discord

The sheer difference there is a room in Matrix can be in 0 to infinite different communities. When would you see the rooms which don't belong to a community (most existing rooms)?

**Comment by ell1e** [comment]
Why is it necessary that a room can be in multiple communities? The rooms not in any community could be on a separate button for them, similar to DMs. So basically from top down the community sidebar would look like this: "DMs", "Unassociated Rooms", "Community 1", "Community 2", ...

**Comment by t3chguy** [comment]
> Why is it necessary that a room can be in multiple communities?

It isn't, but with the current underlying Server implementation that is how it works, Element (the client) can't sanely cover that up.

**Comment by ell1e** [comment]
I mean, in the long run this is probably not possible without server changes anyway. I would suggest room owners eventually just get to pick in what community to stay. Also rooms in multiple communities could still work even if communities stop acting as a filter, a room could still show up in multiple community tabs anyway - but I don't really see it worth keeping either, that is why I brought it up.

It's ok I didn't expect this to be accepted right away. I just wanted to point it out as a radical idea, because I haven't seen a single person like this unnecessary complexity. Who really needs to join a community but not all its rooms? If communities are that large where this is an issue, couldn't there just be multiple? Who needs rooms in multiple communities? Etc. But this is obviously just my personal opinion.

I think your best way forward might be a wider survey what other people think

**Comment by t3chguy** [comment]
There is a whole reword of communities planned, I was just exercising avenues you didn't explicitly consider.

https://github.com/matrix-org/matrix-doc/pull/1772

> Who needs rooms in multiple communities?

A lot of users make personal communities for personalised filtering currently

**Comment by ptman** [comment]
> Who really needs to join a community but not all its rooms?

Me! I'm very often only interested in a small subset of rooms available in a discord "server" or slack team.

**Comment by ell1e** [comment]
> A lot of users make personal communities for personalised filtering currently

I would assume mostly because so many rooms aren't in a community to start with, which is likely because they're so confusing to use.

> Me! I'm very often only interested in a small subset of rooms available in a discord "server" or slack team.

Fair enough. But then again I'm wondering, do you really need that? I'm in 42 discord "servers" (=community equivalent) right now and I'm not interested in all the channels in there either, but that doesn't mean I care that they happen to exist in the respective tabs. There is also a splintering problem right now which makes communities really difficult to use, which is that when creating something which is meant to act as a group of rules channel, community/meme channel, serious on-topic channel etc, most people won't join all of it and it just plain doesn't work, again making communities a pain to use.

But my suggestion would again be either a user survey, or a really long internal talk with all designers to consider all the giant consequences of this. But in the end, communities feel like just a weird filter thing and like it's not really possible to actually make proper communities with people in it that feel as such, a sort of united group, so managing anything but a single channel is just not fun. Again though, just my opinion.

**Comment by t3chguy** [comment]
> I would assume mostly because so many rooms aren't in a community to start with, which is likely because they're so confusing to use.

Sometimes sure, but sometimes users may want their own groupings, where they have all their various related communities under one grouping, say someone was part of 3 Minecraft Discord Guilds and wanted to group them into one.

**Comment by ell1e** [comment]
On discord I'd just have three buttons for the guilds. Is that really so much worse? Also, discord allows just putting these into a folder if you really want to, way easier concept, less powerful too, but again probably enough for most people.

I'm not going to claim this won't upset some people quite a lot, or that this won't lead to some use cases becoming harder. My argument was basically just that maybe you should consider if it's worth keeping it despite of the obvious downsides of switching this concept. I don't think it is, but as I keep reiterating this whole topic is super subjective so we probably won't get anywhere with just a handful of voices on a bug tracker. I was hoping you had some ideas (e.g. surveys) to explore this deeper though, at least if you care about the usability impact of this similarly as I do.

**Comment by t3chguy** [comment]
This is fixed by Spaces landing in Beta in next Release
