### ISSUE TITLE
Consider a privacy-first/privacy-centric mode for Riot

### ISSUE THREAD

**Issue by turt2live** [vector-im/element-web#8961]
Something like turning off typing notifications, read receipts (when possible), etc so as to not leak information to other parties.

**Comment by tiotrom** [comment]
Another idea would be to only mark messages as seen if the user is actively engaging with Riot, like it is clicking the messaging form and starts to type. This way you are truly "marking as read" - so many times I opened Riot to change a setting and it had a room in focus and it marked the messages as "seen by me" without me having any interest in reading them. Ir when I leave Riot in focus and has a chat room in focus and basically all messages are seen as "read by me" even though I am not even at the computer. 
It projects false events. It needs to be way smarter if it is going to respect the user freedom. I feel like my hand is forced every time I open Riot since messages are marked as "seen" even though I either do not read those messages, or I do not want to broadcast that "hey, I am here, and I've seen the messages!". Riot really needs some privacy in this regards.

Cheers!
Signal Messenger has the option to remove the broadcasting of "I am here and I can see your message" thing and I really respect that. Even Skype has the option to be "invisible".

**Comment by lampholder** [comment]
Realted: https://github.com/vector-im/riot-web/issues/8952

**Comment by MasterJubei** [comment]
Wait so emojis aren't being added yet because if some unrealistic way to track users, but you can't disable read receipts? The priorities of this project seem odd.

**Comment by SimonBrandner** [comment]
> Wait so emojis aren't being added yet because of some unrealistic way to track users, but you can't disable read receipts? The priorities of this project seem odd.

I am afraid I don't understand... Emojis are already available in Element...

**Comment by MasterJubei** [comment]
> > Wait so emojis aren't being added yet because of some unrealistic way to track users, but you can't disable read receipts? The priorities of this project seem odd.
> 
> I am afraid I don't understand... Emojis are already available in Element...

Those are stickers though, Emojis are a bit different.

**Comment by SimonBrandner** [comment]
Let's move to [Element Web/Desktop](https://matrix.to/#/#element-web:matrix.org?via=matrix.org&via=privacytools.io&via=mozilla.org), this is getting off-topic...

**Comment by turt2live** [comment]
in all honesty, this issue is covered by others in the issue tracker.
