### ISSUE TITLE
Steam thinks that Riot is suspicious

### ISSUE THREAD

**Issue by turt2live** [vector-im/element-web#9056]
![image](https://user-images.githubusercontent.com/1190097/53841919-4a24a480-3f5b-11e9-82f3-91043de827ea.png)

**Comment by lampholder** [comment]
According to @benparsons Steam thinks _all_ .im domains are suspicious.

**Comment by turt2live** [comment]
Is there any avenue for us to say "hey, we're legit, we promise?"

**Comment by jryans** [comment]
Just to be sure, does it label _every_ URL as suspicious...? Or some URLs are okay?

**Comment by jryans** [comment]
@turt2live and I have debugged further... It does appears that specifically `riot.im` and any subdomain `*.riot.im` is marked as suspicious in Steam. When you hover a suspicious URL in Steam, it says:

<img width="388" alt="2019-03-14 at 18 17" src="https://user-images.githubusercontent.com/279572/54381342-69bb7b80-4685-11e9-843a-623af214172f.png">

## Suspicious

* http://riot.im
* https://pidgin.riot.im
* https://riot.im/develop/#/room/#matrix-spec:matrix.org

## Safe

* http://riot.bpulse.org
* http://matrix.to
* https://matrix.org
* http://vector.im
* https://pidgin.im
* https://riot.pidgin.im
* http://riot.org
* http://riot.co.uk
* http://riot.com

**Comment by egulsoylu** [comment]
> @turt2live and I have debugged further... It does appears that specifically `riot.im` and any subdomain `*.riot.im` is marked as suspicious in Steam. When you hover a suspicious URL in Steam, it says:
> 
> <img alt="2019-03-14 at 18 17" width="388" src="https://user-images.githubusercontent.com/279572/54381342-69bb7b80-4685-11e9-843a-623af214172f.png">
> 
> ## Suspicious
> * http://riot.im
> * https://pidgin.riot.im
> * https://riot.im/develop/#/room/#matrix-spec:matrix.org
> 
> ## Safe
> * http://riot.bpulse.org
> * http://matrix.to
> * https://matrix.org
> * http://vector.im
> * https://pidgin.im
> * https://riot.pidgin.im
> * http://riot.org
> * http://riot.co.uk
> * http://riot.com

I have been searching for an alternative to Discord and saw riot.im today. I sent the link to one of my friends via Steam and I got the same warning. So, I thought there must be a reason for Steam to see that link suspicious and kept searching an alternative. It turns out, https://ricochet.im/ is also marked suspicious. They must have something in common that bothers Steam. 

Although I have not seen any negative comment on privacy policy of riot.im or ricochet.im, I hesitate to use them until I find an explanation why Steam would mark those suspicious even after one year has passed since the open of this issue. 

![image](https://user-images.githubusercontent.com/5408275/80293119-36429000-8765-11ea-83a0-7be2a0121ba4.png)
![image](https://user-images.githubusercontent.com/5408275/80293111-288d0a80-8765-11ea-849e-f84909daa605.png)

**Comment by benparsons** [comment]
I just messaged Steam support, linking this issue. Will see what they respond.

**Comment by MadLittleMods** [comment]
> Are people seeing this for app.element.io by chance?

Closing as no one has responded in the past month ⏩
