### ISSUE TITLE
Overhaul settings interface

### ISSUE THREAD

**Issue by aaronraimist** [vector-im/element-web#9060]
### Initially this issue was "Consider removing/moving the confusing room settings gear icon":
It seems like a lot of people confuse the gear icon in the top right for the user settings or ask why there are two settings pages. Now that we can get to the settings from the three dot menu in the room list or by clicking on the room name, can we get rid of the room settings gear icon in the top right?

See https://matrix.to/#/!iNmaIQExDMeqdITdHH:matrix.org/$1551840431177948lnEbu:matrix.org?via=matrix.org&via=linuxgaming.life&via=feneas.org

### See ZeGentzy comments for more ideas on how settings could be less confusing.
I'm not entirely convinced that room settings should be included with user settings but I can at least see how splitting up user (things like your password that applies to all clients) and client (theme, client preferences, etc) settings may be helpful

**Comment by aaronraimist** [comment]
As a new user, if you are on this page that icon seems like the clear place to go to find settings.

![screen shot 2019-03-05 at 9 05 12 pm](https://user-images.githubusercontent.com/5855073/53853304-8b807880-3f8a-11e9-9c3f-07ce2cb2cdf8.png)

**Comment by ZeGentzy** [comment]
Forgive for the low quality, but here's what I propose
![](https://i.imgur.com/2E49Fop.png)
![](https://i.imgur.com/tho4e10.png)
Ofc, not in red.
Umm, and to be consistent with the rest of the ui, the closed icons in picture two should point to the right, not down.

**Comment by earfolds** [comment]
Discord has a settings icon next to your user icon, which makes it more clear that it's the settings for your user than a drop-down menu, since right now your user/client settings aren't visible at first glance, unlike the room settings.

I think that if the down-arrow in the top-left were replaced with the settings cog, it might be less likely for users to confuse the two. Perhaps making the room configuration icon a wrench would help differentiate, too? 

I think that putting a catch-all settings icon in with the communities might not be the best solution, but it would at least be a quick way to stop people from looking for user settings in the wrong place.

**Comment by aaronraimist** [comment]
Related #8755

**Comment by robintown** [comment]
That particular settings gear no longer exists
