### ISSUE TITLE
Make the `brand` config.json option impact all instances of the name Riot throughout the product.

### ISSUE THREAD

**Issue by ara4n** [vector-im/element-web#9065]
We need a config option to replace the word Riot with whatever the name of the app is (currently the brand setting in config.json is used to request branded IS email templates iirc?)

Also, the custom icon passed in on the config option should be applied to the favicon.

**Comment by rxl881** [comment]
These two items would be really useful for HHS (we're going to be doing some promotion around custom branded Riot). Anything that we can do to get this on the roadmap soon would be really helpful :)

**Comment by lampholder** [comment]
Two parts:
- Riot brand. We already have a `brand` value in config.json - do we know how much of the needful this does?
- Logo/favicon - I don't think this makes as much sense to have as a config option. IIUC riot needs a whole range of different-sized image files, so it's not a matter of providing a url to favicon.png. We could have a config file that looks like:
```
logo: {
    "16x16", "https://coolbrand.io/resources/logo/16x16.png",
    "32x32", "https://coolbrand.io/resources/logo/32x32.png",
    "64x64", "https://coolbrand.io/resources/logo/64x64.png",
    etc...
}
```
but that feels like it's starting to get messy. Would it be better to make sure that the files are all generically named within Riot (e.g. `logo_16_x_16.png` rather than `riot_logo_whatever.png` - this might already be the case) and then have the HHS ansible build process injest a zip of generated image files? Or run some scripted imagemagic business from a provided source image?

**Comment by turt2live** [comment]
> Riot brand. We already have a brand value in config.json - do we know how much of the needful this does?

The config option only affects email notifications (not even email invites as far as I can tell)

**Comment by lampholder** [comment]
Thanks @turt2live - at least we've got a sensible place to start :)

**Comment by rxl881** [comment]
@lampholder - For the favicons, could we have a url path in config that is expected to have all of the required image variants?

This would mimic the behaviour for setting / overriding other images, and we could handle checking for presence of all of the required files on the (Modular) client side as we already do:
![Selection_083](https://user-images.githubusercontent.com/6763606/54421844-256fc000-4705-11e9-98f2-293b6b7382dd.png)

(Invalid image link):
![Selection_084](https://user-images.githubusercontent.com/6763606/54421853-2a347400-4705-11e9-9650-b07b2ec78cf2.png)

**Comment by lampholder** [comment]
Yeah, that sounds nice.

**Comment by menturion** [comment]
+1
This would be great!

**Comment by turt2live** [comment]
https://github.com/matrix-org/matrix-react-sdk/pull/2921 makes the `Brand` useful for changing the name. We don't have a setting for changing the favicon, etc yet though

**Comment by jryans** [comment]
In recent times (post-Element rebranding), the `brand` config option now flows into all text strings presented in the UI.

**Comment by t3chguy** [comment]
> For the favicons, could we have a url path in config that is expected to have all of the required image variants?

> This would mimic the behaviour for setting / overriding other images, and we could handle checking for presence of all of the required files on the (Modular) client side as we already do:

Not for affecting everything, web scrapers/search engines would not execute Javascript so they would only see the image which is coded in index.html

**Comment by t3chguy** [comment]
Configurable icon is tracked in https://github.com/vector-im/element-web/issues/12020
