### ISSUE TITLE
Separated tabs within groups

### ISSUE THREAD

**Issue by CrimsonFork** [vector-im/element-web#9101]
I know it may sount like a strange concept, but I think that it would be very beneficial to have (a function for managing) multiple separated chats within a room.

The most useful example would be that rooms could have an off-topic tab which can be easily accessed by anyone in dhe room, but won't bother anyone who wants to focus on the on-topic conversation only.

These tabs should have their own priority levels set by the moderators, but they should not be able to gain a higher priority than the user has given to the room, unless the user explicitely wants them to. E.g. if the mod sets bots' messages to off while the user has them enabled, it can be overwritten, but if with the same user the mod wants the bots' messages to be noisy, then it stays as per user's setting.

_Sent from my Moto E (4) Plus using [FastHub-Libre](https://github.com/thermatk/FastHub-Libre/)_

**Comment by lampholder** [comment]
So this sounds quite a bit like https://github.com/vector-im/riot-web/issues/5077, but rendered as tabs within a room.

**Comment by OffifialMITX** [comment]
That's not quite what I mean, even though it is linda similar. My idea is that it would be something that the room owners/mods can create / take care of, so that the conversation can easily be separated from the main thread without each user having to join separate rooms.

E.g. if you are a dev and want to split the discussions of different projects, or if you have a room that depends heavily on a certain language to be spoken (e.g. #PUNS:matrix.org) but you can offer multiple threads for different languages, or if you are a teacher and it gets kinda tideous to create a new foom for each combination of each grade.

For now the problem simply is that with the one contact I chat the most with by now we have like 5 separate rooms for different purposes, which is neccessary in order to sort out some mess, but kinda sucks when we switch topics because I have to navigate through a bunch of other rooms, which, too, could have been multiple threads for in a main room.

**Comment by HansJK** [comment]
Sound like you are talking about the Community feature. Just like Slack and Discord, you have a group/community grouping a couple of rooms/channels.

**Comment by koalp** [comment]
I think that there would be beneficial to be able to group or have tabbed rooms within communities.

We would be able to sort rooms in big communities. (and maybe later sort vocal rooms if a federated vocal server software is created)

If we had to compare it with discord (that I consider as the most advanced chat UI today), matrix communities are discord "servers", and tabs/groups would be discord room categories.

**Comment by CrimsonFork** [comment]
Even though they don't actually solve the issue I was describing, Threads make the requested feature is kinda redundant to this, contextual and unsorted as they may be. I'm closing the issue as the devs don't seem to be interested, anyway.
