### ISSUE TITLE
Historical section is inefficient

### ISSUE THREAD

**Issue by turt2live** [vector-im/element-web#9202]
When my homeserver finally did respond, it produced 174mb of JSON before giving up. This was just for the historical section and not a normal sync for me

**Comment by lampholder** [comment]
GAH.

I think I'm struggling at the moment because I don't know how the historical section is _meant_ to work. Questions:

- is it meant to appear all the time?
- is it meant to be a way for me to browse all of the messages in all of the rooms I've ever been in?
- what name is the room meant to have?
- how far back is the data meant to go?
- how much of it is lazy loaded and when?

However it's meant to work, 174mb of hard-earned json blob is putting a fair amount of strain on the homeserver and the client for the relatively limited value _historical_ provides so surely we could be doing something more sensible.

**Comment by turt2live** [comment]
A lot of those questions are covered by other issues btw. Probably need a tracking issue to collect them all and slap a needs-design label on it

**Comment by turt2live** [comment]
This isn't relevant anymore.
