### ISSUE TITLE
New users unable to chat in group chat

### ISSUE THREAD

**Issue by CleanIfElse** [vector-im/element-web#9373]
Good morning,

First off awesome application. You guys did an amazing job with it and my friends and I love it. We will be using it all the time.

The only problem which we are facing is new users state "Your message was not sent" We are confused since there are 10 users that are able to send messages. We also created a new account to solve the problem but are having a difficult time. 

Please let me know about any ideas you can think of. 

Cheers!

**Comment by jryans** [comment]
Thanks for the report! Could one of the users facing this issue please send debug logs and mention this issue? (Top Left Menu -> Settings -> Help & About -> Submit debug logs) That should help us investigate.

**Comment by CleanIfElse** [comment]
Yeah np. We will be submitting it soon.  Thank you!

**Comment by jryans** [comment]
@CleanIfElse I can see a few spots in the log where there are errors like `UnknownDeviceError: This room contains unknown devices which have not been verified. We strongly recommend you verify them before continuing`. 

With Riot's default settings, that should show a prompt above the message composer saying "Message not sent due to unknown devices being present" and offering to continue anyway. However, several settings can change Riot so that it will refuse to speak when there are unverified devices:

* Device settings: Top Left Menu -> Settings -> Security & Privacy -> Cryptography -> Never send encrypted messages to unverified devices from this device
* Per-room settings for the device: Go to room -> Gear icon on top right -> Security & Privacy -> Encryption -> Never send encrypted messages to unverified devices in this room from this device

Can you check whether either of these settings has been enabled for the affected users?

**Comment by SimonBrandner** [comment]
Thank you for opening an issue. Unfortunately, I wasn’t able to reproduce it. If you keep experiencing this defect, please update your description with steps/screenshots/video/more details and add a comment with `@SimonBrandner` to let me know that it’s ready to be reopened.
