### ISSUE TITLE
It's confusing that the homeserver picker persists throughout registration

### ISSUE THREAD

**Issue by lampholder** [vector-im/element-web#9563]
![image](https://user-images.githubusercontent.com/1922197/56740047-08002e00-6768-11e9-8452-e45c89cbe9ac.png)

It's even worse when the spinner is spining - no (real) feedback about what's happening, but active UX elements for me to click, means it's fairly likely I'm going to run out of patience and click on the buttons.

**Comment by robintown** [comment]
This issue still exists, but since the entire login flow has been redesigned, there's no longer anything that looks like clickable buttons, so this can be a lower priority.

![Screenshot 2022-04-20 at 10-05-53 Element](https://user-images.githubusercontent.com/48614497/164249279-02011dc6-36bc-4c12-89a2-b2955db5aafd.png)

**Comment by t3chguy** [comment]
I think this issue can be closed given that the `Edit` button goes away, so its no longer a "picker"
