### ISSUE TITLE
Use pure CSS for "mx_BaseAvatar_image" class instead of avatar images

### ISSUE THREAD

**Issue by menturion** [vector-im/element-web#9992]
Use pure CSS for "mx_BaseAvatar_image" class instead of avatar images and open up the algo for calculating the color code of the no-image avatar of a user.

**Comment by fooness** [comment]
Anyone working on this?

**Comment by t3chguy** [comment]
![image](https://user-images.githubusercontent.com/2403652/79067109-1d41d580-7cb5-11ea-89aa-61835a19ba87.png)

Nope

**Comment by JorikSchellekens** [comment]
Ran into this headlong as well. Some avatars allow css overide because of a bug in how the heights and widths are specified without the unit suffix in some cases. The avatars are specified in js because of the thumbnail mxc api.

An ideal solution would involve a hook that reads the image size from css before hitting the thumbnail api and hit it again if there are any resizes over a significant threshold.

**Comment by t3chguy** [comment]
This got done
